/* ==========================================================================
   SELECT ALL THAT APPLY
   ==========================================================================
   The paper mixes single-answer and select-all items. A select-all item is
   marked all-or-nothing, so it tests whether a whole list is known, not
   whether one member can be recognised. Every question here is built from a
   list the deck prints on one slide, and every option — right or wrong — is
   something that appears somewhere in the course, so a wrong option is a real
   confusion rather than filler.

   Schema: `multi:true`, two or more options with `correct:true`. The quiz and
   the exam simulator render these with toggles and a Check button.
   ========================================================================== */
QUESTIONS.push(

/* ═══════════ TOXICITY — Sikazwe new ═══════════ */
{id:'sa-tox-1', prof:'Sikazwe', tier:'new', topic:'tox', sub:'causes', concept:'toxicophore-categories', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'Which of the following are toxicophore categories? Select all that apply.',
 options:[
  {t:'Electrophilic carbons', correct:true,
   why:'First bullet on slide 30. Halogenated carbons are the existing example, the epoxide carbon the bioactivated one.'},
  {t:'Electrophilic carbonyls', correct:true,
   why:'Second bullet. A carbonyl carbon short of electrons, open to attack by a protein nucleophile.'},
  {t:'Electrophilic double bonds', correct:true,
   why:'Third bullet. The quinone-imine of NAPQI and the diclofenac intermediates on slide 37 are the examples.'},
  {t:'Free radicals (ROS and RNS)', correct:true,
   why:'Fourth bullet, and the one that works by propagation rather than by waiting to be attacked, which is why slide 61 keeps a separate antioxidant defense for it.'},
  {t:'Haptens, azo and N-hydroxy groups', correct:true,
   why:'Fifth bullet. These act through an immune response or a carcinogenic pathway that needs a further step before harm appears.'},
  {t:'Nucleophilic amines', correct:false,
   why:'A nucleophile is what a toxicophore attacks, not a toxicophore itself. Protein and DNA nucleophiles are the targets on every mechanism slide; listing one as a toxicophore reverses the roles.'},
  {t:'Glucuronide conjugates', correct:false,
   why:'A glucuronide is the Phase 2 product formed to end reactivity and speed elimination. It is the defense, not the hazard, and no slide lists it among the toxicophores.'}],
 teach:[
  {h:'The five bullets, and what they share',
   t:'Slide 30 lists five: electrophilic carbons, electrophilic carbonyls, electrophilic double bonds, free radicals with ROS and RNS included, and others covering haptens, azo groups and N-OH. The first three are one idea at three sites, an electron-poor centre waiting for an electron-rich one. Free radicals propagate instead. The others group collects mechanisms that are neither.'},
  {h:'Existing or bioactivated',
   t:'The same slide opens with existing or bioactivated toxicophores in the parent drug, intermediates or metabolites. A halogenated carbon is present in the parent already; an epoxide is made by a CYP. That split decides whether harm is avoided by changing the molecule or by changing its metabolism.'}],
 teachImg:'tx_mech_toxicophores',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 30',
 quote:'Electrophilic carbons · Electrophilic carbonyls · Electrophilic double bonds · Free radicals (ROS/RNS included) · Others: Haptens, Azo, N-OH, etc.'},

{id:'sa-tox-2', prof:'Sikazwe', tier:'new', topic:'tox', sub:'def', concept:'antioxidant-enzymes', multi:true,
 tags:['list','enzyme'], source:'slide',
 stem:'Which of these enzymes defend a cell against oxidative stress by acting on reactive oxygen species or the peroxides they form? Select all that apply.',
 options:[
  {t:'Catalase', correct:true,
   why:'Slide 61 gives its reaction: H2O2 to H2O and O2. It removes the hydrogen peroxide that superoxide dismutase makes.'},
  {t:'Superoxide dismutase', correct:true,
   why:'Slide 61: 2H+ + 2O2•− to H2O2. It takes the superoxide anion, the first reactive oxygen species, down to hydrogen peroxide for catalase to finish.'},
  {t:'Glutathione peroxidase', correct:true,
   why:'Slide 61: LOOH to LOH + H2O. It reduces lipid hydroperoxides, spending glutathione to do it.'},
  {t:'Glutathione reductase', correct:true,
   why:'Slide 61: GS–SG to 2 GSH. It restores the reduced glutathione that the peroxidase consumed, so the pool is not used up.'},
  {t:'Cytochrome C', correct:true,
   why:'Slide 61 lists it with 2H+ + 2O2•− to O2, alongside superoxide dismutase, as a second route for the superoxide anion.'},
  {t:'Glutathione S-transferase', correct:false,
   why:'Glutathione S-transferase is a Phase 2 conjugating enzyme that attaches glutathione to an electrophile, on slide 59 under electrophile deactivation. It is a defense, but not one of the antioxidant enzymes on slide 61, which all act on reactive oxygen species rather than on electrophilic carbon.'},
  {t:'Epoxide hydrolase', correct:false,
   why:'Epoxide hydrolase opens an epoxide ring to a diol. It defends against an electrophilic carbon, not against reactive oxygen, so it sits with the electrophile defenses rather than on the antioxidant slide.'}],
 teach:[
  {h:'Two kinds of defense, on two slides',
   t:'Slide 59 covers electrophile deactivation: epoxide hydrolase and glutathione S-transferase take an electron-poor carbon out of play. Slide 61 covers oxidative stress: the antioxidant enzymes handle reactive oxygen species. A toxicophore that is an electrophile meets the first set; a free radical meets the second.'},
  {h:'How the antioxidant enzymes chain together',
   t:'Superoxide dismutase turns the superoxide anion into hydrogen peroxide. Catalase turns hydrogen peroxide into water and oxygen. Glutathione peroxidase handles lipid hydroperoxides, and in doing so oxidises glutathione to the disulfide, which glutathione reductase turns back into reduced glutathione so the cycle can run again.'}],
 teachImg:'tx_defense2',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 61; electrophile defenses on slide 59',
 quote:'Enzyme Defense - Oxidative Stress Defense by antioxidant enzymes'},

/* ═══════════ ELIMINATION — Sikazwe new ═══════════ */
{id:'sa-el-1', prof:'Sikazwe', tier:'new', topic:'elim', sub:'routes', concept:'non-renal-routes', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'Which of these are non-renal routes by which a drug or its metabolites leave the body? Select all that apply.',
 options:[
  {t:'Hepatic, via bile', correct:true,
   why:'First under non-renal on slide 6, and the largest of them: lipid-soluble drugs and their metabolites leave this way.'},
  {t:'Intestinal', correct:true,
   why:'Listed second. Drug can pass directly into the gut wall and out with the feces without going through bile.'},
  {t:'Lung', correct:true,
   why:'Listed third. Volatile and gaseous agents, the inhaled anesthetics, are exhaled.'},
  {t:'Mammary, in breast milk', correct:true,
   why:'Listed fourth. A minor route for the mother, and the reason it matters is the infant on the other end of it.'},
  {t:'Skin, in sweat and oil', correct:true,
   why:'Listed fifth. Minor, but it is how some drugs and their metabolites are detected in sweat.'},
  {t:'Tears, hair and saliva', correct:true,
   why:'The last three on the slide. None clears a meaningful share of a dose; hair and saliva are sampled for detection rather than counted as clearance.'},
  {t:'Renal, by glomerular filtration', correct:false,
   why:'Renal is the other heading on the slide, not an item under non-renal. It is the major route, for polar free drug and metabolites, and the non-renal list is defined by leaving it out.'}],
 teach:[
  {h:'How the slide is arranged',
   t:'Slide 6 has two headings. Renal stands alone. Non-renal opens into a list of eight: hepatic via bile, intestinal, lung, mammary, skin, tears, hair and saliva. Renal is the major route; within non-renal, hepatic via bile is the largest and the last five are minor.'},
  {h:'What decides between the two headings',
   t:'Slide 7 sends polar free or unbound drug and metabolites renally. Slide 16 sends lipid-soluble drugs and metabolites through the liver into bile. One property, whether the molecule can cross a membrane passively, does most of the sorting.'}],
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 6; slides 7 and 16 for the polar and lipophilic rules',
 quote:'Renal · Non-Renal: Hepatic (via Bile), Intestinal, Lung, Mammary (Breast Milk), Skin (Sweat/Oil), Tears, Hair, Saliva'},

/* ═══════════ CYP — Sikazwe new ═══════════ */
{id:'sa-cyp-1', prof:'Sikazwe', tier:'old', topic:'paths', sub:'cypox', concept:'cyp-reaction-types', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'Which of these reactions are CYP-catalysed oxidations? Select all that apply.',
 options:[
  {t:'Hydroxylation of aliphatic, allylic, benzylic and aryl carbons', correct:true,
   why:'The first line on slide 11: oxidation at carbon, at four kinds of carbon.'},
  {t:'Heteroatom oxidation', correct:true,
   why:'Second line. Oxidation at a nitrogen or sulfur rather than at carbon, giving N-oxides and sulfoxides.'},
  {t:'N-, O- and S-dealkylation', correct:true,
   why:'Three lines on the slide. A carbon next to the heteroatom is oxidised and the alkyl group leaves, which is how imipramine loses a methyl to become desipramine.'},
  {t:'Dehalogenation', correct:true,
   why:'Listed on slide 11, and the practice sheet asks about it directly in question 2(i) alongside epoxidation and dealkylation.'},
  {t:'Epoxidation of double bonds', correct:true,
   why:'The last line: double bonds to form epoxides. Carbamazepine on Lecture 15 slide 33 is the worked case.'},
  {t:'Glucuronidation of hydroxyl groups', correct:false,
   why:'Glucuronidation is a Phase 2 conjugation by UDP-glucuronosyltransferase, on slides 42 to 46. It attaches a group rather than inserting an oxygen, and no CYP is involved.'},
  {t:'Reduction of a nitro group to an amine', correct:false,
   why:'Nitro reduction is a Phase 1 reaction, but a reduction by nitroreductases on slide 33, not a CYP oxidation. The two are opposite in direction.'}],
 teach:[
  {h:'The list on slide 11',
   t:'CYP oxidative reactions include hydroxylation at aliphatic, allylic, benzylic and aryl carbons; heteroatom oxidation; N-, O- and S-dealkylations; dehalogenations; and oxidation of double bonds to epoxides. Everything on the list inserts an oxygen or removes a carbon by way of an oxygen.'},
  {h:'Practice question 2(i)',
   t:'The prep sheet asks, true or false, whether CYPs also catalyse epoxidation, dealkylation and dehalogenation. All three are on this slide, so the answer is true.'}],
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 11; nitroreduction slide 33; glucuronidation slides 42–46',
 quote:'Aliphatic, Allylic, Benzylic, Aryl carbons · Heteroatom · N-dealkylations · O-dealkylations · S-dealkylations · Dehalogenations · Double bonds (dbs) to form Epoxides'},

{id:'sa-cyp-2', prof:'Sikazwe', tier:'old', topic:'paths', sub:'nonc', concept:'non-cyp-oxidases', multi:true,
 tags:['list','enzyme'], source:'slide',
 stem:'Which of these enzymes carry out Phase 1 oxidations without being a cytochrome P450? Select all that apply.',
 options:[
  {t:'Alcohol dehydrogenase (ADH)', correct:true,
   why:'Slide 21: oxidation of OH groups. Primary alcohols go to aldehydes, secondary to ketones, and tertiary are not touched.'},
  {t:'Aldehyde dehydrogenase (ALDH)', correct:true,
   why:'Slide 21: oxidation of aldehydes, to the carboxylic acid. It follows alcohol dehydrogenase as a tandem pair.'},
  {t:'Monoamine oxidase (MAO)', correct:true,
   why:'Slide 21: oxidation of primary and secondary amines. Oxidative deamination, removing the nitrogen as ammonia.'},
  {t:'Flavin-containing monooxygenase (FMO)', correct:true,
   why:'Slide 21: oxidation of amines and thiols, giving N-oxides and sulfoxides. Slide 26 adds that FMO products are not affected by CYP inhibitors.'},
  {t:'Cytochrome P450', correct:false,
   why:'The slide is headed non-CYP. Cytochrome P450 is the CYP; its reactions are the previous slide, 11. Including it here means reading the heading as a list of all oxidases rather than the ones that are not P450.'},
  {t:'UDP-glucuronosyltransferase', correct:false,
   why:'A Phase 2 conjugating enzyme, slides 42 to 46. It transfers glucuronic acid and oxidises nothing.'}],
 teach:[
  {h:'Four enzymes, each named for its substrate',
   t:'Alcohol dehydrogenase oxidises alcohols. Aldehyde dehydrogenase oxidises aldehydes. Monoamine oxidase oxidises primary and secondary amines. Flavin-containing monooxygenase oxidises amines and thiols. Three of the four carry their substrate in their name, which the 09/10 lecture pointed out as the way to keep them straight.'},
  {h:'Why the CYP versus non-CYP split matters',
   t:'A drug cleared by a non-CYP oxidase is not affected by the CYP inducers and inhibitors that cause most drug interactions. Slide 26 states this for FMO. So the split is not a filing convenience; it decides whether a drug interaction check even applies.'}],
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 21; slide 26 for FMO',
 quote:'Non-CYP Oxidation Reactions: ADH oxidation of OH groups · ALDH oxidation of Aldehydes · MAO oxidation of Amines (1o or 2o) · FMO oxidations of Amines & Thiols'},

{id:'sa-p2-1', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'phase2-enzyme-list', multi:true,
 tags:['list','enzyme'], source:'slide',
 stem:'Which of these enzyme families catalyse Phase 2 conjugation? Select all that apply.',
 options:[
  {t:'UDP-glucuronosyltransferases (UGTs)', correct:true,
   why:'First on slide 43. Cofactor UDPGA; conjugates -OH, -CO2H, -NH2 and -SH groups.'},
  {t:'Sulfotransferases (STs or SULTs)', correct:true,
   why:'Second. Cofactor PAPS; conjugates alcohols and, on slide 47, aromatic amines.'},
  {t:'Glutathione S-transferases (GSTs)', correct:true,
   why:'Third. Cofactor glutathione; takes electrophiles such as epoxides and halogenated carbons.'},
  {t:'N-acetyltransferases (NAT)', correct:true,
   why:'Fourth. Cofactor acetyl-CoA; conjugates primary amines and sulfonamides, and NAT2 is polymorphic.'},
  {t:'Acyl synthetases', correct:true,
   why:'Fifth, for amino acid conjugation of carboxylic acids. Slide 55 gives three cofactors: acetyl-CoA, glycine and glutamine.'},
  {t:'Methyltransferases (MTs), such as COMT and TPMT', correct:true,
   why:'Sixth. Cofactor S-adenosylmethionine; catechol-O-methyltransferase and thiopurine methyltransferase are the two named.'},
  {t:'Epoxide hydrolase', correct:false,
   why:'Epoxide hydrolase is a Phase 1 hydrolysis, on slides 34 to 39. It opens a ring with water and attaches nothing, so it is not a conjugating enzyme.'},
  {t:'Carboxylesterase', correct:false,
   why:'Carboxylesterase hydrolyses esters, amides, carbamates and carbonates. Hydrolysis is Phase 1; the slide 43 list is the six Phase 2 transferases.'}],
 teach:[
  {h:'The six, with what each one transfers',
   t:'Slide 43 lists UDP-glucuronosyltransferases, sulfotransferases, glutathione S-transferases, N-acetyltransferases, acyl synthetases and methyltransferases. Every one attaches something to the drug: glucuronic acid, sulfate, glutathione, an acetyl group, an amino acid, or a methyl group. That is the definition of Phase 2.'},
  {h:'Hydrolases are Phase 1',
   t:'Epoxide hydrolase and carboxylesterase both add water and split a bond. Nothing is attached, so they belong with the Phase 1 hydrolyses on slides 34 to 39 rather than with the transferases.'}],
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 43; hydrolyses on slides 34–39',
 quote:'Phase 2 Enzymes: UGTs · STs or SULTs · GSTs · NAT · Acylsynthatases · MTs (e.g., COMT, TPMT)'},

{id:'sa-p2-2', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'ugt-substrate-groups', multi:true,
 tags:['list','structure'], source:'slide',
 stem:'Which of these functional groups can be conjugated directly by a UDP-glucuronosyltransferase? Select all that apply.',
 options:[
  {t:'Hydroxyl (-OH)', correct:true,
   why:'First in the UGT row on slide 29. Morphine-6-glucuronide is the worked example on Lecture 11 slide 48.'},
  {t:'Carboxylic acid (-CO2H)', correct:true,
   why:'Second in the row. The product is an acyl glucuronide, an ester of glucuronic acid.'},
  {t:'Amine (-NH2)', correct:true,
   why:'Third. N-glucuronidation, which is one reason the same amine can appear under several Phase 2 enzymes.'},
  {t:'Thiol (-SH)', correct:true,
   why:'Fourth and last in the UGT row: S-glucuronidation, the thiol attacking the activated sugar in the same way an alcohol does.'},
  {t:'Epoxide', correct:false,
   why:'The epoxide sits in the glutathione S-transferase row of the same table, with R-X. It is an electrophile, which is what GST takes, not a nucleophilic handle for a glucuronide.'},
  {t:'Ester', correct:false,
   why:'An ester is a substrate for carboxylesterase hydrolysis in Phase 1, on slides 14 to 16. It carries no free hydroxyl, carboxyl, amine or thiol to conjugate until it has been hydrolysed.'}],
 teach:[
  {h:'The table row',
   t:'On Lecture 14 slide 29, the UDP-glucuronosyltransferase row reads -OH; -CO2H; -NH2; -SH, with UDPGA as the cofactor and a glucuronide as the conjugate. Four groups, all nucleophilic, all able to attack the activated sugar.'},
  {h:'Where the other rows differ',
   t:'The sulfotransferase row reads -OH only in this table, though Lecture 11 slide 47 adds aromatic amines. The acyl synthetase row takes -CO2H. The glutathione S-transferase row takes R-X and epoxides, which are electrophiles rather than nucleophiles, which is why it is the odd one out.'}],
 teachImg:'tbl_ph2_a',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 29',
 quote:'-OH; -CO2H; -NH2; -SH | UDP-Glucuronosyl transferases (UGTs) | UDPGA | Glucuronide'},

/* ═══════════ METABOLISM FOUNDATIONS — Sikazwe old, and prep-sheet Q2(ii) ═══════════ */
{id:'sa-df-1', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'conseq', concept:'dm-consequences-list', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'Which of the following are consequences of drug metabolism? Select all that apply.',
 options:[
  {t:'Inactivation', correct:true,
   why:'The first arrow on slide 28, and the common case: the metabolite has no activity.'},
  {t:'Similarly acting metabolites', correct:true,
   why:'Under the bioactivation arrow: similarly acting drugs, with less than, greater than or equal to marked beside them. Morphine-6-glucuronide is more potent than morphine.'},
  {t:'Prodrug activation', correct:true,
   why:'Also under bioactivation. An inactive compound converted to the active drug: enalapril to enalaprilat, sulfasalazine to its components.'},
  {t:'Reactive or toxic metabolites', correct:true,
   why:'Under bioactivation as well. Acetaminophen to NAPQI, benzo[a]pyrene to its diol epoxide.'},
  {t:'Altered drug activity', correct:true,
   why:'The last item under bioactivation: a metabolite with a different action from its parent, which slide 37 illustrates.'},
  {t:'Reversible metabolites', correct:true,
   why:'The double-headed arrow on slide 28: a metabolite that converts back to the parent.'},
  {t:'Drug interactions', correct:true,
   why:'The final arrow. A drug that induces or inhibits the metabolism of another, which is a consequence of metabolism rather than a pattern of it.'},
  {t:'Increased metabolite lipophilicity', correct:false,
   why:'Metabolism runs the other way: Phase 1 and Phase 2 raise polarity so the product can be excreted. A more lipophilic metabolite would be the exception, and it is not on the slide.'}],
 teach:[
  {h:'The slide, as drawn',
   t:'Parent drug sits in a box on the left. Arrows lead to inactivation; to bioactivation, which opens into similarly acting drugs (less, more or equally potent), prodrug activation, reactive species (toxic, carcinogens, teratogens) and altered drug activity; to reversible metabolites, with a double arrow; and to drug interactions. That is the whole list the prep sheet asks for.'},
  {h:'Why drug interactions belong on a consequences slide',
   t:'Induction and inhibition are consequences of one drug\'s metabolism for another\'s. Slide 49 of the same lecture works the triazolam and rifampin case as the example.'}],
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 28; Ex4-Prep-Work question 2(ii)',
 quote:'Inactivation · Bioactivation (Similarly Acting Drugs; Prodrug Activation; Reactive; Altered Drug Activity) · Reversible Metabolites · Drug Interactions'},

/* ═══════════ FUNCTIONAL GROUPS — Sikazwe old ═══════════ */
{id:'sa-fg-1', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'acyl', concept:'ca-derivative-list', multi:true,
 tags:['list','structure'], source:'slide',
 stem:'Which of these functional groups belong to the carboxylic acid derivative family? Select all that apply.',
 options:[
  {t:'Ester', correct:true,
   why:'Listed on slides 9 and 60. The acid\'s hydroxyl hydrogen replaced by a carbon.'},
  {t:'Amide', correct:true,
   why:'Listed on both slides. The hydroxyl oxygen replaced by a nitrogen.'},
  {t:'Carbamate', correct:true,
   why:'Listed on both. Oxygen on one side of the carbonyl, nitrogen on the other.'},
  {t:'Carbonate', correct:true,
   why:'Added on the slide 60 recap, though absent from slide 9. Two oxygens flanking the carbonyl.'},
  {t:'Urea, imide and guanidine', correct:true,
   why:'All three on slides 9 and 60. Urea is N-C(=O)-N, imide C(=O)-N-C(=O), guanidine N-C(=N)-N.'},
  {t:'Ketone', correct:false,
   why:'A ketone has a carbonyl with carbon on both sides and no heteroatom beside it. The deck files it under oxygenated hydrocarbons with aldehydes, alcohols, phenols and ethers, not under the carboxylic acid derivatives.'},
  {t:'Sulfonamide', correct:false,
   why:'A sulfonamide is built on sulfur, S(=O)2-N, and the deck files it in the sulfur section on slide 68. It shares the amide name but not the carbonyl.'}],
 teach:[
  {h:'The family, on two slides',
   t:'Slide 9 lists CA, esters, amides, carbamates, ureas, imides and guanidines. The slide 60 recap repeats them and adds carbonates. Every one but guanidine is a carbonyl carbon with heteroatoms on one or both sides; guanidine has C=N in place of C=O, three nitrogens on one carbon, and is grouped with the family because it is the acid with every oxygen swapped for nitrogen. Each is reached from the acid by one edit.'},
  {h:'What is not in the family',
   t:'A ketone and an aldehyde have the carbonyl but no heteroatom beside it, so they are oxygenated hydrocarbons. A sulfonamide has the amide-type nitrogen but on a sulfur rather than a carbonyl, so it is a sulfur group. The name can suggest the family; the structure decides it.'}],
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 9 and 60',
 quote:'CA & Derivatives: CA, Esters, Carbonates, Amides, Carbamates, Ureas, Imides, Guanidines'},

/* ═══════════ YENDAPALLY — physicochemical ═══════════ */
{id:'sa-pc-1', prof:'Yendapally', tier:'old', topic:'physchem', sub:'acidbase', concept:'acidic-groups-list', multi:true,
 tags:['list','structure'], source:'slide',
 stem:'Which of these functional groups are acidic, able to give up a proton and leave a stabilised anion? Select all that apply.',
 options:[
  {t:'Alkyl carboxylic acid', correct:true,
   why:'Slide 12, pKa 5 to 6. Loses the proton to give a carboxylate, with the charge shared across both oxygens by resonance.'},
  {t:'Aryl carboxylic acid', correct:true,
   why:'Slide 12, pKa 4 to 5. The ring withdraws electron density, so it is a slightly stronger acid than the alkyl one.'},
  {t:'Phenol', correct:true,
   why:'Slide 11, weakly acidic, pKa around 9 to 11, giving a phenolate. The ring delocalises the negative charge, which an alcohol cannot do.'},
  {t:'Sulfonamide', correct:true,
   why:'Slide 13, pKa 9 to 10 for an alkyl sulfonamide and 6 to 7 for an N-aryl sulfonamide. The two sulfonyl oxygens pull electron density from the N-H.'},
  {t:'Imide', correct:true,
   why:'Slide 13, pKa 9 to 10. The N-H sits between two carbonyls, both withdrawing from it. Phenytoin salts are made here.'},
  {t:'Thiol and thiophenol', correct:true,
   why:'Slide 13: alkyl thiol pKa 10 to 11, thiophenol 9 to 10, giving thiolate and thiophenolate.'},
  {t:'Alkyl alcohol', correct:false,
   why:'Slide 11 states that alcohols are categorised as neutral. An alcohol has the O-H but no ring or carbonyl to stabilise the anion, so it does not give up its proton at physiological pH. Confusing it with phenol is the most common error in this list.'},
  {t:'Alkyl amine', correct:false,
   why:'An alkyl amine is basic, slide 15, pKa 9 to 11 for its conjugate acid. It accepts a proton rather than donating one.'}],
 teach:[
  {h:'What makes a group acidic',
   t:'A group is acidic when it can give up a proton and the anion left behind is stabilised. Carboxylates spread the charge over two oxygens. Phenolates spread it into the ring. Sulfonamidates and imidates have electron-withdrawing groups on both sides of the nitrogen. Thiols are acidic because sulfur holds a negative charge more comfortably than oxygen does.'},
  {h:'The pKa values, lowest first',
   t:'Aryl carboxylic acid 4 to 5, alkyl carboxylic acid 5 to 6, N-aryl sulfonamide 6 to 7, phenol 9 to 11, sulfonamide 9 to 10, imide 9 to 10, thiophenol 9 to 10, alkyl thiol 10 to 11. Lower pKa means a stronger acid, so the carboxylic acids are the strongest here and the thiols the weakest.'},
  {h:'The one that looks acidic and is not',
   t:'An alkyl alcohol carries the same O-H as a phenol and is neutral. Without the ring there is nothing to take the charge, so the proton stays on.'}],
 cite:'082726_PhysicochemicalProp1.pdf slides 11, 12, 13; basic groups slide 15',
 quote:'Alkylcarboxylic acid (5-6) · Arylcarboxylic acid (4-5) · Sulfonamide (9-10) · Imide (9-10) · Alkylthiol (10-11) · Thiophenol (9-10) · N-Arylsulfonamide (6-7)'},

{id:'sa-pc-2', prof:'Yendapally', tier:'old', topic:'physchem', sub:'acidbase', concept:'neutral-groups-list', multi:true,
 tags:['list','structure'], source:'slide',
 stem:'Which of these functional groups are neutral, neither donating nor accepting a proton in the body? Select all that apply.',
 options:[
  {t:'Alkyl alcohol', correct:true,
   why:'First on slide 19. No ring to stabilise an anion, no lone pair basic enough to take a proton at body pH.'},
  {t:'Ether', correct:true,
   why:'Listed. Oxygen between two carbons; it accepts a hydrogen bond but neither gives nor takes a proton.'},
  {t:'Ester and amide', correct:true,
   why:'Both listed. The carbonyl pulls electron density away, so the amide nitrogen is not basic and the ester oxygen is not either.'},
  {t:'Aldehyde and ketone', correct:true,
   why:'Both listed. Carbonyl groups that accept hydrogen bonds and carry no ionisable proton.'},
  {t:'Sulfoxide and sulfone', correct:true,
   why:'Both listed. One and two oxygens on sulfur; neutral until the third oxygen makes a sulfonic acid.'},
  {t:'Amine oxide, quaternary amine and nitrile', correct:true,
   why:'The last three on the slide. The quaternary amine carries a permanent charge but has no acid-base behaviour, which is why it is filed as neutral.'},
  {t:'Phenol', correct:false,
   why:'Phenol is on the acidic slide, 11, pKa 9 to 11. Its ring stabilises the phenolate, which is exactly what separates it from the alkyl alcohol at the top of the neutral list.'},
  {t:'Guanidine', correct:false,
   why:'Guanidine is the strongest base on slide 15, pKa 12 to 13. The protonated form spreads its positive charge over three nitrogens.'}],
 teach:[
  {h:'The slide 19 list',
   t:'Alkyl alcohol, ether, ester, amide, aldehyde, ketone, sulfoxide, sulfone, amine oxide, quaternary amine, nitrile. Eleven groups, none of which gives up or takes on a proton in the body.'},
  {h:'Two that surprise people',
   t:'The amide looks like an amine and is neutral, because the adjacent carbonyl withdraws the nitrogen lone pair. The quaternary amine is permanently charged and still neutral in acid-base terms, because with four carbons on the nitrogen there is no lone pair left to accept a proton and no proton to give.'}],
 cite:'082726_PhysicochemicalProp1.pdf slide 19; acidic groups slide 11, basic groups slide 15',
 quote:'Neutral Functional Groups: Alkyl alcohol, Ether, Ester, Amide, Aldehyde, Ketone, Sulfoxide, Sulfone, Amine oxide, Quaternary amine, Nitrile'},

/* ═══════════ YENDAPALLY — Absorption II ═══════════ */
{id:'sa-ab2-1', prof:'Yendapally', tier:'old', topic:'admet', sub:'ddi', concept:'ddi-mechanisms-list', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'By which of these mechanisms can a co-administered substance change how much of an oral drug is absorbed? Select all that apply.',
 options:[
  {t:'Presenting a large surface area the drug adsorbs onto', correct:true,
   why:'The first of the four. Activated charcoal, and the bile acid resins cholestyramine and colestipol, hold drug on their surface so less is free to be absorbed.'},
  {t:'Forming chelates with metal ions', correct:true,
   why:'The second. Iron and antacids with quinolones and tetracyclines; the chelate is less soluble and less absorbed.'},
  {t:'Altering gastrointestinal motility', correct:true,
   why:'The third. Loperamide slows transit and bisacodyl speeds it; the effect on absorption is recorded as variable.'},
  {t:'Affecting transport proteins in the gastrointestinal tract', correct:true,
   why:'The fourth. Digoxin is a P-glycoprotein substrate; verapamil inhibits the pump and raises digoxin levels, rifampin induces it and lowers them.'},
  {t:'Inducing hepatic CYP3A4', correct:false,
   why:'Hepatic induction changes how fast a drug is metabolised after absorption. It belongs to the metabolism lectures, not to the four absorption mechanisms, which all act on how much drug crosses the gut wall.'},
  {t:'Displacing the drug from plasma albumin', correct:false,
   why:'Protein displacement is a distribution interaction, in the Distribution deck. It changes the free fraction in blood, not the amount absorbed from the gut.'}],
 teach:[
  {h:'The four, each with its example',
   t:'Adsorption: activated charcoal, cholestyramine and colestipol. Chelation: iron, antacids and mineral supplements with the quinolone and tetracycline antibacterials. Motility: loperamide and bisacodyl. Transport proteins: digoxin with verapamil or rifampin at P-glycoprotein.'},
  {h:'What separates these from the metabolism interactions',
   t:'Every one of the four changes how much drug gets across the gut wall. Induction and inhibition change what happens to the drug once it is in the body. A question about oral absorption is asking about the first set.'}],
 cite:'090426_ADMETAbsorption_II.pdf, "Oral Route of Drug Administration" and "Key Concepts"',
 quote:'Have a large surface area upon which the drug can be adsorbed · Specifically form chelates with metal ions · Alter gastrointestinal motility · Affect transport proteins in the GI tract'},

{id:'sa-ab2-2', prof:'Yendapally', tier:'old', topic:'admet', sub:'prodrug', concept:'prodrug-purposes-list', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'Which of these are purposes for which a prodrug is made? Select all that apply.',
 options:[
  {t:'Improved lipophilicity or permeability', correct:true,
   why:'Enalapril, the ethyl ester of enalaprilat, raising log P from 1.17 to 1.77 and oral bioavailability from 30 to 40 percent up to 50 to 70 percent.'},
  {t:'Carrier-mediated absorption', correct:true,
   why:'Valacyclovir, the valine ester of acyclovir, carried by PepT1 and raising oral bioavailability from 15 to 21 percent up to 54 percent.'},
  {t:'Prolonged duration of action', correct:true,
   why:'Haloperidol decanoate, log P 7.3 against 3.49, taken up by fatty tissue and given once a month.'},
  {t:'Enhanced parenteral administration', correct:true,
   why:'Fosphenytoin, the phosphate ester, soluble at 142 mg/mL for intramuscular use and cleaved by phosphatases in 8 to 15 minutes.'},
  {t:'Improved ophthalmic delivery', correct:true,
   why:'Dipivefrin, the dipivalic acid diester of adrenaline, 600-fold more lipophilic and crossing the cornea 17 times faster.'},
  {t:'Reduced first-pass metabolism', correct:false,
   why:'A prodrug is made to be metabolised, not to avoid it: the conversion to the active drug is a metabolic step. Reducing first-pass loss is not among the five purposes on the Key Concepts slide.'},
  {t:'Blocking P-glycoprotein efflux', correct:false,
   why:'P-glycoprotein appears in the deck under drug interactions, with verapamil as the inhibitor. No prodrug example is built to block efflux.'}],
 teach:[
  {h:'The five, from the Key Concepts slide',
   t:'Improved lipophilicity and permeability, with enalapril. Carrier-mediated absorption, with valacyclovir. Prolonged duration of action, with haloperidol decanoate. Enhanced parenteral administration, with fosphenytoin. Improved ophthalmic delivery, with dipivefrin. Every one is an ester, and reading what the added group does tells which purpose is served.'}],
 cite:'090426_ADMETAbsorption_II.pdf, "Key Concepts: 2" and "Prodrugs (Contd.)" slides',
 quote:'Improved Lipophilicity and Permeability · Carrier-Mediated Absorption · Prolonged Duration of Action · Enhanced Parenteral Administration · Improved Ophthalmic Delivery'},

/* ═══════════ YENDAPALLY — drug discovery ═══════════ */
{id:'sa-dd-1', prof:'Yendapally', tier:'old', topic:'disc', sub:'sources', concept:'natural-product-sources', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'Which of these are sources of natural-product drugs? Select all that apply.',
 options:[
  {t:'Plants', correct:true,
   why:'First under natural products. Digoxin, quinine and quinidine, morphine and camptothecin are the four examples worked.'},
  {t:'Microorganisms', correct:true,
   why:'Second. Penicillin, from the Penicillium mould that contaminated Fleming\'s culture plate.'},
  {t:'Based on mammalian biochemical pathways', correct:true,
   why:'Third. Epinephrine, erythropoietin, insulin and levothyroxine: molecules a mammal makes, given as drugs.'},
  {t:'Synthetic products', correct:false,
   why:'Synthetic products is a separate top-level bullet on the slide, not a sub-heading under natural products. It is the other category, set against natural products.'},
  {t:'Random screening', correct:false,
   why:'Random screening is one of the six discovery approaches on a later slide, a way of finding a drug rather than a source it comes from.'}],
 teach:[
  {h:'How the slide is laid out',
   t:'Two top-level bullets: natural products and synthetic products. Under natural products, four sub-bullets: plants, micro organisms, based on mammalian biochemical pathways, and other sources. Random screening belongs to a different slide, the six discovery approaches, which are ways of finding a drug rather than places it comes from.'}],
 cite:'082026_Drugdiscovery.pdf, "Sources of New Drugs"',
 quote:'Natural products: Plants · Micro organisms · Based on mammalian biochemical pathways · Other sources | Synthetic products'}
);
