/* ==========================================================================
   SELECT ALL THAT APPLY — second set
   ==========================================================================
   Lists from Lectures 13, 14 and 15, which carry 38 of the 50 marks, so that
   the exam simulator draws its select-all items from the material the paper
   weights most. Same schema as q10_sata.js: `multi:true`, two or more options
   with `correct:true`, at least one distractor, marked all-or-nothing.
   ========================================================================== */
QUESTIONS.push(

/* ═══════════ CYP — Lecture 13 ═══════════ */
{id:'sa-cyp-3', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'indinh', concept:'cyp3a-inhibitor-list', multi:true,
 tags:['list','ddi'], source:'slide',
 stem:'Which of the following inhibit CYP3A4, so that a co-administered CYP3A4 substrate accumulates? Select all that apply.',
 options:[
  {t:'Clarithromycin', correct:true,
   why:'A macrolide antibacterial, first on the inhibitor list of Lecture 13 slide 32; erythromycin is the other macrolide there. The substrate is cleared more slowly, so its level rises.'},
  {t:'Ketoconazole', correct:true,
   why:'An azole antifungal, listed with itraconazole. The azole nitrogen coordinates the heme iron of the CYP, which blocks the site where oxygen would bind.'},
  {t:'Grapefruit juice', correct:true,
   why:'On the inhibitor list, and slide 35 tabulates the drugs it affects: the dihydropyridine calcium channel blockers, atorvastatin, lovastatin and simvastatin, buspirone, midazolam and triazolam, cyclosporine. The affected drugs are oral CYP3A4 substrates with a large first-pass loss.'},
  {t:'Quinidine', correct:true,
   why:'On the slide 32 inhibitor list, and again in the CYP2C9 column of the slide 34 table, so it inhibits more than one CYP.'},
  {t:'Rifampin', correct:false,
   why:'Rifampin is an inducer: more enzyme is made, the substrate is cleared faster, and its level falls. Lecture 10 slide 49 shows the triazolam curve collapsing when rifampin is added. Slide 33 gives its induced CYPs as 2C8, 2C9, 2C19, 2D6, 3A4 and 2B6.'},
  {t:'Carbamazepine', correct:false,
   why:'An inducer on slide 32, and slide 33 lists 1A2, 3A4, 2C8, 2C9, 2C19, 2D6 and 2B6 for it. It lowers the level of a co-administered substrate, the opposite direction from an inhibitor.'},
  {t:'St John\'s wort', correct:false,
   why:'A herbal inducer on slide 32; slide 33 gives 1A2, 2C9 and 3A4. Substrate levels fall.'}],
 teach:[
  {h:'The two columns',
   t:'Slide 32 prints the CYP3A inducers in one column and the inhibitors in the other. Inducers: barbiturates, carbamazepine, phenytoin, rifampin, St John\'s wort, ethanol, tobacco, nevirapine. Inhibitors: clarithromycin, erythromycin, the azole antifungals ketoconazole and itraconazole, cimetidine, the protease inhibitors, grapefruit juice, quinidine, omeprazole. Omeprazole also appears as an inducer of 1A2 and 3A4 on slide 33 and as a 2C19 inhibitor on slide 34, so it is left out of this question.'},
  {h:'What each column does to a substrate',
   t:'An inhibitor occupies or inactivates the enzyme that is already there, within hours, and the substrate\'s level rises. An inducer raises the amount of enzyme over days, and the substrate\'s level falls. For an active drug, inhibition means toxicity and induction means loss of effect; for a prodrug, both directions reverse, because the metabolite is the active species.'}],
 teachImg:'cyp_ind_inh_lists',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 32; inducer table slide 33; inhibitor table slide 34; grapefruit juice table slide 35',
 quote:'Common Inducers: Barbiturates · Carbamazepine · Phenytoin · Rifampin · St Johns Wort · Ethanol · Tobacco · Nevirapine | Common Inhibitors: Clarithromycin · Erythromycin · Azole Antifungals (Ketoconazole, Itraconazole) · Cimetidine · Protease inhibitors · Grape Fruit Juice · Quinidine · Omeprazole'},

{id:'sa-cyp-4', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'char', concept:'cyp-location-structure', multi:true,
 tags:['list','structure'], source:'slide',
 stem:'Which of the following are true of the cytochrome P450 (CYP) enzymes? Select all that apply.',
 options:[
  {t:'They sit in the endoplasmic reticulum of liver cells and of other cells', correct:true,
   why:'First bullet on Lecture 13 slide 10. The endoplasmic reticulum is recovered as the microsomal fraction, so CYP activity is measured in liver microsomes.'},
  {t:'They are membrane-bound proteins', correct:true,
   why:'Second bullet. The enzyme is anchored in the endoplasmic reticulum membrane, where its lipophilic substrates partition.'},
  {t:'The catalytic site is a porphyrin holding iron, with a cysteine as the ligand below the ring', correct:true,
   why:'Third bullet: porphyrin with an Fe-cysteine catalytic site. Oxygen binds the iron on the face opposite the cysteine, and the substrate carbon is oxidised there.'},
  {t:'The enzyme-carbon monoxide complex absorbs light at 450 nm, which is where the name comes from', correct:true,
   why:'Fourth bullet, and slide 8: P450 is the CYP plus carbon monoxide complex absorbing at 450 nm. Pigment, 450 nanometres.'},
  {t:'They are soluble enzymes dissolved in the cytosol', correct:false,
   why:'The second bullet on slide 10 makes them membrane-bound in the endoplasmic reticulum. A soluble cytosolic enzyme would not be recovered in the microsomal fraction where CYP activity is found.'},
  {t:'The heme iron is held by a histidine, as in hemoglobin', correct:false,
   why:'Slide 10 names cysteine as the ligand. The thiolate sulfur of that cysteine is what makes the iron able to activate oxygen; hemoglobin holds its iron with a histidine and binds oxygen without activating it.'},
  {t:'The name records an absorbance at 405 nm', correct:false,
   why:'The complex absorbs at 450 nm, on slides 8 and 10; that number is the origin of P450.'}],
 teach:[
  {h:'Four bullets, one enzyme',
   t:'Slide 10 gives location, attachment, active site and spectrum: in the endoplasmic reticulum, membrane-bound, a porphyrin with iron ligated by cysteine, and a carbon monoxide complex absorbing at 450 nm. Slide 8 unpacks the name from the same facts: cyto for cell-bound, chrome for the heme pigment, P450 for the wavelength.'},
  {h:'Why the cysteine matters',
   t:'The iron sits in the porphyrin ring with a cysteine thiolate on one face. Oxygen binds on the other face, is split, and one oxygen atom is delivered to the substrate carbon. Hemoglobin has the same porphyrin with a histidine instead, and it only carries oxygen. The ligand under the ring is the difference between a carrier and an oxidase.'}],
 teachImg:'cyp_characteristics',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 10; nomenclature slide 8',
 quote:'CyPs are in the ER (liver & other cells) · CyPs are membrane bound proteins · Porphyrin with Fe-Cysteine catalytic site · CYP + CO complex absorbs light @ 450 nm'},

/* ═══════════ ELIMINATION — Lecture 15 ═══════════ */
{id:'sa-el-2', prof:'Sikazwe', tier:'new', topic:'elim', sub:'renal', concept:'renal-factors-list', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'Which of the following change how much of a drug the kidney eliminates? Select all that apply.',
 options:[
  {t:'Kidney disease', correct:true,
   why:'First on Lecture 15 slide 9. Slide 10 gives chronic kidney disease, with hypertension and diabetes as its risk factors, and names ceftazidime, procainamide, tobramycin and amikacin as drugs whose doses are adjusted.'},
  {t:'Glomerular filtration rate', correct:true,
   why:'Second. Slide 11: molecules under about 60 kDa are filtered, only unbound drug is filtered, and inflammation of the glomerular capillaries can raise the rate.'},
  {t:'Reabsorption of un-ionised drug from the tubule back into the blood', correct:true,
   why:'Third. Slide 12: the ionised drug is excreted in the urine; the un-ionised drug diffuses back across the tubule into the circulation. A lipophilic drug such as phenytoin is reabsorbed this way, slide 7.'},
  {t:'Active tubular secretion', correct:true,
   why:'Fourth. Slide 13: transporters carry anions and cations from blood into the tubule, and an inhibitor of those transporters slows elimination. Probenecid on the renal OATPs slows penicillin excretion.'},
  {t:'Urinary pH', correct:true,
   why:'Fifth. Slide 14: acidic urine keeps an acidic drug un-ionised and reabsorbable while it ionises and traps a basic drug; basic urine does the reverse.'},
  {t:'Enterohepatic recycling', correct:false,
   why:'Recycling is a hepatic factor, slide 18: drug excreted in bile is reabsorbed from the intestine. It lengthens the time a drug stays in the body, but through bile and gut, not through the kidney.'},
  {t:'Bile flow', correct:false,
   why:'Bile flow, and its reduction in cholestasis, is on slide 17 under hepatic elimination. The kidney is not part of that route.'}],
 teach:[
  {h:'Five renal factors, one slide each',
   t:'Slide 9 lists them and slides 10 to 14 take them one at a time: kidney disease, glomerular filtration rate, reabsorption of un-ionised drug, active tubular secretion and urinary pH. Filtration and secretion move drug into the urine; reabsorption moves it back; disease lowers the capacity of all of it; pH decides how much of an ionisable drug is in the reabsorbable form.'},
  {h:'Renal and hepatic factors are separate lists',
   t:'Slides 17 to 20 hold the hepatic factors: biliary and intestinal disease, the transporters that secrete into bile, and enterohepatic recycling. A question about the kidney takes the first list; bile flow and recycling belong to the second.'}],
 teachImg:'el_renal_factors',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 9; slides 10–14 for each factor; hepatic factors slides 17–18',
 quote:'Kidney Disease · Glomerular Filtration Rate · Reabsorption or Back Diffusion of un-ionized drug · Active Tubular Secretion · Urinary pH'},

{id:'sa-el-3', prof:'Sikazwe', tier:'new', topic:'elim', sub:'renal', concept:'tubular-secretion-transporters', multi:true,
 tags:['list','enzyme'], source:'slide',
 stem:'Which of these renal tubular transporters secrete cationic drugs into the urine? Select all that apply.',
 options:[
  {t:'OCT2', correct:true,
   why:'Organic cation transporter 2, first in the cation line on Lecture 15 slide 13. A protonated amine is the kind of drug it carries.'},
  {t:'MDR1, also called P-glycoprotein', correct:true,
   why:'Multidrug resistance protein 1, the same efflux pump that returns drug to the gut lumen, listed under cations here.'},
  {t:'MATE1 and MATE2K', correct:true,
   why:'Multidrug and toxin extrusion proteins, the last entries in the cation line.'},
  {t:'OATP1 and OATP3', correct:false,
   why:'Organic anion transporting polypeptides 1 and 3 are in the anion line. Probenecid inhibits the renal OATPs and slows penicillin, an acid, which is the example on the slide.'},
  {t:'MRP2 and MRP4', correct:false,
   why:'Multidrug resistance-associated proteins 2 and 4, also in the anion line beside the OATPs.'}],
 teach:[
  {h:'Two lines on slide 13',
   t:'Anions: OATP1 and 3, MRP2 and 4. Cations: OCT2, MDR1, MATE1 and MATE2K. Each transporter moves drug from the blood side of the tubular cell into the urine, and each line takes one charge.'},
  {h:'Why the split decides an interaction',
   t:'An inhibitor acts on one line. Probenecid blocks the anion transporters, so it slows penicillin, an acid, and a drug carried by the cation line is not affected by an anion-transporter inhibitor. Slide 13 states the general rule: inhibitors and inducers of these transporters influence elimination.'}],
 teachImg:'el_tubular_transporters',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 13',
 quote:'Anions: OATP1 & 3; MRP2 & 4 · Cations: OCT2; MDR1; MATE1/MATE2K · Probenecid (inhibits renal OATPs & slows Penicillin excretion)'},

{id:'sa-el-4', prof:'Sikazwe', tier:'new', topic:'elim', sub:'ph', concept:'urinary-ph-rules', multi:true,
 tags:['reasoning','acidbase'], source:'slide',
 stem:'Which of the following statements about urinary pH and drug elimination are correct? Select all that apply.',
 options:[
  {t:'Acidic urine increases the elimination of a basic drug', correct:true,
   why:'Lecture 15 slide 14. In acidic urine a basic amine is protonated; the cation cannot cross the tubule back into blood, so it leaves in the urine.'},
  {t:'Basic urine increases the elimination of an acidic drug', correct:true,
   why:'Slide 14. A carboxylic acid in basic urine is a carboxylate, held in the urine by its charge. This is the direction used for aspirin.'},
  {t:'A drug must carry an ionisable functional group for pH trapping to apply', correct:true,
   why:'The Key line on slide 14. A neutral molecule with no acidic or basic group has the same charge at every pH, so changing the urine pH changes nothing about its reabsorption.'},
  {t:'Aspirin overdose is treated by alkalinising the urine with sodium bicarbonate', correct:true,
   why:'Slide 15. Salicylic acid ionises in the basic urine, cannot be reabsorbed, and is excreted faster.'},
  {t:'Acidic urine increases the elimination of an acidic drug', correct:false,
   why:'The reverse of the slide. Acidic urine keeps an acidic drug un-ionised, and the un-ionised form diffuses back into the circulation, slide 12, so elimination falls.'},
  {t:'Alkalinising the urine speeds the elimination of a basic drug', correct:false,
   why:'Basic urine leaves a base un-ionised and reabsorbable, so its elimination falls. Acidifying the urine is what traps a base.'}],
 teach:[
  {h:'One rule, four cases',
   t:'A drug is reabsorbed from the tubule only in its un-ionised form. An acid is un-ionised in acidic urine and ionised in basic urine; a base is the reverse. So acidic urine holds on to acids and expels bases, and basic urine holds on to bases and expels acids. Slide 14 states both lines; slide 15 applies the second to aspirin.'},
  {h:'The requirement',
   t:'Trapping needs an ionisable group. A drug or metabolite with no acidic or basic group is un-ionised at every urine pH and is reabsorbed regardless, which is why phenytoin on slide 7 is reabsorbed and why the Key line on slide 14 exists.'}],
 teachImg:'el_urinary_ph',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slides 14 and 15; reabsorption slide 12; phenytoin slide 7',
 quote:'Acidic urine: ↓ elim. of acidic drugs & ↑ elim. of basic drugs · Basic urine: ↓ elim. of basic drugs & ↑ elim. of acidic drugs · Key: Drugs/metabolites must have ionizable FGs'},

{id:'sa-el-5', prof:'Sikazwe', tier:'new', topic:'elim', sub:'hep', concept:'enterohepatic-recycling-facts', multi:true,
 tags:['reasoning','recall'], source:'slide',
 stem:'Which of the following are true of enterohepatic recycling? Select all that apply.',
 options:[
  {t:'Drug excreted in bile is reabsorbed from the intestine before it can leave in the feces', correct:true,
   why:'The definition on Lecture 15 slide 18. The drug makes a loop: liver, bile, intestine, portal blood, liver again.'},
  {t:'Oral activated charcoal or an anion-exchange resin can interrupt it', correct:true,
   why:'Slide 18: both trap the drug in the gut so it leaves in the feces instead of being reabsorbed.'},
  {t:'It lengthens a drug\'s duration of action', correct:true,
   why:'Slide 19: ezetimibe undergoes repeated cycling and has a long duration of action, with a half-life of 22 to 24 hours.'},
  {t:'Ezetimibe, isotretinoin and morphine are examples', correct:true,
   why:'The three named on slide 19. Ezetimibe is excreted in bile as its glucuronide, the sugar is cleaved in the gut, and the slide marks its half-life at 22 to 24 hours because of the repeated cycling.'},
  {t:'It shortens the half-life of the drugs that undergo it', correct:false,
   why:'The opposite. Each pass through the loop returns drug to the blood, so the drug persists; ezetimibe\'s 22-to-24-hour half-life is the example.'},
  {t:'It applies mainly to small polar drugs that the kidney filters', correct:false,
   why:'Bile is the route for lipid-soluble drugs and their metabolites, slide 16. A small polar drug is filtered by the kidney and never enters the loop.'}],
 teach:[
  {h:'The loop',
   t:'A drug or a conjugate is secreted into bile by the transporters on slide 17, reaches the intestine, and is reabsorbed into the portal blood, which returns it to the liver. For a glucuronide the step that makes it reabsorbable is on slide 20: β-glucuronidase from the gut microbiota cleaves the sugar off diclofenac, indomethacin and ketoprofen glucuronides and returns the parent acid, which is lipophilic enough to cross back. The 09/17 lecture (transcript) worked ezetimibe the same way: its glucuronide reaches bile, the sugar is cleaved in the intestine, and the parent recycles.'},
  {h:'Breaking it, and what that is for',
   t:'Oral charcoal or an anion-exchange resin binds the drug in the gut lumen, so the reabsorption step fails and the drug leaves in the feces. That is a treatment: slide 62 lists oral activated charcoal among the toxicity treatments, and the recycling slide is where the mechanism is explained.'}],
 teachImg:'el_ehr',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slides 18, 19 and 20; biliary route slide 16; transporters slide 17; lecture audio 09/17 (marked)',
 quote:'Drugs excreted via bile into the intestine undergo reabsorption ("recycling") prior to fecal elim. · Can be clinically disrupted using PO charcoal or anion exchange resins · Examples: Ezetimibe (Zetia), Isotretinoin, Morphine'},

/* ═══════════ TOXICITY — Lecture 15 ═══════════ */
{id:'sa-tox-3', prof:'Sikazwe', tier:'new', topic:'tox', sub:'causes', concept:'causes-of-toxicity-list', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'Which of the following are causes of a drug\'s on-target or off-target toxicity? Select all that apply.',
 options:[
  {t:'A toxicophore in the drug or in a metabolite', correct:true,
   why:'First on Lecture 15 slide 29: a toxic or potentially toxic functional group, present in the parent or made by metabolism.'},
  {t:'Dose, including overdose and narrow-therapeutic-index drugs', correct:true,
   why:'Second. Acetaminophen above 4 g a day is the worked overdose, slide 49; a narrow therapeutic index means the toxic dose sits close to the effective one.'},
  {t:'Drug interactions, including polypharmacy and displacement from binding sites', correct:true,
   why:'Third: polypharmacy and distribution-related interactions. One drug raises another\'s free or total level.'},
  {t:'Low deactivating enzyme capacity, from genetics or an inhibitor', correct:true,
   why:'Fourth. A poor metaboliser, or a patient on an inhibitor, clears an active drug slowly; a depleted glutathione pool clears an electrophile slowly.'},
  {t:'Idiosyncratic reactions', correct:true,
   why:'Fifth: unpredictable toxicity. It does not scale with dose and cannot be forecast from the structure, which separates it from the toxicophore and dose causes above it.'},
  {t:'Hypersensitivity and immune responses', correct:true,
   why:'Sixth. A hapten, slide 42, makes a protein adduct that the immune system attacks.'},
  {t:'High water solubility of the parent drug', correct:false,
   why:'Not a cause on the slide. A water-soluble drug is filtered and excreted by the kidney, slide 7, which shortens exposure rather than lengthening it.'},
  {t:'Rapid glucuronidation', correct:false,
   why:'Fast conjugation removes a drug or an electrophile; it is a defense. Toxicity appears when conjugation is exhausted, as with acetaminophen on slide 49, not when it is fast.'}],
 teach:[
  {h:'Six causes',
   t:'Slide 29 lists toxicophores, dose, drug interactions, low deactivating enzyme capacity, idiosyncratic reactions, and hypersensitivity or immune response. The first four are about how much reactive species is made and how fast it is removed; the last two are about the patient\'s response to it.'},
  {h:'Where each one is worked later',
   t:'Toxicophores fill slides 30 to 44. Dose is acetaminophen on slide 49. Enzyme capacity is the genetics and alcohol lines on slide 47 and the poor-metaboliser phenotypes of Lecture 13. Hypersensitivity is the hapten slide, 42.'}],
 teachImg:'tx_causes',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 29; overdose slide 49; haptens slide 42',
 quote:'Toxicophores (toxic/potentially toxic FGs) · Dose (overdose, Narrow TI drugs, etc.) · Drug Interactions (polypharmacy, distribution related, etc.) · Low deactivating Enzyme capacity (genetics, inhibitors, etc.) · Idiosyncratic reactions (unpredictable toxicity) · Hypersensitivity & Immune response related'},

{id:'sa-tox-4', prof:'Sikazwe', tier:'new', topic:'tox', sub:'hep', concept:'hepatotox-risk-factors', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'Which of the following raise a patient\'s risk of drug-induced liver injury? Select all that apply.',
 options:[
  {t:'Female sex', correct:true,
   why:'Lecture 15 slide 47 marks gender F>>M, with acetaminophen, halothane, diclofenac and sulindac as the drugs.'},
  {t:'Old age', correct:true,
   why:'Elderly patients are listed as vulnerable: lower clearance, less liver mass and blood flow, poor diet.'},
  {t:'Alcohol use', correct:true,
   why:'Alcohol induces cirrhosis and depletes glutathione, the pool that deactivates electrophiles such as NAPQI.'},
  {t:'Herbal remedies', correct:true,
   why:'The last item on the slide: they increase the risk of inducing liver toxicity.'},
  {t:'Sustained-release or long-acting drugs, and polypharmacy', correct:true,
   why:'The pharmacokinetics line: long exposure and many drugs at once.'},
  {t:'A genetic polymorphism that makes the patient a poor or an ultrarapid metaboliser', correct:true,
   why:'The genetics line: drug-metabolising enzyme phenotypes from ultrarapid to poor. Either extreme can raise the level of a toxic species, depending on whether the parent or a metabolite is the toxic one.'},
  {t:'Male sex', correct:false,
   why:'Slide 47 marks gender F>>M for acetaminophen, halothane, diclofenac and sulindac: women are at higher risk, not men.'},
  {t:'A wide therapeutic index', correct:false,
   why:'The pharmacodynamics line names overdose and narrow therapeutic index drugs. A wide index means the toxic dose is far above the effective one, which lowers the risk.'}],
 teach:[
  {h:'Eight lines on slide 47',
   t:'Genetics, age, gender, alcohol use, liver disease, pharmacokinetics, pharmacodynamics and herbal remedies. Four are about the patient as they are (genes, age, sex, existing liver disease including hepatitis B or C in HIV patients), two are about what they take with the drug (alcohol, herbals), and two are about the drug regimen (long-acting drugs and polypharmacy; overdose and narrow therapeutic index).'},
  {h:'Alcohol appears twice in the lecture',
   t:'On slide 47 it is a risk factor because cirrhosis lowers capacity and glutathione depletion removes the electrophile defense. On slide 42 ethanol is also the worked hapten, forming protein immunogens through its own metabolites. Both are hepatotoxicity, by different mechanisms.'}],
 teachImg:'tx_risk_factors',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 47; hapten slide 42',
 quote:'Genetics: polymorphisms (DME phenotypes – UM to PM) · Age: Elderly are vulnerable · Gender: F>>M (Acetaminophen/Halothane/Diclofenac/Sulindac) · Alcohol use: Induces liver cirrhosis, GSH depletion · Liver disease · Pharmacokinetics: SR-drugs, long-acting drugs, polypharmacy · Pharmacodynamics: Overdose, narrow TI drugs · Herbal remedies'},

{id:'sa-tox-5', prof:'Sikazwe', tier:'new', topic:'tox', sub:'hep', concept:'apap-napqi', multi:true,
 tags:['reasoning','mechanism'], source:'slide',
 stem:'Which of the following statements about acetaminophen (APAP) are correct? Select all that apply.',
 options:[
  {t:'At normal doses its major metabolites are the sulfate and glucuronide conjugates', correct:true,
   why:'Lecture 15 slide 49: at a normal dose APAP forms sulfates and glucuronides as the major metabolites, both Phase 2 products of the phenol.'},
  {t:'It is safe below about 4 g per day and hepatotoxic above that', correct:true,
   why:'Slide 49: safe at under 4 g a day, hepatotoxic at higher doses.'},
  {t:'In overdose the conjugating enzymes are exhausted and Phase 1 oxidation produces NAPQI', correct:true,
   why:'Slide 49: overdose exhausts the UGTs and sulfotransferases, and APAP undergoes Phase 1 bioactivation to NAPQI, N-acetyl-p-benzoquinoneimine. The arrow on the slide names CYP2E1, 1A2 and 3A4.'},
  {t:'N-acetylcysteine is the antidote, and it works by deactivating the electrophile', correct:true,
   why:'Slide 63: NAC is the antidote for APAP toxicity, by electrophile deactivation. It supplies the thiol that glutathione would have supplied.'},
  {t:'NAPQI is a Phase 2 conjugate', correct:false,
   why:'NAPQI is the Phase 1 oxidation product, made by CYP2E1, 1A2 or 3A4 once conjugation is saturated. The conjugates are the sulfate and the glucuronide, and those are the safe products.'},
  {t:'Overdose is treated by alkalinising the urine', correct:false,
   why:'Urine alkalinisation is the treatment for aspirin overdose, slide 15, because salicylic acid ionises and is trapped. Acetaminophen toxicity is treated with N-acetylcysteine.'}],
 teach:[
  {h:'Two doses, two fates',
   t:'At a normal dose the phenol is conjugated: sulfotransferase and UDP-glucuronosyltransferase make the sulfate and the glucuronide, and both leave in the urine. At an overdose those enzymes are saturated, the CYP route takes a larger share, and its product is NAPQI, a quinone-imine with an electrophilic double bond. NAPQI binds hepatic proteins and the adduct is the hepatotoxic species drawn on slide 49.'},
  {h:'Why a thiol is the antidote',
   t:'Glutathione normally traps NAPQI through its thiol. An overdose uses the glutathione up, which is also why alcohol use is a risk factor on slide 47. N-acetylcysteine supplies a thiol and restores the glutathione pool, so the electrophile is deactivated before it reaches a protein.'}],
 teachImg:'tx_apap_slide',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 49; antidote slide 63; aspirin slide 15; alcohol slide 47',
 quote:'Safe at < 4g/day; hepatotoxic at higher doses · Normal dose: APAP forms Sulfates & Glucuronides as maj. metabolites · Overdose: APAP exhausts UGTs/STs, and undergoes phase I bioactivation to NAPQI'},

{id:'sa-tox-6', prof:'Sikazwe', tier:'new', topic:'tox', sub:'mech', concept:'other-bioactivations', multi:true,
 tags:['reasoning','mechanism'], source:'slide',
 stem:'The toxicophore list ends with a group headed "others": haptens, azo groups and N-hydroxy groups. Which of the following are examples of toxicity through one of those three? Select all that apply.',
 options:[
  {t:'Ethanol, whose metabolites form hapten-protein immunogens', correct:true,
   why:'Lecture 15 slide 42: ethanol can form hapten-protein immunogens that trigger hepatic hypersensitivity. A hapten is too small to be immunogenic on its own and becomes so once bound to a protein.'},
  {t:'Urushiol, in poison ivy', correct:true,
   why:'The second hapten example on slide 42: urushiol forms hapten-protein immunogens, and the immune response to the adduct is the toxicity.'},
  {t:'Solvent Red 1, reduced to carcinogenic aromatic amines', correct:true,
   why:'Slide 43: azo reduction to carcinogens. The N=N bond is reduced and the two halves are released as aromatic amines.'},
  {t:'Acetylaminofluorene, N-hydroxylated and then sulfated to the carcinogen', correct:true,
   why:'Slide 44: N-hydroxylation to carcinogens. N-OH AAF is sulfated, and the sulfate leaves to give the reactive nitrenium species.'},
  {t:'Isoniazid', correct:false,
   why:'Isoniazid is the free-radical example on slide 39, the fourth toxicophore category, not one of the others group.'},
  {t:'Aflatoxin B1', correct:false,
   why:'Aflatoxin B1 is a bioactivated electrophilic carbon, slide 34: a CYP makes the epoxide and the epoxide binds DNA. That is the first category on slide 30.'}],
 teach:[
  {h:'The three "other" mechanisms',
   t:'Haptens, azo groups and N-hydroxy groups are grouped on slide 30 because none of them is an electrophilic carbon, carbonyl, double bond or free radical as found. A hapten works through the immune system after it binds a protein. An azo group is reduced to two aromatic amines, which are the carcinogens. An N-hydroxy group is made by a CYP and then sulfated, and the sulfate is the leaving group that produces the reactive species.'},
  {h:'Placing an example',
   t:'Ask what the reactive species is. If it is an epoxide or an acyl chloride, the category is an electrophilic carbon or carbonyl. If it is a radical, the category is free radicals. If the harm needs the immune system, a reduction of N=N, or an N-OH that is sulfated, it is one of the others. Slides 42 to 44 give one example of each.'}],
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slides 42, 43 and 44; category list slide 30; isoniazid slide 39; aflatoxin slide 34',
 quote:'Hapten-immunogens can trigger hepatic hypersensitivity: Ethanol, Urushiol · Azo reduction to carcinogens: Solvent Red 1 · N-hydroxylations to carcinogens: Acetylaminofluorene (AAF)'},

{id:'sa-tox-7', prof:'Sikazwe', tier:'new', topic:'tox', sub:'def', concept:'toxicity-treatments-list', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'Which of the following are general treatments for drug toxicity? Select all that apply.',
 options:[
  {t:'An antidote that reverses or reduces the toxicity', correct:true,
   why:'First on Lecture 15 slide 62. N-acetylcysteine for acetaminophen, slide 63, and pralidoxime for organophosphates, slide 64.'},
  {t:'Supportive care', correct:true,
   why:'Second on slide 62: treatment directed at the patient\'s condition while the toxin is removed, which is what remains when no specific antidote exists.'},
  {t:'Oral activated charcoal, given within about an hour of ingestion', correct:true,
   why:'Third, with the one-hour window stated on the slide: charcoal can only adsorb toxin that is still in the gut.'},
  {t:'Enhanced elimination: forced diuresis, ion trapping, dialysis or hemoperfusion', correct:true,
   why:'Fourth. Ion trapping is the urinary pH method from slide 15; dialysis and hemoperfusion remove drug from the blood directly.'},
  {t:'Inducing CYP450 to speed clearance of the toxin', correct:false,
   why:'Induction takes days to raise enzyme levels, and for a toxin that is bioactivated it would make more of the toxic species. It is not on the slide.'},
  {t:'Alkalinising the urine to trap a basic drug', correct:false,
   why:'Alkaline urine leaves a base un-ionised and reabsorbable. Ion trapping is a treatment, but a base is trapped by acidifying the urine and an acid by alkalinising it.'}],
 teach:[
  {h:'Four headings on slide 62',
   t:'Antidotes, supportive care, oral activated charcoal within one hour, and enhanced elimination, which the slide expands to forced diuresis, ion trapping, dialysis, hemoperfusion, hemofiltration and exchange transfusion. The first acts on the toxin\'s chemistry, the second on the patient, the third on toxin not yet absorbed, and the fourth on toxin already in the blood.'},
  {h:'The two antidotes that follow',
   t:'Slide 63: N-acetylcysteine deactivates the NAPQI electrophile. Slide 64: pralidoxime, an oxime, regenerates the cholinesterases that an organophosphate has phosphorylated, with two limits: it does not cross the blood-brain barrier, and it must be given before the phosphorylated enzyme ages into a form that cannot be reactivated.'}],
 teachImg:'tx_treatments',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 62; NAC slide 63; 2-PAM slide 64; pH trapping slide 15',
 quote:'Antidotes to reverse or reduce toxicity · Supportive care · PO activated charcoal (within 1h of toxin ingestion) · Enhanced elimination (forced diuresis, ion trapping, dialysis, hemoperfusion, hemofiltration, exchange transfusion, etc.)'},

/* ═══════════ FUNCTIONAL GROUPS AND METABOLISM — Lecture 14 ═══════════ */
{id:'sa-fg-2', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'ester', concept:'ce-hydrolysis-groups', multi:true,
 tags:['list','enzyme'], source:'slide',
 stem:'Which of these functional groups are hydrolysed by carboxylesterases (CE)? Select all that apply.',
 options:[
  {t:'Ester', correct:true,
   why:'Lecture 14 slide 16: esters undergo CE hydrolysis, to the acid and the alcohol. Amides are more stable than esters in vivo, slide 8, so the ester is the group that goes first.'},
  {t:'Amide', correct:true,
   why:'Slide 8: amides undergo CE hydrolysis but are more stable in vivo than esters, because the nitrogen lone pair delocalises into the carbonyl and leaves the carbonyl carbon less electrophilic.'},
  {t:'Carbamate', correct:true,
   why:'Slide 15: CE hydrolysis gives an amine and an alcohol, with carbon dioxide from the unstable carbamic acid.'},
  {t:'Carbonate', correct:true,
   why:'Slide 14: carbonates undergo CE hydrolysis, giving two alcohols and carbon dioxide.'},
  {t:'Ether', correct:false,
   why:'An ether has no carbonyl for the esterase to attack. Its metabolism is O-dealkylation by a CYP, slide 17.'},
  {t:'Epoxide', correct:false,
   why:'An epoxide is hydrolysed, but by epoxide hydrolase, slide 20, to a diol; it is also conjugated by glutathione S-transferase. No carboxylesterase is involved because there is no acyl group.'},
  {t:'Thioether', correct:false,
   why:'A thioether is oxidised at sulfur to the sulfoxide, slide 18, or S-dealkylated, slide 19. Nothing in it is hydrolysable.'}],
 svg:DIA.acylFamily,
 teach:[
  {h:'The four, sorted by what sits on the carbonyl carbon',
   t:'One oxygen makes an ester, one nitrogen an amide, one of each a carbamate, two oxygens a carbonate. Water attacks the carbonyl carbon and each heteroatom leaves as its own fragment: oxygen as an alcohol, nitrogen as an amine, and a carbon substituent stays behind as the acid. The functional group deck states the same four on slide 52: esters, carbonates, amides and carbamates undergo hydrolytic metabolism by carboxylesterase.'},
  {h:'Hydrolysable is not the same as a CE substrate',
   t:'An epoxide and a phosphate ester are both hydrolysed, by epoxide hydrolase, slide 20, and by phosphatase, slide 27. Carboxylesterase needs an acyl group, a carbonyl carbon with a heteroatom beside it, which is what the four substrates share and the three distractors lack.'}],
 teachImg:'fgd_ce_substrates',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 8, 14, 15 and 16; ether slide 17; thioether slides 18–19; epoxide slide 20; Functional group deck (MCFGs8_1718_26.pdf) slide 52',
 quote:'Amides: Undergo carboxylesterase (CE) hydrolysis, but are more stable in vivo than esters · Carbonates undergo CE hydrolysis · Carbamates: Undergo CE hydrolysis to give amines and … · Esters undergo CE hydrolysis'},

/* ═══════════ FACTORS INFLUENCING METABOLISM — Lecture 14 ═══════════ */
{id:'sa-fa-1', prof:'Sikazwe', tier:'new', topic:'factors', sub:'phys', concept:'intrinsic-factor-list', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'Which of the following are physiological factors, properties of the patient rather than of the drug or of an outside agent, that influence drug metabolism? Select all that apply.',
 options:[
  {t:'Presence of the drug-metabolising enzymes in the tissue', correct:true,
   why:'First under Physiological on Lecture 14 slide 33, and slide 41 maps which tissues hold which enzymes.'},
  {t:'Supply of the enzyme co-factors', correct:true,
   why:'Second, with the Phase 2 co-factors on slide 42 and in the tables on slides 29 and 30: UDPGA, PAPS, glutathione, acetyl-CoA, S-adenosylmethionine. Without the co-factor the transferase has nothing to transfer.'},
  {t:'Disease', correct:true,
   why:'Third. Slide 43 tabulates liver disease, cardiac disease, inflammation and thyroid disease against their effect on enzyme activity.'},
  {t:'Age', correct:true,
   why:'Fourth. Slides 44 to 47: enzyme maturation in the fetus and neonate, then the elderly, with less liver mass and endoplasmic reticulum, less liver blood flow and lower renal filtration.'},
  {t:'Gender', correct:true,
   why:'Fifth on slide 33; slide 48 titles it sexual dimorphism in drug metabolism, a difference in enzyme activity between the sexes.'},
  {t:'Genetics', correct:true,
   why:'Sixth. Slide 49: the polymorphic CYPs 2A6, 2C9, 2C19 and 2D6, and the CYP2D6 phenotypes from poor to ultrarapid metaboliser.'},
  {t:'Dose of the parent drug', correct:false,
   why:'Dose is on the same slide but under Parent Drug, with route, absorption, distribution and physicochemical properties: facts about the drug, not the patient.'},
  {t:'Induction by rifampin or St John\'s wort', correct:false,
   why:'An inducer is an extrinsic factor, slides 51 to 58. It comes from outside both the patient and the drug being metabolised.'}],
 teach:[
  {h:'Intrinsic splits into two columns',
   t:'Slide 33 has Parent Drug on one side, dose, route of administration, absorption, distribution and physicochemical properties, and Physiological on the other, enzyme presence, enzyme co-factors, disease, age, gender and genetics. Extrinsic factors, induction and inhibition by other drugs, food and smoke, are a separate section from slide 51.'},
  {h:'Three headings, one question to sort them',
   t:'Is the factor a property of the molecule, of the patient, or of something taken alongside? Dose and route belong to the molecule and its regimen. Enzymes, co-factors, disease, age, gender and genes belong to the patient. Rifampin, grapefruit juice and cigarette smoke are taken alongside.'}],
 teachImg:'fa_intrinsic_factors',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 33; tissue enzymes slide 41; co-factors slide 42; disease slide 43; age slides 44–47; gender slide 48; genetics slides 49–50; extrinsic factors slides 51–66',
 quote:'Physiological: DME presence · DME co-factors · Disease · Age · Gender · Genetics | Parent Drug (PD): Dose (overdosing) · Route of Administration · Absorption · Distribution (protein or tissue binding) · *Physicochemical (PC) properties'},

{id:'sa-fa-2', prof:'Sikazwe', tier:'new', topic:'factors', sub:'phys', concept:'liver-disease-effect', multi:true,
 tags:['reasoning','recall'], source:'slide',
 stem:'Which of the following correctly describe how a disease state changes drug-metabolising enzyme (DME) activity? Select all that apply.',
 options:[
  {t:'Liver disease decreases DME activity', correct:true,
   why:'First row of the table on Lecture 14 slide 43. Less functioning liver, less enzyme.'},
  {t:'Cardiac disease decreases DME activity because less blood reaches the liver', correct:true,
   why:'Second row: decreased activity due to reduced liver blood flow. The enzyme is intact; the drug reaches it more slowly.'},
  {t:'Inflammation and infection decrease DME activity', correct:true,
   why:'Third row of the table: decreased activity, in the same direction as liver disease, so a hepatically cleared drug persists longer during an infection.'},
  {t:'Hyperthyroidism elevates DME activity because protein synthesis rises', correct:true,
   why:'Fourth row: thyroid disease with increased protein synthesis in hyperthyroidism gives elevated activity. The only row on the table where activity goes up.'},
  {t:'Hyperthyroidism decreases DME activity', correct:false,
   why:'The table gives the opposite: elevated activity, because more enzyme protein is made.'},
  {t:'The effect of a disease on metabolism is always predictable', correct:false,
   why:'The note under the table: effects on drug metabolism are not always predictable. The table gives the usual direction, not a guarantee.'}],
 teach:[
  {h:'Three down, one up',
   t:'Liver disease, cardiac disease and inflammation or infection all lower enzyme activity, by different routes: lost liver tissue, less blood delivering drug to the liver, and the inflammatory response itself. Hyperthyroidism raises it, because the thyroid state raises protein synthesis and the enzymes are proteins.'},
  {h:'When it matters',
   t:'The second note on slide 43: the effect is key if the drug must be metabolised by the liver before elimination. A drug excreted unchanged by the kidney is not affected by any of the four rows.'}],
 teachImg:'fa_disease',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 43',
 quote:'Liver disease: Decreased DME activity · Cardiac disease (blood flow): Decreased DME activity due to reduced liver blood flow · Inflammation/Infections: Decreased DME activity · Thyroid disease (↑ protein synthesis in hyperthyroidism): Elevated DME activity · Effects on DM are not always predictable'},

{id:'sa-fa-3', prof:'Sikazwe', tier:'new', topic:'factors', sub:'pd', concept:'protein-binding-metabolism', multi:true,
 tags:['reasoning','recall'], source:'slide',
 stem:'Which of the following statements about serum protein binding and drug metabolism are correct? Select all that apply.',
 options:[
  {t:'Protein binding decreases metabolism and lengthens the drug\'s half-life', correct:true,
   why:'Lecture 14 slide 38, first line. Bound drug is not available to the enzyme, so clearance slows and the half-life grows.'},
  {t:'Weak acids bind to albumin', correct:true,
   why:'Slide 38. Warfarin, the NSAIDs and the sulfonamides are the examples given.'},
  {t:'Weak bases bind to α1-acid glycoprotein', correct:true,
   why:'Slide 38, the line after the acids: a weak base, a cation at blood pH, binds the acidic glycoprotein, while albumin takes the acids.'},
  {t:'Only the free, unbound drug is available for metabolism', correct:true,
   why:'The note on slide 38, repeated on slide 39 for tissue binding.'},
  {t:'Weak bases bind mainly to albumin', correct:false,
   why:'Reversed: albumin takes the weak acids; the weak bases go to α1-acid glycoprotein.'},
  {t:'Bound drug is metabolised faster because the protein delivers it to the liver', correct:false,
   why:'Bound drug is not metabolised while it is bound. Binding lowers metabolism and raises the half-life, the first line on the slide.'}],
 teach:[
  {h:'Two proteins, two kinds of drug',
   t:'Albumin carries the weak acids, warfarin, the NSAIDs and the sulfonamides; α1-acid glycoprotein carries the weak bases. In both cases the bound fraction is out of reach of the enzyme, so a highly bound drug is metabolised slowly and lasts longer.'},
  {h:'Serum binding and tissue binding',
   t:'Slide 39 adds tissue binding, reversible or covalent, non-specific to proteins or lipids. It raises the total drug concentration in the tissue, free plus bound, and the same note applies: only the free drug is available for metabolism.'}],
 teachImg:'fa_protein_binding',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 38; tissue binding slide 39',
 quote:'Protein binding ↓ metabolism and increases drug t1/2 · Examples: Warfarin; NSAIDs, Sulfonamides · Weak acids bind to albumin · Weak bases bind to α-1 acid glycoproteins · Note: Only the Free or un-bound drug is available for metabolism'}
);
