/* ==========================================================================
   QUESTIONS FROM THE GAPS IN LOUIS'S QUIZLET SETS (09/20)
   ==========================================================================
   Louis's three Quizlet decks (09.15, 09.16, 09.17 lectures) were checked
   card by card against the bank. Most cards were already covered; these are
   the facts that were not, each verified against the rendered slide before it
   was written. Select-all items follow the q10/q11 schema.
   ========================================================================== */
QUESTIONS.push(

/* ═══════════ LECTURE 13 — CYP ═══════════ */
{id:'sa-cyp-5', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'why', concept:'cyp-endobiotic-substrates', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'CYPs metabolise the body\'s own molecules as well as foreign ones. Which of the following are endobiotic substrates of CYP metabolism? Select all that apply.',
 options:[
  {t:'Cholesterol', correct:true,
   why:'First in the endobiotic column of Lecture 13 slide 5. Cholesterol is made in the body and CYPs oxidise it on the way to bile acids and steroid hormones.'},
  {t:'Steroids', correct:true,
   why:'Second in the column. Steroid hormones are built from cholesterol and taken apart by CYP hydroxylations.'},
  {t:'Bile acids', correct:true,
   why:'Third in the column. The oxidations that turn cholesterol into a bile acid are CYP reactions.'},
  {t:'Vitamin D', correct:true,
   why:'Fourth. The hydroxylations that activate vitamin D are CYP reactions.'},
  {t:'Fatty acids, retinoic acid and arachidonic acid', correct:true,
   why:'The last three of the column. All three are the body\'s own lipids, oxidised by CYPs.'},
  {t:'Pesticides, household and agricultural', correct:false,
   why:'Pesticides are in the xenobiotic box on the same slide, with drug molecules, chemical pollutants and dietary chemicals: foreign compounds, not molecules the body makes.'},
  {t:'Drug molecules', correct:false,
   why:'The first entry of the xenobiotic box. A drug is a foreign molecule, which is what xenobiotic means; the endobiotic list holds what the body synthesises itself.'}],
 teach:[
  {h:'Two columns on slide 5',
   t:'Endobiotic metabolism: cholesterol, steroids, bile acids, vitamin D, fatty acids, retinoic acid, arachidonic acid. Xenobiotic metabolism: drug molecules, chemical pollutants, pesticides (household and agricultural), dietary chemicals. The same enzyme family handles both, which is the first of the two reasons on slides 5 to 7 that CYPs matter in pharmacy.'},
  {h:'Why the endobiotic list matters for a drug',
   t:'An enzyme that oxidises steroids and vitamin D is an enzyme a drug can compete with or induce. Slide 33 lists glucocorticoids among the inducers, and slide 17 lists estradiol, progesterone and testosterone among CYP3A substrates: the body\'s own molecules sit in the same substrate lists as the drugs.'}],
 teachImg:'cyp_endo_xeno',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 5; substrate table slide 17; inducer table slide 33',
 quote:'Endobiotic metabolism: Cholesterol · Steroids · Bile Acids · Vitamin D · Fatty Acids · Retinoic Acid · Arachidonic Acid | Xenobiotic metabolism: Drug molecules · Chemical Pollutants · Pesticides (House hold vs. Agricultural) · Dietary chemicals'},

{id:'sa-cyp-6', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'poly', concept:'cyp2d6-pm-population-effects', multi:true,
 tags:['reasoning','list'], source:'slide',
 stem:'Some 20 to 30 million people carry no functional CYP2D6, the poor metabolisers. Which of the following follow for them at an ordinary dose of a CYP2D6 substrate? Select all that apply.',
 options:[
  {t:'Drug metabolism is too slow', correct:true,
   why:'The first consequence in the poor-metaboliser box of Lecture 13 slide 40. With no enzyme, the CYP2D6 route is closed.'},
  {t:'Drug levels are too high at ordinary dosage', correct:true,
   why:'Second in the box. A dose sized for a patient who clears the drug at the usual rate accumulates in one who cannot.'},
  {t:'High risk of adverse drug reactions', correct:true,
   why:'Third in the box, and the consequence of the second: the high level of an active drug is what produces the toxicity.'},
  {t:'No response to certain prodrugs, codeine for example', correct:true,
   why:'Fourth in the box. Codeine is O-demethylated to morphine by CYP2D6, Lecture 11 slide 17; with no enzyme, no morphine is made and the analgesia does not appear.'},
  {t:'Drug metabolism is too rapid', correct:false,
   why:'That is the ultrarapid-metaboliser box on the same slide: 15 to 20 million people with CYP2D6 gene duplications clear the drug too fast.'},
  {t:'No drug response at ordinary dosage, the non-responders', correct:false,
   why:'Also the ultrarapid box. An active drug is cleared before it can act, so the ordinary dose gives no response. For a poor metaboliser the active drug does the opposite and accumulates; the poor metaboliser\'s non-response is limited to prodrugs.'}],
 teach:[
  {h:'Two boxes on slide 40',
   t:'Poor metabolisers, 20 to 30 million with no CYP2D6: too slow metabolism, too high drug levels at ordinary dosage, high risk of adverse drug reactions, no response to certain prodrugs such as codeine. Ultrarapid metabolisers, 15 to 20 million with gene duplications: too rapid metabolism, no drug response at ordinary dosage. The numbers are the slide\'s.'},
  {h:'Active drug and prodrug run opposite ways',
   t:'For an active drug, the poor metaboliser accumulates it and the ultrarapid metaboliser loses it. For a prodrug the direction reverses: the poor metaboliser cannot make the active metabolite and gets no effect, the ultrarapid metaboliser makes it fast and gets more effect or toxicity. Codeine is the prodrug example on the slide, and slides 41 and 42 draw the exposure curves for both cases.'}],
 teachImg:'cyp_pm_um_populations',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 40; exposure curves slides 41–42; codeine O-demethylation Lecture #11 (MCMet-9_10_26.pdf) slide 17',
 quote:'20–30 million subjects have no CYP2D6 enzymes (PMs): Too slow drug metabolism · Too high drug levels at ordinary dosage · High risk for ADRs · No response from certain prodrugs (e.g. codeine) | 15–20 million subjects have CYP2D6 gene duplications (UMs): Too rapid drug metabolism · No drug response at ordinary dosage (non-responders)'},

{id:'sa-cyp-7', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'fam', concept:'cyp2d6-profile', multi:true,
 tags:['list','recall'], source:'slide',
 stem:'Which of the following are true of CYP2D6? Select all that apply.',
 options:[
  {t:'It is minimally inducible', correct:true,
   why:'First bullet on Lecture 13 slide 26: minimal induction. Its drug interactions come from inhibition and from genetics, not from inducers.'},
  {t:'It is polymorphic, with ultrarapid, extensive, intermediate and poor metaboliser phenotypes', correct:true,
   why:'Second bullet. The four phenotypes, and slide 40 gives the population sizes at the two extremes.'},
  {t:'It accounts for about 3% of liver CYP yet metabolises about 21% of clinical drugs', correct:true,
   why:'Third and fifth bullets: 3% of liver CYPs, 21% of clinical drugs. A small amount of enzyme carrying a large substrate load is easily saturated or blocked, which is why CYP2D6 accounts for so many drug interactions.'},
  {t:'It is stereoselective', correct:true,
   why:'Fourth bullet. The enzyme can metabolise one stereoisomer of a drug faster than the other, so the two isomers of a racemic drug can have different fates.'},
  {t:'Codeine and venlafaxine are substrates', correct:true,
   why:'The examples under the last bullet.'},
  {t:'It is strongly induced by rifampin and carbamazepine', correct:false,
   why:'CYP2D6 is minimally inducible, the first bullet on slide 26. Rifampin and carbamazepine are CYP3A inducers on slide 32; CYP2D6 is not on the inducible list.'},
  {t:'It is the most abundant CYP in the liver', correct:false,
   why:'At 3% it is one of the least abundant. Its importance comes from the share of drugs it handles, not from its amount.'}],
 teach:[
  {h:'The six bullets of slide 26',
   t:'Minimal induction; polymorphic phenotypes UM, EM, IM, PM; lots of drug interactions because of low expression, 3% of liver CYPs; stereoselectivity; lots of substrates, 21% of clinical drugs; codeine and venlafaxine as examples. Everything on the slide follows from one fact: a small, variable amount of enzyme that a great many drugs depend on.'},
  {h:'What minimal induction changes',
   t:'A drug cleared by CYP3A4 can be lost to an inducer such as rifampin. A drug cleared by CYP2D6 cannot, because the enzyme is not induced; what changes its clearance is an inhibitor or the patient\'s own genotype. The interaction check for a CYP2D6 substrate is therefore inhibitors and phenotype, not inducers.'}],
 teachImg:'cyp_2d6_profile',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 26; phenotype populations slide 40; CYP3A inducers slide 32',
 quote:'CYP isoform 2D6: Minimal induction · Polymorphic phenotypes: UM; EM; IM; PM · Lots of DDIs due to low expression, i.e., 3% of liver CYPs · Stereo-selectivity · Lots of substrates (21% of clinical drugs): Codeine, Venlafaxine, etc.'},

/* ═══════════ LECTURE 14 — functional groups and factors ═══════════ */
{id:'fg-27', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'ester', concept:'lactone-hydrolysis-product',
 tags:['structure','reasoning'], source:'slide',
 stem:'A carboxylesterase hydrolyses a lactone (cyclic ester). What is the product?',
 options:[
  {t:'One molecule with both acid and alcohol', correct:true,
   why:'Lecture 14 slide 16 draws it under the ester line: the lactone ring on the left, the opened chain on the right with a carboxylic acid at one end and a hydroxyl at the other. In an acyclic ester the acid and the alcohol are two molecules; in a lactone the same two groups are joined by the rest of the ring, so hydrolysis gives one larger, more polar molecule.'},
  {t:'A carboxylic acid and a separate alcohol', correct:false,
   why:'That is the top line of slide 16, the acyclic ester. The bond broken is the same, but in a lactone the acyl carbon and the alcohol oxygen are held in one ring, so cutting it opens the ring instead of separating two fragments.'},
  {t:'A carboxylic acid and a separate amine', correct:false,
   why:'An amine comes from an amide, slide 8, where the ring version is a lactam. A lactone has oxygen in the ring, so the product carries a hydroxyl, not an amine.'},
  {t:'Carbon dioxide and a diol', correct:false,
   why:'Carbon dioxide leaves when a carbonate or a carbamate is hydrolysed, slides 14 and 15, because the carbonyl carbon carries two heteroatoms and departs as CO2. A lactone carbonyl carries one oxygen and one carbon, so the carbon stays in the product as the acid.'}],
 teach:[
  {h:'Ring esters and ring amides open, they do not fragment',
   t:'Slide 16 pairs the acyclic ester with the lactone, and slide 8 pairs the acyclic amide with the lactam. Both hydrolyses break the same carbonyl-to-heteroatom bond. In the open-chain case two molecules result; in the ring case the two products are still tethered by the ring carbons, so one molecule results, carrying an acid and a hydroxyl (lactone) or an acid and an amine (lactam).'},
  {h:'What that does to the drug',
   t:'A lactone is neutral and fairly lipophilic; the opened hydroxy acid carries a carboxylic acid, ionised at body pH, and a free hydroxyl, both of which are Phase 2 handles from slide 29. So the hydrolysis is a Phase 1 step that raises polarity and offers a conjugation site, and for a drug whose activity depends on the ring it is also an inactivation.'}],
 teachImg:'fgm_ester',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 16; lactam slide 8; carbonate and carbamate slides 14–15',
 quote:'Esters: Esters undergo CE hydrolysis'},

{id:'fa-12', prof:'Sikazwe', tier:'new', topic:'factors', sub:'pd', concept:'first-pass-examples',
 tags:['matching','recall'], source:'slide',
 stem:'Isoproterenol, lidocaine and nitroglycerin are examples of drugs with a significant first-pass effect. Which pairing of drug and first-pass enzyme is correct?',
 options:[
  {t:'Isoproterenol: COMT and sulfation; lidocaine: CYPs and carboxylesterase; nitroglycerin: glutathione S-transferase (GST)', correct:true,
   why:'Lecture 14 slide 36 prints the three under the oral route, each with its enzymes: isoproterenol (COMT/sulfation), lidocaine (CYPs/CE, PO ineffective), nitroglycerin (GST/buccal admin.). Each drug is removed by a different enzyme system before it reaches the systemic circulation.'},
  {t:'Isoproterenol: CYPs and carboxylesterase; lidocaine: COMT and sulfation; nitroglycerin: GST', correct:false,
   why:'The first two are swapped. Isoproterenol is a catechol, two adjacent phenolic hydroxyls, which is what catechol-O-methyltransferase and sulfotransferase act on. Lidocaine has an amide and a tertiary amine, the handles for a carboxylesterase and a CYP.'},
  {t:'Isoproterenol: COMT and sulfation; lidocaine: GST; nitroglycerin: CYPs', correct:false,
   why:'Nitroglycerin is the glutathione S-transferase case, and the slide\'s answer to its first-pass loss is buccal administration, which enters the circulation without passing the liver first. Lidocaine has no electrophile for glutathione to attack.'},
  {t:'All three: gut-wall CYP3A4', correct:false,
   why:'The slide names a different route for each, and only one of the three involves a CYP at all. Nitroglycerin is given buccally rather than intravenously to escape the first pass.'}],
 teach:[
  {h:'Three drugs, three enzyme systems',
   t:'Slide 36 illustrates the route-of-administration factor with three structures. Isoproterenol carries a catechol, so catechol-O-methyltransferase and sulfotransferase conjugate it before it reaches the circulation. Lidocaine carries an amide and a tertiary amine, so carboxylesterase and CYPs take it apart, and the slide marks it PO ineffective. Nitroglycerin, a nitrate ester, is handled by glutathione S-transferase, and the slide marks buccal administration as the answer.'},
  {h:'Reading the structure tells you the enzyme',
   t:'The functional groups on each drug are the reason each enzyme system applies, and slide 36 shows structures rather than names so that the reason can be read off the drawing. A catechol is a methyltransferase and sulfotransferase substrate; an amide is a carboxylesterase substrate; a nitrate ester meets glutathione. The pre-systemic sites, gut wall and first liver pass, are on slide 35.'}],
 teachImg:'fa_route',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 36; pre-systemic sites slide 35',
 quote:'Examples of Drugs with significant 1st pass effect: Isoproterenol (COMT/Sulfation) · Lidocaine (CYPs/CE, PO ineffective) · Nitroglycerin (GST/Bucal Admin.)'},

{id:'fa-13', prof:'Sikazwe', tier:'new', topic:'factors', sub:'inhib', concept:'gfj-felodipine-plot',
 tags:['case','reasoning'], source:'slide', img:'fa_gfj_felodipine',
 stem:'The plot shows felodipine plasma concentration after one oral dose taken with water and with grapefruit juice. What explains the difference between the two curves?',
 options:[
  {t:'Furocoumarins inhibit gut-wall CYP3A4; less first-pass loss', correct:true,
   why:'Lecture 14 slides 62 and 63: grapefruit juice contains furocoumarins, bergamottin and 6\',7\'-dihydroxybergamottin the most abundant, and they are mechanism-based inhibitors of CYP3A4. Felodipine is a CYP3A4 substrate with a large first-pass loss, so blocking the enzyme lets more of the same oral dose through. On the plot the peak with juice is close to four times the peak with water, read from the axis at about 10 to 11 nmol/L against about 2.5.'},
  {t:'The juice induces CYP3A4; faster clearance', correct:false,
   why:'Induction would lower the curve, not raise it, and it takes days, not one dose. The juice curve is higher, which is the signature of inhibition.'},
  {t:'Juice acid improves felodipine dissolution', correct:false,
   why:'The slides attribute the effect to furocoumarins acting on CYP3A4, an enzyme, not to pH or dissolution. Slide 35 of Lecture 13 lists which drugs are affected, and they are CYP3A4 substrates, not drugs with a solubility problem.'},
  {t:'The juice blocks renal excretion', correct:false,
   why:'Felodipine is a lipophilic dihydropyridine cleared by metabolism, not by the kidney, and nothing on the slides places the juice at the kidney. The difference is set in the first pass through the gut wall and liver.'}],
 teach:[
  {h:'Reading the plot',
   t:'Both curves rise after the dose and fall over 24 hours. With water the peak is about 2.5 nmol/L; with grapefruit juice it is about 10 to 11 nmol/L at 2 to 3 hours, and the curve stays above the water curve for the rest of the day. A higher curve from the same oral dose means more of the dose reached the circulation.'},
  {h:'Why an inhibitor in the gut changes an oral dose so much',
   t:'Felodipine is metabolised by CYP3A4 in the intestinal wall and the liver before it reaches the systemic circulation. The furocoumarins in the juice are mechanism-based inhibitors, slide 63: the enzyme converts them to a species that inactivates it, so the gut-wall CYP3A4 is lost until new enzyme is made. Slide 35 of Lecture 13 tabulates the drugs affected the same way: the dihydropyridines, several statins, buspirone, midazolam and triazolam, cyclosporine.'}],
 teachImg:'fa_dietary_inh',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 66; furocoumarins slides 62–63; affected drugs Lecture #13 (MCMet-9_15_2026.pdf) slide 35',
 quote:'Q: Explain the inhibition plot below involving GFJ and Felodipine intake.'},

{id:'fa-14', prof:'Sikazwe', tier:'new', topic:'factors', sub:'induce', concept:'cyclosporin-induction-case',
 tags:['case','reasoning'], source:'slide',
 stem:'Cyclosporin A, an immunosuppressant given to prevent transplant rejection, is a CYP3A4 substrate. Co-administration with a CYP3A4 inducer can result in transplant failure. Explain.',
 options:[
  {t:'More CYP3A4; faster inactivation; immunosuppression lost', correct:true,
   why:'Lecture 14 slide 55 draws cyclosporin A going to inactive metabolites under CYP3A4. Slide 53 gives the rule: induction raises enzyme levels and activity, and for an active drug that means lower blood levels, shorter duration of action and reduced efficacy. Immunosuppression is the efficacy here, and losing it is what lets the transplant be rejected.'},
  {t:'Higher cyclosporin levels; graft-kidney toxicity', correct:false,
   why:'Direction reversed. An inducer lowers the level of a drug that is metabolised by the induced enzyme. Raised cyclosporin levels are what an inhibitor produces: slide 65 pairs ketoconazole with cyclosporin and lists immunosuppression as the outcome.'},
  {t:'Inducer competes for CYP3A4; cyclosporin accumulates', correct:false,
   why:'Competition for the enzyme is inhibition, not induction, and it would raise cyclosporin rather than lower it. An inducer makes more enzyme; it does not occupy it.'},
  {t:'Inducer forms an active metabolite that attacks the graft', correct:false,
   why:'Slide 55 labels the CYP3A4 products inactive metabolites. Cyclosporin is an active drug, not a prodrug, so more metabolism means less drug, not a new active species.'}],
 teach:[
  {h:'The case, worked',
   t:'Cyclosporin A is an active drug that CYP3A4 turns into inactive metabolites. Add an inducer, rifampin, carbamazepine, phenytoin, St John\'s wort or the others on slide 54, and over days the patient makes more CYP3A4. The same dose of cyclosporin is now cleared faster, its blood level falls below what suppresses the immune response, and the transplanted organ is attacked. The slide asks for exactly this chain: inducer, more enzyme, less drug, less effect.'},
  {h:'The same drug in the inhibition table',
   t:'Slide 65 puts cyclosporin with ketoconazole and gives the outcome as immunosuppression: an inhibitor raises the level and the effect goes too far. One drug, two interactions in opposite directions, and the direction follows from whether the second drug adds enzyme or blocks it.'}],
 teachImg:'fa_cyclosporin_case',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 55; induction rule slide 53; inducers slide 54; ketoconazole pairing slide 65',
 quote:'Cyclosporin A (CsA, immunosuppressant used to prevent transplant rejection), is substrate of 3A4. Co-administration of CsA with 3A4 inducers can result in transplant failure. Explain?'},

{id:'sa-fa-4', prof:'Sikazwe', tier:'new', topic:'factors', sub:'inhib', concept:'ddi-inhibition-outcomes', multi:true,
 tags:['matching','case'], source:'slide',
 stem:'Each of these pairs an enzyme inhibitor with a drug whose metabolism it blocks and the clinical outcome. Which pairings are correct? Select all that apply.',
 options:[
  {t:'Metronidazole with warfarin (Coumadin): hemorrhage', correct:true,
   why:'First row of the table on Lecture 14 slide 65. Warfarin is an active anticoagulant; blocking its inactivation raises its level and the patient bleeds.'},
  {t:'Erythromycin with glyburide: hypoglycemia', correct:true,
   why:'Second row, and the case on Lecture 10 slide 53. Glyburide keeps lowering blood glucose while its inactivation is blocked.'},
  {t:'Ketoconazole with cyclosporin: immunosuppression', correct:true,
   why:'Third row. Cyclosporin accumulates and the immune suppression goes beyond what is intended.'},
  {t:'Fluoxetine (Prozac) or paroxetine (Paxil) with dextromethorphan: CNS depression', correct:true,
   why:'Fourth row. Fluoxetine and paroxetine block the enzyme that clears dextromethorphan, so the cough suppressant accumulates and depresses the central nervous system.'},
  {t:'Metronidazole with glyburide: hypoglycemia', correct:false,
   why:'The table pairs metronidazole with warfarin, not with glyburide. The outcome column is read across its own row.'},
  {t:'Ketoconazole with dextromethorphan: hemorrhage', correct:false,
   why:'Two rows crossed. Ketoconazole is paired with cyclosporin, and hemorrhage belongs to the warfarin row; dextromethorphan\'s outcome is CNS depression.'}],
 teach:[
  {h:'The table on slide 65',
   t:'Inhibitor, affected drug, potential outcome: metronidazole, Coumadin, hemorrhage; erythromycin, glyburide, hypoglycemia; ketoconazole, cyclosporin, immunosuppression; Prozac and Paxil, dextromethorphan, CNS depression. Every row is an active drug whose inactivation is blocked, so every outcome is the drug\'s own effect taken too far.'},
  {h:'Why every outcome is an excess of the drug\'s own action',
   t:'Slide 59 gives the rule: inhibition raises drug activity, lowers metabolites, raises drug levels and lengthens the duration of action. An anticoagulant bleeds, a sulfonylurea lowers glucose too far, an immunosuppressant suppresses too much, a central depressant depresses too much. If any of the four were a prodrug the outcome would reverse, which is the distinction slide 53 draws for induction.'}],
 teachImg:'tbl_ddi',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 65; inhibition rule slide 59; glyburide case Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 53',
 quote:'Inhibitor · Affected Drug · Potential Outcome: Metronidazole · Coumadin · Hemorrhage | Erythromycin · Glyburide · Hypoglycemia | Ketoconazole · Cyclosporin · Immunosupression | Prozac & Paxil · Dextromethorphan · CNS depression'},

{id:'sa-fa-5', prof:'Sikazwe', tier:'new', topic:'factors', sub:'inhib', concept:'dme-inhibitor-list', multi:true,
 tags:['list','ddi'], source:'slide',
 stem:'Which of the following inhibit drug-metabolising enzymes, so that a co-administered substrate accumulates? Select all that apply.',
 options:[
  {t:'Isoniazid', correct:true,
   why:'In the right-hand column of Lecture 14 slide 60, the inhibitors of drug-metabolising enzymes. Isoniazid also appears in the CYP1A2 and CYP2C19 columns of the Lecture 13 slide 34 table.'},
  {t:'Ciprofloxacin', correct:true,
   why:'Slide 60, right column; a CYP1A2 inhibitor on Lecture 13 slide 34.'},
  {t:'Diltiazem and verapamil', correct:true,
   why:'Both in the right column of slide 60, the two non-dihydropyridine calcium channel blockers; the slide lists them without naming the isoform.'},
  {t:'Amiodarone', correct:true,
   why:'Slide 60, right column, and the first entry of several columns on Lecture 13 slide 34.'},
  {t:'Fluoxetine', correct:true,
   why:'Slide 60, right column, and the Prozac of the dextromethorphan row on slide 65.'},
  {t:'Efavirenz', correct:false,
   why:'Efavirenz is on slide 54, the inducers, in the right-hand box with nevirapine, ritonavir and rifabutin. It lowers the level of a co-administered substrate.'},
  {t:'Rifabutin', correct:false,
   why:'Also on slide 54, the inducers. A rifamycin like rifampin, and Lecture 13 slide 33 lists it inducing 2C8 and 3A4.'}],
 teach:[
  {h:'Slide 60 adds a second column to the familiar list',
   t:'The left column repeats the CYP3A inhibitors of Lecture 13 slide 32: clarithromycin, erythromycin, ketoconazole, itraconazole, cimetidine, protease inhibitors, quinidine, omeprazole. The right column adds isoniazid, ciprofloxacin, diltiazem, verapamil, amiodarone and fluoxetine. Slide 54 does the same for inducers, adding efavirenz, ritonavir and rifabutin to the Lecture 13 list.'},
  {h:'Ritonavir sits on both lists',
   t:'Slide 54 lists ritonavir among the inducers, while slide 32 of Lecture 13 lists protease inhibitors among the CYP3A inhibitors. Both are printed in the course, so ritonavir is left out of this question; if it appears on the paper, the answer depends on which list the question is drawn from.'}],
 teachImg:'fa_inhibitor_list',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 60; inducers slide 54; DDI table slide 65; Lecture #13 (MCMet-9_15_2026.pdf) slides 32–35',
 quote:'Inhibitors of DMEs include: Clarithromycin · Erythromycin · Azole Antifungals (Ketoconazole, Itraconazole) · Cimetidine · Protease inhibitors · Quinidine · Omeprazole | Isoniazid · Ciprofloxacin · Diltiazem · Verapamil · Amiodarone · Fluoxetine'},

{id:'sa-fa-6', prof:'Sikazwe', tier:'new', topic:'factors', sub:'induce', concept:'induction-consequences-list', multi:true,
 tags:['reasoning','list'], source:'slide',
 stem:'A patient on an active drug starts an inducer of the enzyme that clears it. Which of the following follow? Select all that apply.',
 options:[
  {t:'More enzyme is made: mRNA translation rises and protein degradation falls', correct:true,
   why:'The first two bullets of Lecture 14 slide 53: enzymatic levels rise through increased mRNA translation, and protein degradation falls. Both raise the amount of enzyme.'},
  {t:'The drug\'s blood level falls and its duration of action shortens', correct:true,
   why:'The last line of the slide: induction raises drug-metabolising enzyme activity and lowers drug blood levels plus duration of action.'},
  {t:'The drug\'s efficacy falls', correct:true,
   why:'First consequence under inducer plus drug substrate for the same enzyme: reduced drug efficacy. The cyclosporin case on slide 55 is the worked example.'},
  {t:'If the drug were a prodrug instead, its therapeutic effect would rise', correct:true,
   why:'Second consequence on the slide: increased therapeutic effects of prodrugs, because more of the active metabolite is made.'},
  {t:'If the drug is bioactivated to a toxic species, toxicity rises', correct:true,
   why:'Third consequence: increased toxicity, bioactivation to toxicity. Acetaminophen with an induced CYP2E1 is the case from Lecture 15 slide 49.'},
  {t:'The drug\'s blood level rises and its duration of action lengthens', correct:false,
   why:'That is the inhibition rule on slide 59: inhibition raises drug levels and the duration of action. Induction runs the other way.'},
  {t:'The effect appears within hours of the first dose of the inducer', correct:false,
   why:'Induction needs new enzyme to be synthesised, so it develops over days. Slide 59 records that even reversible inhibition lasts 2 to 3 days, and fa-10 in this bank sets the two time courses against each other.'}],
 teach:[
  {h:'Slide 53, line by line',
   t:'Enzyme induction: enzymatic levels and activity rise through increased mRNA translation; protein degradation falls; CYPs, UDP-glucuronosyltransferases and glutathione S-transferases have inducible isoforms. Inducer plus drug substrates for the same enzyme give interactions: reduced drug efficacy, increased therapeutic effects of prodrugs, increased toxicity from bioactivation. Generally, induction raises enzyme activity and lowers drug blood levels and duration of action.'},
  {h:'Three outcomes from one mechanism',
   t:'More enzyme means more metabolism of whatever that enzyme takes. If the substrate is the active drug, the effect is lost. If it is a prodrug, the effect grows. If the metabolite is the toxic species, the toxicity grows. Which of the three applies is decided by the drug, not by the inducer.'}],
 teachImg:'fa_induction_bullets',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 53; inhibition slide 59; cyclosporin case slide 55; acetaminophen Lecture #15 (MCMet-9_17_2026.pdf) slide 49',
 quote:'Enzyme Induction: ↑ Enzymatic levels (↑ mRNA translation) & activity · ↓ Protein degradation · CYPs, UDP-GT, GSTs – have inducible isoforms · Inducer + Drug substrates for same enzyme = DIs: ↓ drug efficacy · ↑ therapeutic effects of prodrugs · ↑ toxicity (bioactivation to toxicity) · Generally, induction ↑ DME activity & ↓ in drug blood levels plus ↓ DOA'},

/* ═══════════ LECTURE 15 — reactive species ═══════════ */
{id:'sa-tox-8', prof:'Sikazwe', tier:'new', topic:'tox', sub:'mech', concept:'ros-rns-classification', multi:true,
 tags:['list','structure'], source:'slide',
 stem:'Oxidative stress involves free radicals and non-radical reactive species. Which of the following are free radicals? Select all that apply.',
 options:[
  {t:'Superoxide anion, O2•−', correct:true,
   why:'First in the reactive oxygen species line of Lecture 15 slide 41. The dot marks the unpaired electron; superoxide dismutase on slide 61 is the enzyme that removes it.'},
  {t:'Hydroxyl radical, •OH', correct:true,
   why:'In the reactive oxygen species line. One unpaired electron on oxygen, and the most reactive of the set.'},
  {t:'Peroxyl, alkoxyl and lipid peroxyl radicals, RO2•, RO•, LOO•', correct:true,
   why:'The rest of the reactive oxygen species line, with hydroperoxyl HO2•. The lipid peroxyl radical is what glutathione peroxidase\'s substrate, the lipid hydroperoxide LOOH on slide 61, comes from.'},
  {t:'Nitric oxide, •NO, and nitrogen dioxide, •NO2', correct:true,
   why:'The reactive nitrogen species line. Both carry an unpaired electron, so both are radicals.'},
  {t:'Hydrogen peroxide, H2O2', correct:false,
   why:'Listed under non-radical species. Every electron in H2O2 is paired; it is reactive because the oxygen-oxygen bond is weak, and catalase on slide 61 splits it to water and oxygen.'},
  {t:'Peroxynitrite, ONOO−', correct:false,
   why:'Non-radical species on the slide. It forms when the two radicals superoxide and nitric oxide combine, and the combination pairs their electrons.'},
  {t:'Hypochlorous acid, HOCl', correct:false,
   why:'The third non-radical species on the slide. An oxidant with no unpaired electron.'}],
 teach:[
  {h:'Three lines on slide 41',
   t:'Reactive oxygen species: superoxide anion O2•−, peroxyl RO2•, hydroxyl •OH, alkoxyl RO•, hydroperoxyl HO2•, lipid peroxyl LOO•. Reactive nitrogen species: nitric oxide •NO, nitrogen dioxide •NO2. Non-radical species: hydrogen peroxide H2O2, peroxynitrite ONOO−, hypochlorous acid HOCl. The dot is the test: a species with a dot has an unpaired electron and is a radical.'},
  {h:'Why the distinction matters for the defense',
   t:'Slide 61 chains the antioxidant enzymes to these species. Superoxide dismutase turns the superoxide radical into hydrogen peroxide, a non-radical; catalase then removes the peroxide before it can be turned back into a hydroxyl radical. Glutathione peroxidase reduces the lipid hydroperoxide that a lipid peroxyl radical leaves behind. A radical propagates a chain; a non-radical oxidant does not, but it is the raw material for the next radical, which is why the enzymes handle both.'}],
 teachImg:'tx_ros',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 41; antioxidant enzymes slide 61',
 quote:'ROS: O2•− (superoxide anion); RO2• (peroxyl); •OH (hydroxyl); RO• (alkoxyl); HO2• (hydroperoxyl); LOO• (lipid peroxyl) · RNS: •NO (nitric oxide); •NO2 (nitrogen dioxide) · Non-Radical Species: H2O2 (hydrogen peroxide); ONOO− (peroxynitrite); HOCl (hypochlorous acid)'},

{id:'cyp-e4', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'expr', concept:'expression-vs-drug-share',
 tags:['reasoning','data'], source:'slide',
 stem:'Which CYP isoform makes up the largest share of liver CYP, and which metabolises the largest share of clinical drugs?',
 options:[
  {t:'Expression: CYP2E1; drugs: CYP3A4/5', correct:true,
   why:'Slide 14, percent of CYP isoforms expressed by human liver, has CYP2E1 as its largest slice at 21%. Slide 16, percent of clinical drugs metabolised by human CYP isoforms, has CYP3A4/5 at 30%. The most abundant enzyme and the busiest enzyme are different isoforms.'},
  {t:'Expression: CYP3A4; drugs: CYP2E1', correct:false,
   why:'The two numbers belong to the other charts. CYP3A4 is 11% of liver CYP on slide 14, and CYP2E1 metabolises 3% of clinical drugs on slide 16; each is large on one pie and small on the other.'},
  {t:'Expression: CYP2D6; drugs: CYP2C9', correct:false,
   why:'CYP2D6 is 2% of liver CYP and 20% of drugs, which is the mismatch slide 26 records as 3% versus 21%. CYP2C9 is 15% of liver CYP and 13% of drugs; neither tops either chart.'},
  {t:'CYP3A4 tops both', correct:false,
   why:'One third is what slide 30 says for CYP3A4, and it holds for drug share on slide 16 (30%). On the slide 14 pie CYP3A4 is 11%, with 3A5 and 3A7 bringing the CYP3A family to 16%; CYP2E1 is the largest slice there. The two slides disagree on expression and agree on drug share.'}],
 teach:[
  {h:'Two questions, two pies',
   t:'A question about which isoform is most expressed, or most abundant, in the liver reads slide 14: CYP2E1 21%, then CYP2C9 15%, 2C8 12%, 3A4 11%, 2A6 and 4F 10%. A question about which isoform metabolises the most drugs reads slide 16: CYP3A4/5 30%, then 2D6 20%, 2C9 13%, 1A2 9%. Adding slices gives the family answers: CYP2 is the largest family on both, 66% of liver CYP and 61% of drugs, and CYP1 the smallest of families 1 to 3 on both, 6% and 9%.'},
  {h:'The conflict, and which figure to give',
   t:'Slide 30 states that CYP3A4 is one third of liver CYP isoforms and metabolises one third of drugs. The drug-share third matches slide 16. The expression third does not match the slide 14 pie, where CYP3A4 is 11%. If a question quotes slide 30, one third is the expected answer for both; if it shows or names the pie, CYP2E1 is the most expressed. The Reference tab holds both pies with every slice.'}],
 teachImg:'cyp_liver_share',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 14 and 16; CYP2D6 mismatch slide 26; one-third statement slide 30',
 quote:'% CYP isoforms expressed by human liver (slide 14) · % Clinical drugs metabolized by hCYP isoforms (slide 16)',
 note:'Adding up the slide 14 slices for the CYP2 family gives 66%, not 52%: 2A6 10 + 2A13 1 + 2B6 3 + 2C8 12 + 2C9 15 + 2C19 2 + 2D6 2 + 2E1 21.'}
);
