const TOPICS = [
 {id:'cyp', name:'CYP450', prof:'Sikazwe', open:true,
  cite:'Lecture #13 — MCMet-9_15_2026.pdf (60 slides)',
  subs:[
   {id:'why',  name:'Why CYPs matter',                cite:'slides 5–7'},
   {id:'char', name:'Characteristics & nomenclature', cite:'slides 8–10'},
   {id:'cycle',name:'Catalytic cycle',                cite:'slides 11–13'},
   {id:'expr', name:'Expression & share of drugs',    cite:'slides 14–19'},
   {id:'fam',  name:'Families, isoforms & substrates',cite:'slides 20–31'},
   {id:'indinh',name:'Induction & inhibition',        cite:'slides 32–35'},
   {id:'bioact',name:'Bioactivation of procarcinogens',cite:'slides 36–37'},
   {id:'poly', name:'Polymorphism',                   cite:'slides 38–42, 49–51'},
   {id:'cases',name:'Cases & applied reasoning',      cite:'slides 43–59'}]},

 {id:'fgdm', name:'Functional groups & metabolism', prof:'Sikazwe',
  cite:'Lecture #14 — MCMet-9_16_2026.pdf, slides 5–31',
  subs:[
   {id:'hc',   name:'Hydrocarbons & halogenated groups', cite:'slides 5–7, 21'},
   {id:'namide',name:'Amines & amides',                  cite:'slides 8–11'},
   {id:'carb', name:'Carbonyls & carboxylic acids',      cite:'slides 12–13'},
   {id:'ester',name:'Esters, carbamates & carbonates',   cite:'slides 14–16'},
   {id:'ether',name:'Ethers, thioethers & epoxides',     cite:'slides 17–20'},
   {id:'oh',   name:'Alcohols & phenols',                cite:'slides 22–23'},
   {id:'hetero',name:'Purines, pyrimidines & quinones',  cite:'slides 24–26'},
   {id:'p2map',name:'Phase 2 map: group → enzyme → cofactor', cite:'slides 29–30'}]},

 {id:'factors', name:'Factors influencing metabolism', prof:'Sikazwe',
  cite:'Lecture #14 — MCMet-9_16_2026.pdf, slides 32–67',
  subs:[
   {id:'pd',   name:'Parent drug: dose, route, transport', cite:'slides 33–39'},
   {id:'phys', name:'Physiological: age, disease, genetics',cite:'slides 41–50'},
   {id:'induce',name:'Extrinsic: induction',                cite:'slides 51–58'},
   {id:'inhib',name:'Extrinsic: inhibition & grapefruit',   cite:'slides 59–66'}]},

 {id:'elim', name:'Elimination', prof:'Sikazwe',
  cite:'Lecture #15 — MCMet-9_17_2026.pdf, slides 4–27',
  subs:[
   {id:'routes',name:'Routes & their ranking',      cite:'slides 5–8, 21–26'},
   {id:'renal', name:'Renal factors',               cite:'slides 9–13'},
   {id:'ph',    name:'Urinary pH & pH trapping',    cite:'slides 14–15'},
   {id:'hep',   name:'Biliary route & recycling',   cite:'slides 16–20'}]},

 {id:'tox', name:'Toxicity', prof:'Sikazwe',
  cite:'Lecture #15 — MCMet-9_17_2026.pdf, slides 28–66',
  subs:[
   {id:'causes',name:'Causes & toxicophores',       cite:'slides 29–30'},
   {id:'mech',  name:'Toxicity mechanisms',         cite:'slides 31–44'},
   {id:'hep',   name:'Hepatotoxicity',              cite:'slides 46–50'},
   {id:'extra', name:'Extrahepatic toxicity',       cite:'slides 51–58'},
   {id:'def',   name:'Defense & antidotes',         cite:'slides 59–64'}]},

 {id:'dmfound', name:'Metabolism foundations', prof:'Sikazwe',
  cite:'Lecture #10 — MCMet-9_4_26-9_9_26.pdf',
  subs:[
   {id:'analysis',name:'What metabolism is & does',  cite:'slides 5–9'},
   {id:'phases',  name:'Phases, patterns & enzymes', cite:'slides 11–17'},
   {id:'sites',   name:'Sites of metabolism',        cite:'slides 18–20'},
   {id:'conseq',  name:'Consequences of metabolism', cite:'slides 28–46'},
   {id:'ddi',     name:'Induction / inhibition DDIs',cite:'slides 47–56'}]},

 {id:'paths', name:'Phase 1 & Phase 2 pathways', prof:'Sikazwe',
  cite:'Lecture #11 — MCMet-9_10_26.pdf',
  subs:[
   {id:'cypox', name:'CYP oxidations',        cite:'slides 11–20'},
   {id:'nonc',  name:'Non-CYP oxidations',    cite:'slides 21–28'},
   {id:'red',   name:'Reductions',            cite:'slides 29–33'},
   {id:'hyd',   name:'Hydrolysis',            cite:'slides 34–39'},
   {id:'p2',    name:'Phase 2 conjugations',  cite:'slides 42–62'}]},

 {id:'fgs', name:'Functional groups', prof:'Sikazwe',
  cite:'MCFGs8_1718_26.pdf (96 slides) + PTI Study Aid',
  subs:[
   {id:'ident', name:'Identify the FGs in a drug',       cite:'slides 56–57'},
   {id:'hc',    name:'Hydrocarbons & halogenated',     cite:'slides 9–23'},
   {id:'ox',    name:'Alcohols, phenols & ethers',     cite:'slides 24–34'},
   {id:'carbonyl',name:'Aldehydes & ketones',          cite:'slides 35–38'},
   {id:'n',     name:'Amines, nitriles & nitro',       cite:'slides 40–45'},
   {id:'acyl',  name:'Acid, ester, amide & relatives', cite:'slides 46–57'},
   {id:'sulf',  name:'Sulfur & phosphorus groups',     cite:'slides 62–70'},
   {id:'rings', name:'Heterocyclic ring recognition',  cite:'slides 73–93'},
   {id:'edg',   name:'Electron-donating vs withdrawing',cite:'slide 94'}]},

 {id:'stereo', name:'Stereochemistry', prof:'Yendapally',
  cite:'081926_Stereochemistry.pdf (33 slides)',
  subs:[{id:'rs', name:'Assigning R and S', cite:'slides 7–13'},
        {id:'terms', name:'Isomer vocabulary', cite:'slides 14–27'}]},

 {id:'disc', name:'Drug discovery, SAR & bioisosterism', prof:'Yendapally',
  cite:'082026_Drugdiscovery.pdf · 082426_IntroductiontoSAR.pdf · 082626_Bioisosterism.pdf',
  subs:[{id:'sources', name:'Sources of drugs, uses & biologics', cite:'drug discovery deck'},
        {id:'approach', name:'The six discovery approaches', cite:'drug discovery deck'},
        {id:'sar', name:'Structure–activity relationship', cite:'SAR deck'},
        {id:'bio', name:'Bioisosterism', cite:'bioisosterism deck slides 3–17'}]},

 {id:'recept', name:'Drug–receptor interactions', prof:'Yendapally',
  cite:'082426_DrugReceptorInteractions.pdf · 082426_ReviewAminoacids.pdf',
  subs:[{id:'bonds', name:'Bond types & strength', cite:'slides 3–8'},
        {id:'aa', name:'Amino acid side chains', cite:'amino acid review deck'}]},

 {id:'physchem', name:'Physicochemical properties', prof:'Yendapally',
  cite:'082726_ / 090226_ / 090326_PhysicochemicalProp1-3.pdf',
  subs:[{id:'acidbase', name:'Acidic, basic & neutral groups', cite:'Prop 1, slides 11–22'},
        {id:'ionization', name:'Degree of ionization & pH', cite:'Prop 1, slides 24–41; practice answers 082726_PracticeProblemAnswers.pdf'},
        {id:'logp', name:'Partition coefficient & solubility', cite:'Prop 2–3'}]},

 {id:'admet', name:'ADMET: absorption & distribution', prof:'Yendapally',
  cite:'090326_/090426_ADMETAbsorption I–II.pdf · 090426_Distribution.pdf',
  subs:[{id:'trans', name:'Efflux & influx transporters', cite:'Absorption I, slides 10–36'},
        {id:'ddi', name:'Absorption drug–drug interactions', cite:'Absorption II'},
        {id:'prodrug', name:'Prodrugs & what they are for', cite:'Absorption II'},
        {id:'vd', name:'Distribution & volume of distribution', cite:'Distribution, slides 3–27'}]}
];

const QUESTIONS = [
/* ═══════════ WHY CYPs MATTER ═══════════ */
{id:'cyp-w1', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'why', concept:'cyp-two-roles',
 tags:['definition','reasoning'], source:'slide',
 stem:'Why are CYP enzymes important in pharmacy? Give both reasons.',
 options:[
  {t:'They carry out most drug metabolism, and they also bioactivate xenobiotics into carcinogens', correct:true,
   why:'CYPs perform most Phase 1 reactions, so most drugs are cleared through them. The second role is harmful. Adding an oxygen atom usually makes a molecule more water soluble, but it can also produce a strained epoxide ring or a carbon that is short of electrons. Either one reacts with protein or DNA and damages it. Benzo[a]pyrene, found in smoked and barbecued food, is converted this way into a compound that binds DNA.'},
  {t:'They carry out most drug metabolism, and they transport drugs across membranes', correct:false,
   why:'The first half is right. The second describes a different set of proteins. Drugs are moved across membranes by the ABC and SLC transporter families, covered in 090326_ADMETAbsorption_I.pdf slides 18 to 25. A CYP changes the drug\'s chemical structure. A transporter moves the drug from one side of a membrane to the other without changing it.'},
  {t:'They conjugate drugs with polar groups, and they regulate gene transcription', correct:false,
   why:'Attaching a polar group is Phase 2, done by transferase enzymes such as UDP-glucuronosyltransferase, sulfotransferase and glutathione S-transferase, in MCMet-9_10_26.pdf slides 42 to 62. A CYP inserts a single oxygen atom instead. Gene transcription belongs to enzyme induction, where a drug increases how much CYP protein the cell makes. The CYP is the target of that process, not the one performing it.'},
  {t:'They eliminate drugs from the body, and they filter blood at the kidney', correct:false,
   why:'Metabolism and elimination are two separate steps. A CYP makes the drug more polar, and the polar product is then removed by the kidney or in bile. Filtration at the glomerulus is a physical process driven by blood pressure and molecular size, described in MCMet-9_17_2026.pdf slide 11. No enzyme carries it out.'}],
 teach:'CYP450 appears twice in this course for opposite reasons. In MCMet-9_15_2026.pdf it is the enzyme family that clears most drugs. In MCMet-9_17_2026.pdf slides 30 to 35 it is the enzyme family that creates several of the reactive species behind drug toxicity. The chemistry is the same in both places: an oxygen atom is inserted into the molecule. Whether the product is harmless or harmful depends only on where that oxygen lands and what structure results.',
 teachImg:'cyp_enzyme_share',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 5–7',
 quote:'They play a big role in xenobiotic bioactivations (e.g., to carcinogens)'},

/* ═══════════ CHARACTERISTICS & NOMENCLATURE ═══════════ */
{id:'cyp-w2', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'why', concept:'fmo-not-a-cyp',
 tags:['enzyme','exam-pattern'], source:'slide',
 stem:'Flavin-containing monooxygenase (FMO) carries out oxidation reactions. Where does it belong among the drug-metabolizing enzymes?',
 options:[
  {t:'A Phase 1 oxidizing enzyme that is not a member of the CYP superfamily', correct:true,
   why:'Oxidation names the chemistry, not the family that performs it. The root name cytochrome P450 refers to a heme pigment whose iron binds carbon monoxide and absorbs light at 450 nanometres, and flavin-containing monooxygenase carries no heme at all; its name gives its cofactor as a flavin. The enzyme share on slide 6 counts it at 1 percent separately from cytochrome P450 at 74 percent, so the two are different enzymes performing overlapping chemistry.'},
  {t:'An isoform inside CYP family 2', correct:false,
   why:'Family 2 holds CYP2B6, CYP2C9, CYP2C19, CYP2D6 and CYP2E1, and each carries the CYP root name because each carries the heme. Flavin-containing monooxygenase has no CYP number because it has no heme, so it cannot be placed in a CYP family or subfamily.'},
  {t:'A Phase 2 conjugating enzyme', correct:false,
   why:'Phase 2 enzymes attach a polar group: UDP-glucuronosyltransferase attaches glucuronic acid, sulfotransferase attaches sulfate, N-acetyltransferase attaches an acetyl group. Flavin-containing monooxygenase attaches nothing. It inserts a single oxygen atom, which is Phase 1 functionalization. UDP-glucuronosyltransferase is the Phase 2 enzyme on that same slide 6 chart, at 15 percent.'},
  {t:'An enzyme restricted to endobiotics, with no role in drug clearance', correct:false,
   why:'It appears on a chart of drug metabolism because it clears drugs. Its targets are nitrogen and sulfur atoms carrying a lone pair, which is why its substrates overlap with CYP substrates containing amines and thioethers, covered as non-CYP oxidation in MCMet-9_10_26.pdf slides 26 to 28.'}],
 teach:'Two enzymes can run the same reaction and still belong to different families, because the family is fixed by the cofactor rather than by the chemistry. A cytochrome P450 holds its iron inside a porphyrin ring bound to a cysteine, and the reaction will not turn over without cytochrome P450 reductase, NADPH and molecular oxygen. Flavin-containing monooxygenase is named for a flavin cofactor instead, so it performs Phase 1 oxidation from outside the CYP superfamily. Slide 6 separates them for that reason: cytochrome P450 74 percent, UDP-glucuronosyltransferase 15 percent, esterase 9 percent, flavin-containing monooxygenase 1 percent, N-acetyltransferase 1 percent, monoamine oxidase 1 percent. Monoamine oxidase, alcohol dehydrogenase and aldehyde dehydrogenase are excluded on the same grounds, all Phase 1, none of them a CYP.',
 teachImg:'cyp_enzyme_share',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 6, 8, 10',
 quote:'They are key for drug metabolism'},

{id:'cyp-c1', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'char', concept:'cyp-name-origin',
 tags:['definition'], source:'slide',
 stem:'Where does each part of the name "cytochrome P450" come from?',
 options:[
  {t:'Cyto means cell-bound, chrome means heme pigment, and P450 refers to the enzyme–carbon monoxide complex absorbing light at 450 nm', correct:true,
   why:'Cyto refers to the enzyme being held inside the cell rather than floating free in plasma. Chrome refers to the heme group, which is coloured. P450 comes from a laboratory measurement: when carbon monoxide is bound to the enzyme, the resulting complex absorbs light most strongly at 450 nanometres. CYP450 is the root name, and every isoform label is built from it.'},
  {t:'Cyto means cytosol, chrome means chromosome, and 450 is the number of amino acids', correct:false,
   why:'CYPs are not in the cytosol. They are bound in the membrane of the endoplasmic reticulum. Sulfotransferase and glutathione S-transferase are the cytosolic enzymes, in MCMet-9_10_26.pdf slides 47 and 49. Chrome refers to colour, not chromosomes. And 450 is a wavelength measured in nanometres, not a count of amino acids.'},
  {t:'It is named for the 450 human isoforms identified so far', correct:false,
   why:'There are more than 18 families and more than 40 subfamilies, which is far fewer than 450. The number in the name is a measurement rather than a count.'},
  {t:'P stands for protein and 450 is its molecular weight in kilodaltons', correct:false,
   why:'A protein of 450 kilodaltons would be very large; a CYP is a fraction of that size. The number refers to light absorption. Molecular weight does matter elsewhere in the course: at the glomerulus, molecules under about 60 kilodaltons are filtered, in MCMet-9_17_2026.pdf slide 11.'}],
 teach:'Two parts of this name carry information you will use again. Cell-bound places the enzyme in the endoplasmic reticulum, which is what makes it microsomal rather than cytosolic. Heme pigment means there is an iron atom at the active site, and that iron is what changes oxidation state during the catalytic cycle on slide 12. The 450 nanometre figure is only how the enzyme was first detected and has no role in how it works.',
 teachImg:'cyp_heme_site',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 8; catalytic cycle slides 11–12',
 quote:'P450 (a "CYP + CO" complex that absorbs light @ 450 nm) · CYP450 (Cytochrome P450) is the "Root Name"'},

{id:'cyp-c2', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'char', concept:'cyp-location-structure',
 tags:['definition','structure'], source:'slide',
 stem:'Which description matches the structure and location of CYP enzymes?',
 options:[
  {t:'Membrane-bound proteins in the endoplasmic reticulum, with a porphyrin ring holding an iron atom bonded to a cysteine residue', correct:true,
   why:'The porphyrin is a flat ring that grips a single iron atom in its centre. A cysteine side chain from the protein bonds to that iron and holds it in place. The iron is the atom that gains and loses electrons during catalysis, and the porphyrin and the cysteine are what keep it positioned and in a state where it can cycle. All three parts have to appear in the description: the endoplasmic reticulum membrane for the location, the porphyrin-held iron for the catalytic centre, and the cysteine bond for the anchor.'},
  {t:'Soluble cytosolic proteins with a zinc catalytic centre', correct:false,
   why:'Both parts are wrong, and each belongs to a different enzyme. Cytosolic means floating in the fluid of the cell, which describes sulfotransferase and glutathione S-transferase in MCMet-9_10_26.pdf slides 47 and 49. The metal in a CYP is iron, not zinc.'},
  {t:'Mitochondrial matrix proteins using a flavin cofactor', correct:false,
   why:'A flavin cofactor identifies flavin-containing monooxygenase, a separate Phase 1 enzyme that oxidizes amines, amides and thiols, in MCMet-9_10_26.pdf slides 26 to 28. Monoamine oxidase is the enzyme associated with mitochondria. CYPs sit in the endoplasmic reticulum.'},
  {t:'Secreted plasma proteins with a serine residue at the active site', correct:false,
   why:'A serine at the active site identifies a hydrolase, an enzyme that uses water to break a bond. Carboxylesterase works this way on esters and amides, in MCMet-9_10_26.pdf slides 35 to 38. CYPs are never released into plasma.'}],
 teach:'Enzyme location decides how the course groups these enzymes. CYPs and UDP-glucuronosyltransferase are in the endoplasmic reticulum and are called microsomal. Sulfotransferase and glutathione S-transferase are in the cytosol. Monoamine oxidase is associated with mitochondria. MCMet-9_4_26-9_9_26.pdf slide 20 lists these three cellular locations, and a question asking where a reaction happens is asking you to place the enzyme in one of them.',
 teachImg:'cyp_heme_site',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 10; cellular sites Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 20',
 quote:'CyPs are in the ER (liver & other cells) · CyPs are membrane bound proteins · Porphyrin with Fe-Cysteine catalytic site'},

{id:'cyp-c3', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'char', concept:'cyp-nomenclature-parsing',
 tags:['definition','exam-pattern'], source:'slide',
 stem:'In CYP2D6*4, what does each element of the label identify?',
 options:[
  {t:'2 is the family, D is the subfamily, 6 is the individual isoform, and *4 is the allelic variant', correct:true,
   why:'The label runs from the broadest grouping to the most specific. Enzymes in one family share more than 40 percent of their amino acid sequence. Enzymes in one subfamily share more than 50 percent. The isoform number names one specific enzyme. The number after the asterisk names which version of that gene a particular patient carries, and that is the part that determines whether the patient is a poor or an ultrarapid metabolizer.'},
  {t:'2 is the subfamily, D is the family, 6 is the allelic variant, and *4 is the isoform', correct:false,
   why:'The pieces are in the wrong order. The label always runs number, letter, number, then asterisk and number, moving from general to specific. The letter is the subfamily, never the family.'},
  {t:'2 is the chromosome, D is the tissue, 6 is the substrate class, and *4 is the activity level', correct:false,
   why:'None of these are in the name. Which tissues an isoform sits in, which drugs it handles, and how active it is are separate facts you learn per isoform. CYP3A4 for example is in liver, intestine and lungs, which slide 30 states separately from its name.'},
  {t:'The whole label is an arbitrary identifier with no internal structure', correct:false,
   why:'The structure tells you which enzymes are related. CYP2C9 and CYP2C19 share the letter C, so they are in one subfamily and share more than half their sequence. That is why both metabolize phenytoin, as slide 24 shows.'}],
 teach:'Shared letters predict shared behaviour. CYP2C9 and CYP2C19 are in the same subfamily and handle several of the same drugs, including phenytoin and mephenytoin. CYP2D6 and CYP2E1 are in family 2 but different subfamilies, and their substrate lists have nothing in common. When an unfamiliar isoform appears, its label tells you which isoform you already know it resembles.',
 teachImg:'cyp_nomenclature',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 9, 19; polymorphism slide 38',
 quote:'>18 Families (>40% homology) · >40 Subfamilies (>50% homology)'},

/* ═══════════ CATALYTIC CYCLE ═══════════ */
{id:'cyp-y1', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'cycle', concept:'cyp-cycle-requirements',
 tags:['mechanism','cofactor'], source:'slide',
 stem:'A CYP-mediated oxidation will not proceed if which one of the following is missing?',
 options:[
  {t:'NADPH', correct:true,
   why:'NADPH supplies electrons. The cycle needs two of them, delivered at two separate points. The first electron converts the iron from Fe³⁺ to Fe²⁺. The second electron is used to convert bound oxygen into the reactive form that attacks the drug. With no NADPH the iron is never reduced, so the cycle stops at the first step.'},
  {t:'UDP-glucuronic acid (UDPGA)', correct:false,
   why:'UDP-glucuronic acid is used by UDP-glucuronosyltransferase, a Phase 2 enzyme, in MCMet-9_10_26.pdf slide 46. That enzyme attaches a whole sugar acid onto the drug. A CYP inserts one oxygen atom instead. The two processes are different in what they attach and in which phase they belong to.'},
  {t:'Glutathione (GSH)', correct:false,
   why:'Glutathione works with glutathione S-transferase, a Phase 2 enzyme, in MCMet-9_10_26.pdf slide 49. Glutathione is electron-rich, so it reacts with carbons that are short of electrons. Some CYP reactions produce exactly that kind of carbon. Glutathione reacts with the product of the CYP reaction, so it acts after the CYP has finished rather than taking part in the oxidation.'},
  {t:'Acetyl-CoA', correct:false,
   why:'Acetyl-CoA has two Phase 2 roles. It donates an acetyl group to N-acetyltransferase, in MCMet-9_10_26.pdf slide 53. It also activates a carboxylic acid group so that glycine or glutamine can be attached, in slide 55. Neither role occurs in a Phase 1 oxidation.'}],
 svg:DIA.cypCycle,
 teach:'Four things are required, and each has one job. The CYP enzyme holds the drug and contains the iron. Molecular oxygen provides the oxygen atom that ends up in the product. NADPH provides the two electrons. CYP450 reductase carries those electrons from NADPH to the iron, because NADPH cannot reach the iron directly. If any one is missing you can say what stops: with no enzyme there is nowhere for the drug to bind, with no oxygen there is nothing to insert, with no NADPH there are no electrons, and with no reductase the electrons cannot reach the iron.',
 teachImg:'cyp_catalytic_cycle',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 12',
 quote:'Reaction requirements/ingredients: CYP450 · CYP450 Reductase · NADPH (e- donor) · Molecular Oxygen (O2)'},

{id:'cyp-y2', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'cycle', concept:'cyp-cycle-order',
 tags:['mechanism','exam-pattern'], source:'slide',
 stem:'Put the four steps of the CYP oxidation cycle in order.',
 options:[
  {t:'Fe³⁺ enzyme binds the drug → first electron reduces the complex → second electron reduces bound O₂ → activated oxygen oxidizes the drug', correct:true,
   why:'The drug binds first, while the iron is still in the Fe³⁺ state. The first electron then converts the iron to Fe²⁺. Oxygen binds to that reduced iron, and the second electron converts it into a reactive form. That reactive oxygen then attacks the drug and the product is released.'},
  {t:'Molecular oxygen binds the iron → drug binds → both electrons arrive together → oxidation', correct:false,
   why:'Oxygen cannot bind until the iron has already been reduced by the first electron, so oxygen cannot come first. The electrons also arrive separately rather than together, one before oxygen binds and one after.'},
  {t:'Activated oxygen oxidizes the drug → NADPH regenerates the enzyme → oxygen binds → drug is released', correct:false,
   why:'This puts the oxidation first. Oxidation is the last step, because the enzyme must already hold both the drug and the activated oxygen before the reaction can happen.'},
  {t:'NADPH donates both electrons → drug binds → oxygen binds → product released without further change', correct:false,
   why:'Reducing the iron before the drug binds reverses the first two steps. This sequence also has no oxidation step, so nothing would happen to the drug.'}],
 svg:DIA.cypCycle,
 teach:'Each step exists because of what the one before it made possible. The drug binds while the iron is Fe³⁺. The first electron converts the iron to Fe²⁺, and only Fe²⁺ can bind oxygen. The second electron converts that bound oxygen into a form reactive enough to break a carbon–hydrogen bond. Then the oxygen is inserted into the drug. Every CYP reaction in MCMet-9_10_26.pdf slides 11 to 20, from aliphatic hydroxylation through N-dealkylation to epoxidation, uses this same cycle on a different part of the molecule.',
 teachImg:'cyp_catalytic_cycle',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 11–12',
 quote:'1. Oxidized (Fe3+) P450 complexes the drug 2. NADPH donates an e- (via CYP450 reductase) to reduce the initial complex 3. NADPH donates another e- to reduce O2 & form an activated "oxidized-CYP450 complex" 4. Activated oxygen oxidizes the bound drug to form the product'},

{id:'cyp-y3', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'cycle', concept:'cyp-reductase-role',
 tags:['mechanism','enzyme'], source:'slide',
 stem:'What is the role of CYP450 reductase in the catalytic cycle?',
 options:[
  {t:'It carries electrons from NADPH to the CYP enzyme', correct:true,
   why:'NADPH is a small molecule dissolved in the cell. The iron it needs to reach is buried inside a protein held in a membrane. The two cannot touch. CYP450 reductase is a second protein that accepts electrons from NADPH and passes them on to the iron. It is listed as its own requirement because losing it stops the cycle just as completely as losing NADPH.'},
  {t:'It reduces the drug substrate directly', correct:false,
   why:'The drug is oxidized in this reaction, not reduced, so a reductase acting on the drug would run the reaction the wrong way. The reductase acts on the enzyme instead. Drug molecules are reduced in Phase 1, but by different enzymes: aldo-keto reductase, azo-reductase and nitro-reductase, in MCMet-9_10_26.pdf slides 29 to 33.'},
  {t:'It supplies the molecular oxygen', correct:false,
   why:'Oxygen comes from the oxygen already dissolved in the cell, not from an enzyme. Slide 12 lists molecular oxygen and CYP450 reductase as two separate requirements, and they enter the cycle at different points.'},
  {t:'It regenerates glutathione after conjugation', correct:false,
   why:'That is glutathione reductase, a different enzyme entirely. It converts disulfide bonds back to free thiols so glutathione can be used again, and it appears under toxicity defense in MCMet-9_17_2026.pdf slide 61. The two enzymes share the word reductase but work on different molecules in different systems.'}],
 teach:'The reductase exists because of a physical distance problem. Electrons have to travel from NADPH in the cell fluid to an iron atom held inside a membrane-bound protein. The reductase spans that gap. It appears at two points in the cycle description because two electrons are delivered, one before oxygen binds and one after.',
 teachImg:'cyp_catalytic_cycle',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 12',
 quote:'NADPH donates an e- (via CYP450 reductase) to reduce the initial complex'},

{id:'cyp-y4', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'cycle', concept:'cyp-oxidation-breadth',
 tags:['mechanism','recall'], source:'both',
 stem:'True or false: CYPs also catalyze epoxidation, dealkylation and dehalogenation reactions.',
 options:[
  {t:'True — all three are listed among CYP oxidative reactions', correct:true,
   why:'The CYP reaction list covers hydroxylation at aliphatic, allylic, benzylic and aromatic positions, removal of alkyl groups from nitrogen, oxygen and sulfur, removal of halogens, and formation of epoxides. All of them start with the enzyme inserting activated oxygen. What differs is where on the molecule the oxygen lands and what the molecule does afterwards.'},
  {t:'False — CYPs only perform hydroxylation', correct:false,
   why:'If this were true, two central examples in the course would have no explanation. Codeine becomes morphine by removal of a methyl group from oxygen, in MCMet-9_10_26.pdf slide 17. Carbamazepine becomes an epoxide, in MCMet-9_17_2026.pdf slide 33. Both are CYP reactions and neither is a simple hydroxylation.'},
  {t:'False — epoxidation is performed only by epoxide hydrolase', correct:false,
   why:'Epoxide hydrolase does the opposite. It adds water to an epoxide and opens the ring, producing a molecule with two hydroxyl groups, in MCMet-9_10_26.pdf slide 39. CYP creates the epoxide and epoxide hydrolase destroys it. Carbamazepine passes through both in sequence.'},
  {t:'False — dealkylation is a Phase 2 reaction', correct:false,
   why:'Phase 2 means attaching a polar partner molecule onto the drug. Dealkylation removes a group rather than attaching one, so it cannot be Phase 2. It is a Phase 1 reaction.'}],
 teach:'Removing a methyl group from nitrogen, oxygen or sulfur looks different from hydroxylation but happens by the same chemistry. The enzyme adds a hydroxyl to the carbon of the methyl group, which produces an unstable structure. That structure falls apart on its own, releasing formaldehyde and leaving a hydrogen on the nitrogen, oxygen or sulfur. This is why N-dealkylation, O-dealkylation and S-dealkylation are one reaction type applied to three different atoms.',
 teachImg:'cyp_oxidative_reactions',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 11; Lecture #13 (MCMet-9_15_2026.pdf) slide 13; Ex4-Prep-Work question 2(i)'},

/* ═══════════ EXPRESSION & SHARE ═══════════ */
{id:'cyp-e1', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'expr', concept:'cyp3a4-dominance',
 tags:['recall','reasoning'], source:'slide',
 stem:'Which CYP isoform accounts for roughly one third of liver CYP content and metabolizes roughly one third of clinical drugs?',
 options:[
  {t:'CYP3A4', correct:true,
   why:'CYP3A4 is about one third of the CYP protein in the liver and handles about one third of clinical drugs. It is also present in the intestine and lungs, and it is the main enzyme responsible for first-pass metabolism. Because it is both abundant and handles so many drugs, it is involved in more interactions than any other isoform.'},
  {t:'CYP2D6', correct:false,
   why:'CYP2D6 is only about 3 percent of liver CYP protein but handles about 21 percent of clinical drugs. Those two numbers do not match, and that mismatch is the reason 2D6 causes so many interactions. It is not the abundant isoform.'},
  {t:'CYP1A2', correct:false,
   why:'CYP1A2 handles aryl amines and ring systems containing nitrogen, with caffeine, imipramine and haloperidol as its named drugs on slide 20. It matters clinically because tobacco smoke increases how much of it the liver makes, but it handles a much smaller share of drugs than 3A4.'},
  {t:'CYP2E1', correct:false,
   why:'CYP2E1 mainly handles environmental chemicals rather than prescribed drugs. Its listed substrates on slide 28 are ethanol, halogenated hydrocarbons and acetaminophen during overdose. It matters more for toxicity than for routine drug clearance.'}],
 teach:'Two different percentages are attached to CYP isoforms and they measure different things. One is how much of the liver\'s CYP protein that isoform makes up. The other is what share of drugs it clears. For CYP3A4 both are about one third. For CYP2D6 they are 3 percent and 21 percent. When a question gives a percentage, check which of the two it means.',
 teachImg:'cyp_drug_share',
 note:'Two figures in this lecture disagree on the liver share. Slide 30 puts CYP3A4 at one third of liver CYP isoforms, while the pie chart on slide 14 shows CYP3A4 at 11 percent, CYP3A5 at 3 percent and CYP3A7 at 2 percent, which is 16 percent for the whole CYP3A group, with CYP2E1 the largest single slice at 21 percent. The share-of-drugs figure is not in dispute: slide 16 gives CYP3A4/5 at 30 percent, matching the one third in the stem. Confirm which liver figure is being examined.',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 14, 16, 30',
 quote:'1/3 of liver CYP isoforms & metabolizes 1/3 of drugs'},

{id:'cyp-e2', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'expr', concept:'cyp2d6-low-expression-ddi',
 tags:['reasoning'], source:'slide',
 stem:'CYP2D6 makes up only about 3% of liver CYP content yet metabolizes about 21% of clinical drugs. What consequence does lecture draw?',
 options:[
  {t:'A large number of drug–drug interactions, because a small amount of enzyme carries a heavy substrate load', correct:true,
   why:'An enzyme can only process so many molecules at a time. Because CYP2D6 is present in small amounts but is needed by many drugs, it is already working near its limit. Adding a second drug that needs the same enzyme, or adding something that blocks it, produces a large drop in how fast either drug is cleared.'},
  {t:'It is the most inducible of all CYP isoforms', correct:false,
   why:'Slide 26 states the opposite: CYP2D6 shows minimal induction. This means the liver cannot make much more of it in response to a drug. CYP3A4 and CYP1A2 can both be increased substantially, which gives them a way to compensate that 2D6 does not have.'},
  {t:'It is responsible for most of the first-pass effect', correct:false,
   why:'First-pass metabolism is mostly CYP3A4, which slide 30 places in the intestine and the liver. An oral drug passes both before reaching general circulation. CYP2D6 is under one percent of intestinal CYP on the slide 15 pie, so it contributes almost nothing to gut-wall first pass.'},
  {t:'Its substrates are mostly environmental chemicals rather than drugs', correct:false,
   why:'That describes CYP2E1 on slide 28. CYP2D6 handles many prescribed drugs, including codeine and venlafaxine on slide 26, and beta blockers and several psychiatric drugs in the substrate table on slide 17.'}],
 svg:DIA.d6Share,
 teach:'Three facts about CYP2D6 combine into its clinical profile. It is present in small amounts, so it saturates easily. It cannot be induced much, so the body cannot increase supply to compensate. And it is strongly polymorphic, with four phenotypes on slide 26, so patients differ from each other before any drug is given. Together these explain why codeine and tramadol produce such different results in different patients.',
 teachImg:'cyp_drug_share',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 26',
 quote:'Lots of DDIs due to low expression · i.e., 3% of liver CYPs · Lots of substrates (21% of clinical drugs)'},

{id:'cyp-e3', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'expr', concept:'cyp-families-80-percent',
 tags:['recall'], source:'slide',
 stem:'Which three CYP families account for about 80% of clinical drug metabolism?',
 options:[
  {t:'Families 1, 2 and 3, because together they metabolize about 80% of clinical drugs', correct:true,
   why:'There are more than 18 families, but three of them handle about 80 percent of clinical drugs. The isoforms named within them are 1A2, 2A6, 2B6, 2C8, 2C9, 2C19, 2D6, 2E1 and 3A4 with 3A5. These are the isoforms the course gives individual profiles for.'},
  {t:'Families 4 through 18, because they handle endogenous compounds', correct:false,
   why:'Higher-numbered families do act mainly on compounds the body makes itself, such as fatty acids and steroids. They are not emphasized because drug interactions do not arise there.'},
  {t:'Only family 3, since 3A4 handles everything clinically important', correct:false,
   why:'CYP3A4 handles about one third of drugs, which leaves two thirds to other isoforms. Two of the most serious interactions in the course sit outside family 3: warfarin through CYP2C9 on slide 24, and codeine through CYP2D6 on slide 26.'},
  {t:'All families equally, since homology within the superfamily makes them interchangeable', correct:false,
   why:'Family members share more than 40 percent of their sequence, which still leaves most of the protein different. Those differences change which drugs an isoform accepts and whether it can be induced.'}],
 teach:'Only a small part of this enzyme superfamily matters for drug therapy. Families 1, 2 and 3 handle about 80 percent of clinical drugs. For each main isoform in those families there are three facts to know: what increases how much of it the liver makes, whether patients inherit different working versions of it, and which drugs it handles. Slides 20 through 31 cover 1A2, 2B6, 2C9 with 2C19, 2D6, 2E1 and 3A4 in that order.',
 teachImg:'cyp_drug_share',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 19',
 quote:'Emphasis is on the 1, 2, 3 CYP families: They metabolize 80% of clinical drugs'},

/* ═══════════ FAMILIES & SUBSTRATES ═══════════ */
{id:'cyp-f1', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'fam', concept:'cyp2c9-warfarin',
 tags:['recall','substrate'], source:'slide',
 stem:'Which CYP isoform metabolizes (S)-warfarin?',
 options:[
  {t:'CYP2C9', correct:true,
   why:'Warfarin is given as a mixture of two mirror-image forms. The S form is the stronger anticoagulant, and CYP2C9 is the enzyme that clears it. The R form is handled by other isoforms including 1A2 and 3A4. Because the more potent form depends on one enzyme, anything that blocks CYP2C9 raises anticoagulation sharply.'},
  {t:'CYP2D6', correct:false,
   why:'The drugs named for CYP2D6 on slide 26 are codeine and venlafaxine, along with beta blockers and several antidepressants. Warfarin is not among them.'},
  {t:'CYP1A2', correct:false,
   why:'CYP1A2 does handle the R form of warfarin in the substrate table on slide 17, but the question asks about the S form. The S form is the more potent anticoagulant and belongs to CYP2C9.'},
  {t:'CYP2E1', correct:false,
   why:'CYP2E1 handles ethanol, halogenated hydrocarbons and acetaminophen during overdose. It has no anticoagulant substrates.'}],
 teach:'Warfarin is active exactly as it is given, and metabolism only destroys it. That makes every interaction predictable in direction. Block CYP2C9 and warfarin builds up, anticoagulation increases, and the patient can bleed. Increase CYP2C9 and warfarin is removed faster, anticoagulation drops, and the patient can clot. The omeprazole case on MCMet-9_4_26-9_9_26.pdf slide 52 is the first of these two.',
 teachImg:'cyp_polymorphic_adr_table',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 24',
 quote:'(S)-Warfarin (2C9) · Phenytoin & (S)-Mephenytoin (2C9/2C19) · Tolbutamide, Glipzide (2C9)'},

{id:'cyp-f2', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'fam', concept:'cyp1a2-induction-smoking',
 tags:['reasoning','induction','case'], source:'slide',
 stem:'A patient stabilized on a CYP1A2 substrate starts smoking heavily. What happens and why?',
 options:[
  {t:'Drug levels fall over days, because polycyclic aromatic hydrocarbons in tobacco smoke increase how much CYP1A2 the liver makes', correct:true,
   why:'Tobacco smoke contains polycyclic aromatic hydrocarbons, which switch on the gene for CYP1A2. The liver then makes more of the enzyme, and the drug is cleared faster, so serum levels fall. This takes days rather than hours because the cell has to transcribe the gene and build new protein.'},
  {t:'Drug levels rise immediately, because tobacco smoke blocks CYP1A2', correct:false,
   why:'Tobacco increases CYP1A2 rather than blocking it, so levels fall rather than rise. The timing is also a clue. A change that appears within hours points to blockade of enzyme already present. A change that takes days points to the liver building more enzyme.'},
  {t:'No change, because CYP1A2 is not inducible', correct:false,
   why:'Slide 20 lists CYP1A2 as induced by polycyclic aromatic hydrocarbons, dioxins and omeprazole. The isoform described as showing minimal induction is CYP2D6 on slide 26.'},
  {t:'Drug levels fall, because smoking increases renal clearance of the parent drug', correct:false,
   why:'The direction is right but the reason is wrong. Smoking does not change filtration at the glomerulus or handling in the renal tubule. The change happens in the liver, where more enzyme is built.'}],
 teach:'This interaction works in both directions. A patient who starts smoking clears the drug faster and may need a higher dose. A patient who stops smoking, for example on admission to a hospital where smoking is not allowed, loses the extra enzyme over several days and drug levels climb. Clozapine is where this matters most, because it is a CYP1A2 substrate, and the case on slide 58 follows exactly this pattern.',
 teachImg:'cyp_inducer_table',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 20; Lecture #14 (MCMet-9_16_2026.pdf) slide 57',
 quote:'Induced by PAHS (tobacco smoke), dioxins, omeprazole, etc.'},

{id:'cyp-f3', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'fam', concept:'cyp2e1-role',
 tags:['recall','toxicity'], source:'slide',
 stem:'Which isoform is key in the carcinogenicity and toxicity of halogenated hydrocarbons, and is induced by ethanol and ketones?',
 options:[
  {t:'CYP2E1', correct:true,
   why:'Slide 28 gives CYP2E1 all of these properties together. It mainly handles environmental chemicals, ethanol and ketones increase how much of it the liver makes, it is central to the toxicity of halogenated hydrocarbons, and it is polymorphic. Its listed substrates are ethanol, acetaminophen during overdose, and halogenated hydrocarbons.'},
  {t:'CYP3A4', correct:false,
   why:'CYP3A4 handles the largest share of prescribed drugs and drives first-pass metabolism. It does activate aflatoxin B1 in the table on slide 37, but the halogenated solvents in that table are listed under CYP2E1.'},
  {t:'CYP2C19', correct:false,
   why:'CYP2C19 works with CYP2C9 on phenytoin and mephenytoin, and it is the enzyme in the clopidogrel case on slide 59. It has no role with environmental halogenated chemicals.'},
  {t:'CYP1A2', correct:false,
   why:'CYP1A2 also acts on environmental chemicals, but a different group: aryl amines and polycyclic aromatic hydrocarbons. The distinction is that polycyclic aromatic hydrocarbons induce CYP1A2 while ethanol induces CYP2E1.'}],
 teach:'CYP2E1 links the metabolism half of this course to the toxicity half. Ethanol increases how much CYP2E1 the liver makes, and CYP2E1 is the enzyme that converts acetaminophen into its toxic form NAPQI. A patient who drinks heavily therefore faces two problems at once: more enzyme producing more NAPQI from the same dose, and less glutathione available to react with it. MCMet-9_17_2026.pdf slide 47 lists alcohol use as a hepatotoxicity risk factor for cirrhosis and glutathione depletion; the CYP2E1 induction comes from MCMet-9_15_2026.pdf slide 28, which names ethanol as a 2E1 inducer.',
 teachImg:'cyp_2e1_substrates',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 28; Lecture #15 (MCMet-9_17_2026.pdf) slides 47, 49',
 quote:'Mainly for environmental chemicals · Induced by ethanol & Ketones · Key in carcinogenicity/toxicity of halogenated HCs'},

{id:'cyp-f4', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'fam', concept:'cyp3a4-first-pass',
 tags:['reasoning'], source:'slide',
 stem:'Which feature of CYP3A4 best explains why it drives so much of the first-pass effect?',
 options:[
  {t:'It is abundant in the intestinal wall as well as the liver', correct:true,
   why:'A swallowed drug crosses the intestinal wall, then travels through the portal vein to the liver, and only then reaches general circulation. CYP3A4 is present in both the intestinal wall and the liver, so the drug is reduced twice before it gets anywhere. That is why oral doses of some drugs must be much larger than intravenous doses.'},
  {t:'It is the only isoform that is polymorphic', correct:false,
   why:'Slide 30 describes CYP3A4 as having only minor genetic variation. The isoforms that are strongly polymorphic are 1A2, 2B6, 2C9, 2C19, 2D6 and 2E1.'},
  {t:'It does not require NADPH', correct:false,
   why:'All CYP reactions need the same four things listed on slide 12: the enzyme, CYP450 reductase, NADPH and molecular oxygen. No isoform is exempt.'},
  {t:'It cannot be inhibited', correct:false,
   why:'CYP3A4 is one of the most frequently inhibited isoforms. Slide 32 lists azole antifungals, macrolide antibiotics, protease inhibitors and grapefruit juice among its inhibitors, and slide 35 devotes a full table to the grapefruit interaction.'}],
 teach:'First-pass metabolism is about position rather than enzyme speed. CYP3A4 happens to sit in both places a swallowed drug must pass. This also explains why grapefruit juice has such a large effect on some drugs: it blocks CYP3A4 in the intestinal wall, removing the first of those two barriers, so more of the swallowed dose survives into circulation.',
 teachImg:'cyp_intestine_share',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 30',
 quote:'Largely responsible for 1st pass effect · Present in liver, intestine, lungs'},

{id:'cyp-f5', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'fam', concept:'cyp1a2-substrates',
 tags:['recall','substrate'], source:'slide',
 stem:'Caffeine, imipramine and haloperidol are substrates of which CYP isoform?',
 options:[
  {t:'CYP1A2', correct:true,
   why:'These three are the drugs named for CYP1A2 on slide 20. They fit its stated preference for aryl amines and ring systems containing nitrogen. Caffeine is a xanthine, which is a nitrogen-containing double ring. Imipramine and haloperidol both contain nitrogen-bearing rings.'},
  {t:'CYP2C9', correct:false,
   why:'The drugs named for CYP2C9 on slide 24 are (S)-warfarin, phenytoin, tolbutamide and glipizide. Those are anticoagulants, anticonvulsants and oral diabetes drugs, a different group.'},
  {t:'CYP3A4', correct:false,
   why:'CYP3A4 does handle caffeine in the wider substrate table on slide 17, but the isoform the lecture names for caffeine is CYP1A2. CYP3A4\'s named drugs are calcium channel blockers, statins, benzodiazepines and immunosuppressants.'},
  {t:'CYP2D6', correct:false,
   why:'The drugs named for CYP2D6 are codeine and venlafaxine. Haloperidol is the tempting choice here because slide 17 lists it under 2D6 as well as under 1A2, and imipramine appears in both columns too. Caffeine is the one of the three that sits only under 1A2, so caffeine is what pins the trio to CYP1A2.'}],
 teach:'Each isoform accepts drugs of a particular shape and electronic character. CYP1A2 takes flat ring systems containing nitrogen, which is also why polycyclic aromatic hydrocarbons, which have the same flat ring shape, switch on its gene. CYP2C9 takes several acidic drugs. CYP2D6 takes basic amines. CYP3A4 takes large, greasy molecules. When an unfamiliar drug appears, its structure points to the likely isoform.',
 teachImg:'cyp_1a2_substrates',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 20–21',
 quote:'1A2 - clinically relevant substrates: Caffeine, Imipramine, Haloperidol, etc.'},

{id:'cyp-f6', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'fam', concept:'cyp2b6-profile',
 tags:['recall','polymorphism'], source:'slide',
 stem:'Which CYP isoform is induced by several drugs, shows polymorphism with efavirenz, and metabolizes bupropion, methadone and insecticides?',
 options:[
  {t:'CYP2B6', correct:true,
   why:'Slide 22 gives CYP2B6 these three properties together. Its substrate list is deliberately mixed: a smoking-cessation and antidepressant drug, an opioid, and insecticides from the environment. That range shows what the course means when it says these enzymes have broad substrate activity.'},
  {t:'CYP2C8', correct:false,
   why:'CYP2C8 appears in the substrate table on slide 17 with amodiaquine, cerivastatin, repaglinide and paclitaxel, but it is not given its own profile of induction and polymorphism.'},
  {t:'CYP2E1', correct:false,
   why:'CYP2E1 is induced by ethanol and ketones rather than by several drugs, and its substrates are ethanol, acetaminophen during overdose, and halogenated hydrocarbons.'},
  {t:'CYP1A2', correct:false,
   why:'CYP1A2 is induced by polycyclic aromatic hydrocarbons, dioxins and omeprazole, and its named drugs are caffeine, imipramine and haloperidol.'}],
 teach:'Slide 22 calls family 2 the largest clinically relevant family, containing 2B6, 2C9, 2C19, 2D6 and 2E1. Most of the polymorphism in this course sits in that family, so it is where a patient\'s genotype changes the outcome most. CYP3A4 by contrast is abundant and easily induced but varies little between individuals.',
 teachImg:'cyp_2b6_substrates',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 22',
 quote:'CYP isoform 2B6: Induced by several drugs · Polymorphism (e.g., observed with Efavirenz) · Diverse substrates including: Bupropion, Methadone, insecticides'},

{id:'cyp-f7', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'fam', concept:'cyp2c-inducible-polymorphic',
 tags:['recall','polymorphism'], source:'slide',
 stem:'What do CYP2C9 and CYP2C19 have in common besides sharing a subfamily?',
 options:[
  {t:'Both are inducible and both are polymorphic, and together they metabolize about 25% of clinically important drugs', correct:true,
   why:'Slide 24 gives all three points for the pair. Being both inducible and polymorphic means their activity varies for two independent reasons: what else the patient is taking, and which version of the gene the patient inherited. Phenytoin and (S)-mephenytoin are handled by both, which follows from their shared subfamily and more than 50 percent sequence match.'},
  {t:'Neither is inducible and neither shows polymorphism', correct:false,
   why:'Slide 24 states both properties for both enzymes. The isoform described as showing minimal induction is CYP2D6 on slide 26.'},
  {t:'Both are induced by ethanol', correct:false,
   why:'Ethanol induces CYP2E1, on slide 28. Ethanol also appears on the general inducer list on slide 32, but slide 33 pairs it with 2D6 and 2E1, and slide 28 gives 2E1 as the isoform ethanol induces.'},
  {t:'Both are confined to the intestine', correct:false,
   why:'Presence in the intestine is a CYP3A4 property from slide 30, and it is what makes 3A4 central to first-pass metabolism. Neither is confined to the intestine: the slide 15 pie of small-intestinal CYP is 82 percent 3A, 14 percent 2C9 and 2 percent 2C19, so 2C enzymes are present there but 3A dominates.'}],
 teach:'Two enzymes sharing a subfamily letter share more than half their amino acid sequence, so they tend to accept the same drugs and respond to the same regulation. That is why phenytoin is listed under both CYP2C9 and CYP2C19. It also means a drug that blocks one may affect the other, so the subfamily letter is a practical warning rather than just a naming detail.',
 teachImg:'cyp_polymorphism_table',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 24',
 quote:'Both are inducible · Both are polymorphic'},

/* ═══════════ INDUCTION & INHIBITION ═══════════ */
{id:'cyp-i1', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'indinh', concept:'induction-mechanism',
 tags:['mechanism','induction'], source:'slide',
 stem:'By what mechanism does enzyme induction increase metabolic capacity?',
 options:[
  {t:'Activation of DNA transcription, so the cell makes more enzyme protein', correct:true,
   why:'Induction increases the number of enzyme molecules rather than making each one faster. The inducer switches on the gene, the cell transcribes it into messenger RNA, and that RNA is used to build more enzyme. Each of those steps takes time, which is why induction develops over days and takes days to wear off after the inducer is stopped.'},
  {t:'Direct activation of enzyme molecules already present', correct:false,
   why:'No such mechanism is described for CYP induction, and the timing rules it out. Activating existing enzyme would change clearance within minutes. Induction takes days, which only fits building new protein.'},
  {t:'Displacement of the drug from plasma protein binding sites', correct:false,
   why:'Displacement from plasma proteins increases the fraction of drug that is free in blood, covered in 090426_Distribution.pdf slides 25 to 26. It does not change how much enzyme exists. More free drug can reach the enzyme, but the enzyme supply is unchanged.'},
  {t:'Blockade of the enzyme active site by a second substrate', correct:false,
   why:'Blocking the active site is inhibition, which reduces metabolism. This option describes the opposite of what the question asks about.'}],
 teach:'Induction and inhibition differ in what they change, how quickly, and how they reverse. Induction changes the number of enzyme molecules, develops over days, and fades over days as the extra protein is broken down. Inhibition changes whether existing enzyme can work, starts immediately, and ends as soon as the inhibitor is cleared. Knowing which one you are dealing with tells you how soon to expect a change after starting or stopping a drug.',
 teachImg:'cyp_inducer_table',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 47; Lecture #14 (MCMet-9_16_2026.pdf) slide 53',
 quote:'Mechanism: Activation of DNA transcription'},

{id:'cyp-i2', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'indinh', concept:'inhibitor-recognition',
 tags:['recall','inhibition','exam-pattern'], source:'slide',
 stem:'Which group of agents appears on the common CYP inhibitor list rather than the inducer list?',
 options:[
  {t:'Azole antifungals such as ketoconazole and itraconazole', correct:true,
   why:'Slide 32 lists the inhibitors as clarithromycin, erythromycin, azole antifungals, cimetidine, protease inhibitors, grapefruit juice, quinidine and omeprazole. Azoles are strong inhibitors because a nitrogen atom in their ring binds directly to the iron at the CYP active site, which prevents oxygen from binding there.'},
  {t:'Barbiturates, carbamazepine and phenytoin', correct:false,
   why:'All three are on the inducer list. Carbamazepine and phenytoin are worth separating out because they are anticonvulsants that increase the clearance of other drugs, and in some cases their own.'},
  {t:'Rifampin and St John\'s wort', correct:false,
   why:'Both are on the inducer list. St John\'s wort matters in practice because patients often do not report supplements when asked what medications they take.'},
  {t:'Tobacco smoke and nevirapine', correct:false,
   why:'Both are on the inducer list. Tobacco increases CYP1A2 through its polycyclic aromatic hydrocarbon content, the same chemistry that appears again on slide 57 of MCMet-9_16_2026.pdf under smoked and barbecued food.'}],
 teach:'The two lists divide along a chemical line. Most inducers are substances taken repeatedly over time that switch on enzyme genes: anticonvulsants, rifampin, alcohol, tobacco and St John\'s wort. Most inhibitors physically interfere with an enzyme that already exists, and the furocoumarins in grapefruit juice are the course\'s worked example: MCMet-9_16_2026.pdf slide 63 calls them mechanism-based inhibitors of CYP3A4, meaning the enzyme oxidises them to an epoxide that then binds the enzyme itself. Azole antifungals inhibit by binding the heme iron, which is standard pharmacology rather than a claim on these slides. Omeprazole is the exception to learn separately, because it appears as an inhibitor on slide 32 and as a CYP1A2 inducer on slide 20.',
 teachImg:'cyp_ind_inh_lists',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 32',
 quote:'Common Inhibitors: Clarithromycin · Erythromycin · Azole Antifungals: Ketoconazole, Itraconazole · Cimetidine · Protease inhibitors · Grape Fruit Juice · Quinidine · Omeprazole'},

{id:'cyp-i7', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'indinh', concept:'omeprazole-dual-role',
 tags:['enzyme','exam-pattern','interaction'], source:'slide',
 stem:'Omeprazole induces CYP1A1/2 and CYP3A4 and also appears among the common CYP inhibitors. How can one drug do both?',
 options:[
  {t:'Induction and inhibition act on different isoforms, so one drug can raise the amount of one enzyme while blocking the activity of another', correct:true,
   why:'The two processes work at different places. Induction increases how many enzyme molecules the cell makes, through gene transcription, and reaches only the isoforms that respond to that signal. Inhibition interferes with enzyme already present, at the active site of whichever isoform the drug binds. Nothing requires those to be the same isoform. Slide 33 gives omeprazole as an inducer of 1A1/2 and 3A4; slide 32 carries it on the common inhibitor list, and slide 34 names the inhibited isoform: omeprazole is the first entry in the CYP2C19 column.'},
  {t:'One of the two must be an error, because a drug cannot both induce and inhibit', correct:false,
   why:'Both hold at once, on different isoforms. A drug that induces one isoform and inhibits another is the reason interaction checks are run per isoform rather than per drug.'},
  {t:'Omeprazole induces at low dose and inhibits at high dose', correct:false,
   why:'Dose changes the size of each effect but is not what separates them. The separation is which isoform is involved: slide 33 names the induced isoforms, 1A1/2 and 3A4, with no dose condition attached.'},
  {t:'Induction and inhibition are the same process observed at different times', correct:false,
   why:'They differ in mechanism as well as in timing. Induction changes the number of enzyme molecules, develops over days, and fades over days as the extra protein is degraded. Inhibition changes the activity of enzyme that already exists and appears with the first doses.'}],
 teach:'An inducer increases how much enzyme the cell makes; an inhibitor blocks enzyme that is already there. Those are different mechanisms acting at different points, so one drug can do one of them to one isoform and the other to a second isoform, in the same patient at the same time. Lecture 13 carries omeprazole three times: slide 33 gives it as an inducer of CYP1A1/2 and CYP3A4, slide 20 repeats the CYP1A2 induction, and slide 34 lists it first in the CYP2C19 column of the inhibitor table. Slide 17 also shows it among the proton pump inhibitors under CYP2C19 as a substrate. So the picture is: induces 1A1/2 and 3A4, inhibits 2C19, and is itself cleared by 2C19. Lecture 14 slide 46 fits that: neonates with low CYP2C19 should avoid omeprazole, because a patient with little of the enzyme that clears it will accumulate it.',
 teachImg:'cyp_inducer_table',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 17, 20, 32, 33, 34; Lecture #14 (MCMet-9_16_2026.pdf) slide 46',
 quote:'Many DIs due to induction/inhibition'},

{id:'cyp-i3', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'indinh', concept:'ddi-inhibition-active-drug',
 tags:['case','reasoning'], source:'slide',
 stem:'Omeprazole and warfarin taken together can produce a bleeding event. What is the mechanism?',
 options:[
  {t:'Omeprazole blocks the CYP that inactivates warfarin, so warfarin builds up and anticoagulation increases', correct:true,
   why:'Warfarin works as given, and metabolism only removes it. Omeprazole is on the inhibitor list on slide 32. Blocking the enzyme that clears (S)-warfarin leaves more warfarin in circulation for longer, so anticoagulation goes further than intended and the patient can bleed.'},
  {t:'Omeprazole increases the CYP that inactivates warfarin, so warfarin is cleared faster', correct:false,
   why:'Faster clearance would reduce anticoagulation and risk a clot, not a bleed, so this does not match the stated outcome. Omeprazole is also listed as an inhibitor rather than an inducer.'},
  {t:'Omeprazole displaces warfarin from plasma proteins and speeds its renal excretion', correct:false,
   why:'Displacement from plasma proteins is a real phenomenon, in 090426_Distribution.pdf slide 25, but it is not the mechanism in this case. Warfarin is also cleared by metabolism rather than by being excreted unchanged in urine.'},
  {t:'Omeprazole is a prodrug that is converted into a second anticoagulant', correct:false,
   why:'No second anticoagulant is produced, and the check that settles it is asking which molecule the excess is made of. An inhibition interaction raises the concentration of a drug that was already there by slowing its removal, so the extra effect has to be warfarin that was not broken down rather than a new agent appearing. Picking this means reading \u2018metabolism is involved\u2019 as \u2018a new active species is formed\u2019, which is bioactivation, a different consequence of metabolism from inhibition.'}],
 svg:DIA.directionGrid,
 teach:'Four cases in these decks all turn on one question: is the drug active as given, or does it need to be converted into something active first? Warfarin and glyburide are active as given, so blocking their metabolism increases the effect. Tramadol and clopidogrel must be converted, so blocking that conversion reduces the effect. Answer that question first and the direction of any interaction follows.',
 teachImg:'cyp_active_drug_grid',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 52; Lecture #13 (MCMet-9_15_2026.pdf) slide 24',
 quote:'Case: Intake of Omeprazole and Warfarin could lead to a bleeding event. Explain.'},

{id:'cyp-i4', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'indinh', concept:'ddi-inhibition-glyburide',
 tags:['case','reasoning'], source:'slide',
 stem:'Erythromycin inhibits the inactivation of glyburide, an antidiabetic. What is the likely clinical outcome?',
 options:[
  {t:'Hypoglycemia, because glyburide stays in the body longer and keeps lowering blood glucose', correct:true,
   why:'Glyburide lowers blood glucose and is active as given. Erythromycin is on the inhibitor list on slide 32. Blocking the enzyme that inactivates glyburide leaves more of it working for longer, so blood glucose falls further than intended.'},
  {t:'Hyperglycemia, because glyburide is cleared more quickly', correct:false,
   why:'Inhibition slows clearance rather than speeding it. Faster clearance and loss of effect is what would happen with an inducer such as rifampin.'},
  {t:'No change, because glyburide is eliminated unchanged by the kidney', correct:false,
   why:'The case describes glyburide as being inactivated by an enzyme, which is why blocking that enzyme matters. Glyburide also appears as a CYP2C9 substrate in the table on slide 17.'},
  {t:'Hypoglycemia, because erythromycin independently lowers blood glucose', correct:false,
   why:'The outcome is right but the cause is wrong. Erythromycin has no glucose-lowering action of its own. All of the extra effect comes from glyburide that was not broken down.'}],
 teach:'Inhibiting an enzyme does not create a new effect. It produces more of the effect the drug already has. For an anticoagulant that means bleeding. For a sulfonylurea it means low blood glucose. For a sedative it means excessive sedation. To predict the adverse event, ask what the drug does, then picture more of it.',
 teachImg:'cyp_active_drug_grid',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 53',
 quote:'Case: Erythromycin inhibits Glyburide (anti-diabetes drug) inactivation, the likely outcome?'},

{id:'cyp-i5', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'indinh', concept:'gfj-mechanism',
 tags:['mechanism','inhibition','case'], source:'slide',
 stem:'Grapefruit juice raises the bioavailability of nifedipine and felodipine. What is responsible?',
 options:[
  {t:'Furocoumarins, chiefly bergamottin and 6\',7\'-dihydroxybergamottin, block CYP3A4', correct:true,
   why:'Grapefruit contains a group of compounds called furocoumarins, and slide 63 names bergamottin and 6\',7\'-dihydroxybergamottin as the most abundant of them. They are mechanism-based inhibitors of CYP3A4: the enzyme oxidises the furan double bond to an epoxide, which then binds the enzyme itself. They block CYP3A4 in the intestinal wall. Because that enzyme normally destroys part of the dose before it is absorbed, blocking it allows more of the swallowed dose to reach circulation.'},
  {t:'Grapefruit juice increases how much CYP3A4 the liver makes', correct:false,
   why:'More enzyme would clear the drug faster and lower the amount reaching circulation, which is the opposite of the observed rise. Grapefruit juice is on the inhibitor list on slide 32.'},
  {t:'Grapefruit juice raises gastric pH, improving tablet dissolution', correct:false,
   why:'A change in stomach pH would affect any drug in that dosage form. This interaction only affects drugs handled by CYP3A4, which points to the enzyme rather than to dissolution.'},
  {t:'Grapefruit juice blocks P-glycoprotein only, with no CYP involvement', correct:false,
   why:'The mechanism taught here is CYP3A4 inhibition. P-glycoprotein is an efflux transporter covered separately in 090326_ADMETAbsorption_I.pdf slides 21 to 24.'}],
 teach:'Where an enzyme sits determines what kind of change results when it is blocked. Blocking CYP3A4 in the intestinal wall increases how much of the swallowed dose gets absorbed, which is a bioavailability change. Blocking the same enzyme in the liver slows removal of drug that is already in circulation. Grapefruit juice does both, and the intestinal part is why the effect is so large for drugs that normally lose most of their dose to first-pass metabolism.',
 teachImg:'cyp_gfj_table',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 62–64; Lecture #13 (MCMet-9_15_2026.pdf) slide 35',
 quote:'Bergamottin & 6\',7\'-dihydroxybergamottin are the most abundant Furocoumarins in GFJ · mechanism-based inhibitors of 3A4'},

{id:'cyp-i6', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'indinh', concept:'gfj-affected-classes',
 tags:['recall','case'], source:'slide',
 stem:'Which two drug classes dominate the grapefruit juice interaction table?',
 options:[
  {t:'Calcium channel blockers and HMG-CoA reductase inhibitors', correct:true,
   why:'The table on slide 35 is built around these two classes, listing amlodipine, felodipine, nifedipine, nimodipine and nisoldipine on one side, and atorvastatin, lovastatin and simvastatin on the other. Both classes contain CYP3A4 substrates that normally lose a large part of their dose to first-pass metabolism, which is what makes blocking intestinal CYP3A4 so significant for them.'},
  {t:'Beta blockers and proton pump inhibitors', correct:false,
   why:'Beta blockers are mostly CYP2D6 substrates and proton pump inhibitors mostly CYP2C19 substrates, as the table on slide 17 shows. Neither class depends on CYP3A4 the way the calcium channel blockers and statins do.'},
  {t:'Aminoglycoside antibiotics and penicillins', correct:false,
   why:'These are polar drugs removed largely unchanged by the kidney, so there is little hepatic metabolism to block. Vancomycin and ampicillin appear as renal elimination examples in MCMet-9_17_2026.pdf slide 8.'},
  {t:'Inhaled anesthetics and volatile solvents', correct:false,
   why:'These leave the body by being breathed out rather than by being metabolized, in MCMet-9_17_2026.pdf slide 22, so blocking an enzyme has little effect on them.'}],
 teach:'The table reduces to one rule: grapefruit matters for CYP3A4 substrates that lose a large fraction of their dose to first-pass metabolism. Not every drug in a class behaves the same way. The table marks pravastatin and fluvastatin differently from simvastatin and lovastatin, because those two depend less on CYP3A4.',
 teachImg:'cyp_gfj_table',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 35',
 quote:'Calcium channel blocker · HMG-CoA reductase inhibitors'},

/* ═══════════ BIOACTIVATION ═══════════ */
{id:'cyp-b1', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'bioact', concept:'cyp-bioactivation-carcinogens',
 tags:['toxicity','reasoning'], source:'slide',
 stem:'Benzo[a]pyrene and other polycyclic aromatic hydrocarbons are bioactivated to carcinogens by which isoforms?',
 options:[
  {t:'CYP1A1 and CYP1A2', correct:true,
   why:'The table on slide 37 groups benzo[a]pyrene, other polycyclic aromatic hydrocarbons, 4-aminobiphenyl and 2-naphthylamine under CYP1A1 and CYP1A2. This matches what those enzymes normally handle, which is aryl amines and flat ring systems. It also creates a loop: polycyclic aromatic hydrocarbons increase how much CYP1A2 the liver makes, and CYP1A2 then converts them into carcinogens.'},
  {t:'CYP2D6 and CYP2C9', correct:false,
   why:'Neither appears in the bioactivation table on slide 37. Both matter for drug interactions and inherited variation, but not for converting environmental chemicals into carcinogens.'},
  {t:'CYP2B6 alone', correct:false,
   why:'CYP2B6 is not in the bioactivation table. Its profile on slide 22 is drug-induced increase, polymorphism seen with efavirenz, and substrates including bupropion, methadone and insecticides.'},
  {t:'No CYP enzymes; bioactivation is performed only by Phase 2 transferases', correct:false,
   why:'Phase 2 conjugation usually ends reactivity by attaching a polar partner molecule. Converting a harmless compound into a carcinogen is a CYP reaction, and slide 7 names it as one of the two reasons CYPs matter.'}],
 teach:'Each isoform activates the chemicals that resemble the drugs it normally handles. CYP1A1 and CYP1A2 take flat aromatic rings and aryl amines. CYP2E1 takes small halogenated solvents such as carbon tetrachloride and chloroform, matching its role with halogenated hydrocarbons on slide 28. CYP3A4 takes larger molecules including aflatoxin B1. Substrate preference and bioactivation profile are the same property described from two directions.',
 teachImg:'cyp_bioactivation_table',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 36–37',
 quote:'CYP1A1 CYP1A2: Benzo[a]pyrene, Other PAHs, 4-Aminobiphenyl, 2-Naphthylamine'},

{id:'cyp-b2', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'bioact', concept:'cyp2e1-solvent-activation',
 tags:['toxicity','recall'], source:'slide',
 stem:'Carbon tetrachloride, chloroform and trichloroethylene are bioactivated by which isoform?',
 options:[
  {t:'CYP2E1', correct:true,
   why:'All three are small molecules carrying chlorine atoms, and the table on slide 37 lists them under CYP2E1. This matches slide 28, which names CYP2E1 as central to the toxicity of halogenated hydrocarbons. The products are carbons that are short of electrons, which is the first category of toxic group listed in MCMet-9_17_2026.pdf slide 30.'},
  {t:'CYP1A2', correct:false,
   why:'CYP1A2 activates aryl amines and polycyclic aromatic hydrocarbons, which are flat ring systems rather than small halogenated molecules. Both isoforms act on environmental chemicals, but of different types.'},
  {t:'CYP3A4', correct:false,
   why:'CYP3A4 activates aflatoxin B1, aflatoxin G1 and some steroids in the table on slide 37. The small halogenated solvents are listed under CYP2E1.'},
  {t:'CYP2C19', correct:false,
   why:'CYP2C19 does not appear in the bioactivation table. In this course it matters for inherited variation, particularly in the clopidogrel case on slide 59.'}],
 teach:'One chemical property explains three separate facts about halogenated hydrocarbons. A chlorine atom pulls electrons away from the carbon it is attached to, leaving that carbon short of electrons and therefore reactive toward proteins. MCMet-9_16_2026.pdf slide 21 states these compounds are very greasy and not easily converted into water-soluble forms, so they stay in the body. MCMet-9_17_2026.pdf slide 31 lists a halogen-bearing carbon as a toxic group and uses halothane as the example.',
 teachImg:'cyp_bioactivation_table',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 37; Lecture #15 (MCMet-9_17_2026.pdf) slide 31',
 quote:'CYP2E1: Benzene, Styrene, Acrylonitrile, Vinyl bromide, Trichloroethylene, Carbon tetrachloride, Chloroform, Methylene chloride'},

/* ═══════════ POLYMORPHISM ═══════════ */
{id:'cyp-p1', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'poly', concept:'poly-phenotypes',
 tags:['definition','polymorphism'], source:'slide',
 stem:'The four polymorphic phenotypes listed for CYP2D6 are ultrarapid, extensive, intermediate and poor metabolizer. In this course, which one did Dr. Sikazwe describe as the normal metabolizer?',
 options:[
  {t:'Intermediate metabolizer', correct:true,
   why:'From lecture audio (09/15, walking slide 26): "The intermediate, IM, is the normal metabolizer phenotype. That is where we want people to be." He repeated it on 09/16: "intermediate, which is like normal metabolizer." That is the definition this course examines. The standard pharmacogenomics definition places normal function under extensive metabolizer instead, and the note under this question carries that conflict, but an exam written from these lectures keys IM as the normal one.'},
  {t:'Extensive metabolizer', correct:false,
   why:'This is the textbook answer, and it is what most pharmacogenomics references say: EM is the normal phenotype and the others are defined against it. It is not what was said in this course. The 09/15 lecture describes EM as behaving like an ultrarapid metabolizer, producing a lot more metabolite. Picking it here means answering from general knowledge rather than from the lecture, which on this one point differ.'},
  {t:'Ultrarapid metabolizer', correct:false,
   why:'Ultrarapid metabolizers usually carry extra working copies of the gene, so they clear the drug faster than normal. Neither the course nor the textbook treats this as the reference; it is the fastest departure from it.'},
  {t:'Poor metabolizer', correct:false,
   why:'Poor metabolizer has the least enzyme function of the four. This is the phenotype that builds up an active parent drug and fails to convert a prodrug. It is the slowest departure from normal, not normal itself.'}],
 teach:'Phenotype alone only tells you whether enzyme activity is higher or lower than normal. To reach a clinical answer you also need to know whether the drug works as given or must be converted first. A poor metabolizer on warfarin over-anticoagulates, because warfarin works as given and is building up. A poor metabolizer on codeine gets no pain relief, because codeine must be converted to morphine and that conversion is not happening. Same phenotype, opposite results.',
 teachImg:'cyp_pm_um_populations',
 note:'Source conflict, stated rather than resolved. Slide 26 lists the four phenotypes with no definitions. The 09/15 and 09/16 lectures both key intermediate metabolizer as the normal phenotype and extensive metabolizer as a fast, high-metabolite one. Standard references (Foye, CPIC) key extensive metabolizer as normal and intermediate as reduced function. Answer this course\'s exam with the lecturer\'s definition; know that a reference outside the course will say the other.',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 26; lecture audio 09/15 and 09/16 (marked)',
 quote:'Polymorphic phenotypes: UM; EM; IM; PM'},

{id:'cyp-p2', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'poly', concept:'poly-prodrug-direction',
 tags:['case','reasoning','polymorphism'], source:'both',
 stem:'Tramadol is converted by CYP2D6 to O-desmethyltramadol, the more active species. What happens in a poor metabolizer?',
 options:[
  {t:'Less active metabolite is formed, so analgesia is reduced', correct:true,
   why:'Tramadol itself is a weak analgesic. Most of its pain relief comes from O-desmethyltramadol, which CYP2D6 produces. A poor metabolizer makes very little of that product, so the patient reports the drug is not working. An ultrarapid metabolizer makes too much of it instead, enough morphine from a standard codeine dose to cause opioid toxicity, so the same enzyme variation produces treatment failure at one extreme and overdose at the other.'},
  {t:'More active metabolite is formed, so analgesia is excessive', correct:false,
   why:'That describes an ultrarapid metabolizer. A poor metabolizer has less enzyme function, so less of the active product is made.'},
  {t:'Parent drug accumulates and produces stronger analgesia', correct:false,
   why:'Parent drug does accumulate, but tramadol itself is the weaker of the two forms. Having more of a weak analgesic does not make up for having almost none of the strong one.'},
  {t:'No change, because CYP2D6 is not polymorphic', correct:false,
   why:'Slide 26 lists all four phenotypes for CYP2D6 and describes its substrate list as extensive. It is one of the most variable isoforms between patients.'}],
 teach:'Codeine and tramadol behave the same way because both depend on CYP2D6 to remove a methyl group from an oxygen. Codeine becomes morphine, in MCMet-9_10_26.pdf slide 17. Tramadol becomes O-desmethyltramadol. In both, a poor metabolizer gets too little pain relief and an ultrarapid metabolizer risks slowed breathing. Recognizing the shared step handles both drugs at once.',
 teachImg:'cyp_tramadol_odt',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 47; Lecture #11 (MCMet-9_10_26.pdf) slide 17'},

{id:'cyp-p3', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'poly', concept:'poly-vs-induction-analogy',
 tags:['reasoning','polymorphism'], source:'slide',
 stem:'TRUE/FALSE. Enzyme induction is analogous to a rapid metabolizer phenotype. Explain your answer.',
 options:[
  {t:'Both raise enzyme activity so the drug clears faster, but induction is acquired and reversible while the phenotype is inherited and fixed', correct:true,
   why:'The result on the drug is the same in both: more enzyme activity, faster clearance, lower drug levels. The difference is where the change comes from and whether it can be undone. An inducer can be stopped and enzyme levels return to normal within days. A patient\'s genotype does not change, so a dose adjustment made for it is permanent.'},
  {t:'Both permanently change the patient\'s genotype', correct:false,
   why:'Induction does not alter DNA sequence. It increases how often the existing gene is transcribed, and that increase reverses once the inducer is gone.'},
  {t:'Both reduce the amount of functional enzyme available', correct:false,
   why:'That describes the other pair: inhibition and the poor metabolizer phenotype. Those two are also comparable to each other, with the same caveat about acquired versus inherited.'},
  {t:'Both apply only to Phase 1 enzymes', correct:false,
   why:'Phase 2 enzymes show all three properties as well. N-acetyltransferase 2 has slow and fast acetylator forms, in MCMet-9_10_26.pdf slide 53, and UDP-glucuronosyltransferase activity is low in newborns, in MCMet-9_16_2026.pdf slide 46.'}],
 svg:DIA.directionGrid,
 teach:'Four situations reduce to a two-by-two grid. Enzyme activity can be higher than normal, from an inducer or from an ultrarapid phenotype, or lower than normal, from an inhibitor or from a poor metabolizer phenotype. Then the drug type decides what that means for the patient. If the drug works as given, more enzyme activity means less effect. If the drug must be converted first, more enzyme activity means more effect.',
 teachImg:'cyp_active_drug_grid',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 50',
 quote:'Enzyme induction is analogous to rapid metabolizer phenotype. TRUE/FALSE'},

{id:'cyp-p4', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'poly', concept:'poly-phase2-also',
 tags:['reasoning','polymorphism'], source:'slide',
 stem:'True or false: only Phase 1 enzymes are inducible, can be inhibited, and exhibit polymorphism.',
 options:[
  {t:'False — Phase 2 enzymes show all three properties as well', correct:true,
   why:'N-acetyltransferase 2 comes in slow and fast acetylator forms, in MCMet-9_10_26.pdf slide 53, which changes how quickly drugs such as isoniazid are cleared. UDP-glucuronosyltransferase activity is low at birth and rises over the first weeks of life, in MCMet-9_16_2026.pdf slide 46, which is why newborns cannot clear bilirubin efficiently.'},
  {t:'True — Phase 2 conjugation is constitutive and unregulated', correct:false,
   why:'If Phase 2 were unregulated, neither the acetylator phenotypes nor newborn jaundice would have an explanation. Both appear in the course as Phase 2 variation.'},
  {t:'True — only CYPs have allelic variants', correct:false,
   why:'Gene variants occur in any gene. N-acetyltransferase 2 variants are what produce the slow and fast acetylator phenotypes.'},
  {t:'False — but only inhibition applies to Phase 2, not induction or polymorphism', correct:false,
   why:'The first word is right and the list after it is not. Polymorphism applies, since N-acetyltransferase 2 acetylator status is inherited and splits patients into slow and fast, on MCMet-9_10_26.pdf slide 53. Induction applies as well: MCMet-9_16_2026.pdf slide 53 states that CYPs, UDP-glucuronosyltransferases and glutathione S-transferases have inducible isoforms, and slide 58 has dioxin and PCB pollutants raising some UGT isoforms. The neonatal case on slide 46, low UGT1A1 at birth, is maturation of the enzyme rather than induction, so it does not carry this point. Choosing this usually means recalling one Phase 2 counterexample and treating it as the only one.'}],
 teach:'Phase 1 gets more attention in this course because CYP interactions are more common, but the same three variables operate in Phase 2 and the consequences can be as serious. A slow acetylator clears isoniazid more slowly and is more prone to its adverse effects. A newborn cannot attach glucuronic acid to bilirubin quickly enough. In both cases the limitation is Phase 2 capacity, not CYP activity.',
 teachImg:'cyp_ethnic_frequencies',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 51; Lecture #11 (MCMet-9_10_26.pdf) slide 53; Lecture #14 (MCMet-9_16_2026.pdf) slide 46',
 quote:'Only phase I enzymes are inducible, can be inhibited, and exhibit polymorphism. TRUE/FALSE'},

{id:'cyp-p5', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'poly', concept:'phase12-both-substrate-types',
 tags:['reasoning'], source:'slide',
 stem:'True or false: Phase 1 and Phase 2 enzymes metabolize both endobiotics and xenobiotics.',
 options:[
  {t:'True — both phases act on compounds the body makes and on compounds from outside it', correct:true,
   why:'Endobiotics are compounds the body produces, such as bilirubin and steroid hormones. Xenobiotics come from outside, including drugs. Bilirubin is handled by UDP-glucuronosyltransferase, in MCMet-9_10_26.pdf slide 46, and steroid hormones appear in the CYP substrate table on slide 17. The same enzymes handle both categories.'},
  {t:'False — Phase 1 handles xenobiotics and Phase 2 handles endobiotics', correct:false,
   why:'There is no such split. A single molecule often goes through a Phase 1 reaction and then a Phase 2 reaction regardless of whether it came from outside the body.'},
  {t:'False — drug-metabolizing enzymes act only on foreign compounds', correct:false,
   why:'These enzymes existed before any drugs did, handling the body\'s own chemistry and compounds from food. Processing drugs is an additional use of a system that was already there.'},
  {t:'True — but only in the liver', correct:false,
   why:'The first part is right but the restriction is not. MCMet-9_4_26-9_9_26.pdf slide 19 describes metabolism in the liver and outside it, and slide 20 lists three cellular locations: the endoplasmic reticulum, the cytosol and the mitochondria.'}],
 teach:'One enzyme handling many unrelated compounds is the reason drug interactions happen at all. If each enzyme accepted only one substrate, two drugs could never compete. Because a single enzyme accepts drugs, hormones and dietary compounds alike, adding one drug changes how everything else in that queue is processed. MCMet-9_4_26-9_9_26.pdf slide 16 lists this broad substrate activity first among enzyme characteristics.',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 49; Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slides 7, 16',
 quote:'Phases I & II enzymes metabolize both endobiotics and xenobiotics. TRUE/FALSE'},

/* ═══════════ CASES ═══════════ */
{id:'cyp-x1', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'cases', concept:'polypharmacy-multiple-enzymes',
 tags:['reasoning','case'], source:'slide',
 stem:'In polypharmacy, why is it preferable for a drug to be metabolically deactivated by several enzymes rather than one?',
 options:[
  {t:'Alternative routes remain if one enzyme is blocked or genetically deficient, so drug levels change less', correct:true,
   why:'If a drug has only one clearance route, anything that disables that route stops clearance almost entirely. Blocking it with an inhibitor, or giving the drug to a patient who inherited a poor-function version, leaves nothing to take over. With several routes, losing one shifts the load to the others and drug levels change much less.'},
  {t:'Multiple enzymes always produce a more active metabolite', correct:false,
   why:'Whether a metabolite is active depends on what the product looks like chemically, not on how many enzymes were involved. Extra routes can also produce harmful products, which is what happens with acetaminophen when a second route opens during overdose.'},
  {t:'It guarantees the drug will not be a transporter substrate', correct:false,
   why:'How a drug is metabolized and whether a transporter moves it are independent. Several CYP3A4 substrates are also moved by P-glycoprotein, in 090326_ADMETAbsorption_I.pdf slide 24.'},
  {t:'It removes the need for renal elimination', correct:false,
   why:'Metabolism makes a drug easier to remove; it does not remove it. The polar products still have to leave the body, usually through the kidney.'}],
 teach:'This matters when a drug is being developed as well as when it is prescribed. A drug that depends on a single polymorphic enzyme will behave very differently in the fraction of patients who carry a poor-function version. Spreading clearance across several enzymes narrows the range of drug levels across a population, which matters most for drugs where the safe and toxic doses are close together.',
 teachImg:'cyp_phase1_enzyme_share',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 45',
 quote:'In polypharmacy, it is preferrable for a drug to be metabolically deactivated by several enzymes. Why?'},

{id:'cyp-x2', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'cases', concept:'meperidine-normeperidine',
 tags:['case','reasoning'], source:'slide',
 stem:'A patient with end-stage renal disease on dialysis receives meperidine for pain and develops myoclonic contractions and a grand mal seizure. What explains this?',
 options:[
  {t:'Normeperidine, formed via CYP3A4 and 2B6, is about three times more potent as a convulsant and builds up when the kidneys fail', correct:true,
   why:'Meperidine is converted to normeperidine. That product is half as strong an analgesic but about three times as strong a convulsant. Normeperidine leaves the body through the kidneys, so its half-life rises sharply in renal failure. The severity of the central nervous system effects tracks its blood concentration, so a patient with no kidney function accumulates a convulsant while getting less pain relief.'},
  {t:'Meperidine itself accumulates because the kidney cannot excrete it', correct:false,
   why:'The seizures are caused by normeperidine rather than by meperidine itself. Meperidine does accumulate in renal failure as well, but it is not a strong convulsant. The convulsant activity belongs to the product formed by metabolism.'},
  {t:'Dialysis increases CYP3A4 and produces excess analgesic effect', correct:false,
   why:'Dialysis removes substances from blood and does not increase enzyme production. The problem described is seizures rather than too much pain relief.'},
  {t:'Normeperidine is a stronger analgesic and caused an opioid overdose', correct:false,
   why:'Normeperidine is half as strong an analgesic as meperidine. The seizures come from a separate action of the molecule, not from an exaggerated opioid effect.'}],
 teach:'This case shows why metabolism and elimination have to be considered together. Producing a metabolite is only safe if the body can then remove it. Normeperidine depends on the kidney, so kidney failure turns an ordinary metabolic route into a dangerous one. MCMet-9_4_26-9_9_26.pdf slide 28 lists production of an active metabolite with different properties among the general consequences of metabolism.',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 57 (Case #1)',
 quote:'Normeperidine, via 3A4/2B6, is half as potent as Meperidine as an analgesic but approx. 3 times more potent as a convulsant'},

{id:'cyp-x3', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'cases', concept:'clozapine-induction-inhibition',
 tags:['case','reasoning','induction'], source:'slide',
 stem:'A patient on clozapine starts rifampicin and isoniazid; his psychosis worsens and serum clozapine falls. Rifampicin is later replaced with ciprofloxacin and clozapine rises 60% above his previous stable level. What is happening?',
 options:[
  {t:'Rifampicin and isoniazid increased CYP1A2 and 3A4 so clozapine cleared faster; ciprofloxacin then blocked CYP1A2, so clozapine built up', correct:true,
   why:'Clozapine is handled by CYP1A2 and CYP3A4. Rifampicin and isoniazid increase how much of those enzymes the liver makes, so clozapine was cleared faster and blood levels fell, which allowed symptoms to return. The dose was raised to compensate. Ciprofloxacin then blocked CYP1A2, and because the dose was still elevated, levels rose 60 percent above the original stable value.'},
  {t:'Rifampicin blocked clozapine metabolism and ciprofloxacin increased it', correct:false,
   why:'The reported levels rule this out. Clozapine fell while rifampicin was given, which means faster clearance. It rose after ciprofloxacin was started, which means slower clearance.'},
  {t:'Clozapine is a prodrug and rifampicin blocked its activation', correct:false,
   why:'Clozapine is active as given. Its metabolism produces a reactive product linked to a fall in white blood cell count, in MCMet-9_17_2026.pdf slide 54, so metabolism harms rather than activates it.'},
  {t:'The psychotic exacerbation was unrelated to drug levels', correct:false,
   why:'The case ties the worsening symptoms to a fall in serum clozapine occurring at the same time, and the symptoms improved once the dose was raised.'}],
 teach:'The danger in this case is at the switchover. A dose that was raised to overcome an inducer becomes too high the moment that inducer is replaced by an inhibitor. Whenever an interacting drug is swapped rather than simply stopped, the dose that was correct under the old combination is likely to be wrong under the new one.',
 teachImg:'cyp_inducer_table',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 58 (Case #2)',
 quote:'After replacing the Rifampicin with Ciprofloxacin (an inhibitor of CYP1A2) the patient\'s serum clozapine level rose to 60% higher than his previously stable level, despite lowering the Clozapine dose'},

{id:'cyp-x4', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'cases', concept:'clopidogrel-2c19',
 tags:['case','reasoning','polymorphism'], source:'slide',
 stem:'Clopidogrel carries an FDA black box warning about reduced efficacy in some patients. Which enzyme and which mechanism?',
 options:[
  {t:'CYP2C19 — clopidogrel must be converted into an active form, so patients with a reduced-function 2C19 gene form less of it and get less platelet inhibition', correct:true,
   why:'Clopidogrel does nothing until CYP2C19 converts it into its active form. Patients carrying a reduced-function version of that gene produce lower levels of the active product, show less platelet inhibition, and have more cardiovascular events including clotting inside a stent. About 3 percent of the population are poor metabolizers, and the proportion is higher among Asian patients.'},
  {t:'CYP2D6 — clopidogrel accumulates in poor metabolizers and causes bleeding', correct:false,
   why:'Both parts are wrong. The enzyme is CYP2C19, and because clopidogrel must be converted before it works, a poor metabolizer is at risk of clotting rather than bleeding.'},
  {t:'CYP3A4 — grapefruit juice inhibits activation', correct:false,
   why:'The case describes an inherited difference in CYP2C19 rather than a dietary interaction. Grapefruit juice acts on CYP3A4 substrates such as calcium channel blockers and statins, on slide 35.'},
  {t:'CYP2E1 — ethanol induction destroys the active metabolite', correct:false,
   why:'CYP2E1 handles ethanol, halogenated hydrocarbons and acetaminophen during overdose. It has no role in converting clopidogrel.'}],
 teach:'Clopidogrel shows what happens when a drug that must be converted meets a patient who cannot convert it. The patient takes the medication exactly as directed and still has a cardiovascular event, because the active form was never produced. This is also where inherited differences between populations appear, which is why slide 39 covers metabolic differences across ethnicities.',
 teachImg:'cyp_ethnic_frequencies',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slide 59 (Case #3); slide 39',
 quote:'Clopidogrel requires transformation into an active metabolite by 2C19 to exert its antiplatelet effect'},

{id:'cyp-x5', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'cases', concept:'pm-profile-recognition',
 tags:['reasoning','polymorphism','exam-pattern'], source:'slide',
 stem:'A profile shows unusually high plasma concentration of an active parent drug at a standard dose, with exaggerated effect. Which phenotype does this suggest?',
 options:[
  {t:'Poor metabolizer', correct:true,
   why:'A high concentration of the parent drug at a normal dose means the drug is being removed more slowly than expected. Since this drug works as given, more of it in blood produces more effect than intended.'},
  {t:'Ultrarapid metabolizer', correct:false,
   why:'An ultrarapid metabolizer removes the parent drug faster, so its concentration would be lower than expected and the drug would appear to be underperforming.'},
  {t:'Extensive metabolizer', correct:false,
   why:'Extensive metabolizer is the normal phenotype, so concentrations at a standard dose would fall in the expected range.'},
  {t:'It cannot be determined without knowing renal function', correct:false,
   why:'Renal function affects removal of polar products of metabolism. The profile described points to slower metabolism of the parent drug itself.'}],
 teach:'Read these profiles in two steps. First ask what the concentration says about clearance: a high parent concentration means slow clearance, a low one means fast. Then ask which form of the drug is active. If the parent is active, slow clearance means too much effect. If the drug must be converted first, slow clearance of the parent means too little effect, because the active form was never produced.',
 teachImg:'cyp_pm_um_populations',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 40–42, 46',
 quote:'TRUE/FALSE. The pharmacotherapeutic profile below is that of PM CYP phenotype.'},

{id:'cyp-x6', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'cases', concept:'active-vs-prodrug-direction-rule',
 tags:['reasoning','exam-pattern'], source:'both',
 stem:'You are told an enzyme is inhibited. What do you need to establish first to predict whether the patient gets more effect or less?',
 options:[
  {t:'Whether the drug works as given or must be converted into an active form first', correct:true,
   why:'This one question settles the direction every time. If the drug works as given, blocking its metabolism leaves more of it and the effect increases, as with warfarin and glyburide. If the drug must be converted first, blocking that conversion means less active form and the effect decreases, as with tramadol and clopidogrel. An inducer reverses both outcomes.'},
  {t:'Whether the drug is acidic or basic', correct:false,
   why:'Acid or base character decides whether a drug carries a charge at a given pH, which affects absorption and whether it is reabsorbed from the renal tubule, in MCMet-9_17_2026.pdf slide 14. It has nothing to do with the direction of an enzyme interaction.'},
  {t:'Whether the enzyme is microsomal or cytosolic', correct:false,
   why:'Location identifies which enzyme family you are dealing with but not what happens to the patient. Blocking a microsomal enzyme and blocking a cytosolic one both reduce that enzyme\'s output.'},
  {t:'Whether the drug is given orally or intravenously', correct:false,
   why:'Route affects how much drug is lost to first-pass metabolism, so it changes the size of an interaction. It does not change the direction, which depends on which form of the drug is active.'}],
 svg:DIA.directionGrid,
 teach:'Four cases across these decks reduce to one question. Warfarin with omeprazole and glyburide with erythromycin are both blockade of an enzyme clearing an already-active drug, so the effect increases. Tramadol and clopidogrel in poor metabolizers are both failure to produce an active form, so the effect decreases. An unfamiliar drug on the exam is still answerable as long as the question tells you which form is active.',
 teachImg:'cyp_prodrug_grid',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slides 50–53; Lecture #13 (MCMet-9_15_2026.pdf) slides 47, 57–59'}
];
