QUESTIONS.push(
/* ======================= FGs & DM ======================= */
{id:'fg-1', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'hc', concept:'alkane-stability',
 tags:['reasoning'], source:'slide',
 stem:'Why are simple alkanes and alkenes largely excreted unchanged?',
 options:[
  {t:'They are metabolically stable in vivo, offering no reactive handle for Phase 1 enzymes', correct:true,
   why:'Both groups are carbon and hydrogen only. With no heteroatom and no activated carbon, there is no site an oxygenase prefers, so the molecule passes through unchanged. Where exceptions occur they run through CYP oxidation, and for alkenes through CYP oxidation followed by epoxide hydrolase.'},
  {t:'They are too polar to be retained and are filtered immediately', correct:false,
   why:'Hydrocarbons are the least polar groups in this lecture. Polarity is what metabolism sets out to create, so a molecule that is already polar needs less metabolism, not more.'},
  {t:'They are conjugated directly by UDP-glucuronosyltransferase without Phase 1', correct:false,
   why:'UDP-glucuronosyltransferase needs a nucleophilic handle, and slide 29 gives its targets as -OH, -CO2H, -NH2 and -SH. A bare alkane offers none of them, which is why Phase 1 usually has to create one first.'},
  {t:'They are destroyed by gastric acid before absorption', correct:false,
   why:'Chemical stability in the stomach is a separate issue from enzymatic stability in the body, and hydrocarbons are stable in both. What is being described here is resistance to enzymes, not to acid.'}],
 teachImg:'fgm_alkene',
 teach:'Metabolism needs somewhere to act, and a functional group is that somewhere. Alkanes and alkenes carry none, so they are mostly stable in vivo and leave unchanged, which sounds convenient and is not: a molecule that cannot be made polar is also hard to eliminate. The halogenated hydrocarbons on slide 21 are the extreme version of the same problem, being very lipophilic, not readily converted to hydrophilic metabolites, and toxic partly because their half-lives are long. Reading each functional group as an opportunity for an enzyme, rather than as a name to recall, is what makes the rest of this lecture predictable.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 5–6',
 quote:'Alkanes: Are mostly metabolically stable in vivo and excreted unchanged'},

{id:'fg-2', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'hc', concept:'halogenated-hc-lipophilicity',
 tags:['reasoning','toxicity'], source:'slide',
 stem:'Halogenated hydrocarbons are very lipophilic and are not readily converted to hydrophilic metabolites. What is the consequence?',
 options:[
  {t:'They persist and accumulate, and their electrophilic carbons create toxicity risk', correct:true,
   why:'Poor conversion to water-soluble products means a long half-life, and a longer half-life means more time for the reactive chemistry to matter. The carbon bearing the halogen is electron poor, which puts it among the existing electrophilic toxicophores in MCMet-9_17_2026.pdf slide 31.'},
  {t:'They are rapidly cleared unchanged by glomerular filtration', correct:false,
   why:'Filtration passes small unbound molecules, but a highly lipophilic one that reaches the tubule diffuses straight back into circulation. That is the tubular reabsorption problem, MCMet-9_17_2026.pdf slide 12, and it is why lipophilic material leaves through bile instead.'},
  {t:'They are safe because halogen blocks all enzyme access', correct:false,
   why:'Halogenated compounds are substrates rather than being shielded. CYP2E1 is named as key in the carcinogenicity and toxicity of halogenated hydrocarbons, MCMet-9_15_2026.pdf slide 28, so an enzyme reaching them is part of the hazard.'},
  {t:'They are conjugated directly by sulfotransferases', correct:false,
   why:'Sulfotransferase acts on -OH, slide 29, which a halogenated carbon does not carry. The Phase 2 enzyme that does handle this group is glutathione S-transferase, listed on slide 30 for R-X and epoxides.'}],
 teachImg:'fgm_hhc',
 teach:'Two properties of this group compound each other. Lipophilicity keeps the molecule in the body, because the renal route returns lipid-soluble material to circulation rather than excreting it, and the halogen leaves the attached carbon electron poor, so what stays is also reactive. Long residence plus reactivity is what produces the hepatotoxicity noted for some of these compounds. The defense is glutathione S-transferase, which attaches glutathione at that electron-poor carbon, so the group appears in the Phase 2 table as R-X. It is the clearest case in this lecture where a physicochemical property and a toxicophore sit on the same atom.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 21',
 quote:'Very lipophilic and not readily metabolized to hydrophilic metabolites · Their long t1/2 increases the potential for toxicity (hepatotoxicity) by some HHCs'},

{id:'fg-3', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'namide', concept:'amide-vs-ester-stability',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'Both esters and amides are hydrolyzed by carboxylesterases. Which is more stable in vivo, and why does it matter?',
 options:[
  {t:'Amides are more stable, so an amide analogue of an ester drug generally lasts longer', correct:true,
   why:'Nitrogen donates its lone pair into the carbonyl more effectively than oxygen does, so the amide carbonyl carbon is less electron poor and less open to attack by water. The same carboxylesterases act on both, just more slowly on the amide, which makes the ester-to-amide swap a standard way to extend duration.'},
  {t:'Esters are more stable, because the C-O bond is stronger than C-N', correct:false,
   why:'Bond strength is not what decides the rate here; susceptibility of the carbonyl carbon to nucleophilic attack is, and that runs the other way. Esters are the more readily hydrolyzed of the two, which is why ester prodrugs are used when rapid release is wanted.'},
  {t:'They are equally stable, since the same enzyme acts on both', correct:false,
   why:'Sharing an enzyme sets no common rate. Carboxylesterases also cleave carbamates and carbonates, and all four hydrolyze at different rates according to what sits on the carbonyl carbon.'},
  {t:'Amides are more stable because they are not enzyme substrates at all', correct:false,
   why:'The conclusion is right for the wrong reason. Amides are substrates, and slide 9 gives specific amidase hydrolytic biotransformations for them; stability here is relative rather than absolute.'}],
 teachImg:'fgm_amide',
 teach:'Four groups in this lecture share one enzyme family and differ only in what sits on the carbonyl carbon, so sorting them by that settles both the rate and the products. An ester has one oxygen and one carbon and gives an acid plus an alcohol. An amide has one nitrogen and gives an acid plus an amine, more slowly, because nitrogen stabilises the carbonyl. A carbamate has one oxygen and one nitrogen and gives an alcohol plus an amine. A carbonate has two oxygens and gives two alcohols. Reading the substituents rather than the name is what makes an unfamiliar structure tractable.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 8–9',
 quote:'Amides: Undergo carboxylesterase (CE) hydrolysis, but are more stable in vivo than esters'},

{id:'fg-4', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'namide', concept:'amine-oxidative-deamination',
 tags:['recall','reasoning'], source:'slide',
 stem:'What biotransformation do 1° amines undergo?',
 options:[
  {t:'Oxidative deamination', correct:true,
   why:'A primary amine has the nitrogen carrying two hydrogens and one carbon, so there is no alkyl group to remove and the nitrogen itself is lost instead, leaving a carbonyl. Secondary and tertiary amines carrying methyl or ethyl groups undergo N-dealkylation instead, because they do have a group to remove.'},
  {t:'N-dealkylation', correct:false,
   why:'N-dealkylation requires an alkyl group on the nitrogen, so it applies to secondary and tertiary amines. The chemistry is the same hydroxylation either way; what differs is whether the hydroxylated carbon leaves with the nitrogen or takes the alkyl group off it.'},
  {t:'Epoxide hydrolysis', correct:false,
   why:'That is what epoxide hydrolase does to epoxides, slide 20, opening a strained three-membered ring into a diol. Nothing about an amine nitrogen resembles that substrate.'},
  {t:'Sulfation', correct:false,
   why:'Sulfation is Phase 2 rather than the Phase 1 reaction asked for, and its target on slide 29 is -OH. Amines do undergo Phase 2 reactions, as slide 11 notes, but through N-acetylation and methylation.'}],
 svg:DIA.amineClasses,
 teachImg:'fgm_amine',
 teach:'Amine reactions divide by how many carbons the nitrogen already carries. A primary amine loses the nitrogen through oxidative deamination and leaves a carbonyl behind. A secondary or tertiary amine with a methyl or ethyl group loses that group by N-dealkylation, which is the same reaction that converts imipramine to desipramine on slide 21. Tramadol is the contrast case: its active metabolite comes from O-demethylation, a methyl leaving an oxygen rather than a nitrogen, on Lecture 13 slide 47. Counting substituents on the nitrogen predicts the product before any mechanism is drawn. Amines also have Phase 2 routes: slide 30 gives N-acetyltransferase acting on -NH2 with acetyl coenzyme A, and methyltransferase acting on -OH, -NH2 and -SH.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 10–11',
 quote:'1o amines undergo oxidative deaminations · 3o & 2o N with Methyl/Ethyl groups undergo N-dealkylations'},

{id:'fg-5', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'ester', concept:'carbamate-hydrolysis-products',
 tags:['reasoning','mechanism'], source:'slide',
 stem:'Carbamates undergo carboxylesterase hydrolysis. What does the reaction release?',
 options:[
  {t:'An amine plus an alcohol, with carbon dioxide from the unstable carbamic acid', correct:true,
   why:'A carbamate carries one oxygen and one nitrogen on the carbonyl carbon, so cleaving it releases both an alcohol and an amine. The remaining carbamic acid fragment is unstable and decomposes with loss of carbon dioxide, which is why the reaction goes to completion.'},
  {t:'Two molecules of alcohol only', correct:false,
   why:'That is the carbonate outcome, slide 14, where the carbonyl carbon carries two oxygens and there is no nitrogen to release an amine.'},
  {t:'A carboxylic acid plus an alcohol', correct:false,
   why:'That is ester hydrolysis, slide 16. An ester has one oxygen and one carbon substituent, so the carbon side stays attached and leaves as the acid.'},
  {t:'A carboxylic acid plus an amine', correct:false,
   why:'That is amide hydrolysis, slide 8. An amide has a nitrogen but no second oxygen, so the carbon side again leaves as the acid.'}],
 svg:DIA.acylFamily,
 teachImg:'fgm_carbamate',
 teach:'All four of these groups are cleaved by carboxylesterases, and the products follow mechanically from the two atoms attached to the carbonyl carbon. Water attacks that carbon, and each attached heteroatom leaves as its own fragment: an oxygen leaves as an alcohol, a nitrogen as an amine, and a carbon substituent stays behind so the fragment departs as a carboxylic acid. A carbamate has one of each heteroatom, so it gives one alcohol and one amine. The leftover one-carbon piece is carbamic acid, which cannot be isolated and breaks down to carbon dioxide.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 15',
 quote:'Carbamates: Undergo CE hydrolysis to give amines and',
 note:'Sorting these four by what sits on the carbonyl carbon settles the products every time: ester = one O, amide = one N, carbamate = O and N, carbonate = two O.'},

{id:'fg-6', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'ester', concept:'carbonate-hydrolysis-products',
 tags:['reasoning','mechanism'], source:'slide',
 stem:'Carbonates undergo carboxylesterase hydrolysis. What are the products?',
 options:[
  {t:'Two alcohols, with loss of carbon dioxide', correct:true,
   why:'A carbonate has two oxygens on the carbonyl carbon, so both sides leave as alcohols and nothing carbon-based stays attached. The remaining fragment is carbonic acid, which decomposes to carbon dioxide and water.'},
  {t:'An amine plus an alcohol', correct:false,
   why:'That needs a nitrogen on the carbonyl carbon, which makes the group a carbamate, slide 15, rather than a carbonate. The two are easy to confuse on a drawing because both carry two heteroatoms.'},
  {t:'A carboxylic acid plus an amine', correct:false,
   why:'That is amide hydrolysis, slide 8, where the carbonyl carbon carries one nitrogen and one carbon rather than two oxygens. The slip is counting how many heteroatoms sit on the carbonyl carbon without checking which ones they are. Both products follow directly from what is attached: a nitrogen leaves as an amine, an oxygen leaves as an alcohol, and a carbon substituent stays behind in the acid.'},
  {t:'An epoxide plus water', correct:false,
   why:'Epoxides are substrates for epoxide hydrolase, slide 20, and are consumed by hydrolysis rather than produced by it. Nothing in carboxylesterase chemistry creates a three-membered ring.'}],
 svg:DIA.acylFamily,
 teachImg:'fgm_carbonate',
 teach:'The carbonate is the endpoint of the series: replace every carbon substituent on the carbonyl with a heteroatom and both fragments leave, so the central carbon departs entirely as carbon dioxide. That property is what makes carbonates and carbamates useful as prodrug linkers, since hydrolysis releases the active alcohol or amine and leaves nothing else behind to account for. Compare the ester, which retains a carbon substituent and therefore leaves an acid fragment in the body, and the amide, which does the same more slowly.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 14',
 quote:'Carbonates: Carbonates undergo CE hydrolysis'},

{id:'fg-7', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'ether', concept:'thioether-oxidation',
 tags:['recall','mechanism'], source:'slide',
 stem:'What two biotransformations do thioethers undergo?',
 options:[
  {t:'Oxidation of the sulfur and S-dealkylation', correct:true,
   why:'Sulfur carries lone pairs and is readily oxidized, giving first the sulfoxide and then the sulfone. The alternative is S-dealkylation, which removes the alkyl group from the sulfur and parallels the O-dealkylation of ethers on slide 17.'},
  {t:'Glucuronidation and sulfation only', correct:false,
   why:'Both are Phase 2 and both need a free group to attach to: UDP-glucuronosyltransferase takes -OH, -CO2H, -NH2 or -SH, and sulfotransferase takes -OH. A thioether sulfur is substituted on both sides, so it offers neither until a Phase 1 step opens it up.'},
  {t:'Epoxidation and hydrolysis', correct:false,
   why:'Epoxidation acts on carbon-carbon double bonds, the alkene route on slide 6, and hydrolysis needs a cleavable linkage such as an ester or amide. A thioether has neither.'},
  {t:'Reduction to a thiol by aldo-keto reductases', correct:false,
   why:'Aldo-keto reductases reduce aldehydes and ketones to alcohols, slide 12. They act on carbonyl carbons, not on sulfur, and reduction is not among the thioether routes.'}],
 teachImg:'fgm_thioether_ox',
 teach:'Sulfur behaves like oxygen with an extra option. An ether undergoes O-dealkylation and little else, because oxygen resists further oxidation. A thioether can be dealkylated the same way, but its sulfur is also large and electron-rich enough to be oxidized directly, giving the sulfoxide and then the sulfone. That extra route matters clinically, since oxidation changes polarity and activity without breaking the molecule apart, and flavin-containing monooxygenase as well as CYP can perform it. It also explains why sulfur-containing drugs often have several circulating metabolites rather than one.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 18–19; Lecture #11 (MCMet-9_10_26.pdf) slide 26 (FMO oxidises sulfur to sulfoxides and sulfones)',
 quote:'Thioethers: Undergo oxidative biotransformations · Thioethers: S-Dealkylations'},

{id:'fg-8', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'ether', concept:'epoxide-dual-fate',
 tags:['reasoning','toxicity'], source:'slide',
 stem:'Epoxides have two fates in the material. What are they?',
 options:[
  {t:'Hydrolysis to diols by epoxide hydrolases, or electrophilic attack on cellular nucleophiles', correct:true,
   why:'Epoxide hydrolase adds water and opens the strained ring to a diol, which ends the reactivity. Slide 20 adds a second protective route, conjugation by Phase 2 glutathione S-transferases. When both are outrun, the strained electron-poor carbons react instead with nucleophilic sites on protein or DNA.'},
  {t:'Direct renal excretion or exhalation', correct:false,
   why:'Both describe stable molecules being removed intact. An epoxide is a reactive intermediate with a short life, so it is consumed chemically long before any elimination route could carry it anywhere.'},
  {t:'Reduction to alkanes or oxidation to ketones', correct:false,
   why:'Neither reaction appears for this group. The epoxide is itself the product of an oxidation, from the alkene route on slide 6, and what follows is either hydrolysis or conjugation rather than a further change in oxidation state.'},
  {t:'N-acetylation or methylation', correct:false,
   why:'These are Phase 2 routes for nucleophilic groups: N-acetyltransferase acts on -NH2 and methyltransferase on -OH, -NH2 and -SH, slide 30. An epoxide is electrophilic, the opposite character, which is why glutathione S-transferase rather than these enzymes handles it.'}],
 teachImg:'fgm_epoxide',
 teach:'The epoxide is the clearest example in this lecture of metabolism creating a hazard rather than removing one. A CYP oxidizes an alkene or an aromatic ring to an epoxide, and from there two protective enzymes compete with the cell for it: epoxide hydrolase opens the ring with water, and glutathione S-transferase attaches glutathione across it. Both have finite capacity, so the outcome depends on how much epoxide is made against how much can be removed. That is the same saturable-defense pattern as carbamazepine in MCMet-9_17_2026.pdf slide 33, and it explains why toxicity from this group appears above a dose threshold rather than at every exposure.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 20',
 quote:'Epoxides are hydrolyzed by EHs (epoxide hydrolases) · Epoxides are also conjugated by phase 2 GSTs'},

{id:'fg-9', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'hetero', concept:'xanthine-oxidase-allopurinol',
 tags:['recall','enzyme'], source:'slide',
 stem:'Which enzyme oxidizes purines to uric acid, and what inhibits it?',
 options:[
  {t:'Xanthine oxidase, inhibited by allopurinol', correct:true,
   why:'Xanthine oxidase carries purine oxidation through to uric acid, and allopurinol blocks it. Because uric acid is what crystallises in gout, lowering its production is the therapeutic aim, which is what makes allopurinol an anti-gout drug.'},
  {t:'Dihydropyrimidine dehydrogenase, inhibited by allopurinol', correct:false,
   why:'The inhibitor is paired with the wrong enzyme. Dihydropyrimidine dehydrogenase deactivates pyrimidines rather than purines, slide 25, and the two heterocycle families are handled separately.'},
  {t:'NQO1, inhibited by dicoumarol', correct:false,
   why:'NADPH quinone oxidoreductase-1 metabolizes quinones, slide 26, and is noted as overexpressed in many cancers as well as inducible and polymorphic. It has no role in purine oxidation.'},
  {t:'Monoamine oxidase, inhibited by tyramine', correct:false,
   why:'Monoamine oxidase acts on amines, and tyramine is its substrate rather than its inhibitor. The interaction on slide 61 runs the other way: an MAO inhibitor lets dietary tyramine survive, which precipitates a hypertensive crisis.'}],
 teachImg:'fgm_purine',
 teach:'Purines and pyrimidines each have a dedicated enzyme, and both matter clinically for opposite reasons. Xanthine oxidase oxidizes purines to uric acid, so inhibiting it with allopurinol lowers urate and treats gout. Dihydropyrimidine dehydrogenase deactivates pyrimidines, so losing it is the danger: it is polymorphic, some patients are deficient, and more than 80 percent of 5-fluorouracil is normally inactivated by it. A deficient patient given a standard dose of that cytotoxic drug clears almost none of it. Same class of enzyme, opposite clinical problem: one is inhibited on purpose, the other must not be missing.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 24',
 quote:'XO (Xanthine Oxidase) oxidize purine to uric Acid · Inhibited by Allopurinol (anti-gout)'},

{id:'fg-10', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'hetero', concept:'dpd-pyrimidine',
 tags:['recall','enzyme'], source:'slide',
 stem:'Which enzyme deactivates pyrimidines?',
 options:[
  {t:'Dihydropyrimidine dehydrogenase (DPD)', correct:true,
   why:'Dihydropyrimidine dehydrogenase is the pyrimidine counterpart to xanthine oxidase, and it inactivates rather than activates. It is polymorphic, so some patients are deficient, and more than 80 percent of 5-fluorouracil is normally inactivated by it.'},
  {t:'Xanthine oxidase', correct:false,
   why:'Xanthine oxidase handles the other heterocycle family, oxidizing purines to uric acid, slide 24. Purines and pyrimidines are kept separate here because each has its own enzyme and its own clinical consequence.'},
  {t:'Epoxide hydrolase', correct:false,
   why:'Epoxide hydrolase opens strained three-membered rings to diols, slide 20. A pyrimidine is an aromatic six-membered ring with two nitrogens and offers no such strain.'},
  {t:'Alcohol dehydrogenase', correct:false,
   why:'Alcohol dehydrogenase oxidizes alcohols to aldehydes, part of the carbonyl chemistry on slide 12. It acts on a hydroxyl carbon rather than on a heterocyclic ring.'}],
 teachImg:'fgm_pyrimidine',
 teach:'The clinical weight here sits in the polymorphism. Dihydropyrimidine dehydrogenase is the route by which 5-fluorouracil, a cytotoxic uracil pyrimidine, is inactivated, and more than 80 percent of a dose normally leaves that way. A deficient patient therefore retains most of a cytotoxic drug that was dosed on the assumption it would be cleared, and severe toxicity follows from a standard prescription. This is the same structure of problem as the polymorphic CYPs on slide 49, where phenotype rather than dose decides exposure, and it is why enzyme deficiency matters most for drugs with narrow margins.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 25',
 quote:'DPD is polymorphic (some patients may be deficient) · > 80% of 5-FU, a cytotoxic uracil pyrimidine, is inactivated by DPD'},

{id:'fg-11', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'ugt-substrates',
 tags:['cofactor','recall'], source:'slide',
 stem:'Which set of functional groups does UDP-glucuronosyltransferase act on?',
 options:[
  {t:'-OH, -CO₂H, -NH₂ and -SH', correct:true,
   why:'All four are nucleophilic, which is what glucuronidation requires: the group attacks the activated sugar of the cofactor. That breadth is why glucuronidation is the most widely applicable Phase 2 route, and it is the only entry in the table covering four target groups.'},
  {t:'Only -OH groups', correct:false,
   why:'That is the sulfotransferase entry on slide 29, whose single listed target is -OH. Narrowing glucuronidation to hydroxyls removes the acids, amines and thiols it also handles.'},
  {t:'Halogen-bearing carbons and epoxides', correct:false,
   why:'Those are the glutathione S-transferase targets on slide 30, written as R-X and epoxide. They are electrophilic rather than nucleophilic, which is the opposite requirement.'},
  {t:'Only -CO₂H groups', correct:false,
   why:'Carboxylic acids alone are the acyl synthetase entry, which conjugates them with an amino acid. Glucuronidation takes carboxylic acids as well, but not only those.'}],
 teachImg:'tbl_ph2_a',
 teach:'The Phase 2 table is easiest to hold as a question of electronic character. Five of the six enzymes act on nucleophiles, so they need an -OH, -NH2, -SH or -CO2H to attack the cofactor: glucuronidation across all four, sulfation on -OH, amino acid conjugation on -CO2H, acetylation on -NH2, and methylation on -OH, -NH2 and -SH. Only glutathione S-transferase works the other way, supplying a nucleophile to attack an electrophilic substrate, which is why its targets are written as R-X and epoxide. Deciding whether the group is electron-rich or electron-poor narrows six enzymes to a short list before any cofactor is considered.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 29',
 quote:'-OH; -CO2H; NH2; -SH | UDP-Glucuronosyl transferases (UGTs) | Uridine-5\'-diphospho-D-glucuronic Acid (UDPGA) | Glucuronide'},

{id:'fg-12', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'papso4-cofactor',
 tags:['cofactor','recall'], source:'slide',
 stem:'What is the cofactor for sulfotransferases?',
 options:[
  {t:'3\'-Phosphoadenosine-5\'-phosphosulfate (PAPS)', correct:true,
   why:'PAPS carries the sulfate in an activated form, ready to be transferred to an -OH. Its supply is limited, which is why sulfation saturates before glucuronidation does and why acetaminophen shifts toward the reactive route in overdose.'},
  {t:'Uridine-5\'-diphospho-D-glucuronic acid (UDPGA)', correct:false,
   why:'UDPGA is the glucuronidation cofactor, the first row of the table on slide 29, and it donates glucuronic acid rather than sulfate. The two routes compete for the same hydroxyl groups, which is why they are listed adjacently.'},
  {t:'S-adenosylmethionine (SAM)', correct:false,
   why:'S-adenosylmethionine is the methyl donor for methyltransferases, slide 30, acting on -OH, -NH2 and -SH. It transfers a single carbon rather than a sulfate group.'},
  {t:'Acetyl-CoA', correct:false,
   why:'Acetyl coenzyme A appears twice in the table, as the acetyl donor for N-acetyltransferase and, with an amino acid, for acyl synthetase. Neither reaction transfers sulfate.'}],
 teachImg:'tbl_ph2_a',
 teach:'Each Phase 2 enzyme has one cofactor and the cofactor names what is transferred, so the pairs follow from the product rather than needing to be held separately. UDP-glucuronic acid donates glucuronic acid, PAPS donates sulfate, S-adenosylmethionine donates a methyl group, acetyl coenzyme A donates an acetyl group, and glutathione is donated whole. Amino acid conjugation is the exception with two components, acetyl coenzyme A plus the amino acid itself, because the acid has to be activated before the amino acid can be attached. Sulfation and glucuronidation both take -OH, which sets up the competition behind the acetaminophen threshold.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 29',
 quote:'-OH | Sulfotransferases (STs/SULTs) | 3\'-Phosphoadenosine-5\'-phosphosulfate (PAPS) | Sulfate'},

{id:'fg-13', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'gst-target',
 tags:['cofactor','reasoning'], source:'slide',
 stem:'Which enzyme family is essential for deactivating electrophilic xenobiotics?',
 options:[
  {t:'Glutathione S-transferases', correct:true,
   why:'Glutathione carries a free thiol, a strong nucleophile, and glutathione S-transferase presents it to the electron-poor centre before a protein or DNA nucleophile reaches it. Its listed targets, R-X and epoxide, are exactly the two electrophilic patterns in this lecture.'},
  {t:'UDP-glucuronosyltransferases', correct:false,
   why:'Glucuronidation requires the substrate to be the nucleophile, attacking the activated sugar. An electrophilic carbon has no lone pair to offer, so it cannot start that reaction.'},
  {t:'Sulfotransferases', correct:false,
   why:'Sulfation also needs a nucleophilic substrate, and its target is -OH. It can even work against safety: sulfation of a hydroxylamine is the step that completes carcinogen activation in MCMet-9_17_2026.pdf slide 44.'},
  {t:'N-acetyltransferases', correct:false,
   why:'N-acetyltransferase acts on -NH2, another electron-rich group. Acetylation lowers the nucleophilic character of an amine but does nothing for an electrophilic carbon.'}],
 teachImg:'tbl_ph2_b',
 teach:'Glutathione S-transferase is the one Phase 2 enzyme whose direction is reversed, and that is what makes it the defense against reactive metabolites. The other five wait for the substrate to attack a cofactor, so they need an electron-rich group. This one brings the nucleophile and pushes it at an electron-poor substrate, which is why it handles halogenated carbons and epoxides and why it appears again in MCMet-9_17_2026.pdf slide 60 as electrophile deactivation alongside epoxide hydrolase. Its capacity is finite, so glutathione depletion from alcohol use or overdose is what converts a safe dose into a toxic one.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 30',
 quote:'R-X; Epoxide | Glutathione S-transferases | Glutathione (GSH) | Glutathione-S'},

{id:'fg-14', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'aa-conjugation-cofactors',
 tags:['cofactor','recall'], source:'slide',
 stem:'List the three co-factors required for amino acid conjugation.',
 options:[
  {t:'Acetyl-CoA, glycine and glutamine', correct:true,
   why:'Amino acid conjugation is the only entry in the table needing more than one component, because the carboxylic acid has to be activated by acetyl coenzyme A before an amino acid can be attached. Glycine and glutamine are the amino acids named.'},
  {t:'UDPGA, PAPS and SAM', correct:false,
   why:'These are the cofactors of three separate enzymes, glucuronidation, sulfation and methylation, collected into one answer. No single reaction uses more than one of them.'},
  {t:'Glutathione, cysteine and glycine', correct:false,
   why:'Glycine appears in both, which makes this the closest wrong answer. Glutathione is a tripeptide containing cysteine and glycine, so this lists the components of the glutathione S-transferase cofactor rather than the amino acid conjugation requirements.'},
  {t:'NADPH, molecular oxygen and CYP reductase', correct:false,
   why:'Those are three of the four requirements of the CYP catalytic cycle, a Phase 1 oxidation, from MCMet-9_15_2026.pdf slide 12. None of them takes part in a conjugation.'}],
 teachImg:'tbl_ph2_a',
 teach:'A carboxylic acid is a poor electrophile as it stands, so it cannot simply accept an amino acid. Acetyl coenzyme A activates it first, and only then is glycine or glutamine attached, which is why the table lists two requirements for this one row while every other enzyme lists one. Acetyl coenzyme A therefore appears twice in the Phase 2 table with different roles: as the acetyl donor for N-acetyltransferase acting on -NH2, and as an activator here. Noticing that a carboxylic acid also has a glucuronidation route explains why slide 13 describes carboxylic acids as undergoing a variety of biotransformations.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 29; Lecture #11 (MCMet-9_10_26.pdf) slide 55 (acetyl CoA activates the -COOH; three co-factors)',
 quote:'- CO2H | Acylsynthatases | Acetyl Co-A & an Amino Acid (e.g., Glycine, Glutamine) | Amino Acid (Glycine/Glutamine)'},

{id:'fg-15', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'nat-targets-polymorphism',
 tags:['cofactor','polymorphism'], source:'slide',
 stem:'N-acetyltransferases act on which functional groups, and what genetic variation is noted?',
 options:[
  {t:'Primary alkyl and aryl amines and sulfonamides; NAT2 gives slow and fast acetylators', correct:true,
   why:'The Phase 2 table gives -NH2 as the target with acetyl coenzyme A as cofactor. The polymorphism splits patients into slow and fast acetylators, so the same dose produces different exposure, which matters for isoniazid and for sulfonamides.'},
  {t:'Alcohols and carboxylic acids; no known polymorphism', correct:false,
   why:'Both halves are wrong. Alcohols belong to sulfotransferase and methyltransferase, carboxylic acids to acyl synthetase and glucuronidation, and acetylator status is one of the better known polymorphisms in this course.'},
  {t:'Epoxides only; polymorphism in EPHX1', correct:false,
   why:'Epoxides are the substrate for epoxide hydrolase and glutathione S-transferase, slides 20 and 30. An epoxide has no amine for acetylation to act on.'},
  {t:'Thiols only; NAT1 gives rapid and slow oxidizers', correct:false,
   why:'Thiols are handled by glucuronidation and methylation, which take -SH among their targets. Acetylation is also not an oxidation, so describing the phenotypes as oxidizer status names the wrong reaction.'}],
 teachImg:'tbl_ph2_b',
 teach:'Acetylation is the Phase 2 route that does not increase polarity much, which makes it unusual: its purpose is to mask the amine rather than to make the molecule water soluble, and an acetylated sulfonamide can be less soluble than the parent. The polymorphism is what gives it clinical weight, since slow acetylators clear isoniazid and sulfonamides more slowly and accumulate them at ordinary doses. That places it alongside the polymorphic CYPs on slide 49 and dihydropyrimidine dehydrogenase on slide 25, and it is the standard counterexample to the idea that only Phase 1 enzymes vary genetically.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 30; Lecture #11 (MCMet-9_10_26.pdf) slide 53 (NAT2 slow and fast acetylators)',
 quote:'-NH2 | N-Acetyltransferases | Acetyl Co-enzyme A | N-Acetylated'},

{id:'fg-16', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'methylation-sam',
 tags:['cofactor','recall'], source:'slide', img:'rx_dimercaprol',
 stem:'Dimercaprol is converted to its inactive metabolite as shown. What enzyme family and cofactor are involved?',
 options:[
  {t:'Methyltransferases, using S-adenosylmethionine', correct:true,
   why:'Dimercaprol carries thiol groups, and -SH is among the methyltransferase targets alongside -OH and -NH2. S-adenosylmethionine donates the methyl group, and capping the thiol removes the metal-binding ability the drug depends on.'},
  {t:'Glutathione S-transferases, using glutathione', correct:false,
   why:'Glutathione S-transferase attaches glutathione to an electrophilic centre such as R-X or an epoxide. Dimercaprol supplies thiols rather than needing one, so it is chemically on the same side as the cofactor here.'},
  {t:'Sulfotransferases, using PAPS', correct:false,
   why:'Sulfotransferase is listed for -OH only on slide 29, so a thiol falls outside its range. This is a pairing error rather than a chemistry one, because the shape of the reaction is right: 3\u2019-phosphoadenosine-5\u2019-phosphosulfate does transfer a group onto a heteroatom, exactly as S-adenosylmethionine does. Only the functional group the enzyme accepts is wrong, which is why the cofactor table is worth reading as enzyme, cofactor and accepted group together rather than as three separate lists.'},
  {t:'Flavin monooxygenase, using NADPH', correct:false,
   why:'Flavin-containing monooxygenase does act on sulfur, oxidizing it, and it is a Phase 1 enzyme. The reaction here attaches a methyl group rather than an oxygen, which makes it a Phase 2 conjugation.'}],
 teach:'Methylation shares all three of its targets with glucuronidation, since the table on slide 29 lists -OH, -NH2 and -SH under UGT as well, so the deciding question is usually which route dominates rather than which is possible. It is also the Phase 2 reaction least useful for elimination, since adding a methyl group raises lipophilicity slightly instead of lowering it; its role is to end activity rather than to speed removal. Dimercaprol shows that plainly: methylating the thiols inactivates a chelating agent whose whole action depends on free sulfur. S-adenosylmethionine is the methyl donor throughout, and the same enzyme family methylates thiopurines, where deficiency is clinically serious.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 30',
 quote:'-OH; -NH2; -SH | Methyltransferases | S- Adenosyl methionine (SAM) | Methylated'},

{id:'fg-17', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'match-enzyme-cofactor',
 tags:['cofactor','matching'], source:'slide',
 stem:'Which enzyme and cofactor pair is correctly matched?',
 options:[
  {t:'Sulfotransferase — PAPS (3\'-phosphoadenosine-5\'-phosphosulfate)', correct:true,
   why:'The sulfotransferase row of the Lecture 14 slide 29 table: substrate -OH, cofactor PAPS, product a sulfate. PAPS carries the sulfate as an activated mixed anhydride, and the phenol or alcohol oxygen attacks the sulfur. Labetalol sulfate on Lecture 11 slide 48 is the worked product.'},
  {t:'UDP-glucuronosyltransferase — S-adenosylmethionine', correct:false,
   why:'UDP-glucuronosyltransferase uses UDP-glucuronic acid, the sugar donor. S-adenosylmethionine is the methyl donor of the methyltransferases on slide 30. The cofactor is named for what it carries, and a glucuronide needs the sugar, not a methyl.'},
  {t:'Glutathione S-transferase — acetyl-CoA', correct:false,
   why:'Glutathione S-transferase transfers glutathione itself, whole, onto an electrophile. Acetyl coenzyme A is the acetyl donor for N-acetyltransferase and the activator in amino acid conjugation; it has no part in the glutathione row.'},
  {t:'Methyltransferase — UDP-glucuronic acid', correct:false,
   why:'Methyltransferases transfer one carbon from S-adenosylmethionine to an -OH, -NH2 or -SH. UDP-glucuronic acid belongs to the glucuronidation row, and it would attach a six-carbon sugar acid rather than a methyl.'}],
 teachImg:'tbl_ph2_a',
 teach:'Matching questions on this table are answered by the transferred group rather than by the enzyme name, since each cofactor is named for what it carries: UDP-glucuronic acid gives glucuronic acid, PAPS gives sulfate, S-adenosylmethionine gives a methyl, acetyl coenzyme A gives an acetyl, and glutathione is transferred whole. The one row that breaks the pattern is amino acid conjugation, which needs an activator as well as the group being attached. Checking that the substrate class also fits gives a second filter, since sulfation and acetylation each take a single functional group while glucuronidation and methylation take several.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 29–30',
 quote:'- CO2H | Acylsynthatases | Acetyl Co-A & an Amino Acid (e.g., Glycine, Glutamine)'},

{id:'fg-18', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'oh', concept:'phenol-phase2',
 tags:['reasoning'], source:'slide',
 stem:'A phenolic -OH is present on a drug. Which Phase 2 routes are available to it?',
 options:[
  {t:'Glucuronidation and sulfation', correct:true,
   why:'A phenolic hydroxyl is nucleophilic, and -OH appears as a target for both UDP-glucuronosyltransferase and sulfotransferase. The two compete for the same group, which is why exhausting one shifts traffic to the other and eventually to Phase 1.'},
  {t:'Glutathione conjugation only', correct:false,
   why:'Glutathione S-transferase acts on electrophilic substrates, R-X and epoxides. A phenol is electron rich, so it is the wrong character entirely for that enzyme.'},
  {t:'N-acetylation only', correct:false,
   why:'N-acetyltransferase acts on -NH2. A phenol offers a hydroxyl rather than an amine, and acetylation of a phenol is not among the listed routes.'},
  {t:'Amino acid conjugation only', correct:false,
   why:'Amino acid conjugation requires a carboxylic acid to activate, slide 29. A phenolic hydroxyl is not an acid in that sense and cannot enter this route.'}],
 teachImg:'fgm_phenol_ph2',
 teach:'Slide 22 gives primary, secondary and tertiary hydroxyls as able to undergo both Phase 1 and Phase 2 metabolism, and slide 23 singles out phenolic hydroxyls for Phase 2. The competition between glucuronidation and sulfation on the same group is what underlies the acetaminophen threshold in MCMet-9_17_2026.pdf slide 49: both routes handle its phenol at ordinary doses, both are saturable, and once they are exhausted the excess is oxidized to NAPQI instead. Methylation is a third possibility on -OH, which is why a phenolic drug commonly has several conjugates circulating at once.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 22–23',
 quote:'Hydroxy (OH): Phenolic OHs can undergo phase 2 metabolism'},

{id:'fa-1', prof:'Sikazwe', tier:'new', topic:'factors', sub:'pd', concept:'dose-overwhelms-capacity',
 tags:['reasoning','toxicity'], source:'slide',
 stem:'How does an overdose change the metabolic picture?',
 options:[
  {t:'It overwhelms the capacity of the metabolizing enzymes, so alternative routes and toxicity become significant', correct:true,
   why:'Enzymes are finite and saturate. Once the usual route is full, the excess is not simply left unmetabolized; it flows into whichever route still has capacity, and that alternative is often the one producing a reactive metabolite.'},
  {t:'It induces the metabolizing enzymes within minutes, so clearance rises to match', correct:false,
   why:'Induction is a real response but far too slow, working through increased transcription over days, slide 53. Nothing about a single large dose makes new enzyme appear inside the dosing interval.'},
  {t:'It has no metabolic effect because enzyme capacity is unlimited', correct:false,
   why:'Finite capacity is the entire point of this factor. If capacity were unlimited, acetaminophen would be as safe at 15 grams as at 3, which it is not.'},
  {t:'It shifts elimination entirely to the lungs', correct:false,
   why:'Pulmonary elimination requires a volatile or gaseous drug, MCMet-9_17_2026.pdf slide 22, and no overdose confers volatility. Routes do shift under load, but within the limits each route sets.'}],
 svg:DIA.apapNapqi,
 teachImg:'fa_dose',
 teach:'Dose is listed first among the intrinsic factors because it is the one the prescriber controls, and its effect is not linear. Below saturation, raising the dose raises the amount metabolized proportionally and nothing changes qualitatively. Above it, the usual route is full and the surplus takes a different path, which is how a safe drug becomes a toxic one at a threshold rather than gradually. Acetaminophen is the example given: sulfation and glucuronidation carry the normal dose, and once they are exhausted CYP oxidation produces NAPQI. The same shape recurs wherever a protective route saturates before a harmful one does.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 34',
 quote:'Overdosing can overwhelm DME capacity leading to toxicity · Example – APAP toxicity'},

{id:'fa-2', prof:'Sikazwe', tier:'new', topic:'factors', sub:'pd', concept:'route-presystemic',
 tags:['reasoning'], source:'slide',
 stem:'Why does the oral route expose a drug to more metabolism than an intravenous dose?',
 options:[
  {t:'Oral dosing is susceptible to pre-systemic metabolism in the gut wall and liver before the drug reaches circulation', correct:true,
   why:'A swallowed drug passes the stomach, the intestinal mucosa and its microbiome, then the liver on its first pass, and each can metabolize it before any reaches the systemic circulation. The result is diminished bioavailability of the parent drug.'},
  {t:'Oral drugs are more lipophilic by definition', correct:false,
   why:'Lipophilicity is a property of the molecule, not of how it is given, and the same drug can be formulated both ways. It does affect absorption, but it is not what distinguishes the two routes here.'},
  {t:'Oral dosing raises plasma protein binding', correct:false,
   why:'Protein binding is a separate intrinsic factor, slide 38, and it depends on the drug and the available binding proteins rather than on the route. Binding also decreases metabolism, which is the opposite direction from the effect described.'},
  {t:'Intravenous drugs are excluded from hepatic metabolism entirely', correct:false,
   why:'An intravenous drug still reaches the liver and is still metabolized; what it avoids is being metabolized before entering the circulation. The difference is in the timing and the fraction lost, not in whether the liver participates.'}],
 teachImg:'fa_route',
 teach:'First-pass metabolism explains why the same drug needs different doses by different routes, and why some drugs cannot be given orally at all. Two sites contribute: the gut, including the stomach, the intestinal mucosa and the resident microbiome, and the liver on the drug\'s first transit. CYP3A4 sits in both, which is why it dominates first-pass effects and why grapefruit juice acting on intestinal CYP3A4 raises bioavailability so sharply. The measurable consequence is reduced bioavailability of the parent drug, and for a prodrug the same pass can work in favour of the drug by producing the active species sooner.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 35–36',
 quote:'Pre-systemic metabolism occurs in: i) gut (stomach, intestine mucosa & micro biome) ii) 1st time the drug passes through the liver'},

{id:'fa-3', prof:'Sikazwe', tier:'new', topic:'factors', sub:'pd', concept:'protein-binding-metabolism',
 tags:['reasoning'], source:'slide',
 stem:'What effect does extensive plasma protein binding have on metabolism?',
 options:[
  {t:'It decreases metabolism, because only unbound drug is available to enzymes', correct:true,
   why:'Bound drug travels as part of a large complex that enzymes cannot act on and the glomerulus cannot filter. Holding drug in that form lowers the fraction available for metabolism and lengthens the half-life.'},
  {t:'It increases metabolism by delivering drug directly to hepatocytes', correct:false,
   why:'Binding proteins retain drug in plasma rather than carrying it into cells. Warfarin, the non-steroidal anti-inflammatory drugs and sulfonamides are the examples given, and all are long-acting partly for this reason.'},
  {t:'It has no effect, since enzymes strip drug off albumin', correct:false,
   why:'Only free drug is available, which is stated directly on the slide. Binding is reversible, so bound drug becomes available as free concentration falls, but that is a gradual release rather than enzymes extracting it.'},
  {t:'It converts the drug into a prodrug', correct:false,
   why:'A prodrug is inactive until it is chemically converted. Protein binding changes where a drug is and how much is free, without altering the molecule at all.'}],
 svg:DIA.renalHandling,
 teachImg:'fa_distribution',
 teach:'Only free drug is available for metabolism, and the same rule governs filtration at the glomerulus, so protein binding slows both of the main clearance processes at once. Which protein does the binding follows the drug\'s character: weak acids bind albumin, weak bases bind alpha-1 acid glycoprotein. That matters for interactions, since two drugs competing for the same binding site can displace one another and raise the free fraction of a narrow-index drug sharply. Tissue binding, slide 39, works differently again: it raises total drug concentration in the tissue while still leaving only the free portion available.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 38',
 quote:'Protein binding ↓ metabolism and increases drug t1/2 · Note: Only the Free or un-bound drug is available for metabolism'},

{id:'fa-4', prof:'Sikazwe', tier:'new', topic:'factors', sub:'phys', concept:'neonate-ugt',
 tags:['reasoning','age'], source:'slide',
 stem:'Why are neonates particularly vulnerable to bilirubin accumulation?',
 options:[
  {t:'UGT1A1 activity is low at birth, so bilirubin conjugation is limited', correct:true,
   why:'Bilirubin is a hemoglobin metabolite cleared by glucuronidation, and the responsible isoform is not yet at adult activity. Unconjugated bilirubin therefore accumulates, producing jaundice or hyperbilirubinemia.'},
  {t:'Neonates over-express CYP3A4 and destroy bilirubin too quickly', correct:false,
   why:'The fetal isoform named on slide 45 is CYP3A7 rather than CYP3A4, and faster clearance would lower bilirubin rather than raise it. The problem is too little conjugation, not too much destruction.'},
  {t:'Neonatal kidneys hyperfiltrate and concentrate bilirubin', correct:false,
   why:'Renal function is immature rather than excessive at this age, and bilirubin is handled by hepatic conjugation followed by biliary elimination rather than by filtration.'},
  {t:'Neonates lack glutathione S-transferases', correct:false,
   why:'Glutathione S-transferase conjugates electrophiles such as R-X and epoxides, slide 30. Bilirubin is not an electrophilic substrate, so this enzyme is not the route in question.'}],
 teachImg:'fa_neonate',
 teach:'Enzyme systems mature at different rates, and Phase 1 leads Phase 2, so a neonate has proportionally more oxidative capacity than conjugating capacity. The consequences are practical and specific. Low UGT1A1 causes jaundice and also means drugs depending heavily on glucuronidation should be avoided, chloramphenicol being the named example through gray baby syndrome. Low CYP2C19 is the second warning on the same slide, with omeprazole named as a drug to avoid. The elderly present the mirror image on slide 47, where capacity declines through reduced liver mass, reduced hepatic blood flow and polypharmacy rather than through immaturity.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 46',
 quote:'Low UGT (i.e., UGT1A1) conjugation of bilirubin (hemoglobin metabolite) leads to Jaundice or hyperbilirubinemia'},

{id:'fa-5', prof:'Sikazwe', tier:'new', topic:'factors', sub:'phys', concept:'elderly-metabolism',
 tags:['reasoning','age'], source:'slide',
 stem:'Which changes in the elderly reduce metabolic capacity?',
 options:[
  {t:'Reduced liver mass and hepatic blood flow, along with changed body composition', correct:true,
   why:'Less liver mass and less endoplasmic reticulum mean less enzyme, and reduced hepatic blood flow means less drug delivered to what remains. Reduced renal filtration compounds it on the elimination side, and polypharmacy adds interactions.'},
  {t:'Increased liver mass with higher enzyme density', correct:false,
   why:'This reverses the change. Liver mass and endoplasmic reticulum both decline, and endoplasmic reticulum is where the CYPs sit, so the loss falls directly on Phase 1 capacity.'},
  {t:'Complete loss of Phase 2 conjugation', correct:false,
   why:'The decline is partial rather than absolute, and it is not specific to Phase 2. A complete loss of conjugation would be incompatible with ordinary drug handling.'},
  {t:'A shift of all metabolism to the kidney', correct:false,
   why:'Renal function declines too, with reduced filtration rates listed alongside the hepatic changes. The kidney is under the same pressure rather than compensating for the liver.'}],
 teachImg:'fa_elderly',
 teach:'Several changes point the same way in the elderly, which is why the effect on exposure is larger than any one of them suggests. Less liver mass and less endoplasmic reticulum reduce the amount of enzyme; reduced hepatic blood flow reduces delivery to it; reduced renal filtration slows the elimination of what is produced; and polypharmacy raises the chance that something else is competing for the same enzymes. Slow metabolism means susceptibility to toxicity, which is the reasoning behind starting low and going slow. Neonates on slide 46 arrive at the same caution from immaturity rather than decline.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 47',
 quote:'Slow metabolism = toxicity susceptibility - so "Start low & go slow"'},

{id:'fa-6', prof:'Sikazwe', tier:'new', topic:'factors', sub:'phys', concept:'liver-disease-effect',
 tags:['reasoning','disease'], source:'slide',
 stem:'What is the effect of liver disease on drug metabolism?',
 options:[
  {t:'Decreased metabolism, so parent drug persists and doses often need reducing', correct:true,
   why:'Liver disease lowers drug-metabolizing enzyme activity directly. That matters most when a drug has to be metabolized by the liver before it can be eliminated, since no alternative route takes over.'},
  {t:'Increased metabolism from compensatory enzyme induction', correct:false,
   why:'The one disease on the table that raises activity is thyroid disease, where increased protein synthesis in hyperthyroidism elevates enzyme levels. Liver disease moves in the opposite direction, and damaged tissue does not compensate by inducing.'},
  {t:'No change, because extrahepatic sites take over completely', correct:false,
   why:'Extrahepatic metabolism exists, in the gut and elsewhere, but it does not replace hepatic capacity. The slide notes this factor as key precisely when the liver is required for a drug to be eliminated.'},
  {t:'Metabolism is unaffected but elimination doubles', correct:false,
   why:'Reduced metabolism slows the production of the polar metabolites that elimination depends on, so both are impaired rather than one compensating for the other.'}],
 teachImg:'fa_disease',
 teach:'Four disease states appear on this table and three lower enzyme activity: liver disease directly, cardiac disease through reduced hepatic blood flow, and inflammation or infection. Only thyroid disease raises it, through the increased protein synthesis of hyperthyroidism. Two cautions accompany the table. The effects are not always predictable, so a dose change is guided by response and monitoring rather than by the diagnosis alone. And the factor matters most when the liver is required for elimination, since a drug cleared renally as intact drug is comparatively unaffected by what the liver can no longer do.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 43',
 quote:'Liver disease | Decreased DME activity · Cardiac disease (blood flow) | Decreased DME activity due to reduced liver blood flow'},

{id:'fa-7', prof:'Sikazwe', tier:'new', topic:'factors', sub:'induce', concept:'dietary-inducers',
 tags:['recall','induction','diet'], source:'slide',
 stem:'Which dietary exposures act as enzyme inducers?',
 options:[
  {t:'Indoles from cruciferous vegetables and polycyclic aromatic hydrocarbons from smoked or barbecued food', correct:true,
   why:'Indoles from sprouts, cabbage, broccoli and cauliflower raise CYP1A1 and 1A2, and polycyclic aromatic hydrocarbons from smoked or barbecued food and cigarette smoke raise the same two isoforms. Organosulfur compounds from garlic raise CYP1A and CYP3A plus some Phase 2 enzymes.'},
  {t:'Grapefruit juice and its furocoumarins', correct:false,
   why:'Grapefruit juice is the dietary inhibitor, slides 62 and 63, where bergamottin and 6\',7\'-dihydroxybergamottin act as mechanism-based inhibitors of CYP3A4. It belongs on the opposite list.'},
  {t:'Tyramine from aged cheese', correct:false,
   why:'Tyramine is a substrate whose metabolism is blocked rather than an inducer. The interaction on slide 61 arises because monoamine oxidase inhibitors prevent its inactivation, which produces a hypertensive crisis.'},
  {t:'Activated charcoal taken with meals', correct:false,
   why:'Charcoal adsorbs drug in the gastrointestinal tract, which is an absorption and elimination effect from MCMet-9_17_2026.pdf slide 62. It does not change how much enzyme the liver makes.'}],
 teachImg:'fa_dietary_ind',
 teach:'The dietary inducers share a pattern: flat aromatic or small reactive molecules that raise CYP1A1 and CYP1A2, the isoforms that handle exactly that kind of compound. Polycyclic aromatic hydrocarbons from smoke and charred food are the clearest case, and they explain why tobacco smoke affects CYP1A2 substrates such as caffeine, clozapine and theophylline. Indoles from cruciferous vegetables act on the same pair, and garlic organosulfur compounds extend to CYP3A and some Phase 2 enzymes. Because induction requires new protein, all of these develop over days and fade over days, which distinguishes them from the grapefruit effect.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 56–57',
 quote:'Indoles from cruciferous vegetables (sprouts, cabbage, broccoli, cauliflower) ↑ CYP1A1 & 1A2'},

{id:'fa-8', prof:'Sikazwe', tier:'new', topic:'factors', sub:'inhib', concept:'tyramine-maoi',
 tags:['case','inhibition','diet'], source:'slide',
 stem:'Why does eating aged cheese while taking an MAO inhibitor risk a hypertensive crisis?',
 options:[
  {t:'Tyramine normally destroyed by MAO is absorbed intact and drives a pressor response', correct:true,
   why:'Tyramine is a dietary amine from smoked, aged and pickled foods that monoamine oxidase would normally inactivate. With the enzyme inhibited, systemic tyramine rises and promotes release of epinephrine and norepinephrine, which can precipitate a fatal hypertensive crisis.'},
  {t:'MAO inhibitors induce CYP1A2, which converts cheese proteins to pressors', correct:false,
   why:'This describes induction rather than inhibition, and in the wrong enzyme. The pressor amines are released from the patient\'s own stores in response to tyramine, not manufactured from dietary protein.'},
  {t:'Cheese inhibits renal elimination of the MAO inhibitor', correct:false,
   why:'The drug\'s own clearance is not the issue. What accumulates is the dietary amine, because the enzyme that would normally destroy it is blocked.'},
  {t:'Tyramine forms a hapten–protein complex causing an immune reaction', correct:false,
   why:'Hapten formation produces hypersensitivity, MCMet-9_17_2026.pdf slide 42, which has a different presentation and time course. This reaction is pharmacological and immediate, driven by catecholamine release rather than by immune recognition.'}],
 teachImg:'fa_dietary_inh',
 teach:'Most interactions in this lecture concern a drug whose own metabolism is altered. This one inverts that: the drug blocks an enzyme, and the substance that accumulates is a food component. Tyramine is normally destroyed before it reaches the circulation, so an ordinary meal is harmless; with monoamine oxidase inhibited, it survives, reaches the systemic circulation and drives release of epinephrine and norepinephrine. The consequence can be fatal, which is why the dietary restriction is absolute rather than advisory. It also shows why enzymes handling endogenous and dietary substrates matter as much as those handling drugs.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 61',
 quote:'Tyramine promotes the release of hypertensive monoamines (i.e.,Epi, Norepi)'},

{id:'fa-9', prof:'Sikazwe', tier:'new', topic:'factors', sub:'inhib', concept:'inhibition-types',
 tags:['mechanism','inhibition'], source:'slide',
 stem:'Enzyme inhibition is divided into which two categories in lecture?',
 options:[
  {t:'Reversible (competitive and non-competitive) and irreversible', correct:true,
   why:'Reversible inhibition lasts 2 to 3 days. Irreversible inhibition holds the substrate bound for longer, through complexation of the drug, an intermediate or a metabolite with the enzyme, and recovery then requires the enzyme to be regenerated rather than merely released.'},
  {t:'Transcriptional and translational', correct:false,
   why:'Those terms describe how induction works, by increasing messenger RNA translation and reducing protein degradation, slide 53. Inhibition acts on enzyme already present rather than on how much is made.'},
  {t:'Hepatic and extrahepatic', correct:false,
   why:'That is a distinction of location rather than mechanism. Inhibition occurs at both sites and is classified by whether the enzyme recovers when the inhibitor leaves.'},
  {t:'Microsomal and cytosolic', correct:false,
   why:'That distinguishes where enzymes sit, with CYPs and UDP-glucuronosyltransferase in the endoplasmic reticulum and sulfotransferase and glutathione S-transferase in the cytosol. It says nothing about how an inhibitor acts.'}],
 teachImg:'tbl_ddi',
 teach:'The two categories differ in what it takes to recover. Reversible inhibition ends when the inhibitor is cleared, so the effect lasts 2 to 3 days and tracks the inhibitor\'s own presence. Irreversible inhibition leaves the enzyme complexed with the drug, an intermediate or a metabolite, so activity returns only as new enzyme is synthesized, which takes considerably longer. The furocoumarins in grapefruit juice are the mechanism-based example on slide 63, and that is why a single glass can affect CYP3A4 substrates for far longer than the juice itself remains in the body.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 59',
 quote:'Reversible inhibition - lasts 2 - 3 days · Irreversible inhibition – substrate is bound for longer times'},

{id:'fa-10', prof:'Sikazwe', tier:'new', topic:'factors', sub:'inhib', concept:'inhibition-onset-vs-induction',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'A patient starts an interacting drug today. Which interaction shows an effect soonest, and why?',
 options:[
  {t:'Inhibition, because it acts on enzyme already present rather than requiring new synthesis', correct:true,
   why:'An inhibitor binds enzyme that is already there, so the effect appears as soon as the inhibitor reaches the enzyme, within a dose or two. Induction has to raise messenger RNA translation and build new protein first, so it develops over days.'},
  {t:'Induction, because transcription responds within minutes', correct:false,
   why:'Transcription may begin quickly but the functional change requires enough new enzyme to accumulate, and that is a matter of days. The same delay applies in reverse when the inducer stops, because the extra protein has to be degraded.'},
  {t:'They appear at the same time, since both act on the same enzyme', correct:false,
   why:'Acting on the same enzyme says nothing about the time course, because the two change different things: inhibition changes the activity of existing enzyme, induction changes how many enzyme molecules exist.'},
  {t:'Neither has a measurable time course', correct:false,
   why:'Both have well-defined courses, and the difference between them is often what identifies which is operating. Reversible inhibition lasts 2 to 3 days, slide 59, while induction builds and fades over days.'}],
 teachImg:'tbl_ddi',
 teach:'Three differences separate the two, and any one of them can identify which is at work. Mechanism: inhibition blocks existing enzyme, induction makes more of it. Direction: inhibition raises drug levels, activity and duration of action, while induction lowers drug levels and duration and reduces efficacy. Timing: inhibition appears within a dose or two, induction over days, and both reverse on the same timescale they appeared. The direction inverts for a prodrug, since induction increases the therapeutic effect by producing more active species, which is listed among the consequences on slide 53 alongside increased toxicity from bioactivation.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 53, 59',
 quote:'Generally, induction ↑ DME activity & ↓ in drug blood levels plus ↓ DOA'},

{id:'fa-11', prof:'Sikazwe', tier:'new', topic:'factors', sub:'phys', concept:'interspecies-differences',
 tags:['recall'], source:'slide', teachImg:'fa_species',
 stem:'Cats have sulfotransferases (STs) but lack UDP-glucuronosyltransferases (UGTs). What does that inter-species difference mean in practice?',
 options:[
  {t:'A drug that humans clear by glucuronidation can accumulate to toxic levels in a cat, so animal data does not transfer across species', correct:true,
   why:'Losing UGT removes the widest phase II route, the one that handles -OH, -CO2H, -NH2 and -SH groups. A drug that humans clear as a glucuronide has no such route in the cat, so it is cleared more slowly or by a different route. Pigs are the reverse case: they have UGTs but lack STs.'},
  {t:'All mammals share an identical set of drug-metabolizing enzymes', correct:false,
   why:'The same slide gives three counterexamples: cats, pigs, and rats, which carry six CYP2D isoforms where humans carry one.'},
  {t:'Species differences apply only to phase 1 enzymes', correct:false,
   why:'UGT and ST are both phase 2 conjugating enzymes, so this example is a phase 2 difference. The amphetamine panel on the same slide shows a phase 1 difference as well, with rats hydroxylating the ring while humans, rabbits and guinea pigs oxidize the side chain to benzoic acid.'},
  {t:'Cats metabolize all drugs faster than humans', correct:false,
   why:'This inverts what losing a pathway does. A route that is absent cannot clear anything, so the drugs depending on it are removed more slowly and build up, which is why the cat and acetaminophen case is a toxicity case. The word \u2018all\u2019 is the second problem: a species difference changes the handling of drugs that use the missing route, not of every drug, since the routes a species does have are unaffected.'}],
 teach:'Inter-species differences sit under genetic factors. Two consequences follow. In drug development, a preclinical safety result obtained in one species may not predict the human outcome, because the species may route the drug differently. In veterinary practice, a dose that is safe for a human or a dog can be toxic to a cat when the cat lacks the enzyme that normally clears it.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 50'}
);
