QUESTIONS.push(
/* ======================= DM FOUNDATIONS ======================= */
{id:'df-1', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'analysis', concept:'dm-definition',
 tags:['definition'], source:'slide',
 stem:'What is drug metabolism?',
 options:[
  {t:'Enzyme-catalyzed reactions on drug and non-drug substrates', correct:true,
   why:'The definition is deliberately broad. Metabolism acts on xenobiotics, both drug and non-drug, and on endobiotics as well.'},
  {t:'Passive chemical breakdown of drugs in plasma', correct:false,
   why:'Metabolism is enzyme-catalysed by definition, so a reaction with no enzyme is not metabolism however much it changes the molecule. Spontaneous degradation in solution is a formulation stability problem, and it is treated separately for that reason: it happens outside the body as readily as inside it.'},
  {t:'Physical removal of drug from the body', correct:false,
   why:'That is elimination, which is the step metabolism prepares a drug for rather than metabolism itself. Conflating the two is the usual route here, and the test that separates them is whether the molecule changed: metabolism alters chemical structure, elimination removes whatever structure is there.'},
  {t:'Binding of drug to its receptor', correct:false,
   why:'Receptor binding is the pharmacodynamic event, what the drug does to the body, while metabolism is part of pharmacokinetics, what the body does to the drug. Both involve a drug and a protein, which is what makes this option readable as metabolism, but binding changes no covalent structure.'}],
 teach:'Every word of the definition does work. Enzyme-catalysed rules out spontaneous chemical breakdown, which happens to some drugs in solution but is not metabolism. Substrates being drugs or non-drugs means the same enzymes act on endogenous molecules as well, which is why dopamine and sumatriptan appear side by side as substrates of one enzyme. And a change in chemical structure is the result, which separates metabolism from elimination: metabolism alters the molecule, elimination removes it. A drug can be eliminated without ever being metabolised, and several are.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 6'},

{id:'df-2', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'analysis', concept:'dm-chemical-defense',
 tags:['reasoning'], source:'slide',
 stem:'Metabolism acts as a chemical defense system by:',
 options:[
  {t:'Making lipophilic drugs hydrophilic', correct:true,
   why:'A lipophilic molecule is reabsorbed and retained. Adding or exposing polar groups, then conjugating them, makes the molecule water soluble enough to leave in urine or bile.'},
  {t:'Making hydrophilic drugs lipophilic', correct:false,
   why:'This runs the solubility change backwards. A more lipophilic metabolite would be reabsorbed from the renal tubule more readily than the parent, so it would be retained rather than removed, which is the opposite of a defence. Storage is not a metabolic goal anywhere in the course.'},
  {t:'Blocking systemic drug exposure', correct:false,
   why:'Metabolism reduces exposure for some drugs but does not block absorption outright, and not all drugs are metabolized.'},
  {t:'Binding drugs to plasma proteins', correct:false,
   why:'Plasma protein binding is reversible and belongs to distribution rather than metabolism, and it makes no covalent change to the drug. It does hold drug out of circulation temporarily, which is what makes it sound like a defence, but the drug is released unchanged and is no easier to eliminate for having been bound.'}],
 teach:'The defence is a change in solubility. A lipophilic molecule crosses membranes easily in both directions, so the kidney filters it and the tubule reabsorbs it, and the drug circulates instead of leaving. Metabolism adds or exposes polar groups in Phase 1, then attaches a large polar conjugate in Phase 2, and the product is water-soluble enough to stay in the tubular fluid or to be carried into bile. Two qualifications come with it: not every metabolite is more hydrophilic than its parent, and not every metabolite is harmless, since some are active and some are reactive.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 9'},

{id:'df-3', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'phases', concept:'phase1-vs-phase2-role',
 tags:['definition','exam-pattern'], source:'slide',
 stem:'Phase 1 enzymes are ______ and Phase 2 enzymes are ______.',
 options:[
  {t:'oxygenases; transferases', correct:true,
   why:'The two names describe the chemistry. An oxygenase inserts oxygen, which either builds a new functional group or uncovers one that was masked, so Phase 1 produces the handle. A transferase moves a group from a cofactor onto that handle, which is the Phase 2 reaction. Phase 2 can also act straight away when the drug already carries a suitable group, so the pair describes two kinds of chemistry rather than a fixed order.'},
  {t:'always first; always required', correct:false,
   why:'Phase 2 can use existing functional groups directly. The metabolic patterns slide includes routes that skip Phase 1 entirely.'},
  {t:'gut enzymes; liver enzymes', correct:false,
   why:'Both phases occur mainly in the liver, and both also occur at extrahepatic sites including the gut wall, kidney and lung. Splitting them by organ is a reasonable guess given that first-pass metabolism involves gut then liver, but the gut-then-liver sequence is about where a dose travels, not about which phase happens where.'},
  {t:'conjugases; oxidases', correct:false,
   why:'This swaps the two. Conjugation is the Phase 2 activity, carried out by transferases; oxidation is Phase 1, carried out by oxygenases. Since both phases are named only by number, there is nothing in the labels themselves to fix the order, which is why the chemistry behind each has to carry it.'}],
 teach:'The two phases are named for the chemistry their enzymes do, not for an order they run in. Phase 1 enzymes are oxygenases: cytochrome P450, flavin-containing monooxygenase, monoamine oxidase, alcohol and aldehyde dehydrogenase, the aldo-keto reductases, carboxylesterase and epoxide hydrolase. They insert oxygen, remove hydrogen, add electrons or add water, and the result is a functional group that was either absent or masked. Phase 2 enzymes are transferases: the glucuronosyltransferases, sulfotransferases, glutathione S-transferases, N-acetyltransferases, methyltransferases and acyl synthetases. Each moves a group from a cofactor onto a functional group that is already present, which is why a drug carrying a suitable group can go straight to Phase 2.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slides 12–13'},

{id:'df-4', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'phases', concept:'metabolic-patterns',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'Regarding drug metabolism patterns, which statement is correct?',
 options:[
  {t:'Parent drug can go straight to Phase 2', correct:true,
   why:'The patterns slide lists several routes, and direct conjugation is one of them. It applies whenever the parent already carries a conjugatable group such as a phenol.'},
  {t:'Phase 1 always precedes Phase 2', correct:false,
   why:'The numbering names two kinds of chemistry rather than two stages, so no order is mandatory. Four patterns are listed, including a parent drug going straight to a Phase 2 metabolite and a Phase 2 metabolite afterwards undergoing a Phase 1 reaction. Reading 1 and 2 as first and second is what makes this option look safe.'},
  {t:'Every drug is metabolised', correct:false,
   why:'Not all drugs are metabolized. Some are eliminated unchanged, which is stated plainly in the introduction.'},
  {t:'Phase 2 metabolites are always inactive', correct:false,
   why:'Most are inactive, but conjugation can retain or create activity, and consequences include bioactivation.'}],
 teach:'Four patterns are listed, and only the first is the familiar one. A parent drug can go through Phase 1 to a Phase 1 metabolite and then through Phase 2; a Phase 1 metabolite can undergo a second Phase 1 reaction; a parent drug can go directly to a Phase 2 metabolite; and a Phase 2 metabolite can undergo a Phase 1 reaction afterwards. The numbering of the phases describes two kinds of chemistry, so any sequence of them is possible, and the sequence a given drug takes depends only on which functional groups it carries and which it acquires.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slides 8, 14'},

{id:'df-5', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'phases', concept:'enzyme-characteristics',
 tags:['recall','reasoning'], source:'slide',
 stem:'Broad substrate activity of drug-metabolizing enzymes matters clinically because:',
 options:[
  {t:'Shared enzymes cause drug interactions', correct:true,
   why:'Broad specificity is what makes drug–drug interactions so common. Two unrelated drugs can collide simply because one enzyme handles both.'},
  {t:'Each enzyme has one substrate', correct:false,
   why:'This describes narrow specificity, one enzyme to one substrate, which is the reverse of the characteristic the stem names. If it held, two drugs could only meet at an enzyme by coincidence, so metabolic interactions would be rare events rather than something to check on every new prescription. Reaching for it usually means picturing a metabolic enzyme the way an enzyme with one natural substrate works, which does not fit a family whose role is to handle whatever foreign compound arrives.'},
  {t:'Only endobiotics are metabolised', correct:false,
   why:'These enzymes act on endogenous and foreign molecules alike, which is the substance of the broad-substrate characteristic: dopamine and sumatriptan appear as two substrates of one enzyme for exactly that reason. Restricting them to endogenous compounds would leave no explanation for how drugs are metabolised at all.'},
  {t:'Enzyme levels cannot change', correct:false,
   why:'Enzyme amount does change, and inducibility is listed as its own characteristic beside broad substrate activity. Picking this confuses two separate properties: broad specificity is about which molecules the enzyme accepts, while inducibility is about how much enzyme is present, and the two vary independently.'}],
 teach:'Broad substrate activity is the first of the listed enzyme characteristics, and the clinical consequence follows from it directly. One enzyme accepting many unrelated molecules means two drugs prescribed for unrelated reasons can compete at the same active site, so an interaction needs no chemical similarity between the drugs at all. Dopamine and sumatriptan are the paired example. The other characteristics compound it: multiple families and subfamilies, polymorphism producing rapid through poor metaboliser phenotypes, a cytoprotective role, constitutive expression, and inducibility. Broad specificity makes interactions common; inducibility and polymorphism make their size vary between patients.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slides 16–17'},

{id:'df-6', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'sites', concept:'presystemic-vs-systemic',
 tags:['definition'], source:'slide',
 stem:'Pre-systemic metabolism occurs:',
 options:[
  {t:'In gut wall and liver before circulation', correct:true,
   why:'This is the first-pass effect. It is why an oral dose often differs so much from an intravenous one, and why intestinal CYP3A4 matters.'},
  {t:'Only after tissue distribution', correct:false,
   why:'That is systemic metabolism, the other half of the pair. The dividing line is the systemic circulation: everything before it is pre-systemic, everything after it systemic. Choosing this means having the two halves of the distinction but attaching the wrong one to the prefix.'},
  {t:'In the formulation before dosing', correct:false,
   why:'Degradation in the vial is a formulation stability problem, not metabolism, because no enzyme and no body is involved. The word pre-systemic invites this reading since it does mean before the systemic circulation, but the reference point is the circulation rather than the moment of administration.'},
  {t:'By plasma esterases only', correct:false,
   why:'Plasma esterase activity is systemic and is only one of several enzyme systems.'}],
 teach:'The distinction is geographic. Pre-systemic metabolism happens between swallowing and the systemic circulation, in the gut wall and then in the liver by way of the portal vein, which is the first-pass effect. Systemic metabolism happens after the drug has reached the circulation and been distributed. The practical consequence is that an oral dose and an intravenous dose of the same drug can produce very different exposures, because only the oral route passes the liver before reaching the rest of the body, and intestinal CYP3A4 removes some of the dose before the liver sees it.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 18'},

{id:'df-7', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'sites', concept:'cellular-sites',
 tags:['recall'], source:'slide',
 stem:'At the cellular level, where does metabolism occur?',
 options:[
  {t:'Microsomal (endoplasmic reticulum), cytosol and mitochondria', correct:true,
   why:'Location tracks with enzyme family: CYPs and UGTs are microsomal, SULTs and GSTs are cytosolic, and some oxidases such as MAO are mitochondrial.'},
  {t:'Nucleus and nucleolus only', correct:false,
   why:'The nucleus is where induction is triggered through transcription, but the reactions themselves occur elsewhere.'},
  {t:'Lysosomes and peroxisomes only', correct:false,
   why:'Neither lysosomes nor peroxisomes is among the three compartments listed, which are the endoplasmic reticulum, the cytosol and the mitochondria. Both organelles do degrade material, which is what makes them plausible, but the drug-metabolising enzyme families are not found in them.'},
  {t:'Plasma membrane exclusively', correct:false,
   why:'CYPs are membrane bound, but within the endoplasmic reticulum rather than the plasma membrane.'}],
 teach:'Three cellular compartments hold the enzymes, and the compartment tracks the enzyme family. Microsomal means the endoplasmic reticulum, where the cytochrome P450 enzymes and the glucuronosyltransferases sit as membrane-bound proteins. The cytosol is where the sulfotransferases and glutathione S-transferases float free. The mitochondria hold monoamine oxidase and some other oxidases. The nucleus is where induction is triggered, since a drug that induces an enzyme does so by increasing transcription, but no metabolic reaction is carried out there.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 20'},

{id:'df-8', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'conseq', concept:'consequences-list',
 tags:['recall','exam-pattern'], source:'slide',
 stem:'Which of these is one of the general consequences of xenobiotic metabolism?',
 options:[
  {t:'Bioactivation of a prodrug to the active species', correct:true,
   why:'The consequences run well beyond inactivation: bioactivation of prodrugs, formation of similarly or more active metabolites, altered activity, reversible metabolites, and bioactivation to toxic, carcinogenic or teratogenic species.'},
  {t:'Increased plasma protein binding of the parent drug', correct:false,
   why:'Plasma protein binding is a distribution property rather than a consequence of metabolism, and it applies to the parent drug whether or not any metabolism occurs. The consequence categories all describe what happened to the molecule chemically: inactivation, activation, conversion to another active species, or bioactivation to a reactive one.'},
  {t:'Reduced glomerular filtration rate', correct:false,
   why:'Glomerular filtration rate measures kidney function and is not altered by metabolising a drug. The link that makes this tempting runs the other way: metabolism produces polar metabolites that the kidney then filters, so filtration acts on the output of metabolism rather than being changed by it.'},
  {t:'Change in the drug\'s route of administration', correct:false,
   why:'Route is a clinical decision made before dosing.'}],
 teach:'Metabolism has more than one outcome, and the possibilities are not all favourable. A drug can be inactivated, which is the expected result. An inactive prodrug can be activated. An active drug can be converted to another active metabolite. And a drug can be bioactivated to a reactive species that damages the cell that made it. The same enzyme can produce different outcomes for different substrates, so the consequence is a property of the drug and the reaction rather than of the enzyme.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 28'},

{id:'df-9', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'conseq', concept:'prodrug-ester-azo',
 tags:['reasoning','case'], source:'slide',
 stem:'Enalapril and sulfasalazine are both prodrugs. How does each get activated?',
 options:[
  {t:'Enalapril by ester hydrolysis, sulfasalazine by bacterial azo reduction in the gut', correct:true,
   why:'Two different chemistries achieve the same end. The ester is cleaved by esterases, while the azo bond is split by intestinal microbial reductases to release the active fragment.'},
  {t:'Both by CYP3A4 oxidation', correct:false,
   why:'Neither prodrug is activated by oxidation. Enalapril is an ester, activated by carboxylesterase hydrolysis; sulfasalazine carries an azo bond, activated by bacterial azo-reductases in the gut. Reaching for CYP3A4 is the reflex answer whenever a prodrug is mentioned, and it is wrong for both of these.'},
  {t:'Enalapril by azo reduction, sulfasalazine by ester hydrolysis', correct:false,
   why:'The two are swapped. Enalapril carries the ester and is hydrolysed; sulfasalazine carries the azo bond and is reduced. Both halves of the answer are individually correct chemistry, which is what makes it the closest wrong option: the error is in the pairing rather than in either reaction.'},
  {t:'Both by glucuronidation', correct:false,
   why:'Glucuronidation is a Phase 2 conjugation that generally inactivates rather than activates.'}],
 teach:'A prodrug is designed around the enzyme that will convert it, and the two examples take different routes. Enalapril is an ester prodrug: carboxylesterase hydrolyses the ester to release enalaprilat, the active diacid, and the ester exists because the acid itself is absorbed poorly. Azo prodrugs are cleaved by bacterial azo-reductases in the intestine, splitting the nitrogen-nitrogen double bond to give two amines, and in the named case both halves are active, one an antibiotic and one an anti-inflammatory. Site matters as much as chemistry in the second case, since the enzyme belongs to the gut flora and the release therefore happens in the colon.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slides 35–36'},

{id:'df-10', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'conseq', concept:'reactive-metabolite-withdrawals',
 tags:['recall','case'], source:'slide',
 stem:'Acetaminophen carries a hepatotoxicity precaution rather than a withdrawal because:',
 options:[
  {t:'NAPQI forms only after conjugation is exhausted', correct:true,
   why:'The deck separates drugs withdrawn for reactive metabolites from drugs kept in use with precautions. Acetaminophen sits in the second group because the hazard is dose dependent.'},
  {t:'It forms no reactive metabolite', correct:false,
   why:'Acetaminophen does form a reactive metabolite, N-acetyl-p-benzoquinone imine, and it is the worked example of one. Reading a hepatotoxicity precaution as meaning no reactive metabolite inverts the reason for the precaution: the warning exists because the metabolite forms, not because it does not.'},
  {t:'It is not metabolised', correct:false,
   why:'Acetaminophen is extensively metabolised, mainly by sulfation and glucuronidation at ordinary doses. Those two routes saturate in overdose, which is precisely when more of the dose goes down the Phase 1 route to the reactive metabolite, so the metabolism is both present and central to the toxicity.'},
  {t:'Its reactive metabolite is exhaled', correct:false,
   why:'Reactive metabolites are neutralised by conjugation, not exhaled.'}],
 teach:'Reactive metabolites are the reason several drugs carry a black box warning or were withdrawn, and the lists are kept separate for a reason. One list holds drugs withdrawn because of reactive metabolites. A second holds drugs never approved in the United States for the same reason. A third holds drugs that remain in use with hepatotoxicity precautions, acetaminophen, carbamazepine and clozapine among them. The third list is the clinically important one, because those drugs are still prescribed and the risk is managed by dose limits and monitoring rather than by removal.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slides 25–26; acetaminophen dose threshold Lecture #15 (MCMet-9_17_2026.pdf) slide 49'},

/* ======================= PHASE 1 PATHWAYS (with images) ======================= */
{id:'p1-1', prof:'Sikazwe', tier:'old', topic:'paths', sub:'cypox', concept:'cyp-oxidation-types',
 tags:['recall'], source:'slide',
 stem:'Which reactions are among the CYP oxidative reactions?',
 options:[
  {t:'Epoxidation, dealkylation and dehalogenation', correct:true,
   why:'The prep sheet asks this as a true/false. CYPs catalyze aliphatic, allylic, benzylic and aromatic hydroxylation, N-, O- and S-dealkylation, dehalogenation and epoxidation.'},
  {t:'Glucuronidation, sulfation and acetylation', correct:false,
   why:'All three are Phase 2 conjugations carried out by transferases, not oxidations. The reason they read as reactions CYP might do is that they all change the molecule chemically, but every one of them attaches a group supplied by a cofactor, while a CYP oxidation supplies only oxygen.'},
  {t:'Ester and amide hydrolysis', correct:false,
   why:'Ester and amide hydrolysis are carboxylesterase reactions. They are Phase 1, which is what makes this option plausible, but Phase 1 covers oxidation, reduction and hydrolysis as three separate categories, and only the first is CYP work.'},
  {t:'Azo and nitro reduction', correct:false,
   why:'Azo and nitro reduction are reductions carried out by azo- and nitro-reductases, several of them bacterial. They belong to Phase 1 alongside the CYP oxidations, so the phase is right and the direction of the chemistry is wrong: CYP adds oxygen, a reductase adds electrons.'}],
 teach:'Cytochrome P450 (CYP) inserts a single oxygen atom, and each reaction on the list is named for where that oxygen lands. Hydroxylation leaves it as an alcohol, and the carbon it lands on supplies the label: aliphatic on a saturated chain, allylic beside a double bond, benzylic beside an aromatic ring, aryl on the ring itself. Dealkylation is named instead for the heteroatom that loses its substituent, giving N-, O- and S-dealkylation. Epoxidation adds the oxygen across a double bond as a three-membered ring, and dehalogenation replaces a halogen. The common thread is that CYP supplies only oxygen, so nothing endogenous is attached. That is the line between the two phases: Phase 1 exposes or installs a handle by oxidation, reduction or hydrolysis, and Phase 2 attaches a molecule the body supplies to a handle that is already there.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 11, with worked examples on slides 13–15; Sikazwe PTI study aid Q2i',
 quote:'CYP Oxidative Reactions Include: Aliphatic, Allylic, Benzylic, Aryl carbons · Heteroatom · N-dealkylations · O-dealkylations · S-dealkylations · Dehalogenations · Double bonds (dbs) to form Epoxides'},

{id:'p1-2', prof:'Sikazwe', tier:'old', topic:'paths', sub:'cypox', concept:'allylic-hydroxylation-ident',
 tags:['structure','reaction-id'], source:'slide', img:'rx_allylic_pentazocine', teachImg:'rx_allylic_pentazocine_labeled',
 stem:'Pentazocine is converted to the metabolite shown. Which specific CYP oxidation is this?',
 options:[
  {t:'Allylic hydroxylation', correct:true,
   why:'The new hydroxyl appears on a carbon directly adjacent to a carbon–carbon double bond, which is the definition of the allylic position.'},
  {t:'Benzylic hydroxylation', correct:false,
   why:'Benzylic means the carbon next to an aromatic ring. The hydroxylated carbon here sits beside an alkene, not a ring.'},
  {t:'Aromatic hydroxylation', correct:false,
   why:'Aromatic hydroxylation places the -OH directly onto a ring carbon. Here it lands on a chain carbon.'},
  {t:'Omega hydroxylation', correct:false,
   why:'Omega hydroxylation targets the terminal carbon of an alkyl chain, with no reference to a double bond.'}],
 teach:'Allylic hydroxylation is named for where the carbon sits rather than for what it becomes. A carbon adjacent to a carbon-carbon double bond is allylic, and cytochrome P450 hydroxylates it in preference to an ordinary saturated carbon because the radical formed at that position is stabilised by the neighbouring double bond. The product is an alcohol, exactly as in plain aliphatic hydroxylation; the label changes because the position does. Finding a double bond in a structure is therefore the clue that the carbons on either side of it are likely oxidation sites.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 13'},

{id:'p1-3', prof:'Sikazwe', tier:'old', topic:'paths', sub:'cypox', concept:'benzylic-hydroxylation-ident',
 tags:['structure','reaction-id'], source:'slide', img:'rx_benzylic_tolbutamide',
 stem:'Tolbutamide becomes hydroxytolbutamide as shown. Which oxidation pattern is this?',
 options:[
  {t:'Benzylic hydroxylation', correct:true,
   why:'The methyl group attached to the aromatic ring is oxidized to -CH₂OH. A carbon directly bonded to a ring is the benzylic position.'},
  {t:'Aromatic hydroxylation', correct:false,
   why:'That would put the hydroxyl on a ring carbon itself. Here the ring is untouched and the substituent carbon is oxidized.'},
  {t:'Allylic hydroxylation', correct:false,
   why:'Allylic hydroxylation requires a carbon next to a carbon-carbon double bond; benzylic requires a carbon next to an aromatic ring. Both labels describe a carbon made reactive by its neighbour, which is what makes them easy to exchange, and the only thing that separates them is whether that neighbour is an alkene or a ring.'},
  {t:'N-dealkylation', correct:false,
   why:'No alkyl group leaves here and no nitrogen is involved: a carbon simply gains a hydroxyl. N-dealkylation would remove a substituent from a nitrogen and release it as an aldehyde, leaving a smaller amine behind. Comparing the atom count of parent and metabolite settles it, since hydroxylation adds one oxygen and removes nothing.'}],
 teach:'A benzylic carbon is the carbon directly attached to an aromatic ring, and only that one. The carbon one position further along is not benzylic. Cytochrome P450 hydroxylates it readily for the same reason it favours the allylic position: the adjacent ring stabilises the intermediate. Tolbutamide is the worked example, where the methyl group on the ring is hydroxylated. Distinguishing benzylic from aromatic hydroxylation is a matter of which atom takes the oxygen, the side-chain carbon or a carbon of the ring itself.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 14'},

{id:'p1-4', prof:'Sikazwe', tier:'old', topic:'paths', sub:'cypox', concept:'aromatic-hydroxylation-ident',
 tags:['structure','reaction-id'], source:'slide', img:'rx_aromatic_estradiol',
 stem:'Estradiol gives the two metabolites shown. What reaction has occurred?',
 options:[
  {t:'Aromatic hydroxylation at two different ring positions', correct:true,
   why:'Both products carry a new hydroxyl directly on the aromatic ring, at positions 2 and 4. One substrate giving several regioisomers is typical of aromatic hydroxylation.'},
  {t:'O-dealkylation of a methyl ether', correct:false,
   why:'There is no ether being cleaved; a hydrogen on the ring is replaced by a hydroxyl.'},
  {t:'Benzylic hydroxylation', correct:false,
   why:'The new hydroxyls sit on ring carbons rather than on a carbon attached to the ring.'},
  {t:'Epoxidation followed by hydrolysis', correct:false,
   why:'The products are phenols rather than diols, so no epoxide-to-diol conversion is shown.'}],
 teach:'Aromatic hydroxylation puts the hydroxyl directly onto a carbon of the ring rather than onto a side chain. Estradiol is the worked example, and it also shows that one drug usually gives more than one metabolite, since the hydroxyl can be introduced at more than one ring position. A phenol appearing where a plain benzene ring was is the signature of the reaction, and it matters downstream because a phenol is a substrate for glucuronidation and sulfation, so an aromatic hydroxylation often creates the handle a Phase 2 enzyme then uses.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 15'},

{id:'p1-5', prof:'Sikazwe', tier:'old', topic:'paths', sub:'cypox', concept:'n-dealkylation-ident',
 tags:['structure','reaction-id'], source:'slide', img:'rx_ndemeth_imipramine',
 stem:'Imipramine\'s conversion to desipramine (shown) exemplifies:',
 options:[
  {t:'N-demethylation', correct:true,
   why:'A methyl group is removed from the nitrogen, turning a tertiary amine into a secondary one. Tertiary and secondary amines bearing methyl or ethyl groups undergo this reaction.'},
  {t:'Oxidative deamination', correct:false,
   why:'Deamination removes the whole nitrogen and leaves a carbonyl. Here the nitrogen remains with a hydrogen in place of the methyl.'},
  {t:'N-oxidation', correct:false,
   why:'N-oxidation adds oxygen to the nitrogen and keeps both alkyl groups.'},
  {t:'N-acetylation', correct:false,
   why:'That is a Phase 2 reaction that adds an acetyl group rather than removing a methyl.'}],
 teach:'N-dealkylation looks like a group being removed, and the naming follows the heteroatom that loses it. Cytochrome P450 oxidises the carbon next to the nitrogen, and that carbon then leaves as an aldehyde, so a secondary amine appears where a tertiary one was and formaldehyde is released when the group removed was a methyl. The oxygen is inserted at a carbon even though the reaction is named for the nitrogen, which is why N-, O- and S-dealkylation are one reaction type with three labels: the difference is only which heteroatom the departing alkyl group was attached to.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 16'},

{id:'p1-6', prof:'Sikazwe', tier:'old', topic:'paths', sub:'cypox', concept:'s-dealkylation-ident',
 tags:['structure','reaction-id'], source:'slide', img:'rx_sdemeth_mtp',
 stem:'6-Methylthiopurine becomes 6-mercaptopurine as shown. Which reaction is this?',
 options:[
  {t:'S-demethylation', correct:true,
   why:'The methyl group is removed from sulfur, leaving a free thiol. CYPs perform N-, O- and S-dealkylation by the same underlying chemistry on different heteroatoms.'},
  {t:'O-demethylation', correct:false,
   why:'The heteroatom losing the methyl is sulfur, not oxygen.'},
  {t:'Methylation by SAM', correct:false,
   why:'That runs the opposite direction, adding a methyl group. This reaction removes one.'},
  {t:'Sulfoxidation', correct:false,
   why:'Sulfoxidation adds oxygen to sulfur while keeping the methyl. Here the methyl is gone and no oxygen is added.'}],
 teach:'S-dealkylation removes an alkyl group from a sulfur, by the same route as its nitrogen and oxygen counterparts: the carbon adjacent to the heteroatom is oxidised and departs, leaving a free thiol where a thioether was. Reading the reaction from the structure means finding which heteroatom lost a substituent, so a thiol appearing in a metabolite where a sulfur-carbon bond used to be identifies the reaction without needing the enzyme to be named.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 18'},

{id:'p1-7', prof:'Sikazwe', tier:'old', topic:'paths', sub:'cypox', concept:'codeine-morphine',
 tags:['case','recall'], source:'slide',
 stem:'The conversion of codeine to morphine involves which reaction?',
 options:[
  {t:'O-demethylation', correct:true,
   why:'Codeine is the methyl ether of morphine, so removing that methyl from oxygen reveals the phenol and gives morphine. CYP2D6 carries it out, which is why 2D6 phenotype changes codeine\'s effect.'},
  {t:'N-demethylation', correct:false,
   why:'N-demethylation of codeine does happen, but it gives norcodeine rather than morphine, and norcodeine is not the active species. Codeine carries a methyl on both a nitrogen and an oxygen, so both demethylations are available; only the O-demethylation produces the analgesic.'},
  {t:'Aromatic hydroxylation', correct:false,
   why:'No new hydroxyl is added to a ring carbon; an existing ether is cleaved.'},
  {t:'Glucuronidation', correct:false,
   why:'Morphine is glucuronidated afterwards, but that is a later Phase 2 step rather than the conversion itself.'}],
 teach:'Codeine to morphine is an O-demethylation, and it is the case where the reaction decides whether the drug works. The methyl group on codeine\'s phenolic oxygen is removed by CYP2D6, giving morphine, and morphine is the species with meaningful analgesic activity. A poor metaboliser produces little morphine and reports no relief; an ultrarapid metaboliser produces a great deal and can reach respiratory depression from a standard dose. The whole clinical picture follows from one methyl group and the enzyme that removes it.',
 teachImg:'fgm_ether',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 17'},

{id:'p1-8', prof:'Sikazwe', tier:'old', topic:'paths', sub:'nonc', concept:'adh-aldh-sequence',
 tags:['mechanism','enzyme'], source:'slide', img:'rx_adh', teachImg:'rx_adh_labeled',
 stem:'A primary alcohol is oxidized as shown. Which enzyme does this, and what acts next?',
 options:[
  {t:'Alcohol dehydrogenase gives the aldehyde; aldehyde dehydrogenase then gives the carboxylic acid', correct:true,
   why:'The two work in sequence. ADH makes the aldehyde and ALDH clears it, which matters because the aldehyde intermediate is itself a reactive electrophilic carbonyl.'},
  {t:'Aldehyde dehydrogenase gives the aldehyde; alcohol dehydrogenase then gives the acid', correct:false,
   why:'The names are swapped. Each enzyme is named for the substrate it acts on rather than the product it makes, so alcohol dehydrogenase takes the alcohol and aldehyde dehydrogenase takes the aldehyde. Reading the name as the product is the single most common way to reverse this pair.'},
  {t:'Monoamine oxidase gives the aldehyde; carboxylesterase gives the acid', correct:false,
   why:'MAO acts on amines rather than alcohols, and CEs hydrolyze rather than oxidize.'},
  {t:'CYP450 gives the aldehyde; epoxide hydrolase gives the acid', correct:false,
   why:'EH opens epoxides to diols and has no role in this sequence.'}],
 teach:'Ethanol is cleared in two oxidation steps by two different enzymes, and the order cannot be swapped. Alcohol dehydrogenase oxidises the primary alcohol to an aldehyde. Aldehyde dehydrogenase then oxidises that aldehyde to a carboxylic acid. Each step removes hydrogen and raises the oxidation state of the same carbon, so the pair reads as one ladder: alcohol, aldehyde, acid. Naming the enzyme from a structure means asking which rung the starting material sits on, since the substrate of the second enzyme is the product of the first.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 22–23',
 note:'ALDH is inhibited by disulfiram, which is how disulfiram causes acetaldehyde to build up after drinking.'},

{id:'p1-9', prof:'Sikazwe', tier:'old', topic:'paths', sub:'nonc', concept:'aldh-disulfiram',
 tags:['case','enzyme'], source:'slide',
 stem:'Disulfiram inhibits aldehyde dehydrogenase. What is the result after alcohol intake?',
 options:[
  {t:'Acetaldehyde accumulates, producing the unpleasant reaction that discourages drinking', correct:true,
   why:'ADH still makes acetaldehyde but ALDH can no longer clear it. The accumulated reactive aldehyde causes the flushing and nausea that make disulfiram work therapeutically.'},
  {t:'Ethanol accumulates unchanged because ADH is blocked', correct:false,
   why:'Disulfiram blocks the second enzyme, aldehyde dehydrogenase, not the first. Ethanol is therefore still oxidised normally to acetaldehyde; what stops is the removal of that acetaldehyde. Blocking a middle step makes the intermediate accumulate, which is a different outcome from blocking the entry step.'},
  {t:'Acetic acid accumulates and causes acidosis', correct:false,
   why:'Acetate is the product that cannot form when ALDH is inhibited.'},
  {t:'Nothing changes, because ALDH is not involved in ethanol metabolism', correct:false,
   why:'ALDH is central to it, converting acetaldehyde to acetate.'}],
 teach:'Disulfiram works by stopping the second step rather than the first. It inhibits aldehyde dehydrogenase, so ethanol is still oxidised to acetaldehyde by alcohol dehydrogenase but the acetaldehyde is not cleared onward to acetic acid. Acetaldehyde accumulates, and the flushing, nausea and headache that follow are the deterrent the drug is prescribed for. Pyrazole inhibits the same enzyme. The design point is that blocking a middle step of a pathway causes the intermediate to build up, which is a different kind of effect from blocking the first step.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 23'},

{id:'p1-10', prof:'Sikazwe', tier:'old', topic:'paths', sub:'nonc', concept:'mao-substrate',
 tags:['enzyme','recall'], source:'slide',
 stem:'Monoamine oxidase converts amines to what?',
 options:[
  {t:'Aldehydes', correct:true,
   why:'MAO performs oxidative deamination, replacing the amine with a carbonyl. The aldehyde is then usually cleared by ALDH.'},
  {t:'Carboxylic acids directly', correct:false,
   why:'Monoamine oxidase stops at the aldehyde; reaching the carboxylic acid takes a second oxidation by aldehyde dehydrogenase. Naming the eventual fate rather than the single reaction is what leads here, and the same two-step ladder appears in ethanol metabolism.'},
  {t:'Alcohols', correct:false,
   why:'Reduction of the aldehyde to an alcohol would be an aldo-keto reductase reaction running the other way.'},
  {t:'N-oxides', correct:false,
   why:'N-oxidation is performed by flavin monooxygenase and by CYPs, keeping the nitrogen in place.'}],
 teach:'Monoamine oxidase oxidises an amine to an aldehyde, and its substrates are largely neurotransmitters rather than foreign compounds. The two isoforms divide by preference: MAO-A handles serotonin, MAO-B handles phenethylamines. That division is why MAO inhibitors carry the interactions they do, since blocking the enzyme leaves dietary amines such as tyramine unmetabolised and free to act. The reaction itself is an oxidative deamination, so the nitrogen leaves and a carbonyl appears where the amine carbon was.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 24–25'},

{id:'p1-11', prof:'Sikazwe', tier:'old', topic:'paths', sub:'nonc', concept:'fmo-targets',
 tags:['enzyme','recall'], source:'slide',
 stem:'Flavin-containing monooxygenase oxidizes which functional groups?',
 options:[
  {t:'Amines, amides and thiols', correct:true,
   why:'FMO is the non-CYP oxidase for nitrogen and sulfur nucleophiles. CYPs can also perform N-oxidation, so the two overlap.'},
  {t:'Only aromatic rings', correct:false,
   why:'Aromatic hydroxylation is a cytochrome P450 reaction, and flavin-containing monooxygenase does not touch rings at all. Its substrates are defined by heteroatom rather than by carbon skeleton: nitrogen in amines and amides, and sulfur in thiols and thioethers.'},
  {t:'Esters and carbamates', correct:false,
   why:'Esters and carbamates are hydrolysed by carboxylesterases, which break a bond by adding water. Flavin-containing monooxygenase inserts oxygen onto a heteroatom and breaks nothing, so the two enzymes share neither a substrate nor a kind of chemistry.'},
  {t:'Epoxides only', correct:false,
   why:'Epoxides are handled by epoxide hydrolase, which opens the ring to a diol, and by glutathione S-transferase, which attacks the electrophilic ring carbon. Flavin-containing monooxygenase creates oxidised products rather than consuming them, so an epoxide is the kind of thing that chemistry produces rather than something it acts on.'}],
 teach:'Flavin-containing monooxygenase handles nitrogen and sulfur, and the products are named by the heteroatom that receives the oxygen. Tertiary amines and amides give N-oxides. Sulfur gives sulfoxides and then sulfones. Three major isoforms are known. What separates it from cytochrome P450 is the note on slide 26 that it is not affected by CYP450 inhibitors, so a drug cleared mainly by FMO escapes that class of interaction. Cytochrome P450 can also carry out N-oxidation, so the product alone does not always identify the enzyme.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 26–28'},

{id:'p1-12', prof:'Sikazwe', tier:'old', topic:'paths', sub:'red', concept:'akr-function',
 tags:['enzyme','reaction-id'], source:'slide', img:'rx_akr', teachImg:'rx_akr_labeled',
 stem:'Which enzyme family carries out the conversions shown, and what is the general transformation?',
 options:[
  {t:'Aldo-keto reductases, reducing aldehydes and ketones to alcohols', correct:true,
   why:'AKRs run the reductive counterpart to ADH. The doxorubicin example matters clinically because the alcohol metabolite doxorubicinol is the cardiotoxic species.'},
  {t:'Alcohol dehydrogenases, oxidizing alcohols to aldehydes', correct:false,
   why:'Alcohol dehydrogenase runs the reaction the other way, removing hydrogen from an alcohol to give an aldehyde, which is an oxidation. The conversions shown go from carbonyl to alcohol, which is a reduction. Both families involve the same two functional groups, so naming the enzyme from the groups present rather than from which one is the starting material is what leads here.'},
  {t:'Carboxylesterases, hydrolyzing esters', correct:false,
   why:'No ester bond is cleaved in these reactions.'},
  {t:'Azo-reductases, reducing N=N bonds', correct:false,
   why:'Azo reduction splits a nitrogen–nitrogen double bond, which is not what is shown.'}],
 teach:'Aldo-keto reductase runs the reduction that alcohol dehydrogenase runs in reverse, converting aldehydes and ketones to alcohols. The clinical example is doxorubicin, whose ketone is reduced to the secondary alcohol doxorubicinol, and the alcohol is the species responsible for the cardiotoxicity. Metabolism here neither inactivates the drug nor prepares it for elimination but creates the toxicity, which is why reduction reactions cannot be assumed to be detoxifying.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 30–31'},

{id:'p1-13', prof:'Sikazwe', tier:'old', topic:'paths', sub:'red', concept:'azo-reduction-ident',
 tags:['structure','reaction-id','enzyme'], source:'slide', img:'rx_azo_sulfasalazine',
 stem:'What enzymes are implicated in the sulfasalazine reaction shown?',
 options:[
  {t:'Intestinal microbiota azo-reductases', correct:true,
   why:'The N=N azo bond is reduced and cleaved, releasing sulfapyridine and 5-aminosalicylic acid. Gut bacteria perform the reduction, which is why the active fragment is delivered to the colon.'},
  {t:'Hepatic CYP3A4', correct:false,
   why:'The reaction is reductive and bacterial, not an oxidation in the liver.'},
  {t:'Carboxylesterases (amidases)', correct:false,
   why:'The bond broken is N=N, not a carbonyl-containing linkage.'},
  {t:'Nitro-reductases', correct:false,
   why:'Nitro reduction converts -NO₂ to -NH₂. The starting material here has an azo bond instead.'}],
 teach:'Azo reduction splits a nitrogen-nitrogen double bond and yields two amines, one from each side. The enzymes belong to the intestinal microbiota rather than to the liver, so the reaction happens in the colon and depends on gut flora being present. Prontosil and sulfasalazine are the cases where this activates the drug, since neither parent is active until the azo bond is cleaved. A metabolite pair that together account for the whole parent structure, each carrying a new amine, identifies the reaction.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 32; Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 36'},

{id:'p1-14', prof:'Sikazwe', tier:'old', topic:'paths', sub:'red', concept:'nitro-reduction-ident',
 tags:['structure','reaction-id','enzyme'], source:'slide', img:'rx_chloramphenicol',
 stem:'What enzymes are implicated in the chloramphenicol reaction shown?',
 options:[
  {t:'Nitro-reductases, converting the nitro group to an amine', correct:true,
   why:'The -NO₂ on the ring becomes -NH₂. The reduction runs in three two-electron steps, nitro to nitroso to hydroxylamine to amine, so the whole conversion is a six-electron reduction, and the two middle species are the reactive ones. It passes through nitroso and hydroxylamine intermediates, the same reactive species implicated in nitrofurantoin toxicity.'},
  {t:'Azo-reductases, cleaving an N=N bond', correct:false,
   why:'There is no azo bond in chloramphenicol. The reduced group is a nitro substituent.'},
  {t:'Carboxylesterases, hydrolyzing the amide', correct:false,
   why:'The amide is unchanged in the product; only the nitro group is altered.'},
  {t:'CYP450, performing aromatic hydroxylation', correct:false,
   why:'No hydroxyl is added to the ring, and the change is a reduction rather than an oxidation.'}],
 teach:'Nitro reduction converts a nitro group to a primary amine, passing through nitroso and hydroxylamine intermediates on the way. The intermediates matter beyond bookkeeping, because a hydroxylamine is itself reactive and is one of the structural alerts in the toxicity material. So the same reduction that detoxifies by finishing at an amine can cause harm if it stalls at the middle. Recognising it from a structure is a matter of seeing an -NO2 in the parent and an -NH2 in the metabolite at the same position.',
 teachImg:'rx_nitro_chloramphenicol',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 33; PTI Study Aid Q1'},

{id:'p1-15', prof:'Sikazwe', tier:'old', topic:'paths', sub:'hyd', concept:'ce-four-substrates',
 tags:['enzyme','recall','exam-pattern'], source:'slide',
 stem:'Carboxylesterases hydrolyze which four functional groups?',
 options:[
  {t:'Esters, carbamates, amides and carbonates', correct:true,
   why:'All four carry a carbonyl with a heteroatom leaving group. When CEs act on amides they are also called amidases.'},
  {t:'Esters, epoxides, azo groups and nitro groups', correct:false,
   why:'Epoxides go to epoxide hydrolases, while azo and nitro groups are reduced rather than hydrolyzed.'},
  {t:'Alcohols, phenols, thiols and amines', correct:false,
   why:'These are conjugation targets for Phase 2 enzymes, not hydrolysis substrates.'},
  {t:'Ethers, thioethers, alkanes and alkenes', correct:false,
   why:'Ethers undergo O-dealkylation, thioethers are oxidized, and alkanes and alkenes are largely stable.'}],
 svg:DIA.acylFamily,
 teach:'Carboxylesterase hydrolyses four functional groups, and all four share the same carbonyl carbon with two substituents, so the products follow from what is attached. An ester gives a carboxylic acid and an alcohol. An amide gives a carboxylic acid and an amine. A carbamate gives an alcohol and an amine, losing carbon dioxide. A carbonate gives two alcohols, also losing carbon dioxide. Counting the heteroatoms on the carbonyl carbon and naming which ones they are gives the products without any further rule.',
 teachImg:'fgm_ester',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 35–38; Lecture #14 (MCMet-9_16_2026.pdf) slides 14–16'},

{id:'p1-16', prof:'Sikazwe', tier:'old', topic:'paths', sub:'hyd', concept:'procaine-hydrolysis',
 tags:['structure','reaction-id','enzyme'], source:'slide', img:'rx_procaine',
 stem:'Procaine yields 4-aminobenzoic acid and 2-(diethylamino)ethanol as shown. What phase, enzyme and process is this?',
 options:[
  {t:'Phase 1, carboxylesterase, ester hydrolysis', correct:true,
   why:'Splitting into an acid and an alcohol is the signature of ester hydrolysis. It is Phase 1 because it cleaves the molecule and exposes functional groups rather than attaching a conjugate.'},
  {t:'Phase 2, UGT, glucuronidation', correct:false,
   why:'Glucuronidation adds a sugar acid to the molecule. Here the molecule is cut into two smaller pieces and nothing is added.'},
  {t:'Phase 1, CYP450, oxidative dealkylation', correct:false,
   why:'Dealkylation removes an alkyl group from a heteroatom. This reaction breaks the ester carbon–oxygen bond and needs only water.'},
  {t:'Phase 2, GST, glutathione conjugation', correct:false,
   why:'GSH conjugation attaches the tripeptide to an electrophilic carbon and would increase molecular weight.'}],
 teach:'Procaine\'s short duration of action follows directly from its ester. That bond is cleaved by esterases in plasma and tissue to give para-aminobenzoic acid and diethylaminoethanol, neither of which is a local anaesthetic, so the drug\'s action ends as soon as hydrolysis occurs. An ester in a drug is therefore a design decision about duration as much as a functional group, and replacing it with an amide, as in lidocaine, gives a molecule that survives plasma esterases and lasts longer.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 35; PTI Study Aid Q4'},

{id:'p1-17', prof:'Sikazwe', tier:'old', topic:'paths', sub:'hyd', concept:'epoxide-hydrolase-function',
 tags:['enzyme','recall'], source:'slide',
 stem:'Epoxide hydrolases convert epoxides to:',
 options:[
  {t:'Alcohols', correct:true,
   why:'Water opens the strained three-membered ring to give a dihydrodiol. This is a detoxifying step, removing the electrophilic carbons.'},
  {t:'Ketones', correct:false,
   why:'No oxidation occurs; the ring opens by addition of water.'},
  {t:'Amines', correct:false,
   why:'No nitrogen is introduced.'},
  {t:'Glutathione conjugates', correct:false,
   why:'That is the parallel GST route for epoxides, not the EH reaction.'}],
 teach:'Epoxide hydrolase adds water across an epoxide and opens the three-membered ring, giving a molecule with two adjacent hydroxyl groups. The reaction is a detoxification, because the epoxide carbon is electrophilic and will otherwise be attacked by nucleophiles on protein and DNA. It is also saturable, and that is the limitation that matters clinically: at a high enough exposure the epoxide is produced faster than the enzyme can open it, and the surplus is left for glutathione S-transferase or for whatever macromolecule it reaches first.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 39'},

/* ======================= PHASE 2 (with images) ======================= */
{id:'p2-1', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'glucuronidation-ident',
 tags:['structure','reaction-id','cofactor'], source:'slide', img:'rx_apap_gluc',
 stem:'Acetaminophen reacts with the cosubstrate shown. What enzyme and cofactor are involved, and how is the product eliminated?',
 options:[
  {t:'UGT with UDPGA; renal', correct:true,
   why:'The sugar acid bearing the UDP leaving group is the giveaway. The product carries an ionized carboxylate, making it water soluble enough for urinary excretion.'},
  {t:'SULT with PAPS; biliary', correct:false,
   why:'A sulfate conjugate would add SO₃⁻ rather than a six-carbon sugar acid, and the cosubstrate shown carries UDP.'},
  {t:'GST with glutathione; biliary', correct:false,
   why:'A GSH conjugate attaches a tripeptide to an electrophilic carbon. Acetaminophen\'s phenol is nucleophilic and the cosubstrate is a sugar.'},
  {t:'NAT with acetyl-CoA; renal', correct:false,
   why:'Acetaminophen is already acetylated, and the reaction shown occurs at the phenolic oxygen rather than at nitrogen.'}],
 teach:'Glucuronidation is the widest Phase 2 route and the one to check first. UDP-glucuronosyltransferase is microsomal, its cofactor is UDP-glucuronic acid, and it accepts alcohols, carboxylic acids, aromatic amines and thiols. Bilirubin is its endogenous substrate, which is why a newborn with low UGT activity becomes jaundiced. The conjugate is recognisable from its structure: a six-carbon sugar carrying a carboxyl group, so the metabolite is both much larger than the parent and ionised at physiological pH, which is what makes it eliminable.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 46; PTI Study Aid Q6'},

{id:'p2-2', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'gsh-conjugation-ident',
 tags:['structure','reaction-id','cofactor'], source:'slide', img:'rx_cdnb_gsh',
 stem:'1-Chloro-2,4-dinitrobenzene is converted as shown, with GSSG as a byproduct. Which enzyme and cofactor?',
 options:[
  {t:'Glutathione S-transferase with glutathione', correct:true,
   why:'The chlorine is displaced and replaced by the glutathione sulfur, shown as SG. The two nitro groups make that ring carbon strongly electrophilic, which is exactly what GSTs target.'},
  {t:'UGT with UDP-glucuronic acid', correct:false,
   why:'Glucuronidation attaches a sugar acid to a nucleophilic group. Here a halogen on an electron-poor carbon is displaced.'},
  {t:'Methyltransferase with SAM', correct:false,
   why:'Methylation would add a single CH₃ group, not a tripeptide.'},
  {t:'Nitro-reductase with NADPH', correct:false,
   why:'The nitro groups are unchanged in the product; the reaction occurs at the carbon bearing chlorine.'}],
 teach:'Glutathione conjugation is the defence against electrophilic carbon, and its two target types are specific. Glutathione S-transferase acts on carbons bearing a halogen and on the carbons of an epoxide, both of which are electron-poor and open to attack. The cofactor is glutathione itself, a tripeptide whose cysteine sulfhydryl does the attacking. The conjugate is identified by the tripeptide appearing in the metabolite, often abbreviated as GS- or -SG, and the conjugate is later trimmed by peptidases and acetylated to the mercapturic acid that leaves in urine.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 49; PTI Study Aid Q7'},

{id:'p2-3', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'nac-mimics-gsh',
 tags:['mechanism','reasoning'], source:'both',
 stem:'N-Acetylcysteine (NAC) can substitute for glutathione because it:',
 options:[
  {t:'Carries a free nucleophilic thiol', correct:true,
   why:'The reactive part of glutathione (GSH) is the sulfhydryl on its cysteine residue. N-acetylcysteine (NAC) carries that same group, so it can attack the electrophile directly once glutathione stores are exhausted.'},
  {t:'Is converted to glucuronic acid', correct:false,
   why:'NAC is not a glucuronidation precursor. Its action is direct nucleophilic attack.'},
  {t:'Induces GST transcription', correct:false,
   why:'It works chemically and immediately, not through induction.'},
  {t:'Raises urine pH', correct:false,
   why:'That is the aspirin overdose strategy, a renal intervention.'}],
 teach:'Glutathione (GSH) is a tripeptide, and only one of its three residues does the chemistry: the cysteine in the middle carries a sulfhydryl, and sulfur is a soft nucleophile that attacks electron-poor carbon. Glutathione S-transferase (GST) uses it on two kinds of electrophilic carbon, the carbon bearing a halogen and the carbon of an epoxide. Acetaminophen (APAP) overdose makes both parts of that matter at once. At a normal dose the drug leaves as sulfate and glucuronide conjugates, but an overdose exhausts the sulfotransferases (SULTs) and glucuronosyltransferases (UGTs), so more of the drug goes through Phase 1 bioactivation to N-acetyl-p-benzoquinone imine (NAPQI), and NAPQI consumes glutathione until there is none left to deactivate it. N-acetylcysteine (NAC) is cysteine with an acetyl group on its nitrogen, so it brings the same free sulfhydryl without the rest of the tripeptide, and it restores the nucleophile rather than the enzyme. That is why the antidote works within the same chemistry rather than by changing how much enzyme is present.',
 teachImg:'tbl_ph2_b',
 note:'The class transcript records the professor giving glutathione’s residues as glutamine, cysteine and glycine. Glutathione is γ-glutamyl-cysteinyl-glycine, so the first residue is glutamate; the auto-caption is the likely source of the difference, and the cysteine sulfhydryl, which is the part the question turns on, is the same either way.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 50–51; Lecture #15 (MCMet-9_17_2026.pdf) slides 49, 63; lecture audio 09/10 (marked)',
 quote:'NAC - antidote for APAP toxicity · Electrophile deactivation by NAC'},

{id:'p2-4', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'nat-ident',
 tags:['structure','reaction-id','cofactor'], source:'slide', img:'rx_nat',
 stem:'Procainamide and celecoxib are converted to their N-acetyl products as shown. What cofactor is used?',
 options:[
  {t:'Acetyl-CoA', correct:true,
   why:'N-acetyltransferases transfer an acetyl group from acetyl-CoA onto a primary amine or a sulfonamide nitrogen. NAT2 is polymorphic, giving slow and fast acetylators.'},
  {t:'UDP-glucuronic acid', correct:false,
   why:'That would attach a sugar acid, which is not what appears in the products.'},
  {t:'PAPS', correct:false,
   why:'PAPS donates sulfate, giving a sulfate ester rather than an acetamide.'},
  {t:'S-adenosylmethionine', correct:false,
   why:'SAM donates a methyl group, a single carbon, not the two-carbon acetyl unit shown.'}],
 teach:'N-acetylation moves an acetyl group from acetyl coenzyme A onto a nitrogen, and it is the Phase 2 route that does not increase polarity. Its targets are primary amines, both alkyl and aryl, and sulfonamide nitrogens. NAT2 is polymorphic, splitting patients into slow and fast acetylators, which changes exposure to isoniazid, hydralazine and the sulfonamides. Because the acetamide product is often less water-soluble than the parent amine, this is the conjugation that can precipitate in the renal tubule, so it is the exception to the rule that Phase 2 makes elimination easier.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 53–54'},

{id:'p2-5', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'aa-conjugation-ident',
 tags:['structure','reaction-id','cofactor'], source:'slide', img:'rx_aaconj_benzoic',
 stem:'Benzoic acid is converted to hippuric acid as shown. What conjugation is this?',
 options:[
  {t:'Amino acid conjugation with glycine', correct:true,
   why:'Hippuric acid is the glycine conjugate of benzoic acid. The carboxylic acid is activated by acetyl-CoA before glycine is attached, so three cofactors are listed for this pathway.'},
  {t:'Glucuronidation with UDPGA', correct:false,
   why:'A glucuronide would attach a six-carbon sugar acid. The added fragment here is a two-carbon amino acid.'},
  {t:'Sulfation with PAPS', correct:false,
   why:'Sulfation requires an -OH and adds a sulfate ester. Benzoic acid has a carboxyl, not a hydroxyl.'},
  {t:'Glutathione conjugation with GSH', correct:false,
   why:'GSH conjugation needs an electrophilic carbon. A carboxylic acid is not one.'}],
 teach:'Amino acid conjugation attaches a whole amino acid, usually glycine or glutamine, to a carboxylic acid. The mechanism has an extra step the other conjugations lack: acetyl coenzyme A first activates the carboxyl group, and only then does acyl synthetase join the amino acid to it. Three cofactors are therefore listed rather than one. Benzoic acid conjugated with glycine to give hippuric acid is the classical case. Recognising it means finding an amide bond in the metabolite whose nitrogen side is a recognisable amino acid.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 55–56'},

{id:'p2-6', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'gluc-vs-sulf-targets',
 tags:['reaction-id','cofactor'], source:'slide', img:'rx_gluc_sulf',
 stem:'The two conjugations shown use, respectively:',
 options:[
  {t:'UGT/UDPGA and SULT/PAPS', correct:true,
   why:'Both act on hydroxyl groups, which is why they compete for the same substrate. Acetaminophen forms both, and the balance between them is what shifts in overdose.'},
  {t:'UGT/UDPGA for both', correct:false,
   why:'The products differ chemically: one carries a sugar acid, the other a sulfate ester.'},
  {t:'GST/GSH and NAT/acetyl-CoA', correct:false,
   why:'Neither product contains a tripeptide or an acetamide.'},
  {t:'Phase 1 oxidation for both', correct:false,
   why:'Both attach a polar group to an existing handle, which defines Phase 2 conjugation.'}],
 teach:'Two Phase 2 reactions compete for the same hydroxyl, and the cofactor is what tells them apart. UDP-glucuronosyltransferase (UGT) draws on uridine-5’-diphospho-D-glucuronic acid (UDPGA) and transfers glucuronic acid, a six-carbon sugar carrying a carboxyl group, so the conjugate is bulky and charged. Sulfotransferase (SULT) draws on 3’-phosphoadenosine-5’-phosphosulfate (PAPS) and transfers a sulfate, which is small and charged. Neither reaction runs at all without its cofactor, so naming the cofactor is how you name the enzyme from a structure alone. Slide 48 pairs one example with each enzyme: morphine goes to morphine-6-O-glucuronide under UGT, and labetalol goes to labetalol sulfate under SULT. Morphine-6-glucuronide is more potent than morphine itself, so a conjugation step can raise activity rather than end it. The two enzymes also accept different handles. UGT takes hydroxyl, carboxyl, amino and thiol groups. SULT takes alkyl and aryl alcohols and, on Lecture 11 slide 47, aromatic amines as well.',
 teachImg:'tbl_ph2_a',
 note:'Two slides list sulfotransferase substrates differently. Lecture 11 slide 47 prints "Alkyl- & Ar-alcohols · Aromatic amines", and the 09/10 lecture said the same aloud. The cofactor table on Lecture 14 slide 29 abbreviates the entry to -OH. Both are printed, so know both: an alcohol is the common case, and an aromatic amine can also be sulfated.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 46–48; cofactor table in Lecture #14 (MCMet-9_16_2026.pdf) slide 29',
 quote:'-OH; -CO2H; -NH2; -SH · UDP-Glucuronosyl transferases (UGTs) · Uridine-5’-diphospho-D-glucuronic Acid (UDPGA) · Glucuronide // -OH · Sulfotransferases (STs/SULTs) · 3’-Phosphoadenosine-5’-phosphosulfate (PAPS) · Sulfate'},

{id:'p2-7', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'tamoxifen-two-enzymes',
 tags:['structure','reaction-id','enzyme'], source:'slide', img:'rx_tamoxifen',
 stem:'Tamoxifen is converted to the N-oxide shown. What two enzymes can facilitate this?',
 options:[
  {t:'Flavin-containing monooxygenase and CYP450', correct:true,
   why:'FMO is the primary N-oxidizing enzyme, and the deck notes explicitly that CYPs can carry out N-oxidations as well. Overlapping capability is common between these two oxidase systems.'},
  {t:'Monoamine oxidase and aldehyde dehydrogenase', correct:false,
   why:'MAO performs oxidative deamination on primary amines and gives an aldehyde, not an N-oxide on a tertiary amine.'},
  {t:'Carboxylesterase and epoxide hydrolase', correct:false,
   why:'Both are hydrolases. No bond is hydrolyzed here; an oxygen is added to nitrogen.'},
  {t:'UGT and sulfotransferase', correct:false,
   why:'These are Phase 2 conjugating enzymes and would attach a large polar group.'}],
 teach:[
  {h:'What an N-oxide is',
   t:'Tamoxifen carries a tertiary amine, a nitrogen with three carbons and one lone pair. N-oxidation puts an oxygen on that lone pair, giving the N-oxide drawn on the slide: the nitrogen keeps all three carbons and gains an oxygen, so nothing is removed from the molecule. That separates it from N-dealkylation, where a carbon next to the nitrogen is oxidised and an alkyl group leaves.'},
  {h:'Two enzymes for one reaction',
   t:'Lecture 11 slide 26 gives flavin-containing monooxygenase as the enzyme that oxidises tertiary amines and amides to N-oxides and sulfur to sulfoxides and sulfones, with the note that its products are not affected by CYP450 inhibitors. Slide 27 adds the note that CYPs can facilitate N-oxidations too. So a drug N-oxidised mainly by FMO keeps that route when a CYP inhibitor is present, and the prep sheet asks for both enzymes by name.'}],
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 26–27; Ex4-Prep-Work question 3',
 quote:'FMO oxidation of Amines (Note: CYPs can facilitate N-oxidations, too)'},

{id:'p2-8', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'phase2-enzyme-list',
 tags:['recall'], source:'slide',
 stem:'Which set lists the Phase 2 conjugating enzyme families?',
 options:[
  {t:'UGTs, SULTs, GSTs, NATs, acyl synthetase and methyltransferases', correct:true,
   why:'These six cover the conjugation reactions: glucuronidation, sulfation, glutathione conjugation, N-acetylation, amino acid conjugation and methylation.'},
  {t:'CYP450, FMO, MAO, ADH, ALDH and AKR', correct:false,
   why:'These are Phase 1 oxidases and reductases.'},
  {t:'Carboxylesterase, epoxide hydrolase, azo-reductase and nitro-reductase', correct:false,
   why:'These are Phase 1 hydrolytic and reductive enzymes.'},
  {t:'Xanthine oxidase, DPD and NQO1', correct:false,
   why:'These are the functional-group-specific enzymes from the Lecture #14 material, and they are oxidoreductases rather than transferases.'}],
 teach:'Six families carry out Phase 2, and each one is a transferase named for what it transfers rather than for what it acts on. UDP-glucuronosyltransferases (UGTs) transfer glucuronic acid, sulfotransferases (STs or SULTs) transfer sulfate, glutathione S-transferases (GSTs) transfer glutathione, N-acetyltransferases (NATs) transfer an acetyl group, acylsynthatases transfer an amino acid, and methyltransferases (MTs, such as catechol-O-methyltransferase and thiopurine methyltransferase) transfer a methyl group. Reading the name backwards gives the reaction, so the six enzymes and the six reactions are one list learned once. The distractors here are all Phase 1: the oxidases and reductases, the hydrolytic and reductive enzymes, and the functional-group-specific oxidoreductases. What separates the two phases is the direction of the chemistry, since a Phase 1 enzyme alters the drug itself while a Phase 2 transferase attaches a molecule the body supplies.',
 teachImg:'tbl_ph2_b',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 43, 45, 62; cofactor tables in Lecture #14 (MCMet-9_16_2026.pdf) slides 29–30',
 quote:'UGTs = Uridine Diphosphate Glucuronosyl Transferases · STs or SULTs = Sulfotransferases · GSTs = Glutathione S-transferases · NAT = N-Acetyltransferases · Acylsynthatases · MTs = Methyltransferases (e.g., COMT, TPMT)'},

/* ======================= FUNCTIONAL GROUPS ======================= */
{id:'fgg-1', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'acyl', concept:'ester-vs-amide-recognition',
 tags:['structure','exam-pattern'], source:'slide',
 stem:'At the carbonyl carbon, an ester bears ______ and an amide bears ______.',
 options:[
  {t:'oxygen; nitrogen', correct:true,
   why:'This single check also separates the whole family: carbamate has both an O and an N, and carbonate has two oxygens. The heteroatom pattern predicts the hydrolysis products.'},
  {t:'a ring; no ring', correct:false,
   why:'Neither group requires or excludes a ring.'},
  {t:'no C=O; a C=O', correct:false,
   why:'Both have a C=O. That is what makes them carbonyl compounds.'},
  {t:'a charge; no charge', correct:false,
   why:'Neither group is ionizable at physiological pH. Carboxylic acids and amines are.'}],
 svg:DIA.acylFamily,
 teach:'An ester and an amide differ by one atom on the carbonyl carbon, and everything else follows from it. The ester carries an oxygen, so hydrolysis gives a carboxylic acid and an alcohol. The amide carries a nitrogen, so hydrolysis gives a carboxylic acid and an amine. The amide is also the more stable of the two, because the nitrogen lone pair delocalises into the carbonyl and strengthens the carbon-nitrogen bond, which is why procaine with its ester is short-acting while lidocaine with its amide is not. Reading the atom attached to the carbonyl carbon therefore predicts both the products and the rough stability.',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 48, 50, 52; Sikazwe PTI study aid review list'},

{id:'fgg-2', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'n', concept:'amine-classification',
 tags:['structure','reasoning'], source:'slide',
 stem:'Amine class (1o, 2o, 3o) matters to metabolism because it determines:',
 options:[
  {t:'Deamination versus N-dealkylation', correct:true,
   why:'Counting the carbons on nitrogen tells you the reaction. A primary amine has a hydrogen-bearing nitrogen suited to deamination, while substituted nitrogens have alkyl groups available for removal.'},
  {t:'Which amines are basic', correct:false,
   why:'All three classes are basic. Basicity varies with substitution but is not confined to tertiary amines.'},
  {t:'Which amines are conjugated', correct:false,
   why:'NAT targets primary amines specifically, but UGTs and methyltransferases act on amines more broadly.'},
  {t:'Whether the drug is absorbed', correct:false,
   why:'Oral absorption depends on lipophilicity, size and transport, not on amine class alone.'}],
 teach:'Amines are classified by how many carbons are on the nitrogen, not by how many carbons the molecule has. A primary amine carries one, a secondary two, a tertiary three, and a quaternary ammonium four, which leaves the nitrogen permanently charged. The class determines which reactions apply: primary amines are the targets for N-acetylation, tertiary amines and amides form N-oxides under flavin-containing monooxygenase, and a quaternary nitrogen cannot be neutralised at any pH, so it does not cross into the central nervous system by passive diffusion. Counting substituents on the nitrogen is therefore the first step in predicting a nitrogen-containing drug\'s fate.',
 teachImg:'fgm_amine',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 10; functional group deck'},

{id:'fgg-3', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'sulf', concept:'sulfur-fg-fates',
 tags:['structure','reasoning'], source:'slide',
 stem:'A free thiol (-SH) can undergo:',
 options:[
  {t:'FMO oxidation, glucuronidation and methylation', correct:true,
   why:'The thiol is both oxidizable and nucleophilic. FMO oxidizes thiols, UGT lists -SH among its substrates, and methyltransferases target -OH, -NH₂ and -SH.'},
  {t:'Carboxylesterase hydrolysis only', correct:false,
   why:'CEs need a carbonyl-containing linkage. A free thiol offers none.'},
  {t:'Epoxide hydrolase activity only', correct:false,
   why:'EH requires an epoxide ring.'},
  {t:'No metabolism', correct:false,
   why:'Sulfur groups are among the more reactive handles, which is why they appear in several pathways.'}],
 teach:'Sulfur appears in several oxidation states and each has its own enzyme. A thiol can be methylated by a methyltransferase using S-adenosylmethionine, glucuronidated by UDP-glucuronosyltransferase, or oxidised by flavin-containing monooxygenase. A thioether can be S-dealkylated by cytochrome P450 or oxidised through the sulfoxide to the sulfone. The oxidation ladder runs sulfide to sulfoxide to sulfone, adding one oxygen at each step, so naming the metabolite is a matter of counting oxygens on the sulfur. Sulfur is also where dimercaprol\'s activity lies, which is why methylating its thiols removes the drug\'s ability to bind metals.',
 teachImg:'fgm_thioether_ox',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 28, 46, 57; Lecture #14 (MCMet-9_16_2026.pdf) slides 18–19'},

{id:'fgg-4', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'acyl', concept:'fg-predicts-pathway',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'A drug carries a single carboxylic acid group and nothing else reactive. Which Phase 2 routes are open to it?',
 options:[
  {t:'Glucuronidation and amino acid conjugation', correct:true,
   why:'UGTs list -CO₂H among their substrates, and acyl synthetase acts specifically on carboxylic acids to form glycine or glutamine conjugates. No other Phase 2 enzyme targets a carboxyl.'},
  {t:'Sulfation and methylation', correct:false,
   why:'SULTs need an -OH or an aromatic amine, and methyltransferases need -OH, -NH₂ or -SH.'},
  {t:'Glutathione conjugation and N-acetylation', correct:false,
   why:'GST needs an electrophilic carbon and NAT needs a nitrogen. A carboxylic acid supplies neither.'},
  {t:'None, since carboxylic acids are excreted unchanged', correct:false,
   why:'Carboxylic acids have two available conjugation routes and are described as undergoing a variety of biotransformations.'}],
 teach:'A functional group predicts its own metabolic route, which is what makes structure reading the whole skill. A hydroxyl invites glucuronidation, sulfation or methylation. A carboxylic acid invites glucuronidation or amino acid conjugation. A primary amine invites acetylation. An epoxide or a halogen-bearing carbon invites glutathione conjugation. An ester or amide invites carboxylesterase. Working from the structure rather than from a memorised list of drugs means a drug never seen before can still be placed, because the groups it carries are the same groups the course has already assigned to enzymes.',
 teachImg:'tbl_ph2_a',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 13, 29; Lecture #11 (MCMet-9_10_26.pdf) slides 46, 55',
 note:'Working backwards from the functional group to the enzyme is the pattern behind most of the prep sheet questions.'}
);

QUESTIONS.push(
{id:'p2-9', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'cofactor-ugt',
 tags:['cofactor'], source:'slide', teachImg:'tbl_ph2_a',
 stem:'Which enzyme and co-factor pair carries out glucuronidation?',
 options:[
  {t:'UDP-glucuronosyl transferases (UGTs) with UDPGA', correct:true,
   why:'UGT is the enzyme and uridine-5\u2032-diphospho-D-glucuronic acid (UDPGA) is the co-factor that carries the sugar. UGT accepts -OH, -CO2H, -NH2 and -SH groups, which is the widest substrate range of any phase II enzyme.'},
  {t:'UGTs with PAPS', correct:false,
   why:'PAPS is 3\u2032-phosphoadenosine-5\u2032-phosphosulfate, which carries a sulfate, not glucuronic acid. Pairing UGT with PAPS mixes the enzyme of one row with the co-factor of another.'},
  {t:'Sulfotransferases (STs) with UDPGA', correct:false,
   why:'Same mismatch in reverse. STs are real enzymes but they use PAPS.'},
  {t:'Methyltransferases with SAM', correct:false,
   why:'This pair is correct in itself, but it produces a methylated product rather than a glucuronide.'}],
 teach:'Each phase II row pairs one enzyme with one co-factor, and exam distractors are built by shuffling them. Read the co-factor name for the group it carries: UDPGA carries glucuronic acid, PAPS carries sulfate, SAM carries a methyl, acetyl CoA carries an acetyl. The co-factor names the product.',
 cite:'MCMet-9_16_2026.pdf slide 29'},

{id:'p2-10', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'cofactor-sult',
 tags:['cofactor'], source:'slide', teachImg:'tbl_ph2_a',
 stem:'Sulfotransferases (STs/SULTs) transfer sulfate from which co-factor, and onto which functional group?',
 options:[
  {t:'PAPS, onto -OH', correct:true,
   why:'3\u2032-Phosphoadenosine-5\u2032-phosphosulfate (PAPS) is the sulfate donor, and the table lists -OH as the accepting group. Sulfation is high affinity but low capacity, which is why it saturates first in an acetaminophen overdose.'},
  {t:'UDPGA, onto -OH', correct:false,
   why:'UDPGA is the glucuronidation co-factor. The accepting group is right but the donor is wrong.'},
  {t:'PAPS, onto -CO2H', correct:false,
   why:'The donor is right but -CO2H is the group handled by acylsynthatases in amino acid conjugation.'},
  {t:'SAM, onto -SH', correct:false,
   why:'SAM does donate a methyl to -SH among other groups, but that is methylation, not sulfation.'}],
 teach:'Sulfation and glucuronidation compete for the same -OH group. Sulfation binds more tightly but runs out of PAPS quickly, so at low dose the sulfate predominates and at higher dose the glucuronide takes over. That capacity difference is the basis of dose-dependent toxicity.',
 cite:'MCMet-9_16_2026.pdf slide 29'},

{id:'p2-11', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'cofactor-aa',
 tags:['cofactor'], source:'slide', teachImg:'tbl_ph2_a',
 stem:'Amino acid conjugation acts on which functional group, using which enzyme and cofactors?',
 options:[
  {t:'-CO2H; acylsynthetase, acetyl CoA + glycine/glutamine', correct:true,
   why:'The carboxylic acid is activated as an acyl CoA thioester first, then the amino acid nitrogen attacks it. Two components are needed, the CoA and the amino acid, which is why this row lists more than one co-factor.'},
  {t:'-CO2H; UGT, UDPGA', correct:false,
   why:'A carboxylic acid can be glucuronidated, giving an acyl glucuronide, but that is a different row and gives a different product.'},
  {t:'-NH2; NAT, acetyl CoA', correct:false,
   why:'That row is real, but it is N-acetylation of an amine. Acetyl CoA appears in both rows, which is what makes this distractor work.'},
  {t:'-SH; GST, glutathione', correct:false,
   why:'GST uses glutathione as the nucleophile and attacks electrophilic centres such as R-X and epoxides.'}],
 teach:'Acetyl CoA appears in two different phase II rows. In N-acetylation it donates the acetyl group to an amine. In amino acid conjugation it activates the drug\u2019s own carboxylic acid so an amino acid can be attached. Reading which group is being modified separates them.',
 cite:'MCMet-9_16_2026.pdf slides 29–30'},

{id:'p2-12', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'cofactor-gst',
 tags:['cofactor'], source:'slide', teachImg:'tbl_ph2_b',
 stem:'Glutathione S-transferases act on which substrates, and what is the conjugate called?',
 options:[
  {t:'R-X and epoxides; the product is a glutathione-S conjugate', correct:true,
   why:'Both substrates carry an electron-poor carbon. Glutathione supplies a thiol that attacks that carbon and displaces the leaving group or opens the ring, giving a glutathione-S conjugate that is then processed to a mercapturic acid.'},
  {t:'-OH and -CO2H; the product is a glucuronide', correct:false,
   why:'Those groups and that product belong to the UGT row.'},
  {t:'-NH2 only; the product is an N-acetylated amine', correct:false,
   why:'That is the NAT row, which uses acetyl CoA.'},
  {t:'-OH, -NH2 and -SH; the product is methylated', correct:false,
   why:'Those groups and that product belong to the methyltransferase row, which uses SAM.'}],
 teach:'GST is the only phase II enzyme whose listed substrates are defined by reactivity rather than by a named functional group. R-X and epoxide both describe an electrophilic carbon, which is why this enzyme is the front-line defense against reactive metabolites and why its co-factor gets consumed during toxicity.',
 cite:'MCMet-9_16_2026.pdf slide 30'},

{id:'p2-13', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'cofactor-sam',
 tags:['cofactor'], source:'slide', teachImg:'tbl_ph2_b',
 stem:'Methyltransferases accept which groups, and what is the methyl donor?',
 options:[
  {t:'-OH, -NH2 and -SH; the donor is S-adenosyl methionine (SAM)', correct:true,
   why:'SAM carries a reactive methyl on a positively charged sulfur, and all three of those groups have a lone pair that can attack it. Methylation is unusual among phase II reactions because the product is often less water soluble than the parent.'},
  {t:'-OH and -CO2H; the donor is UDPGA', correct:false,
   why:'UDPGA donates glucuronic acid, not a methyl.'},
  {t:'-NH2 only; the donor is acetyl CoA', correct:false,
   why:'That describes N-acetylation. Acetyl CoA transfers an acetyl group, which is larger than a methyl and blocks the nitrogen differently.'},
  {t:'R-X and epoxides; the donor is glutathione', correct:false,
   why:'That is the GST row, and glutathione is a nucleophile rather than a methyl donor.'}],
 teach:'Most phase II reactions add a large polar group and raise water solubility. Methylation and acetylation are the exceptions: both cap a polar hydrogen-bond donor and can make the metabolite less soluble. That is the basis of the isoniazid and sulfonamide precipitation problems.',
 cite:'MCMet-9_16_2026.pdf slide 30'},

{id:'p2-14', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'cofactor-list',
 tags:['cofactor'], source:'prep', teachImg:'tbl_ph2_a',
 stem:'List all phase II enzyme co-factors.',
 options:[
  {t:'UDPGA, PAPS, acetyl CoA (with an amino acid), glutathione, SAM', correct:true,
   why:'These are the five donors across the six rows: UDPGA for glucuronidation, PAPS for sulfation, acetyl CoA for both N-acetylation and amino acid conjugation, glutathione for GST, and SAM for methylation.'},
  {t:'NADPH, FAD, UDPGA, PAPS, SAM', correct:false,
   why:'NADPH and FAD supply reducing equivalents to phase I enzymes such as CYP and FMO. They are not conjugation donors.'},
  {t:'UDPGA, PAPS, SAM, NADPH, oxygen', correct:false,
   why:'NADPH and molecular oxygen are the two things a CYP needs, which makes this a phase I list.'},
  {t:'Glutathione, glycine, glutamine, cysteine, taurine', correct:false,
   why:'Glycine and glutamine are the amino acids attached in amino acid conjugation, but listing them alone omits the enzymes\u2019 activating co-factors and leaves out UDPGA, PAPS and SAM.'}],
 teach:'The separation that matters is between phase I co-substrates, which supply electrons or oxygen, and phase II co-factors, which supply the group being attached. NADPH and O2 belong to phase I; UDPGA, PAPS, acetyl CoA, glutathione and SAM belong to phase II.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 29–30; Ex4-Prep-Work.pdf question 7'}
);
