/* Second and third wordings for high-yield concepts, so a missed concept
   returns as a different question rather than the identical item (rules 2 and 6). */
QUESTIONS.push(
/* ---- CYP ---- */
{id:'v-cyp-y1b', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'cycle', concept:'cyp-cycle-requirements',
 tags:['mechanism','cofactor'], source:'slide',
 stem:'A microsomal preparation contains CYP450, CYP450 reductase and molecular oxygen, but no oxidation occurs. What is most likely missing?',
 options:[
  {t:'NADPH, the electron donor', correct:true,
   why:'Four ingredients are required and three are present. NADPH supplies the two electrons the cycle consumes, so without it the ferric iron is never reduced to the ferrous form and the sequence stops at the first step, with the drug bound but unchanged.'},
  {t:'Glutathione', correct:false,
   why:'Glutathione is the cofactor for glutathione S-transferase in Phase 2 and the nucleophile that deactivates electrophiles, MCMet-9_17_2026.pdf slide 60. It acts on products of CYP reactions rather than taking part in the oxidation itself.'},
  {t:'PAPS', correct:false,
   why:'3-phosphoadenosine-5-phosphosulfate is the sulfate donor for sulfotransferases, a Phase 2 conjugation cofactor. Nothing in the CYP cycle transfers a sulfate.'},
  {t:'Epoxide hydrolase', correct:false,
   why:'Epoxide hydrolase opens epoxides that CYP oxidation has already produced, so it acts after this cycle rather than within it, and its absence would raise toxicity rather than stop the reaction.'}],
 teach:'The catalytic cycle needs four things and each has one job: the CYP enzyme holds the drug and the iron, molecular oxygen supplies the atom that ends up in the product, NADPH supplies the two electrons, and CYP450 reductase carries those electrons from NADPH to the iron. Removing any one stops the cycle, but at different points. Without NADPH the first reduction never happens, since only the ferrous form binds oxygen. Without the reductase the electrons exist but cannot reach the iron. Without oxygen the enzyme can be reduced but has nothing to insert. Reading a question of this kind means identifying which of the four is absent and which step that blocks.',
 teachImg:'cyp_catalytic_cycle',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 11–12',
 quote:'Reaction requirements/ingredients: CYP450 · CYP450 Reductase · NADPH (e- donor) · Molecular Oxygen (O2)'},

{id:'v-cyp-e1b', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'expr', concept:'cyp3a4-dominance',
 tags:['reasoning'], source:'slide',
 stem:'A new drug is a substrate of a single CYP isoform. Which isoform would make drug interactions most likely, simply because so many other drugs use it?',
 options:[
  {t:'CYP3A4', correct:true,
   why:'CYP3A4 and CYP3A5 together clear about 30 percent of clinical drugs, the largest share of any isoform, and CYP3A4 also sits in the intestinal wall as well as the liver. A larger substrate pool means more drugs competing at the same site and more inducers and inhibitors that reach it.'},
  {t:'CYP1A2', correct:false,
   why:'CYP1A2 accounts for about 9 percent of clinical drugs and takes a narrower set of substrates, chiefly aryl amines and flat heterocyclic compounds such as caffeine, imipramine and haloperidol. Interactions do occur, notably with tobacco smoke as an inducer, but from a smaller pool.'},
  {t:'CYP2E1', correct:false,
   why:'CYP2E1 mainly handles environmental chemicals such as ethanol and halogenated hydrocarbons, and about 3 percent of clinical drugs. It matters more for toxicity, through acetaminophen and halogenated solvents, than for routine interaction risk.'},
  {t:'CYP2C19', correct:false,
   why:'CYP2C19 clears about 7 percent of clinical drugs. It is heavily polymorphic, so it is a large source of between-patient variation, but that is a different kind of risk from the sheer number of co-prescribed substrates.'}],
 teach:'Interaction likelihood follows the size of the substrate pool, which is why CYP3A4 dominates this question rather than any property of the enzyme itself. Two separate measures are attached to isoforms and they answer different questions. Share of liver CYP protein says how much enzyme is present. Share of clinical drugs says how much of the prescribing load it carries, and that is the figure that predicts collisions. CYP2D6 shows why the two must be kept apart: it is a small fraction of liver CYP yet clears about 20 percent of clinical drugs, so it saturates easily and is a frequent interaction site despite being scarce.',
 teachImg:'cyp_drug_share',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 16, 30',
 quote:'1/3 of liver CYP isoforms & metabolizes 1/3 of drugs'},

{id:'v-cyp-i2b', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'indinh', concept:'inhibitor-recognition',
 tags:['recall','induction'], source:'slide',
 stem:'A patient on a narrow therapeutic index CYP substrate starts rifampin. Expected substrate levels?',
 options:[
  {t:'Fall over several days', correct:true,
   why:'Rifampin induces a wide range of isoforms, 2C8, 2C9, 2C19, 2D6, 3A4 and 2B6. Induction works by increasing how much enzyme the cell makes, so the effect builds as new protein is synthesized and fades over days after the drug is stopped.'},
  {t:'Rise immediately', correct:false,
   why:'That is the pattern for an inhibitor such as clarithromycin, erythromycin or an azole antifungal, where enzyme already present is blocked and concentrations move within a dose or two. Rifampin sits on the inducer list and moves them the other way.'},
  {t:'Unchanged', correct:false,
   why:'Its antibacterial target is bacterial RNA polymerase, so the premise is understandable, but rifampin also induces human drug-metabolizing enzymes. That second action is the source of its interaction profile.'},
  {t:'Fall within an hour', correct:false,
   why:'The direction is right and the timing is wrong. Induction requires transcription and protein synthesis, so it takes days to develop; an effect within an hour points to inhibition instead.'}],
 teach:'Induction and inhibition differ in what they change, how fast, and how they reverse, and those three differences identify which is operating. Induction changes the number of enzyme molecules, takes days to build and days to fade. Inhibition changes the activity of enzyme already present and appears with the first doses. For a narrow therapeutic index substrate both directions are dangerous, and the switchover is more dangerous still: a dose raised to overcome an inducer becomes an overdose once that inducer is removed and the extra enzyme is degraded. The clozapine case on slide 58 is that exact sequence.',
 teachImg:'cyp_inducer_table',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 32–33',
 quote:'Many DIs due to induction/inhibition'},

{id:'v-cyp-p7b', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'poly', concept:'active-vs-prodrug-direction-rule',
 tags:['reasoning','case'], source:'both',
 stem:'A prodrug is activated by CYP2D6. In an ultrarapid metabolizer, expect:',
 options:[
  {t:'More active metabolite; more toxicity', correct:true,
   why:'For a prodrug the enzyme makes the active species, so more enzyme activity means more of it. The direction is the reverse of the intuition built on active drugs, where faster metabolism means less effect.'},
  {t:'Less active metabolite; drug failure', correct:false,
   why:'That is the poor metabolizer outcome for the same prodrug, and it is the codeine failure case. Both belong to the same column of the grid; only the enzyme activity differs.'},
  {t:'Parent drug accumulation; toxicity', correct:false,
   why:'Accumulation of parent drug is what happens when an active drug meets reduced enzyme activity, the warfarin and glyburide situation. Here conversion is faster, so the parent is cleared more quickly rather than building up.'},
  {t:'No change', correct:false,
   why:'Prodrugs are the drugs most affected by phenotype, because the enzyme-dependent step is the one that creates activity rather than the one that ends it. That is why codeine and clopidogrel carry warnings tied to metabolizer status.'}],
 teach:'Two questions settle every case of this kind. First, is the drug active as given or does it need conversion? Second, is enzyme activity higher or lower than normal? Those combine into four outcomes. An active drug with reduced activity gives more effect, and with raised activity gives less. A prodrug reverses both: reduced activity gives less effect, raised activity gives more. Phenotype and interaction enter the same grid, since an inhibitor imitates a poor metabolizer and an inducer imitates an ultrarapid one. Knowing which species carries the activity is what makes the prediction possible, and it is the step most often skipped.',
 teachImg:'cyp_prodrug_grid',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 41–42, 47',
 quote:'Drug exposure under UM & PM conditions'},

{id:'v-cyp-p2b', prof:'Sikazwe', tier:'new', topic:'cyp', sub:'poly', concept:'poly-prodrug-direction',
 tags:['case','polymorphism'], source:'slide',
 stem:'A CYP2D6 poor metabolizer takes codeine (O-demethylated to morphine) for pain. Most likely outcome?',
 options:[
  {t:'Little morphine; poor pain relief', correct:true,
   why:'Codeine depends on conversion for most of its analgesic effect, and CYP2D6 performs that O-demethylation. A poor metabolizer makes little morphine, so the patient takes the drug exactly as directed and still has pain.'},
  {t:'Excess morphine; oversedation', correct:false,
   why:'That is the ultrarapid metabolizer outcome for the same drug, and it is the more dangerous one, since respiratory depression rather than treatment failure is the result. Same drug, opposite end of the phenotype range.'},
  {t:'Normal effect; codeine is active', correct:false,
   why:'Codeine has little analgesic activity of its own; the morphine it becomes does the work. A drug that is active as given, such as warfarin, behaves the opposite way under reduced enzyme activity and accumulates instead.'},
  {t:'Hypersensitivity reaction', correct:false,
   why:'Polymorphism changes how much active species is produced, which is a quantitative effect. Hypersensitivity is an immune response and is unrelated to metabolizer status.'}],
 teach:'Codeine and tramadol behave alike because both depend on CYP2D6 to remove a methyl group from an oxygen, and both produce a metabolite more active than the parent: codeine becomes morphine, tramadol becomes O-desmethyltramadol. In a poor metabolizer the conversion fails and the drug fails with it, which presents as a patient reporting no benefit rather than as an adverse event. The same enzyme and the same chemistry in an ultrarapid metabolizer produce too much active opioid instead. CYP2D6 is a small share of liver CYP yet clears about 20 percent of clinical drugs and cannot be induced much, which is why phenotype rather than dose adjustment governs the outcome.',
 teachImg:'cyp_prodrug_grid',
 cite:'Lecture #13 (MCMet-9_15_2026.pdf) slides 26, 42, 47',
 quote:'Polymorphic phenotypes: UM; EM; IM; PM'},

/* ---- Phase 2 cofactors ---- */
{id:'v-fg-11b', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'ugt-substrates',
 tags:['cofactor','reasoning'], source:'slide',
 stem:'Which Phase 2 enzyme has the broadest range of target functional groups?',
 options:[
  {t:'UDP-glucuronosyltransferase', correct:true,
   why:'Its entry on slide 29 lists four targets, -OH, -CO2H, -NH2 and -SH, more than any other row in the table. All four are nucleophilic, which is what the reaction requires, and that breadth makes glucuronidation the most widely available conjugation route.'},
  {t:'N-acetyltransferase', correct:false,
   why:'N-acetyltransferase lists a single target, -NH2, with acetyl coenzyme A as cofactor. It is clinically important through acetylator status rather than through range.'},
  {t:'Acyl synthetase', correct:false,
   why:'Acyl synthetase also takes one group, -CO2H, and is the only entry needing two components: acetyl coenzyme A to activate the acid plus the amino acid being attached.'},
  {t:'Glutathione S-transferase', correct:false,
   why:'Its targets are R-X and epoxide, which is a narrow range and also a different electronic class. It is the one enzyme here acting on electrophiles rather than nucleophiles.'}],
 teachImg:'tbl_ph2_a',
 teach:'Breadth follows from what the reaction needs. Glucuronidation asks only that the substrate be nucleophilic enough to attack the activated sugar of UDP-glucuronic acid, and -OH, -CO2H, -NH2 and -SH all qualify, so one enzyme covers four groups. Methylation is next with three. The narrower enzymes are narrow because they are more particular: sulfation takes -OH only, acetylation -NH2 only, amino acid conjugation -CO2H only. Glutathione S-transferase is narrow for a different reason, since it works in the opposite direction and needs an electron-poor substrate. Breadth is also why glucuronidation is often the route that saturates last.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 29',
 quote:'-OH; -CO2H; NH2; -SH | UDP-Glucuronosyl transferases (UGTs)'},

{id:'v-fg-12b', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'papso4-cofactor',
 tags:['cofactor','matching'], source:'slide',
 stem:'A drug forms a sulfate conjugate. Which enzyme and cofactor were involved, and where in the cell?',
 options:[
  {t:'Sulfotransferase with PAPS, in the cytosol', correct:true,
   why:'Sulfotransferase transfers sulfate from 3-phosphoadenosine-5-phosphosulfate to an -OH group, and it is a cytosolic enzyme. Its location separates it from the microsomal enzymes and explains why it and glucuronidation compete for the same hydroxyl from different compartments.'},
  {t:'UGT with UDPGA, in the endoplasmic reticulum', correct:false,
   why:'The location is right for that enzyme, since UDP-glucuronosyltransferase is microsomal, but the product would be a glucuronide rather than a sulfate. The two routes compete for the same -OH, which is what makes them easy to interchange.'},
  {t:'GST with glutathione, in the cytosol', correct:false,
   why:'Glutathione S-transferase is indeed cytosolic, so the location fits, but it attaches glutathione to an electrophilic centre. Its targets are R-X and epoxide rather than a hydroxyl.'},
  {t:'Methyltransferase with SAM, in the mitochondria', correct:false,
   why:'Methyltransferase uses S-adenosylmethionine and transfers a methyl group, so neither the cofactor nor the product matches a sulfate conjugate.'}],
 teachImg:'tbl_ph2_a',
 teach:'Sulfation and glucuronidation share a substrate and differ in almost everything else. Sulfotransferase is cytosolic and uses PAPS; UDP-glucuronosyltransferase sits in the endoplasmic reticulum and uses UDP-glucuronic acid. The practical difference is capacity: the PAPS pool is limited, so sulfation saturates at lower doses and traffic shifts to glucuronidation, and when that fills too the remainder goes to Phase 1. That sequence is exactly what the acetaminophen threshold describes in MCMet-9_17_2026.pdf slide 49, where sulfates and glucuronides are the major metabolites at normal doses.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 29; Lecture #11 (MCMet-9_10_26.pdf) slide 47 (sulfotransferases are cytosolic)',
 quote:'-OH | Sulfotransferases (STs/SULTs) | 3\'-Phosphoadenosine-5\'-phosphosulfate (PAPS) | Sulfate'},

{id:'v-fg-13b', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'gst-target',
 tags:['reasoning','cofactor'], source:'slide',
 stem:'A reactive epoxide has formed from a drug. Which Phase 2 enzyme is positioned to neutralize it?',
 options:[
  {t:'Glutathione S-transferase', correct:true,
   why:'Epoxide is named directly among its targets alongside R-X. The enzyme brings glutathione, whose free thiol attacks the strained electron-poor carbon, converting the reactive intermediate into a stable conjugate before it can reach protein or DNA.'},
  {t:'Sulfotransferase', correct:false,
   why:'Sulfation needs a nucleophilic -OH to attack PAPS. An epoxide carbon is electrophilic, so it cannot begin that reaction; sulfation can even complete a bioactivation, as with the hydroxylamine on MCMet-9_17_2026.pdf slide 44.'},
  {t:'N-acetyltransferase', correct:false,
   why:'N-acetyltransferase acts on -NH2, another electron-rich group. An epoxide offers no amine and no lone pair to donate.'},
  {t:'Acyl synthetase', correct:false,
   why:'Acyl synthetase conjugates carboxylic acids with an amino acid after activating them with acetyl coenzyme A. An epoxide is neither an acid nor a nucleophile.'}],
 teachImg:'tbl_ph2_b',
 teach:'Epoxides have two protective routes and both are named in this lecture: epoxide hydrolase opens the ring with water, slide 20, and glutathione S-transferase conjugates across it. The two act on the same substrate by different chemistry, which is why MCMet-9_17_2026.pdf slide 60 names them together as the enzyme defense against electrophiles. Choosing the right Phase 2 enzyme for any reactive intermediate is a matter of electronic character: an electron-poor substrate needs the enzyme that supplies a nucleophile, and glutathione S-transferase is the only one in the table that does.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 30',
 quote:'R-X; Epoxide | Glutathione S-transferases | Glutathione (GSH) | Glutathione-S'},

{id:'v-fg-14b', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'aa-conjugation-cofactors',
 tags:['cofactor','reasoning'], source:'slide',
 stem:'In amino acid conjugation, acetyl-CoA serves to:',
 options:[
  {t:'Activate the carboxylic acid', correct:true,
   why:'A carboxylic acid is not electrophilic enough for an amine to attack directly. Acetyl coenzyme A converts it to an activated acyl form, and only then does glycine or glutamine bond to it, which is why this row of the table lists two requirements.'},
  {t:'Donate the nitrogen', correct:false,
   why:'The nitrogen comes from the amino acid, glycine or glutamine. Acetyl coenzyme A carries an acetyl group and no usable nitrogen.'},
  {t:'Donate a methyl group', correct:false,
   why:'Methyl transfer uses S-adenosylmethionine, slide 30. Acetyl coenzyme A donates a two-carbon acetyl unit in the N-acetyltransferase reaction, which is a different role from the one it plays here.'},
  {t:'Neutralise the electrophilic carbon', correct:false,
   why:'Neutralizing electrophiles is the glutathione S-transferase function. Here the problem is the reverse: the carboxylic acid carbon is not electrophilic enough, and activation makes it more reactive rather than less.'}],
 teachImg:'tbl_ph2_a',
 teach:'Acetyl coenzyme A appears twice in the Phase 2 table with two different jobs. For N-acetyltransferase acting on -NH2 it is the donor, and the acetyl group ends up on the drug. For acyl synthetase acting on -CO2H it is an activator, and what ends up on the drug is the amino acid. That is why the cofactor column for this row reads acetyl coenzyme A and an amino acid rather than one or the other. The same underlying difficulty, that a carboxylic acid is a poor electrophile, is why carboxylic acids have several competing routes on slide 13.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 29; Lecture #11 (MCMet-9_10_26.pdf) slide 55 (acetyl CoA activates the -COOH)',
 quote:'Acetyl Co-A & an Amino Acid (e.g., Glycine, Glutamine)'},

{id:'v-fg-16b', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'p2map', concept:'methylation-sam',
 tags:['cofactor','matching'], source:'slide',
 stem:'S-adenosylmethionine is the cofactor for which reaction, and on which groups?',
 options:[
  {t:'Methylation, on -OH, -NH₂ and -SH groups', correct:true,
   why:'S-adenosylmethionine donates a single methyl group, and the methyltransferase row lists three targets. All three are nucleophilic, which is what lets them attack the activated methyl.'},
  {t:'Acetylation, on primary amines', correct:false,
   why:'Acetylation uses acetyl coenzyme A and transfers a two-carbon acetyl unit to -NH2. The target overlaps with methylation, but the cofactor and the group transferred are different.'},
  {t:'Sulfation, on aryl alcohols', correct:false,
   why:'Sulfation uses PAPS and acts on -OH. That target also overlaps, which is why the cofactor is the reliable way to tell these apart rather than the substrate.'},
  {t:'Glucuronidation, on carboxylic acids', correct:false,
   why:'Glucuronidation uses UDP-glucuronic acid and covers four groups including -CO2H. Again the substrate overlaps and the cofactor does not.'}],
 teachImg:'tbl_ph2_b',
 teach:'Several Phase 2 enzymes compete for the same functional groups, so the cofactor rather than the substrate is what identifies a reaction. A hydroxyl can be glucuronidated, sulfated or methylated; an amine can be glucuronidated, acetylated or methylated; a thiol can be glucuronidated or methylated. Naming the product settles it, because each cofactor gives its own conjugate: a glucuronide, a sulfate, an N-acetylated product, a methylated product, or a glutathione conjugate. Methylation is also the route that does least for elimination, since adding a methyl group raises lipophilicity slightly; its purpose is to end activity.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 30',
 quote:'-OH; -NH2; -SH | Methyltransferases | S- Adenosyl methionine (SAM) | Methylated'},

/* ---- fgdm/carb: carbonyls and carboxylic acids ---- */
{id:'fg-19', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'carb', concept:'aldehyde-dual-fate',
 tags:['reasoning','structure'], source:'slide',
 stem:'Aldehydes are oxidised and reduced, respectively, by:',
 options:[
  {t:'Aldehyde dehydrogenase; aldo-keto reductase', correct:true,
   why:'An aldehyde sits between the alcohol and the acid in oxidation state, so it can move in either direction. Aldehyde dehydrogenase carries it up to the carboxylic acid, and aldo-keto reductase takes it back down to the primary alcohol.'},
  {t:'Alcohol dehydrogenase; epoxide hydrolase', correct:false,
   why:'Alcohol dehydrogenase makes the aldehyde by oxidizing an alcohol, so it acts one step earlier. Epoxide hydrolase performs a hydrolysis on a strained ring and is not a reductase at all.'},
  {t:'CYP450; UGT', correct:false,
   why:'UDP-glucuronosyltransferase is a Phase 2 conjugating enzyme and performs no reductions. CYPs do oxidize, but the named enzyme for aldehyde oxidation here is aldehyde dehydrogenase.'},
  {t:'Carboxylesterase; carboxylesterase', correct:false,
   why:'Carboxylesterase hydrolyses esters, amides, carbamates and carbonates, slides 8 and 14 to 16. Hydrolysis changes no oxidation state, so it can do neither of the reactions described.'}],
 teachImg:'fgm_carbonyl',
 teach:'The aldehyde is the only group in this lecture that can go in both directions, because it sits in the middle of the alcohol-aldehyde-acid sequence. Ketones cannot: they have no hydrogen on the carbonyl carbon to lose, so they are only reduced, giving the secondary alcohol on slide 12. That asymmetry explains why aldehydes matter for toxicity, since they are electrophilic carbonyls in MCMet-9_17_2026.pdf slide 36 and are hazardous while they persist. Ethanol shows both sides: alcohol dehydrogenase makes acetaldehyde, which is reactive, and aldehyde dehydrogenase converts it onward to harmless acetate.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 12; Lecture #11 (MCMet-9_10_26.pdf) slide 23 (ALDH) and slide 30 (AKR)',
 quote:'Aldehydes undergo oxidative & reductive metabolism'},

{id:'fg-20', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'carb', concept:'ketone-reduction',
 tags:['reasoning','structure'], source:'slide',
 stem:'Ketones undergo reductive metabolism. What is the product and which enzyme family is responsible?',
 options:[
  {t:'A secondary alcohol, formed by aldo-keto reductases', correct:true,
   why:'A ketone carbonyl has two carbon substituents, so reducing it adds a hydrogen and a hydroxyl to a carbon that already carries two carbons, which is a secondary alcohol by definition. Aldo-keto reductases perform the reduction.'},
  {t:'A carboxylic acid, formed by aldehyde dehydrogenase', correct:false,
   why:'That is the aldehyde route. A ketone cannot be oxidized to an acid without breaking a carbon-carbon bond, because it has no hydrogen on the carbonyl carbon to remove.'},
  {t:'An epoxide, formed by CYP450', correct:false,
   why:'Epoxidation acts on a carbon-carbon double bond, the alkene route on slide 6. A carbon-oxygen double bond is not a substrate for it.'},
  {t:'An amine, formed by nitro-reductase', correct:false,
   why:'Nitro reduction converts a nitro group to an amine through nitroso and hydroxylamine intermediates, the nitrofurantoin pathway in MCMet-9_17_2026.pdf slide 48. It requires nitrogen, which a ketone does not have.'}],
 teachImg:'fgm_carbonyl',
 teach:'Counting substituents on the carbonyl carbon predicts both the reaction and the product. An aldehyde has one carbon and one hydrogen there, so it can be oxidized to an acid or reduced to a primary alcohol. A ketone has two carbons and no hydrogen, so only reduction is available and the product is a secondary alcohol. That newly created hydroxyl then opens Phase 2 routes that were not there before, since -OH is a target for glucuronidation, sulfation and methylation. Reduction of a ketone is therefore a functionalization step in the usual Phase 1 sense, even though it lowers rather than raises the oxidation state.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 12',
 quote:'Ketones undergo reductive metabolism to 2O alcohols'},

{id:'fg-21', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'carb', concept:'carboxylic-acid-routes',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'Carboxylic acids undergo which two phase II conjugations?',
 options:[
  {t:'Glucuronidation (UGT); amino acid conjugation (acyl synthetase)', correct:true,
   why:'Both routes appear in the Phase 2 table for -CO2H. Glucuronidation attaches glucuronic acid to give an acyl glucuronide; amino acid conjugation activates the acid with acetyl coenzyme A and attaches glycine or glutamine.'},
  {t:'Sulfation (SULT); methylation (MT)', correct:false,
   why:'Sulfotransferase takes -OH only, so a carboxylic acid is outside its range. Methyltransferase takes -OH, -NH2 and -SH, which also excludes it.'},
  {t:'N-acetylation (NAT); glutathione conjugation (GST)', correct:false,
   why:'N-acetyltransferase acts on -NH2 and glutathione S-transferase on electrophilic R-X and epoxides. A carboxylic acid is neither an amine nor an electrophile.'},
  {t:'Hydrolysis (CE); reduction (AKR)', correct:false,
   why:'Carboxylesterase produces carboxylic acids by hydrolysing esters and amides rather than consuming them, and aldo-keto reductase reduces aldehydes and ketones. Both act on the wrong side of this group.'}],
 teachImg:'fgm_ca',
 teach:'The carboxylic acid is the one functional group with two Phase 2 routes competing directly for it, which is what makes the variety on slide 13 more than a phrase. Glucuronidation gives an acyl glucuronide; amino acid conjugation gives a glycine or glutamine conjugate. The difference matters beyond naming, because acyl glucuronides can be chemically reactive and are implicated in the toxicity of some carboxylic acid drugs, while amino acid conjugates are stable. It is also the only group in the table needing an activation step before conjugation, which is why its row lists two cofactor components.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slides 13, 29',
 quote:'Carboxylic Acids: Undergo a variety of biotransformations'},

/* ---- dmfound/ddi ---- */
{id:'df-11', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'ddi', concept:'induction-timecourse-clinical',
 tags:['case','reasoning'], source:'slide',
 stem:'Triazolam serum levels fall when an inducer is co-administered. This is because the inducer:',
 options:[
  {t:'Raised enzyme amount; faster clearance', correct:true,
   why:'Induction increases transcription and therefore enzyme quantity. More enzyme means faster clearance and lower serum concentration of the substrate.'},
  {t:'Blocked the enzyme; accumulation', correct:false,
   why:'Blockade would raise levels. Falling levels point to induction.'},
  {t:'Displaced triazolam from plasma proteins', correct:false,
   why:'Displacement raises free drug rather than lowering total serum levels through clearance.'},
  {t:'Reduced triazolam gut absorption', correct:false,
   why:'Reduced absorption would also lower serum levels, so the direction fits and the mechanism does not. What separates them is where the change happens: an absorption effect keeps drug out of the circulation in the first place, while induction removes drug that was absorbed normally, by building more enzyme to clear it. The stem says an inducer was added, which names the mechanism, and induction acts on clearance rather than on uptake from the gut.'}],
 teach:'Induction changes how much enzyme is present, so it takes time and then persists. A drug that induces acts on transcription, so more enzyme protein accumulates over days rather than the effect appearing with the first dose, and the extra enzyme decays over days after the inducer stops. While it is present, a substrate of that enzyme is cleared faster and its serum concentration falls. Triazolam with rifampin is the worked case on Lecture 10 slide 49. The figure is a single-dose concentration–time plot over ten hours with two curves: plot X, triazolam alone, peaks at about 2.5 ng/mL; plot T, triazolam after rifampin pretreatment, peaks at about 0.3 ng/mL and stays lower throughout. The rifampin was given for days beforehand, so by the time triazolam is dosed the extra enzyme is already present and the whole curve sits roughly ten times lower. A question built from this slide asks which plot is the rifampin one, and the answer is T, the low curve. The handwritten note on the slide reads NTK, will present a case like this.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 49'},

{id:'df-12', lowYield:true, prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'ddi', concept:'ddi-serious-drug-list',
 tags:['recall'], source:'slide',
 stem:'Which drug is involved in serious drug-drug interactions?',
 options:[
  {t:'Cyclosporine', correct:true,
   why:'The serious-interaction list includes cyclosporine, erythromycin and fluconazole among others. Cyclosporine is also used as the inducer case example elsewhere in the material.'},
  {t:'Acetaminophen (therapeutic dose)', correct:false,
   why:'Acetaminophen appears under hepatotoxicity precautions rather than on the serious interaction list.'},
  {t:'Vancomycin', correct:false,
   why:'Vancomycin appears as an example of renal elimination, not as a major interaction drug.'},
  {t:'Atenolol', correct:false,
   why:'Atenolol is cited as a renally eliminated drug.'}],
 teach:'The list of drugs involved in serious interactions is worth reading as a set of categories rather than as names. Cyclosporin and phenytoin are there for a narrow therapeutic index, so a modest change in clearance crosses into toxicity or loss of effect. Erythromycin, fluconazole and itraconazole are strong inhibitors. Rifampin is the strong inducer. The protease inhibitors, the SSRIs and the HMG-CoA reductase inhibitors appear because they combine a common indication with a CYP dependence. Theophylline combines a narrow index with CYP1A2 metabolism, which is why smoking status changes its dose.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 55'},

{id:'df-13', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'ddi', concept:'tylenol-ethanol-ddi',
 tags:['case','reasoning'], source:'slide',
 stem:'Why does chronic ethanol use raise acetaminophen hepatotoxicity risk?',
 options:[
  {t:'CYP2E1 induction; glutathione depletion', correct:true,
   why:'Two effects compound. More 2E1 means more NAPQI formed from a given dose, and less glutathione means less capacity to neutralise it.'},
  {t:'CYP2E1 inhibition; APAP accumulates', correct:false,
   why:'Ethanol is listed as a 2E1 inducer. Accumulation of unchanged parent is also not the toxic mechanism.'},
  {t:'Blocked renal elimination', correct:false,
   why:'The interaction taught is metabolic, not renal.'},
  {t:'Plasma protein binding competition', correct:false,
   why:'Protein binding is not the mechanism described for this pair.'}],
 teach:'Acetaminophen with ethanol is a CYP2E1 interaction, and chronic use is what makes it dangerous rather than a single drink. Ethanol induces CYP2E1, so more of an acetaminophen dose goes down the route that produces N-acetyl-p-benzoquinone imine. Chronic alcohol use also depletes glutathione, which is the defence against that metabolite. Both changes move in the same direction, so a dose that would be safe produces more reactive metabolite and less of what neutralises it, and liver toxicity follows at doses below the usual threshold.',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slide 54; Lecture #13 (MCMet-9_15_2026.pdf) slide 28; Lecture #15 (MCMet-9_17_2026.pdf) slide 47'},

/* ---- pathways variants ---- */
{id:'v-p1-15b', prof:'Sikazwe', tier:'old', topic:'paths', sub:'hyd', concept:'ce-four-substrates',
 tags:['enzyme','reasoning'], source:'slide',
 stem:'Which functional group is NOT hydrolyzed by carboxylesterases?',
 options:[
  {t:'Epoxide', correct:true,
   why:'Epoxides are opened by epoxide hydrolases, a separate enzyme. Carboxylesterases handle esters, carbamates, amides and carbonates, all of which contain a carbonyl with a heteroatom leaving group.'},
  {t:'Carbonate', correct:false, why:'Carbonates are among the four CE substrates, giving two alcohols on hydrolysis.'},
  {t:'Carbamate', correct:false, why:'Carbamates are CE substrates, giving an amine and an alcohol.'},
  {t:'Amide', correct:false, why:'Amides are CE substrates, and CEs acting on them are also called amidases.'}],
 svg:DIA.acylFamily,
 teach:'Carboxylesterase takes four substrates, and they differ only in what sits on the carbonyl carbon beside the carbon skeleton. One oxygen makes an ester, which hydrolyses to an acid and an alcohol. One nitrogen makes an amide, giving an acid and an amine. One of each makes a carbamate, giving an alcohol and an amine with loss of carbon dioxide. Two oxygens make a carbonate, giving two alcohols and again losing carbon dioxide. Identifying the group therefore means counting and naming the heteroatoms on that one carbon, and the products follow without a separate rule for each.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 35–38'},

{id:'v-fg-5b', prof:'Sikazwe', tier:'new', topic:'fgdm', sub:'ester', concept:'carbamate-hydrolysis-products',
 tags:['structure','reasoning'], source:'slide',
 stem:'Hydrolysis of a functional group yields one alcohol and one amine. Which group was it?',
 options:[
  {t:'Carbamate', correct:true,
   why:'Only the carbamate carries one oxygen and one nitrogen on the carbonyl carbon, so only it can release one of each. The remaining carbamic acid fragment decomposes with loss of carbon dioxide.'},
  {t:'Ester', correct:false,
   why:'An ester has one oxygen and one carbon substituent, so hydrolysis gives an alcohol and a carboxylic acid. There is no nitrogen to release as an amine.'},
  {t:'Amide', correct:false,
   why:'An amide has one nitrogen and one carbon substituent, so it gives an amine and a carboxylic acid. It supplies the amine but not the alcohol.'},
  {t:'Carbonate', correct:false,
   why:'A carbonate has two oxygens on the carbonyl carbon, so hydrolysis releases two alcohols and no amine at all. Confusing it with the carbamate is the usual route to this answer, since both carry two heteroatoms and both lose carbon dioxide. What separates them is that the carbamate swaps one of those oxygens for a nitrogen, and that nitrogen is what leaves as the amine the stem asks about.'}],
 svg:DIA.acylFamily,
 teachImg:'fgm_carbamate',
 teach:'This question runs the usual reasoning backwards, from products to structure, and the method is the same in both directions. Each heteroatom on the carbonyl carbon leaves as its own fragment: an oxygen departs as an alcohol, a nitrogen as an amine, and a carbon substituent keeps the carbonyl so that fragment leaves as a carboxylic acid. One alcohol plus one amine therefore requires exactly one oxygen and one nitrogen, which identifies the carbamate uniquely. Because the leftover central carbon is bonded only to heteroatoms, it leaves as carbon dioxide, so nothing else has to be accounted for.',
 cite:'Lecture #14 (MCMet-9_16_2026.pdf) slide 15',
 quote:'Carbamates: Undergo CE hydrolysis to give amines and'},

{id:'v-p1-8b', prof:'Sikazwe', tier:'old', topic:'paths', sub:'nonc', concept:'adh-aldh-sequence',
 tags:['mechanism','reasoning'], source:'slide',
 stem:'Ethanol is metabolized through which sequence?',
 options:[
  {t:'Ethanol → acetaldehyde by ADH → acetate by ALDH', correct:true,
   why:'Each enzyme is named for the substrate it consumes. The reactive acetaldehyde in the middle is what causes harm when it accumulates, whether from disulfiram or from a slow ALDH phenotype.'},
  {t:'Ethanol → acetate by ADH → acetaldehyde by ALDH', correct:false,
   why:'The intermediate and the product are reversed. Acetaldehyde comes first.'},
  {t:'Ethanol → ethoxy radical by ALDH → acetate by ADH', correct:false,
   why:'The ethoxy radical comes from CYP2E1, a separate route, and the enzyme assignments here are wrong.'},
  {t:'Ethanol → acetaldehyde by MAO → acetate by CYP2E1', correct:false,
   why:'MAO acts on amines, not alcohols.'}],
 teach:'Two enzymes run the ethanol ladder in a fixed order. Alcohol dehydrogenase takes a primary alcohol to an aldehyde; aldehyde dehydrogenase takes that aldehyde to a carboxylic acid. Both are oxidations of the same carbon, each removing hydrogen and raising the oxidation state one step. The order cannot reverse, since the second enzyme\'s substrate is the first enzyme\'s product, and that dependency is what disulfiram exploits: inhibiting the second step leaves the intermediate aldehyde to accumulate.',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slides 22–23'},

{id:'v-p2-1b', prof:'Sikazwe', tier:'old', topic:'paths', sub:'p2', concept:'glucuronidation-ident',
 tags:['cofactor','reasoning'], source:'slide',
 stem:'A metabolite is more water soluble than the parent and carries an ionized carboxylate on a six-carbon sugar. What was formed?',
 options:[
  {t:'A glucuronide, from UGT using UDPGA', correct:true,
   why:'Glucuronic acid is a six-carbon sugar bearing a carboxyl group. That added charge is what makes the conjugate polar enough for renal elimination.'},
  {t:'A sulfate, from SULT using PAPS', correct:false,
   why:'A sulfate conjugate carries SO₃⁻ rather than a sugar.'},
  {t:'A glutathione conjugate, from GST', correct:false,
   why:'A glutathione conjugate adds a tripeptide, recognizable by its peptide bonds and amino acid residues.'},
  {t:'An N-acetyl product, from NAT', correct:false,
   why:'Acetylation adds only a small two-carbon acetyl group and reduces rather than increases polarity.'}],
 teach:'A conjugate can be named from its structure alone, because each Phase 2 enzyme attaches one recognizable fragment. Glucuronic acid is a six-carbon sugar with a carboxyl group at C6, so the clue is a sugar ring carrying a charge, and the enzyme is UDP-glucuronosyltransferase (UGT) drawing on uridine-5’-diphospho-D-glucuronic acid (UDPGA). A sulfate is a small SO3- group with no carbon, from sulfotransferase (SULT) using 3’-phosphoadenosine-5’-phosphosulfate (PAPS). A glutathione conjugate shows peptide bonds and amino acid side chains, from glutathione S-transferase (GST). An N-acetyl product shows a two-carbon acetamide on a nitrogen, from N-acetyltransferase (NAT) using acetyl coenzyme A. The charge is what does the pharmacokinetic work in the glucuronide case: the carboxylate is ionized at physiological pH, and an ionized metabolite is held in the aqueous phase and cleared by the kidney rather than reabsorbed.',
 teachImg:'tbl_ph2_a',
 cite:'Lecture #11 (MCMet-9_10_26.pdf) slide 46; cofactor table in Lecture #14 (MCMet-9_16_2026.pdf) slide 29'},

/* ---- elimination variants ---- */
{id:'v-el-7b', prof:'Sikazwe', tier:'new', topic:'elim', sub:'ph', concept:'ph-trapping-definition',
 tags:['reasoning','mechanism'], source:'slide',
 stem:'An ionized drug in the renal tubule is eliminated more because it:',
 options:[
  {t:'Cannot be passively reabsorbed', correct:true,
   why:'Reabsorption from the tubule is passive back diffusion, which requires a molecule able to dissolve in membrane lipid. A charge prevents that, so the drug remains in the tubular fluid and continues into urine.'},
  {t:'Is pumped out by efflux transporters', correct:false,
   why:'Active secretion is real and uses the organic anion and cation carriers on slide 13, but it is a separate process that moves drug into the tubule. Trapping rests on blocking passive return rather than on adding transport.'},
  {t:'Is filtered faster at the glomerulus', correct:false,
   why:'Filtration selects on size and protein binding, slide 11, not on charge, and it has already happened before the drug reaches the tubule where the pH acts.'},
  {t:'Is metabolised in the tubule', correct:false,
   why:'No metabolic step is involved. The molecule leaves chemically unchanged; what changes is its protonation state and therefore its ability to cross a membrane.'}],
 svg:DIA.renalHandling,
 teach:'Trapping is tubular reabsorption denied. The tubule returns drug to circulation only when the molecule can cross lipid, so converting it to the charged form closes that path and leaves urine as the only exit. Because the effect works through an acid-base equilibrium, the drug must have an ionizable group for the pH to act on, and the direction follows the character of the drug: an acid is charged in alkaline urine, a base in acidic urine. Aspirin overdose treated by alkalinizing urine with sodium bicarbonate, slide 15, is this mechanism used deliberately, and ion trapping reappears among the enhanced elimination measures on slide 62.',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slides 12, 14',
 quote:'The un-ionized drug is reabsorbed from the renal tubule back into circulation (mostly via passive back diffusion)'},

{id:'v-el-3b', prof:'Sikazwe', tier:'new', topic:'elim', sub:'routes', concept:'polar-renal-lipophilic-biliary',
 tags:['reasoning','exam-pattern'], source:'both',
 stem:'Lipid-soluble parent drugs are primarily eliminated via which route?',
 options:[
  {t:'Hepatic, through bile into feces', correct:true,
   why:'A log P of 4 is strongly lipophilic, and lipid-soluble material is moved into bile by active transport. The same property would defeat the renal route, since such a molecule reaching the tubule diffuses back into circulation rather than staying in urine.'},
  {t:'Renal, through glomerular filtration', correct:false,
   why:'The renal route is primary for polar free or unbound drug, slide 7. Filtration itself would occur if the molecule is small and unbound, but what follows is reabsorption, so little is actually eliminated this way.'},
  {t:'Pulmonary, through exhalation', correct:false,
   why:'Exhalation carries volatile or gaseous agents such as inhaled anesthetics, slide 22. Lipophilicity and volatility are different properties, and a log P of 4 says nothing about entering the gas phase.'},
  {t:'Salivary', correct:false,
   why:'Saliva is not a major route and is used for monitoring, detecting exposure from 5 to 48 hours afterwards, slide 26. It has no capacity to clear a meaningful fraction of a dose.'}],
 svg:DIA.routeRank,
 teach:'One property, whether the molecule can cross a membrane passively, sorts most drugs between the two major routes. Polar drug cannot, so once filtered it is committed to urine. Lipophilic drug can, so the kidney filters it and then takes it back, and the body uses active transport into bile instead. The same drug\'s metabolites are a separate question with a different answer: Phase 1 and Phase 2 steps raise polarity, so the conjugates of a lipophilic parent leave renally even while the intact parent goes through bile. Prep-sheet question 6 asks about the metabolite\'s route for exactly this reason, and there the answer is renal. Here the question is the intact parent, and the answer is bile.',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slides 7, 16',
 quote:'Non-polar drugs (e.g., Phenytoin) excreted here are subject to tubular reabsorption'},

{id:'v-el-11b', prof:'Sikazwe', tier:'new', topic:'elim', sub:'hep', concept:'enterohepatic-definition',
 tags:['reasoning','case'], source:'both',
 stem:'A drug\'s duration of action is long despite rapid hepatic metabolism. Which phenomenon explains it?',
 options:[
  {t:'Enterohepatic recycling', correct:true,
   why:'Each loop returns drug that had already been committed to elimination, so the observed duration exceeds what metabolic clearance alone predicts. Ezetimibe is the lecture example, cycling repeatedly to a half-life of 22 to 24 hours.'},
  {t:'Renal pH trapping', correct:false,
   why:'Trapping keeps a drug in urine and speeds elimination, slide 14, so it shortens duration rather than extending it. It would be the explanation for an unexpectedly short effect in a patient whose urine pH had shifted.'},
  {t:'Intestinal P-glycoprotein efflux', correct:false,
   why:'Efflux pumps drug back into the intestinal lumen and contributes to intestinal elimination, slide 21, where diltiazem and midazolam are the examples. That removes drug rather than returning it to circulation.'},
  {t:'Rapid glomerular filtration', correct:false,
   why:'Efficient filtration shortens duration. It is also unrelated to a drug described as extensively hepatically metabolized, since filtration acts on what reaches the kidney unchanged.'}],
 svg:DIA.enterohepatic,
 teach:'A mismatch between measured metabolic clearance and observed duration is the signature of recycling. The liver may conjugate the drug quickly and send it into bile, but gut bacteria can hydrolyse the conjugate and release the original lipophilic molecule, which is then reabsorbed. Elimination is delayed without metabolism being slow. Ezetimibe, isotretinoin and morphine are the examples on slide 19. The same reasoning identifies the intervention, since binding drug in the lumen with oral activated charcoal or an anion exchange resin removes the reabsorption option and breaks the loop.',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slides 18–19',
 quote:'*Zetia undergoes repeated cycling - long DoA (t1/2= 22-24 h)'},

{id:'v-el-2b', prof:'Sikazwe', tier:'new', topic:'elim', sub:'routes', concept:'route-ranking',
 tags:['ranking'], source:'slide',
 stem:'Within the non-renal routes, which is the largest?',
 options:[
  {t:'Hepatic via bile into feces', correct:true,
   why:'Bile is the route with real capacity once the renal route is set aside, because it takes the lipid-soluble material the kidney handles poorly. Active transport moves drug and metabolites into bile, and steroids, digoxin and many anticancer agents leave this way.'},
  {t:'Pulmonary exhalation', correct:false,
   why:'Exhalation is the primary route for volatile or gaseous agents, slide 22, so it ranks first for that narrow class and negligibly for everything else. Volatility is a requirement rather than a matter of degree.'},
  {t:'Mammary/breast milk', correct:false,
   why:'Milk is not a major route, slide 23. It matters for a different reason: the dose delivered to a nursing infant, with topotecan and cimetidine named, rather than the fraction removed from the mother.'},
  {t:'Skin and sweat', correct:false,
   why:'Skin is a minor route used for monitoring and testing, slide 24. It is unusual in accepting both polar and lipophilic drugs, through sweat and sebum, but carries too little to affect clearance.'}],
 svg:DIA.routeRank,
 teach:'Each route accepts only a certain kind of molecule, so the ranking follows from how much of what the body actually produces each one can take. Renal takes polar free or unbound drug, which is most of what metabolism produces, so it leads overall. Bile takes lipid-soluble material by active transport, which is the largest remaining category and makes it the main non-renal route. Intestinal elimination follows, covering unabsorbed oral drug plus what P-glycoprotein effluxes back into the lumen, with diltiazem and midazolam as examples. Pulmonary requires volatility. The rest are limited by capacity rather than by selectivity, which is why their value is monitoring.',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slides 16, 21–26',
 quote:'Hepatic/Bile/Fecal Primary route for lipid-soluble drugs, metabolites'},

/* ---- toxicity variants ---- */
{id:'v-tx-1b', prof:'Sikazwe', tier:'new', topic:'tox', sub:'causes', concept:'toxicophore-definition',
 tags:['definition','exam-pattern'], source:'both',
 stem:'A toxicophore is:',
 options:[
  {t:'A toxic or potentially toxic FG', correct:true,
   why:'Both name a minimal structural feature rather than a whole molecule, and they differ only in what that feature produces. One molecule commonly carries both, which is why a useful drug can also be hazardous for reasons visible in its structure.'},
  {t:'Always a metabolite, never the parent', correct:false,
   why:'Toxicophores can be present in the parent drug already, as with halogenated and allylic carbons on slides 31 and 32, or created by metabolism, as with epoxides. That split into existing and bioactivated is a separate distinction from parent against metabolite.'},
  {t:'A protein binding site', correct:false,
   why:'Both terms describe features of the small molecule. The protein contributes the nucleophilic site that a toxicophore attacks and the binding site that a pharmacophore fits, but neither term names the protein.'},
  {t:'Another name for a pharmacophore', correct:false,
   why:'They are built on the same pattern precisely so they can be contrasted. Sharing a structure of definition is what makes the difference in outcome, activity against toxicity, the thing being tested.'}],
 svg:DIA.toxicophores,
 teach:'Both terms reduce a molecule to the part that matters for a given outcome, which is what makes them useful in design: keep the pharmacophore, remove the toxicophore. Whether that is possible depends on how far apart they sit in the structure. Toxicophores are further divided by origin, existing in the parent or created by metabolism, and that decides the remedy. An existing toxicophore, such as a halogenated or allylic carbon, is addressed by changing the molecule. A bioactivated one, such as an epoxide, depends on which enzymes act and on how much deactivating capacity the patient has, which is why the same dose is not equally safe in everyone.',
 teachImg:'tx_halothane',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slides 29–30',
 quote:'Toxicophores (toxic/potentially toxic FGs)'},

{id:'v-tx-3b', prof:'Sikazwe', tier:'new', topic:'tox', sub:'mech', concept:'toxicophore-categories',
 tags:['structure','reasoning'], source:'slide',
 stem:'Which set lists the electrophilic toxicophores?',
 options:[
  {t:'Carbons, carbonyls and double bonds', correct:true,
   why:'The three differ only in where the electron deficiency sits: on a carbon made poor by a halogen or an adjacent double bond, on a carbonyl carbon, or on a carbon within a conjugated system. In every case a nucleophile on a macromolecule attacks and a covalent adduct results.'},
  {t:'Free radicals, haptens and azo groups', correct:false,
   why:'Only haptens work through the immune system, by binding protein to form a complex recognised as foreign, slide 42. Radicals damage by propagation and azo groups by releasing carcinogenic aromatic amines, so the three have different endpoints.'},
  {t:'Epoxides, glucuronides and sulfates', correct:false,
   why:'Only the epoxide is reactive. Glucuronides and sulfates are the detoxified Phase 2 products formed to end reactivity, and their exhaustion is what begins acetaminophen toxicity, slide 49, rather than causing harm themselves.'},
  {t:'Alcohols, amines and thiols', correct:false,
   why:'These are correctly grouped as nucleophiles, but that is the opposite electronic character. They are the attacking partners and the targets for Phase 2 conjugation, not the toxicophores.'}],
 svg:DIA.toxicophores,
 teachImg:'tx_aflatoxin',
 teach:'Three of the five toxicophore bullets on slide 30 describe the same event at different positions in a molecule. Anything electron poor invites attack from the electron-rich sites that fill proteins and DNA: cysteine thiols, lysine amines, DNA base nitrogens. The remaining two categories do damage by routes that share nothing with direct attack. Free radicals carry an unpaired electron and propagate, creating a new radical with each reaction rather than being consumed, which is why a separate antioxidant defense exists on slide 61. The others group, haptens, azo compounds and N-hydroxy groups, covers immune and carcinogenic routes that need an extra step before harm appears.',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 30',
 quote:'Electrophilic carbons · Electrophilic carbonyls · Electrophilic double bonds · Free radicals (ROS/RNS included) · Others: Haptens, Azo, N-OH, etc.'},

{id:'v-tx-11b', prof:'Sikazwe', tier:'new', topic:'tox', sub:'hep', concept:'apap-napqi',
 tags:['case','reasoning'], source:'both',
 stem:'APAP is safe at normal doses but hepatotoxic in overdose because:',
 options:[
  {t:'UGTs and STs become exhausted', correct:true,
   why:'Sulfation and glucuronidation are the major routes at normal doses and have a finite capacity. Phase 1 oxidation does not saturate in the same way, so once the conjugation routes are full the excess is diverted into it and NAPQI production rises sharply.'},
  {t:'NAPQI forms only in genetic variants', correct:false,
   why:'NAPQI is formed in everyone; it is simply removed by glutathione while supplies last. Genetics and alcohol use shift where the threshold falls by changing production and removal capacity, but they do not create the pathway.'},
  {t:'NAPQI is toxic only when fasting', correct:false,
   why:'Nutritional state does matter, because poor intake lowers glutathione stores and therefore the capacity to remove NAPQI. That moves the threshold rather than being the reason a threshold exists.'},
  {t:'Absorption needs a threshold dose', correct:false,
   why:'Absorption is not the limiting step and does not behave that way. The limit is metabolic capacity, which is why the same total dose given as one large amount is more dangerous than the same amount spread out.'}],
 svg:DIA.apapNapqi,
 teachImg:'tx_nac',
 teach:'Threshold toxicity appears whenever a protective route saturates before a harmful one does. Below about 4 grams a day, sulfation and glucuronidation carry essentially the whole dose and the drug is safe. Above it those routes are full, the excess goes through CYP oxidation, and NAPQI accumulates. A second threshold follows, since glutathione removes NAPQI until it too runs out. That is why the risk factors compound as they do: alcohol use induces CYP2E1, raising production, and depletes glutathione, lowering removal, so both thresholds move at once. The same shape explains the carbamazepine epoxide, where epoxide hydrolase and glutathione S-transferase can also be outrun.',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 49',
 quote:'Safe at < 4g/day; hepatotoxic at higher doses'},

{id:'v-tx-15b', dupOf:'v-tx-11b', prof:'Sikazwe', tier:'new', topic:'tox', sub:'def', concept:'gst-eh-defense',
 tags:['reasoning','enzyme'], source:'slide',
 stem:'Why can a normally safe drug become toxic at high dose despite GST and EH defence?',
 options:[
  {t:'Their deactivating capacity is exceeded', correct:true,
   why:'Defense is a rate rather than a barrier. Glutathione S-transferase and epoxide hydrolase remove reactive species as fast as their capacity allows, and anything produced beyond that rate remains long enough to reach a protein or DNA nucleophile.'},
  {t:'High doses inhibit GST and EH', correct:false,
   why:'Direct inhibition of these enzymes is a real way to lower defense, and drug interactions can do it, but the mechanism here is exhaustion. The enzymes keep working; there is simply more substrate than they can process.'},
  {t:'They act only on parent drug', correct:false,
   why:'The reverse is true. Both act on reactive metabolites and intermediates, which is exactly why they are described as the defense against electrophiles, slide 60.'},
  {t:'They are absent from the liver', correct:false,
   why:'They are present in the liver and are the named enzyme defense. Their presence is why ordinary doses are safe at all.'}],
 svg:DIA.apapNapqi,
 teachImg:'tx_defense1',
 teach:'Saturable defense explains why toxicity so often appears abruptly above a threshold rather than rising smoothly with dose. Below the limit, essentially all reactive material is removed and no injury occurs; above it, the excess survives and adducts begin to form. The same logic recurs across the lecture: acetaminophen with glutathione, the carbamazepine epoxide with epoxide hydrolase and glutathione S-transferase, and the procarcinogens where a small surviving fraction is enough for a DNA adduct. It also explains why anything that lowers capacity, alcohol use depleting glutathione or a poor metabolizer phenotype, moves the threshold down without changing the mechanism.',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slides 33, 60',
 quote:'Enzyme Defense- Electrophile deactivation by GSTs and EHs'},

{id:'v-tx-12b', prof:'Sikazwe', tier:'new', topic:'tox', sub:'def', concept:'nac-antidote',
 tags:['case','antidote','reasoning'], source:'both',
 stem:'N-acetylcysteine (NAC) neutralises NAPQI through:',
 options:[
  {t:'Nucleophilic thiol; electrophile deactivation', correct:true,
   why:'NAPQI is a quinone-imine carrying conjugated double bonds, so one of its carbons is electron poor. Sulfur is a good nucleophile, and the thiol adds to that carbon, giving a water-soluble conjugate instead of a protein adduct.'},
  {t:'Acetyl group blocking CYP2E1', correct:false,
   why:'Blocking the enzyme would prevent NAPQI being made, which is a coherent strategy but not this one. N-acetylcysteine acts after the metabolite has formed, which is why it remains useful once an overdose has been taken.'},
  {t:'Chelation of CYP heme iron', correct:false,
   why:'Binding the heme iron is how azole antifungals inhibit CYPs, from MCMet-9_15_2026.pdf, so the mechanism exists but belongs elsewhere. It would also prevent formation rather than neutralize what has formed.'},
  {t:'Urine alkalinisation; NAPQI trapping', correct:false,
   why:'Urinary alkalinization is the aspirin strategy on slide 15 and needs an ionizable drug in the tubule. NAPQI is a reactive species in the liver that binds proteins within seconds, so a renal manoeuvre never reaches it.'}],
 svg:DIA.apapNapqi,
 teachImg:'tx_nac',
 teach:'N-acetylcysteine works by being what glutathione is: a small molecule with a free sulfhydryl group. Glutathione normally adds its thiol across the electrophilic carbon of NAPQI and the conjugate leaves in urine; in overdose that supply is spent, and the antidote restores the missing nucleophile rather than interfering with any enzyme. The timing follows from the chemistry, since the thiol must arrive while NAPQI is still free and before it has bound protein, which is why the antidote is given early. This is the general electrophile defense of slide 60 used as treatment, and it contrasts with pralidoxime, which reverses a covalent bond already made.',
 cite:'Lecture #15 (MCMet-9_17_2026.pdf) slide 63',
 quote:'NAC - antidote for APAP toxicity · Electrophile deactivation by NAC'},

/* ---- foundations variants ---- */
{id:'v-df-3b', prof:'Sikazwe', tier:'old', topic:'dmfound', sub:'phases', concept:'phase1-vs-phase2-role',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'A drug already carries a phenolic hydroxyl. Its metabolism can begin with:',
 options:[
  {t:'Direct phase II conjugation', correct:true,
   why:'Phase 1 exists to create a handle. When a suitable group is already present, glucuronidation or sulfation can act on the parent directly.'},
  {t:'Mandatory CYP oxidation first', correct:false,
   why:'That would only be true if the molecule lacked a conjugatable group.'},
  {t:'No metabolism; already polar', correct:false,
   why:'A phenol is a prime Phase 2 substrate, not an obstacle.'},
  {t:'Unchanged pulmonary excretion', correct:false,
   why:'Pulmonary elimination serves volatile agents.'}],
 teach:'Phase 1 and Phase 2 name two kinds of chemistry rather than two stages in a fixed order. Phase 1 enzymes are oxygenases and related enzymes that insert oxygen, remove hydrogen, add electrons or add water, and the result is a functional group that was absent or masked. Phase 2 enzymes are transferases that move a group from a cofactor onto a functional group already present. Because the second only needs a suitable group and does not care where it came from, a drug that already carries a hydroxyl or a carboxyl can go straight to conjugation, and a Phase 2 metabolite can afterwards undergo a Phase 1 reaction.',
 teachImg:'fgm_phenol_ph2',
 cite:'Lecture #10 (MCMet-9_4_26-9_9_26.pdf) slides 12–14; Lecture #14 (MCMet-9_16_2026.pdf) slide 23'},

/* ---- Yendapally variants ---- */
{id:'v-ad-1b', prof:'Yendapally', tier:'old', topic:'admet', sub:'trans', concept:'abc-vs-slc',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'A transporter moves drug against its concentration gradient using ATP directly. Which family is it, and which direction does it usually move drug at the intestinal apical membrane?',
 options:[
  {t:'ABC family, moving drug back out into the gut lumen', correct:true,
   why:'Direct ATP use is the definition of primary active transport, which identifies the ABC family. Many ABC transporters sit on the apical side of the membrane facilitating secretion, so at the intestine they return drug to the lumen and reduce the absorbed fraction.'},
  {t:'SLC family, moving drug into the enterocyte', correct:false,
   why:'The direction is right for SLC, which generally facilitates influx, but the energy source is not. SLC transporters are secondary active and use a gradient another pump created rather than hydrolysing ATP themselves.'},
  {t:'ABC family, moving drug into the enterocyte', correct:false,
   why:'The family follows correctly from the ATP clue, but every ABC transporter in this deck is an efflux pump, so the direction is inverted.'},
  {t:'SLC family, moving drug out into the lumen', correct:false,
   why:'Both halves miss. SLC is secondary active rather than ATP-driven, and it mostly carries drug inward, although a few members are capable of efflux.'}],
 teach:'Two clues in a transporter question point to the same answer, and checking both guards against a half-right choice. Direct ATP use means primary active, which means ABC, which means efflux. A gradient supplied by something else means secondary active, which means SLC, which generally means influx. The direction then gives the clinical consequence without any further recall: efflux at the intestinal apical membrane limits bioavailability, so inhibiting it raises exposure and inducing it lowers exposure, which is the digoxin pattern with verapamil and rifampin.',
 cite:'ADMET Absorption I (090326_ADMETAbsorption_I.pdf) slides 15, 18–21',
 quote:'ABC (ATP-binding cassette) Transporters · Primary active transporters (use ATP as an energy source)'},

{id:'v-ad-3b', prof:'Yendapally', tier:'old', topic:'admet', sub:'ddi', concept:'efflux-effect-on-bioavailability',
 tags:['case','reasoning'], source:'slide',
 stem:'A patient on digoxin starts a P-glycoprotein inhibitor. Expected digoxin levels?',
 options:[
  {t:'Rise; less efflux into gut', correct:true,
   why:'Digoxin is a named P-glycoprotein substrate, so intestinal efflux normally returns part of each dose to the lumen. Verapamil inhibits that efflux and raises digoxin blood levels, and digoxin has little margin for a rise.'},
  {t:'Fall; more efflux into gut', correct:false,
   why:'That is the inducer pattern rather than the inhibitor one. Rifampin induces intestinal P-glycoprotein expression and lowers digoxin blood levels, which is the same interaction running the other way.'},
  {t:'Unchanged; not a transporter substrate', correct:false,
   why:'Digoxin is listed among the P-glycoprotein substrates alongside loperamide, fexofenadine and paclitaxel, and it is the deck\'s worked example of a transporter-mediated interaction.'},
  {t:'Rise; CYP3A4 inhibition', correct:false,
   why:'The direction is right and the mechanism is wrong, which makes this the closest miss. The interaction named for digoxin is transporter-mediated, and attributing it to a CYP would predict the wrong set of interacting drugs.'}],
 teach:'Digoxin with verapamil and rifampin is the cleanest transporter interaction in the course, because one substrate is paired with both an inhibitor and an inducer. Inhibiting intestinal P-glycoprotein leaves more drug absorbed and levels rise; inducing it pumps more back to the lumen and levels fall. Neither involves metabolism, which is what distinguishes this class of interaction: exposure changes with no new metabolite and no CYP explanation. Because digoxin has a narrow margin, the direction matters clinically in both cases, and the same substrate-inhibitor-inducer structure reappears at the blood-brain barrier with loperamide and quinidine.',
 cite:'ADMET Absorption II (090426_ADMETAbsorption_II.pdf) slides 13; Absorption I slide 24',
 quote:'Verapamil is an inhibitor of intestinal P-gp efflux. Increases digoxin blood levels · Rifampin inducer of intestinal P-gp expression. Results in the lowering of digoxin blood levels'},

{id:'v-ad-11b', prof:'Yendapally', tier:'old', topic:'admet', sub:'vd', concept:'vd-interpretation',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'At equal doses, drug A has a much higher plasma concentration than drug B. Which has the smaller Vd?',
 options:[
  {t:'Drug A', correct:true,
   why:'Concentration is the denominator, so the relationship is inverse. A high plasma concentration means most of the dose stayed in the vascular compartment, which gives a small calculated volume.'},
  {t:'Drug B', correct:false,
   why:'That inverts the equation. A large Vd goes with a low plasma concentration, because most of the drug has left plasma for tissue, which is the amiodarone situation.'},
  {t:'Neither; same dose, same Vd', correct:false,
   why:'Vd depends on both the amount in the body and the resulting concentration. Two drugs given at the same dose can differ enormously, as amiodarone at 4620 litres and chlorpropamide at 6.8 litres show.'},
  {t:'Cannot tell without half-life', correct:false,
   why:'Vd is calculated from amount in the body and plasma concentration alone. Half-life is a separate parameter that depends on both Vd and clearance, so it follows from this comparison rather than being needed for it.'}],
 teach:'Working from the equation rather than from a remembered pairing handles any version of this question. Vd is the amount in the body over the plasma concentration, so concentration and volume move in opposite directions at a fixed dose. High concentration means the drug is still in plasma, so the volume is small and the drug is likely polar or heavily protein bound. Low concentration means it has gone elsewhere, so the volume is large and the drug is likely lipophilic or sequestered in a reservoir. Reading the number as a statement about where the dose went makes the physical impossibility of a 4620 litre volume stop being a problem.',
 cite:'ADMET Distribution (090426_Distribution.pdf) slides 3–5, 10',
 quote:'Vd = Amount of drug in the body / C'},

{id:'v-dr-1b', prof:'Yendapally', tier:'old', topic:'recept', sub:'bonds', concept:'bond-strength-order',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'A drug binds its receptor through an interaction of roughly 5–10 kcal/mol. Which type is it?',
 options:[
  {t:'Ionic', correct:true,
   why:'That range belongs to ionic bonding, sitting between hydrogen bonding at 2 to 5 and covalent at 50 to 150. It pairs a charged group on the drug with an oppositely charged amino acid side chain.'},
  {t:'Covalent', correct:false,
   why:'Covalent bonds are 50 to 150 kcal/mol, five to thirty times the value given. The practical difference is reversibility: at 5 to 10 the drug can dissociate, at 50 to 150 it cannot.'},
  {t:'Hydrogen bond', correct:false,
   why:'Hydrogen bonds are 2 to 5 kcal/mol, the next band down and the closest miss. Several of them together can exceed a single ionic interaction, since multiple hydrogen bonds commonly form and add up.'},
  {t:'Hydrophobic', correct:false,
   why:'Hydrophobic interactions are the weakest at 0.5 to 1 kcal/mol, roughly a tenth of the value given. Choosing this usually means holding the ranking without the numbers that produce it, and the stem supplies only a number. Reading the four bands in order settles every version of this question: hydrophobic 0.5 to 1, hydrogen bond 2 to 5, ionic 5 to 10, covalent 50 to 150.'}],
 teach:'The four bands are separated widely enough that a single figure identifies the interaction without ambiguity: 0.5 to 1 hydrophobic, 2 to 5 hydrogen bonding, 5 to 10 ionic, and 50 to 150 covalent. The gap between the third and fourth is the meaningful one, because it separates reversible binding from binding that ends only when the receptor is replaced. Within the reversible group the differences are smaller than they look, since weak interactions occur in numbers, so a drug making one ionic contact and several hydrogen bonds and hydrophobic contacts may owe most of its affinity to the weaker ones.',
 cite:'Drug–Receptor Interactions (082426_DrugReceptorInteractions.pdf) slides 4–8',
 quote:'Ionic Bond · Two atoms are attracted to each other by electrostatic forces · Strength: 5-10 kcal/mol'},

{id:'v-pc-1b', prof:'Yendapally', tier:'old', topic:'physchem', sub:'acidbase', concept:'pka-direction-acids',
 tags:['ranking','reasoning'], source:'slide',
 stem:'Acidic drugs have pKa 3.5, 5.0 and 8.0. Which is the strongest acid and most ionized at pH 7.4?',
 options:[
  {t:'pKa 3.5', correct:true,
   why:'Lower pKa means a stronger acid, so 3.5 is strongest. It is also furthest below pH 7.4, and an acid is more ionized the further the pH sits above its pKa, so the same drug answers both halves.'},
  {t:'pKa 8.0', correct:false,
   why:'This applies the base rule to acids. At pKa 8.0 the drug is the weakest of the three and, sitting above pH 7.4, is mostly unionized there, which is the amobarbital case worked through in the deck.'},
  {t:'pKa 5.0', correct:false,
   why:'Proximity to neutral pH is not a measure of strength. What a pKa near the surrounding pH does mean is that the drug is close to half ionized, since the two forms are equal when pH equals pKa.'},
  {t:'All equally ionized', correct:false,
   why:'Ionization depends on the gap between pH and pKa, and here the gaps are 3.9, 2.4 and -0.6, so the three differ by orders of magnitude. Each unit of difference changes the ratio tenfold.'}],
 teach:'Both halves of this question are answered by the same comparison, which is why they agree. Strength is read from pKa alone: lower is stronger for an acid. Ionization is read from the gap between pH and pKa, and for an acid every unit that pH sits above pKa multiplies the ionized fraction by ten. So at pH 7.4 the drug at pKa 3.5 is close to fully ionized, the one at 5.0 substantially so, and the one at 8.0 mostly unionized. The two questions can come apart when comparing an acid with a base, which is why identifying the group first matters more than remembering a rule.',
 cite:'Physicochemical Properties 1 (082726_PhysicochemicalProp1.pdf) slides 9, 18, 33',
 quote:'Lower the pKa for acids, higher is their strength · Higher the pKa for bases, higher is their strength'},

{id:'v-pc-6b', prof:'Yendapally', tier:'old', topic:'physchem', sub:'logp', concept:'hydrophilic-group-effect',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'Metabolism converts a drug to a glucuronide. What happens to log P and water solubility?',
 options:[
  {t:'Log P falls and water solubility rises', correct:true,
   why:'Glucuronic acid brings several hydroxyls and a carboxylic acid, all able to hydrogen bond with water and all contributing negatively to log P. That is the whole purpose of the conjugation: to make the molecule water soluble enough to be eliminated.'},
  {t:'Log P rises and water solubility falls', correct:false,
   why:'That would defeat the point of the reaction, leaving the metabolite harder to excrete than the parent. Raising log P is what a prodrug strategy does deliberately, as with haloperidol decanoate, not what Phase 2 metabolism does.'},
  {t:'Both stay the same, since the core structure is unchanged', correct:false,
   why:'Log P is a property of the whole molecule rather than of a core, so attaching a large polar fragment changes it substantially even with the original skeleton intact.'},
  {t:'Log P falls and water solubility also falls', correct:false,
   why:'These two move in opposite directions by definition, since log P measures preference for an organic phase over water. Both falling together is not possible.'}],
 teach:'Phase 2 conjugation is a deliberate reduction in log P, which connects the physicochemical material to the metabolism lectures. Attaching glucuronic acid, sulfate or an amino acid adds hydrogen-bonding groups and often a charge, so the metabolite is far more water soluble than the parent and can be eliminated renally. The same logic in reverse explains prodrug design, where log P is raised on purpose to improve absorption or prolong action. Reading a metabolic step as a movement along the log P scale predicts what happens to the molecule\'s fate without recalling the specific enzyme.',
 cite:'Physicochemical Properties 2 (090226_PhysicochemicalProp2.pdf) slides 6, 9; the conjugates and their groups, Lecture #14 (MCMet-9_16_2026.pdf) slides 29–30',
 quote:'Approaches to address solubility issues: Salt formation · Chemical modification by adding polar groups like –OH, NH2 etc.'},

{id:'v-st-5b', prof:'Yendapally', tier:'old', topic:'stereo', sub:'terms', concept:'enantiomer-vs-diastereomer',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'A molecule has three chiral centres. Another molecule has the opposite configuration at all three. What is the relationship?',
 options:[
  {t:'Enantiomers', correct:true,
   why:'Inverting every centre produces the complete mirror image, which is what enantiomers are. The number of centres does not matter; what matters is that none was left unchanged.'},
  {t:'Diastereomers', correct:false,
   why:'Diastereomers differ at some centres and match at others. With three centres, inverting one or two would give this relationship, but inverting all three does not.'},
  {t:'Geometric isomers', correct:false,
   why:'Geometric isomerism concerns the arrangement of substituents around a double bond or a ring, where rotation is restricted. It does not arise from chiral centres.'},
  {t:'Identical molecules', correct:false,
   why:'A complete mirror image is a distinct compound unless the molecule contains an internal mirror plane, which would make the two halves reflections of each other and the molecule achiral despite having centres.'}],
 teach:'One question resolves the relationship for any number of centres: were all of them inverted, or only some? All gives the mirror image and therefore enantiomers, which share ordinary physical properties and differ only in a chiral environment. Some gives diastereomers, which are not mirror images and differ in melting point, boiling point and solubility as well as in biology. That difference has a practical consequence, since diastereomers can be separated by ordinary means while enantiomers require a chiral method.',
 teachImg:'st_diastereomers',
 cite:'Stereochemistry (081926_Stereochemistry.pdf) slides 14, 21',
 quote:'Enantiomers are nonsuperimposable mirror images'},

{id:'v-st-3b', prof:'Yendapally', tier:'old', topic:'stereo', sub:'rs', concept:'rs-rotation-direction',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'Priorities 1 to 3 run clockwise, but the lowest-priority group points toward you. The configuration is:',
 options:[
  {t:'S', correct:true,
   why:'The rule specifies viewing the molecule from the side opposite the lowest-priority atom. Looking from the wrong side reverses the apparent sense of rotation, so an apparent clockwise reading corresponds to a true counterclockwise one, which is S.'},
  {t:'R', correct:false,
   why:'Clockwise means R only when read from the correct side. Applying the rule without checking the orientation is the single most common source of an inverted answer.'},
  {t:'Cannot be determined', correct:false,
   why:'It can be determined directly by reversing the reading, which takes no redrawing. Rebuilding gives the same answer more slowly.'},
  {t:'Depends on optical rotation', correct:false,
   why:'Optical rotation is measured experimentally and has no fixed relationship to the R and S assignment, which is derived from structure alone.'}],
 teach:'The orientation requirement exists because a tetrahedral centre presents opposite senses of rotation from opposite sides, so the rule fixes a viewpoint to make the answer unambiguous. One consequence follows. When the lowest-priority group points toward the viewer, read the rotation as drawn and reverse the letter, which is faster than redrawing and depends on the ranking already being right.',
 teachImg:'st_cip_rules2',
 cite:'Stereochemistry (081926_Stereochemistry.pdf) slides 10, 13',
 quote:'The molecule is viewed from the side opposite the lowest-priority atom.'},

{id:'v-dd-3b', prof:'Yendapally', tier:'old', topic:'disc', sub:'bio', concept:'classical-vs-nonclassical',
 tags:['reasoning','exam-pattern'], source:'slide',
 stem:'Replacing a carboxylic acid with a tetrazole is which type of bioisosteric substitution?',
 options:[
  {t:'Non-classical', correct:true,
   why:'A carboxylic acid is three atoms carrying the acidic function; a tetrazole is a five-membered ring of four nitrogens and a carbon. Neither the atom count nor the valence configuration corresponds, which places the substitution outside the classical categories even though the groups behave alike.'},
  {t:'Classical; both acidic', correct:false,
   why:'Shared acidity is why the substitution works, not why it would be classical. The classical categories are defined by matching valency and atom count rather than by matching chemical behaviour.'},
  {t:'Classical; both monovalent', correct:false,
   why:'Monovalent substitution means swapping single atoms or groups that form one bond each, as fluorine does for hydrogen in 5-fluorouracil. A carboxylic acid is three atoms and a tetrazole is a five-membered ring, so both are multi-atom groups attached through a carbon skeleton rather than single-bonded atoms, which puts the pair outside the monovalent category regardless of how alike they behave.'},
  {t:'Not bioisosteric; different MW', correct:false,
   why:'Molecular weight is not a criterion in either category. Bioisosterism turns on shape, volume and electron distribution, so a difference in weight does not disqualify a pair.'}],
 teach:'Classifying a substitution means asking first whether the correspondence is structural or behavioural. If the substitute matches the original in valency and atom count, it is classical, which covers monovalent, divalent, trivalent and tetrasubstituted atoms and ring equivalents. If it does not match but still produces similar biological activity, it is non-classical, which covers exchangeable groups and rings against non-cyclic structures. Tetrazole for carboxylic acid sits in the first non-classical group, alongside sulfhydryl for carboxylic acid in the ACE inhibitors and sulfonamide for the meta hydroxyl of isoproterenol.',
 cite:'Bioisosterism (082626_Bioisosterism.pdf) slides 5, 12, 14–15',
 quote:'Nonclassical Bioisosteres: A. Exchangeable groups B. Rings versus noncyclic structure'}
);
