/* Functional groups — MCFGs8_1718_26.pdf (96 slides).
   Dr. Sikazwe writes in abbreviations, so stems use them; explanations expand them. */
QUESTIONS.push(

/* ───────── picking groups out of a drug (his slide 56 format) ───────── */
{id:'fgx-1', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'ident', concept:'drugx-urea',
 tags:['structure'], source:'slide', img:'fg_drugX',
 stem:'In drug X above, which number marks the urea?',
 options:[
  {t:'1', correct:true,
   why:'Position 1 shows a carbonyl carbon with a nitrogen on each side: H₂N–C(=O)–NH–. Two nitrogens attached to the same carbonyl is the definition of a urea. Neither nitrogen is a mistake for something else here, because no oxygen is attached to that carbonyl carbon.'},
  {t:'2', correct:false,
   why:'Position 2 is a primary amide. The carbonyl carbon carries one nitrogen (as NH₂) and one carbon. A urea needs a second nitrogen in place of that carbon.'},
  {t:'6', correct:false,
   why:'Position 6 is a carbamate. The carbonyl carbon carries one oxygen and one nitrogen. A urea has two nitrogens and no oxygen on the carbonyl carbon.'},
  {t:'7', correct:false,
   why:'Position 7 is an ester inside a ring, also called a lactone. The carbonyl carbon carries one oxygen and one carbon, with no nitrogen at all.'}],
 svg:DIA.acylFamily,
 teach:'Every group in this family is built on one carbonyl carbon, and you tell them apart by what the two other atoms on that carbon are. Two nitrogens is a urea. One nitrogen and one carbon is an amide. One oxygen and one nitrogen is a carbamate. Two oxygens is a carbonate. One oxygen and one carbon is an ester. Slide 9 groups all of these together as carboxylic acid derivatives.',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 53, 56; carboxylic acid derivatives slides 9 and 60',
 quote:'Carboxylic Acid (CA) & derivatives: CA/Esters/Amides/Carbamates/Ureas/Imides/Guanidines'},

{id:'fgx-2', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'ident', concept:'drugx-carbamate',
 tags:['structure'], source:'slide', img:'fg_drugX',
 stem:'In drug X above, which number marks the carbamate?',
 options:[
  {t:'6', correct:true,
   why:'Position 6 shows –O–C(=O)–NH–. One oxygen and one nitrogen on the same carbonyl carbon is a carbamate. This is the group that yields both an alcohol and an amine when it is hydrolyzed.'},
  {t:'4', correct:false,
   why:'Position 4 is a carbonate. It has –O–C(=O)–O–, two oxygens on the carbonyl carbon and no nitrogen. Hydrolysis gives two alcohols instead of an alcohol and an amine.'},
  {t:'1', correct:false,
   why:'Position 1 is a urea, with two nitrogens on the carbonyl carbon and no oxygen.'},
  {t:'3', correct:false,
   why:'Position 3 is a carboxylic acid, –C(=O)OH. The oxygen carries a hydrogen rather than connecting to another part of the molecule, so nothing is released on hydrolysis.'}],
 svg:DIA.acylFamily,
 teach:'Carbamate and carbonate look alike because both have an oxygen attached to the carbonyl carbon. Check the other side. If it is a nitrogen, the group is a carbamate and hydrolysis gives an amine plus an alcohol. If it is a second oxygen, the group is a carbonate and hydrolysis gives two alcohols. Both are cleaved by CE, carboxylesterase.',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 51–52, 56',
 quote:'Esters/Carbonates/Amides/Carbamates undergo hydrolytic metabolism by Carboxyesterase or CE enzymes'},

{id:'fgx-3', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'ident', concept:'drugx-combination',
 tags:['structure','list'], source:'slide', img:'fg_drugX',
 stem:'Which answer combination correctly identifies the urea, ester and amide FGs in drug X?',
 options:[
  {t:'1; 2; 7', correct:true,
   why:'Position 1 is the urea, with two nitrogens on the carbonyl carbon. Position 2 is the amide, with one nitrogen as NH₂. Position 7 is the ester, sitting inside a ring as a lactone. Those three numbers together cover exactly the three groups asked for.'},
  {t:'3; 4; 6', correct:false,
   why:'These are the carboxylic acid, the carbonate and the carbamate. All three are carboxylic acid derivatives, but none of them is a urea, an ester or an amide.'},
  {t:'2; 3; 6', correct:false,
   why:'Position 2 is the amide, which belongs in the answer, but position 3 is a carboxylic acid and position 6 is a carbamate. The urea and the ester are both missing.'},
  {t:'4; 5; 6', correct:false,
   why:'Position 4 is a carbonate, position 5 is a cyclic ether with no carbonyl at all, and position 6 is a carbamate. None of the three requested groups appears.'}],
 teach:'Work one number at a time rather than looking for the whole set at once. For each circled group, find the carbonyl carbon and name the two atoms attached to it. Position 5 has no carbonyl, which rules it out of this family immediately: it is an oxygen bridging two carbons, which makes it an ether.',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 56',
 quote:'Q: What answer combination correctly identifies the urea, ester and amide FGs in drug X?'},

{id:'fgx-4', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'ident', concept:'drugx-carbonate',
 tags:['structure'], source:'slide', img:'fg_drugX',
 stem:'In drug X above, which number marks the carbonate, and which marks the ether?',
 options:[
  {t:'Carbonate is 4, ether is 5', correct:true,
   why:'Position 4 has two oxygens on one carbonyl carbon, which is a carbonate. Position 5 is an oxygen inside a five-membered ring with a carbon on either side and no carbonyl, which is an ether. The presence or absence of the C=O is what separates them.'},
  {t:'Carbonate is 5, ether is 4', correct:false,
   why:'These are swapped. Position 5 has no carbonyl carbon, and a carbonate requires one.'},
  {t:'Carbonate is 7, ether is 4', correct:false,
   why:'Position 7 has only one oxygen on its carbonyl carbon plus a carbon, making it an ester rather than a carbonate.'},
  {t:'Carbonate is 4, ether is 3', correct:false,
   why:'Position 3 is a carboxylic acid. Its oxygen carries a hydrogen and there is a C=O present, so it is not an ether.'}],
 svg:DIA.acylFamily,
 teach:'An ether is an oxygen with a carbon on each side and no double bond to oxygen anywhere on that carbon. A carbonate also has oxygens on both sides, but the central carbon carries a C=O as well. Looking for the C=O first sorts the whole carboxylic acid derivative family away from the ethers and alcohols.',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 31, 49, 56'},

{id:'fgx-5', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'ident', concept:'ca-derivative-family',
 tags:['structure','list'], source:'slide', img:'fg_az2357',
 stem:'AZ2357 activity is linked to FGs derived from carboxylic acid. Which set lists those derivatives?',
 options:[
  {t:'Esters, amides, carbamates, ureas, imides and guanidines', correct:true,
   why:'Slide 9 groups these six together with the carboxylic acid itself. All of them are built around a carbon that carries a double bond to oxygen, or in the case of guanidine around a carbon carrying three nitrogens. Recognizing the family lets you predict that most of them are cleaved by CE, carboxylesterase.'},
  {t:'Alcohols, phenols, ethers, aldehydes and ketones', correct:false,
   why:'Slide 9 groups these separately as oxygenated hydrocarbons. Aldehydes and ketones do contain a C=O, but neither has a heteroatom leaving group attached to that carbon, so neither is a carboxylic acid derivative.'},
  {t:'Sulfides, sulfoxides, sulfones and sulfonamides', correct:false,
   why:'These are the sulfur-containing groups from slides 64 to 68. Sulfonamide contains a nitrogen but the central atom is sulfur, not a carbonyl carbon.'},
  {t:'Alkanes, alkenes, alkynes and aromatics', correct:false,
   why:'These are the hydrocarbons from slides 10 to 20, built only from carbon and hydrogen.'}],
 teach:'Slide 9 sorts every functional group in the course into five families: hydrocarbons, halogenated hydrocarbons, oxygenated hydrocarbons, amines and their derivatives, and carboxylic acid derivatives. Placing a group in its family tells you in advance which reactions to expect, because the carboxylic acid derivatives are the ones that undergo hydrolysis.',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 9, 57',
 quote:'Q: AZ2357 drug activity is linked to FGs derived from carboxylic acid (CA). Circle and list all such FGs.'},

/* ───────── hydrocarbons and halogenated ───────── */
{id:'fgx-6', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'hc', concept:'alkane-lipophilicity',
 tags:['define'], source:'slide',
 stem:'What property does an alkyl chain add to a drug molecule?',
 options:[
  {t:'Lipophilicity', correct:true,
   why:'An alkyl chain is made only of carbon and hydrogen, which share electrons almost evenly, so the chain carries no charge and no ability to hydrogen bond with water. Adding one shifts the molecule toward fat and away from water, which raises log P and lowers water solubility.'},
  {t:'Acidity', correct:false,
   why:'An alkyl group has no hydrogen loose enough to give up as a proton. The acidic groups in this course are the carboxylic acid, phenol, sulfonamide, sulfonic acid, imide and thiol.'},
  {t:'A permanent positive charge', correct:false,
   why:'That belongs to the quaternary amine on slide 43, where a nitrogen carries four carbon substituents and holds a positive charge at any pH.'},
  {t:'Hydrogen bonding capacity', correct:false,
   why:'Hydrogen bonding needs an oxygen, nitrogen or sulfur. A pure hydrocarbon chain has none of these.'}],
 teach:'Adding carbon and hydrogen moves a molecule toward fat. Adding oxygen or nitrogen moves it toward water. That single contrast explains most of what functional groups do to a drug\'s absorption, distribution and elimination, and it is why metabolism works by adding oxygen-containing groups.',
 teachImg:'fgd_alkanes',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 10–11',
 quote:'Introduce lipophilicity in the drug molecule'},

{id:'fgx-7', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'hc', concept:'alkene-notes',
 tags:['define'], source:'slide',
 stem:'An alkene is present in a drug structure. What two consequences follow from that C=C?',
 options:[
  {t:'They show cis/trans geometric isomerism, and they can undergo metabolic epoxidation', correct:true,
   why:'A carbon–carbon double bond cannot rotate, so the groups on either end are locked into one arrangement, giving cis and trans forms. That same double bond is also where CYP adds an oxygen to form an epoxide, a strained three-membered ring listed as a toxic group in MCMet-9_17_2026.pdf slide 33.'},
  {t:'They are always acidic, and they are excreted unchanged', correct:false,
   why:'An alkene has no acidic hydrogen. Simple alkenes are described as largely stable in MCMet-9_16_2026.pdf slide 6, but the epoxidation note shows they are not entirely unreactive.'},
  {t:'They carry a permanent charge, and they cannot cross membranes', correct:false,
   why:'An alkene is neutral. A permanent charge belongs to the quaternary amine on slide 43.'},
  {t:'They are hydrolyzed by CE, and they yield two alcohols', correct:false,
   why:'CE, carboxylesterase, needs a carbonyl carbon attached to an oxygen or nitrogen. An alkene has neither.'}],
 svg:DIA.cisTransEpox,
 teach:'A carbon–carbon double bond does two things at once. It fixes the shape of that part of the molecule, which matters for how the drug fits a receptor. It also provides electrons that CYP can attack, producing an epoxide. Both consequences trace back to the same structural feature.',
 teachImg:'fgd_alkenes',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 16',
 quote:'Cis (Z)/Trans (E) geometric isomerism · Alkenes can undergo metabolic epoxidation'},

{id:'fgx-8', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'hc', concept:'halogenated-hc-definition',
 tags:['define'], source:'slide',
 stem:'Which halogens appear in the halogenated hydrocarbon (HHC) group?',
 options:[
  {t:'F, Cl, Br and I', correct:true,
   why:'Slide 9 lists fluorine, chlorine, bromine and iodine. Each pulls electrons away from the carbon it is attached to, which leaves that carbon short of electrons and open to attack by proteins, the mechanism behind halothane toxicity in MCMet-9_17_2026.pdf slide 31.'},
  {t:'O, N and S', correct:false,
   why:'These are the heteroatoms that appear in alcohols, amines and thiols. They are not halogens, and they generally make a molecule more water soluble rather than less.'},
  {t:'Na, K and Ca', correct:false,
   why:'These are metals that appear as counter-ions in drug salts, not as atoms bonded into an organic structure.'},
  {t:'P and B', correct:false,
   why:'Phosphorus appears in the phosphonate and phosphate groups on slides 69 and 70. Neither is a halogen.'}],
 teach:'Halogens are unusual among common substituents because they make a molecule both greasier and more reactive at the same time. MCMet-9_16_2026.pdf slide 21 notes halogenated hydrocarbons are very lipophilic and hard to convert into water-soluble forms, so they stay in the body, and MCMet-9_15_2026.pdf slide 28 names CYP2E1 as the enzyme central to their toxicity.',
 teachImg:'fgd_halogenated',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 9, 22',
 quote:'Halogenated HCs: Hydrocarbons + Halogens (F, Cl, Br, I)'},

/* ───────── oxygenated groups ───────── */
{id:'fgx-9', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'ox', concept:'phenol-storage',
 tags:['predict'], source:'slide',
 stem:'Why should phenolic drugs be protected from air and light?',
 options:[
  {t:'They oxidize to ortho- and para-quinones', correct:true,
   why:'A phenol is a hydroxyl attached directly to an aromatic ring. Oxygen and light drive it to lose hydrogens and form a quinone, in which the ring carries two C=O groups. That is a different compound from the drug, so potency falls, and quinones are reactive enough to cause harm.'},
  {t:'They hydrolyze to carboxylic acids', correct:false,
   why:'Hydrolysis requires a bond that water can split, such as an ester or an amide. A phenol has only a hydroxyl on a ring, with nothing for water to break.'},
  {t:'They lose their halogen atoms', correct:false,
   why:'A phenol contains no halogen. Removal of halogens is a CYP reaction, listed as dehalogenation in MCMet-9_10_26.pdf slide 19.'},
  {t:'They gain a permanent positive charge', correct:false,
   why:'A phenol is weakly acidic, so if anything it loses a proton and becomes negative. Permanent positive charge belongs to the quaternary amine on slide 43.'}],
 teach:'This is a storage and handling point that follows directly from structure. A hydroxyl on an aromatic ring is easy to oxidize because the ring can absorb the electronic change. Amber bottles and tight closures exist for exactly this reason. The quinone formed is also relevant to toxicity, since MCMet-9_16_2026.pdf slide 26 covers quinone metabolism by NQO1.',
 teachImg:'fgd_phenol',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 30',
 quote:'Protect phenolic drugs from air/light because they oxidize to o,p-quinones'},

{id:'fgx-10', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'ox', concept:'pegylation',
 tags:['predict'], source:'slide',
 stem:'What is PEGylation used for?',
 options:[
  {t:'Improving a drug\'s pharmacokinetic and safety profile', correct:true,
   why:'PEG stands for polyethylene glycol, a long chain of repeating ether units. Attaching it to a small or large molecule increases size and water solubility, which slows clearance and reduces how strongly the immune system reacts to the drug.'},
  {t:'Making a drug more lipophilic so it enters the brain', correct:false,
   why:'PEG chains carry many oxygens and are strongly water-attracting, so they lower rather than raise lipophilicity. Brain entry is discussed under the blood–brain barrier in 090426_Distribution.pdf slides 11 to 13.'},
  {t:'Converting a drug into a prodrug requiring CYP activation', correct:false,
   why:'PEGylation is a formulation and chemistry strategy rather than a bioactivation step. Prodrug examples in this course are enalapril and sulfasalazine in MCMet-9_4_26-9_9_26.pdf slides 35 and 36.'},
  {t:'Adding a permanent positive charge', correct:false,
   why:'PEG is neutral. Its oxygens are ether oxygens, which do not ionize.'}],
 teach:'A PEG chain is many ether groups joined in a row. Each ether oxygen can accept a hydrogen bond from water, so a long chain holds a large shell of water around the drug. That extra bulk and water association is what slows removal and softens the immune response.',
 teachImg:'fgd_ether_peg',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 32–34',
 quote:'PEGylation of small or large molecules is used to improve drug PK and safety profiles'},

{id:'fgx-11', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'carbonyl', concept:'aldehyde-rarity',
 tags:['predict'], source:'slide',
 stem:'Why are aldehydes uncommon in drug molecules?',
 options:[
  {t:'The group is reactive: it can oxidize, or even polymerize', correct:true,
   why:'An aldehyde has a carbonyl carbon carrying a hydrogen, and that carbon is short of electrons and exposed. It reacts easily, either being oxidized to a carboxylic acid or joining to other aldehyde molecules. A drug that changes in the bottle or reacts with proteins is not usable, which is why MCMet-9_17_2026.pdf slide 36 lists aldehydes as toxic groups.'},
  {t:'They cannot be absorbed orally', correct:false,
   why:'Absorption depends on size, lipophilicity and transport, not on this group specifically. The stated problem is chemical reactivity.'},
  {t:'They are too water soluble to cross membranes', correct:false,
   why:'An aldehyde is polar but small, and polarity alone is not why they are avoided.'},
  {t:'No enzyme can metabolize them', correct:false,
   why:'Several do. ALDH, aldehyde dehydrogenase, oxidizes them to carboxylic acids, and AKR, aldo-keto reductase, reduces them to alcohols, in MCMet-9_10_26.pdf slides 23 and 30.'}],
 teach:'A ketone has two carbons attached to its carbonyl, which shield that carbon and spread electron density onto it. An aldehyde has only one carbon and a hydrogen, so its carbonyl carbon is more exposed and more positive. That single structural difference is why ketones appear in drugs and aldehydes mostly do not.',
 teachImg:'fgd_aldehyde',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 36',
 quote:'Few in drug molecules. Why? Because this is a reactive FG – it can oxidize or even polymerize.'},

/* ───────── nitrogen groups ───────── */
{id:'fgx-12', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'n', concept:'quaternary-amine-properties',
 tags:['predict'], source:'slide',
 stem:'What are the consequences of a quaternary amine in a drug structure?',
 options:[
  {t:'The nitrogen carries a permanent positive charge at any pH, which blocks passive absorption into the CNS, and the molecule is neutral in acid–base character', correct:true,
   why:'A quaternary amine has four carbon groups on the nitrogen and no hydrogen to lose, so its positive charge cannot be removed by changing pH. A permanently charged molecule cannot pass through the lipid of the blood–brain barrier by simple diffusion. Because it can neither donate nor accept a proton, it is classified as neutral in acid–base terms despite carrying a charge.'},
  {t:'The nitrogen is strongly basic and becomes uncharged in basic conditions', correct:false,
   why:'That describes a primary, secondary or tertiary amine, which has a lone pair available to accept a proton and can therefore lose that proton again. A quaternary nitrogen has no lone pair left.'},
  {t:'The charge appears only at low pH', correct:false,
   why:'Slide 43 states the charge is permanent regardless of pH. pH-dependent charge belongs to the other amine classes.'},
  {t:'It increases passive entry into the brain', correct:false,
   why:'The opposite. A permanent charge prevents passive entry into the central nervous system.'}],
 svg:DIA.amineClasses,
 teach:'Count the carbons on the nitrogen to predict behaviour. One carbon is primary, two is secondary, three is tertiary, and all three of those are basic and change charge with pH. Four carbons is quaternary: permanently charged, unable to gain or lose a proton, and classed as neutral in acid–base character. That fourth carbon changes everything about how the drug distributes.',
 teachImg:'fgd_quat_amine',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 43',
 quote:'The charge on the N-atom is permanent, regardless of pH and prevents passive absorption into CNS. These molecules also have a neutral acid/base character.'},

{id:'fgx-13', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'n', concept:'amine-class-counting',
 tags:['structure'], source:'slide',
 stem:'A nitrogen in a drug carries two carbon substituents and one hydrogen. What class is it, and what Phase 1 reaction does it undergo?',
 options:[
  {t:'Secondary amine; N-dealkylation', correct:true,
   why:'Two carbons on the nitrogen makes it secondary. Secondary and tertiary amines carrying methyl or ethyl groups undergo N-dealkylation, where CYP removes one of those alkyl groups. Imipramine losing a methyl to become desipramine, in MCMet-9_10_26.pdf slide 16, is this reaction.'},
  {t:'Primary amine; oxidative deamination', correct:false,
   why:'A primary amine has only one carbon on the nitrogen and two hydrogens. Oxidative deamination removes the nitrogen entirely and leaves a carbonyl, and it is the reaction MAO, monoamine oxidase, performs.'},
  {t:'Tertiary amine; N-acetylation', correct:false,
   why:'A tertiary amine has three carbons. N-acetylation is also wrong because NAT, N-acetyltransferase, acts on primary amines and sulfonamides, and it is a Phase 2 reaction rather than Phase 1.'},
  {t:'Quaternary amine; no metabolism', correct:false,
   why:'A quaternary nitrogen has four carbons and no hydrogen.'}],
 svg:DIA.amineClasses,
 teach:'Counting carbons on the nitrogen tells you the class, and the class tells you the reaction. One carbon means a primary amine, which loses its nitrogen through oxidative deamination. Two or three carbons means a secondary or tertiary amine, which loses an alkyl group through N-dealkylation. Four carbons means a quaternary amine, permanently charged and largely untouched.',
 teachImg:'fgd_amines',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 40–43; Lecture #14 (MCMet-9_16_2026.pdf) slide 10'},

{id:'fgx-14', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'n', concept:'nitro-vs-nitrile',
 tags:['structure'], source:'slide',
 stem:'How do you tell a nitro group from a nitrile on sight?',
 options:[
  {t:'A nitro group is R–NO₂ with nitrogen bonded to two oxygens; a nitrile is R–C≡N with a triple bond to nitrogen and no oxygen', correct:true,
   why:'The atoms differ. Nitro has a nitrogen carrying two oxygens attached to the rest of the molecule. Nitrile, also called cyano, has a carbon triple-bonded to a nitrogen and contains no oxygen at all. Their metabolism differs too: nitro groups are reduced to amines by nitro-reductase, in MCMet-9_10_26.pdf slide 33.'},
  {t:'A nitro group has a triple bond and a nitrile has two oxygens', correct:false,
   why:'These are reversed. The triple bond belongs to the nitrile and the two oxygens belong to the nitro group.'},
  {t:'They are two names for the same group', correct:false,
   why:'Slides 44 and 45 treat them as separate groups with different atoms.'},
  {t:'A nitrile contains sulfur and a nitro group contains phosphorus', correct:false,
   why:'Neither contains sulfur or phosphorus. Sulfur groups are on slides 64 to 68 and phosphorus groups on slides 69 and 70.'}],
 teach:'Both appear on the electron-withdrawing side of the EDG and EWG chart on slide 94, so both pull electron density out of a ring they are attached to. They behave very differently in metabolism, though. The nitro group is reduced through nitroso and hydroxylamine intermediates, the same reactive species implicated in nitrofurantoin liver toxicity in MCMet-9_17_2026.pdf slide 48.',
 teachImg:'fgd_nitrile',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 44–45'},

/* ───────── sulfur and phosphorus ───────── */
{id:'fgx-15', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'sulf', concept:'sulfur-oxidation-series',
 tags:['structure'], source:'slide',
 stem:'A sulfur atom sits between two carbons with no oxygens on it. Adding one oxygen, then a second, produces which sequence?',
 options:[
  {t:'Sulfide (thioether) → sulfoxide → sulfone', correct:true,
   why:'The sulfur starts with two carbon neighbours and no oxygen, which is a sulfide, also called a thioether. One oxygen on the sulfur makes it a sulfoxide. A second oxygen makes it a sulfone. Each addition is an oxidation, and MCMet-9_16_2026.pdf slide 18 lists oxidation as what thioethers undergo.'},
  {t:'Sulfonamide → sulfonic acid → sulfide', correct:false,
   why:'These are not related by adding oxygens in that order. A sulfonamide has a nitrogen on the sulfur and a sulfonic acid has an OH on the sulfur, both with two oxygens already present.'},
  {t:'Sulfone → sulfoxide → sulfide', correct:false,
   why:'This runs the sequence backwards. Metabolism adds oxygens rather than removing them.'},
  {t:'Thiol → disulfide → sulfonic acid', correct:false,
   why:'A thiol is SH attached to one carbon, a different starting point from a sulfur with two carbon neighbours.'}],
 svg:DIA.sulfurSeries,
 teach:'Sulfur can hold different numbers of oxygens, and each count has its own name. Zero oxygens with two carbons is a sulfide. One oxygen is a sulfoxide. Two oxygens is a sulfone. Two oxygens plus a nitrogen is a sulfonamide, and two oxygens plus a hydroxyl is a sulfonic acid. Counting the oxygens on the sulfur names the group.',
 teachImg:'fgd_sulfur_list',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 62–68',
 quote:'Sulfur: Sulfide, Oxygenated Sulfur & Derivatives'},

{id:'fgx-16', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'sulf', concept:'sulfonamide-nat',
 tags:['enzyme'], source:'slide',
 stem:'A drug carries a sulfonamide (SO₂NH₂). Which Phase 2 enzyme acts on it?',
 options:[
  {t:'NAT', correct:true,
   why:'NAT, N-acetyltransferase, acts on primary alkyl and aryl amines and on sulfonamides, in MCMet-9_10_26.pdf slide 53. It attaches an acetyl group to the nitrogen, using acetyl-CoA as the source. NAT2 comes in slow and fast acetylator forms, so how quickly this happens varies between patients.'},
  {t:'GST', correct:false,
   why:'GST, glutathione S-transferase, attaches glutathione to carbons that are short of electrons, such as a carbon carrying a halogen or an epoxide carbon. A sulfonamide nitrogen is electron-rich, not electron-poor.'},
  {t:'EH', correct:false,
   why:'EH, epoxide hydrolase, opens epoxide rings using water. There is no epoxide in a sulfonamide.'},
  {t:'ALDH', correct:false,
   why:'ALDH, aldehyde dehydrogenase, oxidizes aldehydes to carboxylic acids. It is a Phase 1 enzyme and has no aldehyde to act on here.'}],
 svg:DIA.sulfurSeries,
 teach:'Sulfonamide is one of only two group types NAT accepts, the other being primary amines. Sulfamethoxazole appears again in MCMet-9_17_2026.pdf slide 58, where reactive products of its metabolism act as haptens and trigger a skin hypersensitivity reaction. The same group therefore connects a Phase 2 pathway and a toxicity mechanism.',
 teachImg:'fgd_sulfonamide',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 68; Lecture #11 (MCMet-9_10_26.pdf) slide 53',
 quote:'Target FGs: 1o N (Alkyl- & Aryl-amines) · SO2NH2 (Sulfonamides)'},

{id:'fgx-17', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'sulf', concept:'phosphate-hydrolysis',
 tags:['enzyme'], source:'slide',
 stem:'A phosphate ester on a drug is cleaved by which enzyme, and what is that strategy used for?',
 options:[
  {t:'Phosphatase; the phosphate makes the drug water soluble enough to inject, and is removed in the body to release the active drug', correct:true,
   why:'A phosphate group carries negative charges, so attaching one makes a poorly soluble drug soluble enough to give by injection. Phosphatase enzymes then cut it off, releasing the parent drug. Fosphenytoin is the example named in MCMet-9_16_2026.pdf slide 27.'},
  {t:'CE; the phosphate is a carboxylic acid derivative', correct:false,
   why:'CE, carboxylesterase, acts on esters, carbamates, amides and carbonates, all built on a carbonyl carbon. A phosphate ester is built on phosphorus instead, so a different enzyme is needed.'},
  {t:'GST; the phosphate carbon is electron-poor', correct:false,
   why:'GST, glutathione S-transferase, targets carbons short of electrons, such as those bearing a halogen or in an epoxide. The phosphate group has no such carbon.'},
  {t:'MAO; phosphates contain nitrogen', correct:false,
   why:'MAO, monoamine oxidase, acts on amines. A phosphate contains no nitrogen.'}],
 teach:'Sulfate esters follow the same pattern with a different enzyme. MCMet-9_16_2026.pdf slide 28 pairs sulfate esters with sulfatase, just as slide 27 pairs phosphate esters with phosphatase. In both, a charged group is attached to improve solubility and then removed to release the active drug.',
 teachImg:'fgd_phosphonate',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 69–70; Lecture #14 (MCMet-9_16_2026.pdf) slides 27–28'},

/* ───────── heterocyclic rings (drawn structures) ───────── */
{id:'fgx-18', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'rings', concept:'ring-pyrrole-vs-pyrrolidine',
 tags:['structure'], source:'slide',
 stem:'Name the ring shown.',
 options:[
  {t:'Pyrrole', correct:true,
   why:'Five atoms in the ring, one of them a nitrogen, with two double bonds inside the ring. The double bonds make it aromatic, which flattens the ring and holds the nitrogen lone pair inside the ring system rather than leaving it free to pick up a proton.'},
  {t:'Pyrrolidine', correct:false,
   why:'Pyrrolidine has the same five atoms and one nitrogen but no double bonds. Its nitrogen lone pair is free, so pyrrolidine is basic while pyrrole is not.'},
  {t:'Furan', correct:false,
   why:'Furan is also a five-membered aromatic ring, but the heteroatom is oxygen rather than nitrogen.'},
  {t:'Imidazole', correct:false,
   why:'Imidazole is a five-membered aromatic ring with two nitrogens rather than one.'}],
 fg:'Pyrrole',
 teach:'Reading a ring takes three questions in order. How many atoms are in the ring. Which of them are not carbon. And whether there are double bonds inside the ring. Those three answers name almost every ring in slides 73 to 93, and the double-bond answer also tells you whether a nitrogen in the ring is basic.',
 teachImg:'fgd_ring_5_n',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 75–76'},

{id:'fgx-19', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'rings', concept:'ring-piperidine',
 tags:['structure'], source:'slide',
 stem:'Name the ring shown.',
 options:[
  {t:'Piperidine', correct:true,
   why:'Six atoms in the ring, one nitrogen, and no double bonds. With no double bonds the nitrogen keeps its lone pair available, so piperidine is basic and will be protonated at physiological pH.'},
  {t:'Pyridine', correct:false,
   why:'Pyridine has the same six atoms and one nitrogen but three double bonds inside the ring, which makes it aromatic and flat.'},
  {t:'Piperazine', correct:false,
   why:'Piperazine is also saturated but has two nitrogens, positioned across the ring from each other.'},
  {t:'Pyrimidine', correct:false,
   why:'Pyrimidine is aromatic and has two nitrogens with one carbon between them.'}],
 fg:'Piperidine',
 teach:'Piperidine and pyridine contain the same atoms and differ only in whether the ring is saturated. That difference changes the chemistry: the saturated nitrogen in piperidine is a good proton acceptor, while the aromatic nitrogen in pyridine is much weaker because its lone pair is partly tied up in the ring system.',
 teachImg:'fgd_ring_6_n',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 82, 85'},

{id:'fgx-20', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'rings', concept:'ring-pyrimidine-vs-pyrazine',
 tags:['structure'], source:'slide',
 stem:'Name the ring shown.',
 options:[
  {t:'Pyrimidine', correct:true,
   why:'Six atoms, two nitrogens, aromatic, and the two nitrogens are separated by a single carbon. That 1,3 arrangement defines pyrimidine, the ring found in the DNA and RNA bases cytosine, thymine and uracil.'},
  {t:'Pyrazine', correct:false,
   why:'Pyrazine also has six atoms and two aromatic nitrogens, but they sit directly across the ring from each other rather than with one carbon between them. Pyrazinamide, the anti-tuberculosis drug, contains this ring.'},
  {t:'Piperazine', correct:false,
   why:'Piperazine has two nitrogens across the ring like pyrazine, but with no double bonds, so it is saturated.'},
  {t:'Pyridine', correct:false,
   why:'Pyridine has only one nitrogen.'}],
 fg:'Pyrimidine',
 teach:'Pyrimidine and pyrazine are the pair most often mixed up, because both are six-membered aromatic rings with two nitrogens. Count the carbons between the nitrogens. One carbon between them is pyrimidine. Two carbons on each side, putting them opposite, is pyrazine.',
 teachImg:'fgd_ring_6_2n_1',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 83–84'},

{id:'fgx-21', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'rings', concept:'ring-thiazole',
 tags:['structure'], source:'slide',
 stem:'Name the ring shown.',
 options:[
  {t:'Thiazole', correct:true,
   why:'Five atoms, aromatic, containing both a sulfur and a nitrogen. Thiazole appears in nizatidine, which slide 11 of the bioisosterism deck uses as the replacement for the furan ring in ranitidine.'},
  {t:'Imidazole', correct:false,
   why:'Imidazole also has five atoms and two heteroatoms, but both are nitrogen. There is no sulfur in it.'},
  {t:'Thiophene', correct:false,
   why:'Thiophene has a sulfur but no nitrogen, so it has only one heteroatom.'},
  {t:'Furan', correct:false,
   why:'Furan has a single oxygen as its only heteroatom.'}],
 fg:'Thiazole',
 teach:'Slides 75 to 81 organize the five-membered rings by which heteroatoms they contain: one oxygen gives furan, one nitrogen gives pyrrole, one sulfur gives thiophene, two nitrogens gives imidazole, and one sulfur with one nitrogen gives thiazole. Naming the heteroatoms present identifies the ring.',
 teachImg:'fgd_ring_5_sn',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 77, 80'},

{id:'fgx-22', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'rings', concept:'ring-imidazole',
 tags:['structure'], source:'slide',
 stem:'Name the ring shown.',
 options:[
  {t:'Imidazole', correct:true,
   why:'Five atoms, aromatic, with two nitrogens separated by one carbon. This is the ring in the histidine side chain, which is why histidine can act as both a proton donor and acceptor near physiological pH.'},
  {t:'Pyrazole', correct:false,
   why:'Pyrazole also has five atoms and two nitrogens, but the two nitrogens are next to each other rather than separated by a carbon.'},
  {t:'Pyrrole', correct:false,
   why:'Pyrrole has only one nitrogen.'},
  {t:'Pyrimidine', correct:false,
   why:'Pyrimidine has two nitrogens separated by one carbon like imidazole, but the ring has six atoms rather than five.'}],
 fg:'Imidazole',
 teach:'Count ring atoms before counting heteroatoms. Imidazole and pyrimidine both have two nitrogens with a single carbon between them, and the only difference is that imidazole has five ring atoms and pyrimidine has six. Getting the ring size first prevents that mix-up.',
 teachImg:'fgd_ring_5_2n',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 79'},

/* ───────── EDG vs EWG ───────── */
{id:'fgx-23', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'edg', concept:'edg-list',
 tags:['list'], source:'slide', img:'fg_edg_ewg',
 stem:'Using the chart above, which set contains only electron-donating groups (EDGs)?',
 options:[
  {t:'Aromatic hydroxyl, aromatic amine, aromatic thiol, aromatic ether, ionized acidic group, alkyl group', correct:true,
   why:'These six sit on the left of the chart. Each pushes electron density into the ring it is attached to. The aromatic hydroxyl is a phenol, the aromatic ether is shown as a methoxy group, the ionized acidic group is shown as a carboxylate, and the alkyl group is shown as a methyl.'},
  {t:'Halogens, nitrile, nitro, aldehyde, amide, ester, sulfonamide', correct:false,
   why:'These are the electron-withdrawing groups on the right of the chart. They pull electron density out of the ring instead of pushing it in.'},
  {t:'Aromatic hydroxyl, nitro, alkyl, ester', correct:false,
   why:'This mixes the two sides. Aromatic hydroxyl and alkyl are donating, while nitro and ester are withdrawing.'},
  {t:'Nitrile, aromatic amine, halogens, methoxy', correct:false,
   why:'This also mixes the two sides. Aromatic amine and methoxy donate, while nitrile and halogens withdraw.'}],
 teach:'The two sides differ in which way electrons move relative to the ring. A donating group has a lone pair it can push into the ring, which makes the ring more electron-rich and more open to attack by electron-poor species. A withdrawing group pulls density out, leaving the ring electron-poor. That change affects how acidic or basic nearby groups are and how readily CYP can oxidize the ring.',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 94',
 quote:'EDGs vs. EWGs · Electron density influencing FGs or moieties'},

{id:'fgx-24', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'edg', concept:'ewg-effect-on-acidity',
 tags:['predict'], source:'slide',
 stem:'A nitro group (EWG) is added to a ring bearing a phenol. What happens to the phenol\'s acidity?',
 options:[
  {t:'It becomes more acidic, because the nitro group pulls electron density away and stabilizes the negative charge left after the proton leaves', correct:true,
   why:'Acidity depends on how comfortable the molecule is after losing a proton. Losing the phenol hydrogen leaves a negative charge on the oxygen. A nitro group pulls electron density toward itself and spreads that negative charge over more atoms, which makes the deprotonated form more stable and therefore easier to reach.'},
  {t:'It becomes less acidic, because the nitro group adds electron density', correct:false,
   why:'Nitro is on the withdrawing side of the chart on slide 94, so it removes electron density rather than adding it.'},
  {t:'Acidity does not change, because the nitro group is not attached to the oxygen directly', correct:false,
   why:'The effect travels through the ring. Groups anywhere on a ring change the electron density at every position, which is why the chart exists.'},
  {t:'The phenol becomes basic', correct:false,
   why:'A phenol has a hydrogen to give away rather than a lone pair available to accept one, so it cannot become basic by adding a withdrawing group.'}],
 teach:'The same principle runs in reverse for bases. An electron-donating group next to a nitrogen makes that nitrogen more able to pick up a proton, so the molecule is more basic. An electron-withdrawing group makes it less able. This is why an aryl amine is less basic than an alkyl amine: the ring pulls the lone pair away from the nitrogen, as the physicochemical deck explains at slide 16.',
 teachImg:'fgd_edg_ewg',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 94; Physicochemical Properties 1 slide 16'},

/* ───────── relevance and classification ───────── */
{id:'fgx-25', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'acyl', concept:'fg-relevance-three-areas',
 tags:['list'], source:'slide',
 stem:'In what three areas do FGs matter in pharmacy?',
 options:[
  {t:'Physicochemical properties, pharmacodynamics, and pharmacokinetics', correct:true,
   why:'Physicochemical covers reactivity and stability, acid and base character, stereochemistry and melting point. Pharmacodynamics covers how the drug binds its receptor and what effects follow. Pharmacokinetics covers absorption, distribution, metabolism and elimination. Every topic in this course sits in one of those three.'},
  {t:'Manufacturing cost, packaging and shelf placement', correct:false,
   why:'These are commercial rather than chemical considerations and do not appear on slide 4.'},
  {t:'Dosage form, route and frequency only', correct:false,
   why:'These are clinical decisions. Functional groups influence them indirectly through the three areas named on slide 4.'},
  {t:'Molecular weight, colour and taste', correct:false,
   why:'Melting point appears on slide 4 under physicochemical properties, but colour and taste are not among the listed areas.'}],
 teach:'These three areas are the organizing structure of the whole course. Physicochemical properties come first, because whether a group is acidic, basic or neutral determines its charge. Charge then determines absorption and distribution, which is pharmacokinetics. And the groups that remain available to contact a protein determine binding, which is pharmacodynamics.',
 teachImg:'fgd_relevance',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 4',
 quote:'Physicochemical: Reactivity (stability/toxicity), Acid, Base, Neutral, Amphoteric, Stereochemistry, Melting Point · Pharmacodynamics · Pharmacokinetics'},

{id:'fgx-26', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'acyl', concept:'ce-four-substrates-fg',
 tags:['enzyme'], source:'slide',
 stem:'Which four FGs undergo hydrolytic metabolism by CE?',
 options:[
  {t:'Esters, carbonates, amides and carbamates', correct:true,
   why:'CE stands for carboxylesterase. All four of these groups have a carbonyl carbon attached to an oxygen or a nitrogen that can leave. Water breaks that bond and the molecule splits in two. Which two pieces come out depends on which group it was.'},
  {t:'Alcohols, phenols, thiols and amines', correct:false,
   why:'None of these has a bond that water can break. They are targets for Phase 2 conjugation instead, by UGT, SULT or MT.'},
  {t:'Epoxides, azo groups, nitro groups and alkenes', correct:false,
   why:'Epoxides go to EH, epoxide hydrolase. Azo and nitro groups are reduced rather than hydrolyzed. Alkenes are largely unreactive.'},
  {t:'Sulfonamides, sulfones, phosphates and sulfates', correct:false,
   why:'Phosphates go to phosphatase and sulfates to sulfatase. The sulfur groups have sulfur at the centre rather than a carbonyl carbon.'}],
 svg:DIA.acylFamily,
 teach:'One enzyme handles four groups because all four share the same arrangement: a carbonyl carbon attached to an atom that can leave. The products differ by group. An ester gives an acid plus an alcohol. An amide gives an acid plus an amine. A carbamate gives an alcohol plus an amine. A carbonate gives two alcohols.',
 teachImg:'fgd_ce_substrates',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 52',
 quote:'Esters/Carbonates/Amides/Carbamates undergo hydrolytic metabolism by Carboxyesterase or CE enzymes'},

{id:'fgx-27', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'acyl', concept:'imide-guanidine-recognition',
 tags:['structure'], source:'slide',
 stem:'A nitrogen sits between two carbonyl groups, so that one N carries two C=O. Which FG is this?',
 options:[
  {t:'Imide', correct:true,
   why:'An imide is a nitrogen flanked by two carbonyls. Having two electron-withdrawing carbonyls on the same nitrogen pulls electron density away from the N–H bond, which makes that hydrogen acidic. This is why imide appears on the acidic group list in the physicochemical deck rather than the basic list.'},
  {t:'Amide', correct:false,
   why:'An amide has one carbonyl on the nitrogen, not two. With only one withdrawing group the N–H is not acidic enough to count as an acidic functional group.'},
  {t:'Urea', correct:false,
   why:'A urea has one carbonyl with a nitrogen on each side. An imide reverses that: one nitrogen with a carbonyl on each side.'},
  {t:'Guanidine', correct:false,
   why:'A guanidine is a carbon carrying three nitrogens and no oxygen. It is strongly basic rather than acidic, because the positive charge formed when it picks up a proton is shared across all three nitrogens.'}],
 svg:DIA.acylFamily,
 teach:'Urea and imide are easy to reverse because both contain two of one atom and one of another. A urea is one carbonyl carbon with two nitrogens on it. An imide is one nitrogen with two carbonyl carbons on it. The consequence differs sharply: the imide N–H is acidic, while the urea is not.',
 teachImg:'fgd_urea',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 53–55; imide on the acidic list, 082726_PhysicochemicalProp1.pdf slide 13'}
);

QUESTIONS.push(
{id:'fgx-28', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'rings', concept:'ring-pyrazine-vs-piperazine',
 tags:['structure'], source:'slide',
 stem:'Name the ring shown.',
 options:[
  {t:'Pyrazine', correct:true,
   why:'Six ring atoms, two nitrogens sitting directly across from each other, and double bonds inside the ring. The double bonds make it aromatic. Pyrazinamide, the anti-tuberculosis drug, is built on this ring.'},
  {t:'Piperazine', correct:false,
   why:'Piperazine has the same six atoms with nitrogens in the same two positions, but no double bonds. That saturation is the whole difference, and it changes the nitrogens from weakly basic to strongly basic.'},
  {t:'Pyrimidine', correct:false,
   why:'Pyrimidine is also aromatic with two nitrogens, but they are separated by a single carbon rather than sitting opposite each other.'},
  {t:'Pyridazine', correct:false,
   why:'Pyridazine has its two nitrogens next to each other, sharing a bond.'}],
 cmp:['Pyrazine','Piperazine','Pyrimidine'],
 fg:'Pyrazine',
 teach:'Three six-membered aromatic rings carry two nitrogens and differ only in where those nitrogens sit. Adjacent is pyridazine. One carbon apart is pyrimidine. Directly opposite is pyrazine. Trace around the ring and count the carbons between the two nitrogens.',
 teachImg:'fgd_ring_6_2n_2',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 83–84'},

{id:'fgx-29', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'rings', concept:'ring-piperazine',
 tags:['structure'], source:'slide',
 stem:'Name the ring shown.',
 options:[
  {t:'Piperazine', correct:true,
   why:'Six ring atoms, two nitrogens directly opposite each other, and no double bonds. Because the ring is saturated, both nitrogens keep a free lone pair, so both are basic and will carry a positive charge at physiological pH.'},
  {t:'Pyrazine', correct:false,
   why:'Pyrazine has the nitrogens in the same positions but is aromatic. Its nitrogen lone pairs are partly held within the ring system, so it is far less basic.'},
  {t:'Piperidine', correct:false,
   why:'Piperidine is also saturated but contains only one nitrogen.'},
  {t:'Morpholine', correct:false,
   why:'Morpholine is a saturated six-membered ring with one nitrogen and one oxygen opposite each other, rather than two nitrogens.'}],
 fg:'Piperazine',
 teach:'Piperazine appears in many drugs precisely because it carries two basic nitrogens in a rigid ring. One can be attached to the rest of the molecule while the other stays free to pick up a proton, which adds water solubility without changing the drug\'s shape.',
 teachImg:'fgd_ring_6_pip',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 85'},

{id:'fgx-30', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'rings', concept:'ring-furan',
 tags:['structure'], source:'slide',
 stem:'Name the ring shown.',
 options:[
  {t:'Furan', correct:true,
   why:'Five ring atoms, one oxygen, and two double bonds inside the ring. Ranitidine is built on a furan ring, and slide 11 of the bioisosterism deck replaces it with a thiazole to give nizatidine, raising oral bioavailability from about 50% to about 90%.'},
  {t:'Thiophene', correct:false,
   why:'Thiophene has the same five-atom aromatic ring but the heteroatom is sulfur rather than oxygen.'},
  {t:'Pyrrole', correct:false,
   why:'Pyrrole has a nitrogen in that position instead of an oxygen.'},
  {t:'Tetrahydrofuran', correct:false,
   why:'Tetrahydrofuran has the same oxygen in a five-membered ring but is fully saturated, with no double bonds. Position 5 of drug X on slide 56 is a tetrahydrofuran.'}],
 cmp:['Furan','Thiophene','Pyrrole','Tetrahydrofuran THF'],
 fg:'Furan',
 teach:'Slides 75 to 81 sort the five-membered rings by heteroatom: oxygen gives furan, sulfur gives thiophene, nitrogen gives pyrrole. Adding a second heteroatom gives imidazole for two nitrogens, thiazole for sulfur plus nitrogen, and oxazole for oxygen plus nitrogen.',
 teachImg:'fgd_ring_5_o',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 75; Bioisosterism deck slide 11'},

{id:'fgx-31', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'rings', concept:'ring-pyridine',
 tags:['structure'], source:'slide',
 stem:'Name the ring shown.',
 options:[
  {t:'Pyridine', correct:true,
   why:'Six ring atoms, one nitrogen, three double bonds inside the ring. The aromatic nitrogen is weakly basic, because its lone pair sits in the plane of the ring rather than being pulled into the ring system, but it is a much weaker base than a saturated amine.'},
  {t:'Piperidine', correct:false,
   why:'Piperidine contains the same atoms but has no double bonds. Its nitrogen is strongly basic.'},
  {t:'Benzene', correct:false,
   why:'Benzene is the same six-membered aromatic ring but with six carbons and no heteroatom at all.'},
  {t:'Pyrrole', correct:false,
   why:'Pyrrole also has one nitrogen but only five ring atoms.'}],
 cmp:['Pyridine','Piperidine','Pyrrole'],
 fg:'Pyridine',
 teach:'Ring size and saturation state together decide basicity. Pyridine and piperidine both have one nitrogen in a six-membered ring, and the aromatic one is the weaker base. The rule to carry forward is that anything pulling the lone pair into a delocalized system reduces basicity, which is the same reason an aryl amine is weaker than an alkyl amine.',
 teachImg:'fgd_ring_6_n',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slide 82; Physicochemical Properties 1 slide 16'},

{id:'fgx-32', prof:'Sikazwe', tier:'old', topic:'fgs', sub:'ident', concept:'drugx-amide-vs-acid',
 tags:['structure'], source:'slide', img:'fg_drugX',
 stem:'In drug X above, which numbers mark the amide and the carboxylic acid?',
 options:[
  {t:'Amide is 2, carboxylic acid is 3', correct:true,
   why:'Position 2 has a carbonyl carbon bearing an NH₂, which is a primary amide. Position 3 has a carbonyl carbon bearing an OH, which is a carboxylic acid. The difference is the single atom attached: nitrogen for the amide, oxygen with a hydrogen for the acid.'},
  {t:'Amide is 3, carboxylic acid is 2', correct:false,
   why:'These are swapped. An OH on the carbonyl carbon makes the acid, not the amide.'},
  {t:'Amide is 1, carboxylic acid is 7', correct:false,
   why:'Position 1 has two nitrogens on the carbonyl carbon, making it a urea. Position 7 has an oxygen linking back into a ring, making it a cyclic ester.'},
  {t:'Amide is 6, carboxylic acid is 4', correct:false,
   why:'Position 6 has both an oxygen and a nitrogen, making it a carbamate. Position 4 has two oxygens, making it a carbonate.'}],
 svg:DIA.acylFamily,
 teach:'The carboxylic acid is the only member of this family whose group can ionize at physiological pH. That gives it a negative charge in the body, which affects solubility, protein binding and renal handling, and it is the group targeted by acyl synthetase in amino acid conjugation.',
 cite:'Functional group deck (MCFGs8_1718_26.pdf) slides 46, 50, 56'}
);
