const TELL_HTML = `
<h2>Tell apart</h2>
<p class="sub">Pairs from lectures 13, 14 and 15 that share wording. Each row gives the one feature that separates them, the answer a question is fishing for, and the slide it comes from. Nothing here is scored.</p>

<h3>Lecture 13 (MCMet-9_15_2026.pdf) &mdash; cytochrome P450</h3>
<table class="reftab"><thead><tr><th style="width:22%">Looks alike</th><th>What separates them</th><th style="width:26%">The trap</th><th style="width:9%">Slide</th></tr></thead><tbody>
<tr><td><b>Expressed</b> in the liver vs <b>metabolises</b> clinical drugs</td><td>Two pies. Slide 14 is the share of the liver's CYP each isoform makes up: CYP2E1 is the largest slice at 21%. Slide 16 is the share of clinical drugs each isoform metabolises: CYP3A4/5 is the largest at 30%. "Expressed" points at the first pie, "metabolises" at the second.</td><td>"CYP3A4 tops both." Slide 30 does say 3A4 is one third of liver CYP and metabolises one third of drugs, but the slide-14 pie gives it 11%. Answer from the pie the question names.</td><td>14, 16, 30</td></tr>
<tr><td><b>Family</b> vs <b>subfamily</b> vs <b>isoform</b> vs <b>allele</b></td><td>CYP2D6*4: 2 is the family (&gt;40% homology), D the subfamily (&gt;50% homology), 6 the isoform, *4 the allele. More than 18 families and more than 40 subfamilies.</td><td>The two homology cut-offs swapped, or written as 55% (the slide says &gt;50%).</td><td>9, 19</td></tr>
<tr><td><b>Families 1, 2, 3</b> vs <b>the CYP2 family</b></td><td>Families 1, 2 and 3 together metabolise 80% of clinical drugs. CYP2 alone is the largest clinically relevant family, with isoforms 2B6, 2C9, 2C19, 2D6 and 2E1.</td><td>80% belongs to the three families, not to CYP2 or to 3A4.</td><td>19, 22</td></tr>
<tr><td><b>Inducible</b> vs <b>polymorphic</b></td><td>Two different properties, and each isoform has its own pair: 1A2 induced (PAHs in tobacco smoke, dioxins, omeprazole) and polymorphic; 2B6 induced by several drugs and polymorphic (efavirenz); 2C9 and 2C19 both inducible and both polymorphic; <b>2D6 polymorphic but minimal induction</b>; 2E1 induced by ethanol and ketones and polymorphic.</td><td>Calling 2D6 inducible. It is the one isoform the deck marks "minimal induction".</td><td>20, 22, 24, 26, 28</td></tr>
<tr><td>CYP2D6: <b>little enzyme</b>, <b>many drugs</b></td><td>3% of liver CYPs yet 21% of clinical drugs (the pies say 2% and 20%). Low expression with a heavy substrate load is why it causes many drug&ndash;drug interactions. Also stereo-selective; codeine and venlafaxine are its named substrates.</td><td>Reading 21% as its share of the liver.</td><td>26</td></tr>
<tr><td><b>CYP2E1</b> vs <b>CYP3A4</b></td><td>2E1: environmental chemicals, induced by ethanol and ketones, key to halogenated hydrocarbon toxicity, ethanol and APAP (toxicity) as substrates. 3A4: largest clinically relevant isoform, drives first-pass, sits in liver, intestine and lungs, induction and inhibition are its big issues, grapefruit juice interactions.</td><td>Putting the halogenated hydrocarbons on 3A4, or the first-pass effect on 2E1.</td><td>28, 30, 35</td></tr>
<tr><td><b>Inhibitor</b> list vs <b>inducer</b> list</td><td>Slide 32 inhibitors: clarithromycin, erythromycin, ketoconazole, itraconazole, cimetidine, protease inhibitors, grapefruit juice, quinidine, omeprazole. Inducers: barbiturates, carbamazepine, phenytoin, rifampin, St John's wort, ethanol, tobacco, nevirapine.</td><td>Omeprazole is on both: an inducer of 1A1/2 and 3A4 (slide 33) and an inhibitor of CYP2C19 (slide 34). Induction and inhibition act on different isoforms.</td><td>32, 33, 34</td></tr>
<tr><td>The <b>four-step cycle</b>, in order</td><td>1 Oxidised Fe<sup>3+</sup> CYP complexes the drug. 2 NADPH donates an electron through CYP450 reductase. 3 NADPH donates a second electron to reduce O<sub>2</sub> and form the activated complex. 4 Activated oxygen oxidises the bound drug.</td><td>Oxygen before the drug, or both electrons at once. The drug binds first; the two electrons arrive one at a time.</td><td>12</td></tr>
<tr><td><b>Cyto</b> / <b>chrome</b> / <b>P450</b></td><td>Cyto = cell bound; chrome = heme pigment; P450 = the CYP + CO complex absorbs light at 450 nm; CYP450 is the root name. The enzyme sits in the ER, membrane-bound, with a porphyrin holding iron on a cysteine.</td><td>450 as a count of isoforms or a molecular weight.</td><td>8, 10</td></tr>
<tr><td><b>Endobiotic</b> vs <b>xenobiotic</b></td><td>Endobiotics are made by the body; xenobiotics are foreign. Phase I and phase II enzymes metabolise both (slide 49 TRUE/FALSE: true).</td><td>"CYPs only handle drugs."</td><td>5, 49</td></tr>
<tr><td><b>Induction</b> vs a <b>rapid-metaboliser phenotype</b></td><td>Both raise enzyme activity, so a drug clears faster; induction is acquired from an inducer and reverses when it stops, the phenotype is inherited. Slide 50 asks whether they are analogous: the parallel holds, the origin differs.</td><td>Treating induction as a change in the patient's genes.</td><td>50</td></tr>
<tr><td><b>UM / EM / IM / PM</b>: which one is "normal"</td><td>In this course the lectures (09/15 and 09/16 audio) name the intermediate metaboliser as the normal phenotype. The pharmacogenomics textbook convention makes the extensive metaboliser normal. An exam written from these lectures keys IM.</td><td>Answering from the textbook. The conflict is real; the drill states it on the question.</td><td>26; L14 49</td></tr>
<tr><td><b>PM</b> on an <b>active drug</b> vs <b>PM</b> on a <b>prodrug</b></td><td>The phenotype only says the enzyme is slow or fast. The outcome needs the second fact: active as given, or must be converted. PM + active drug (warfarin type) = drug accumulates, more effect and toxicity. PM + prodrug (codeine to morphine by 2D6; tramadol to ODT on slide 47) = little active metabolite, treatment fails. UM reverses both.</td><td>"PM always means toxicity."</td><td>41, 42, 47</td></tr>
<tr><td>"Only phase I enzymes are inducible, can be inhibited, and are polymorphic"</td><td>False. Phase 2 enzymes share all three: UGTs and GSTs have inducible isoforms (L14 slide 53), NAT2 gives slow and fast acetylators, NQO1 is inducible and polymorphic (L14 slide 26).</td><td>The absolute word "only".</td><td>51</td></tr>
<tr><td><b>One enzyme</b> vs <b>several enzymes</b> for deactivation (polypharmacy)</td><td>Several is preferable: if one route is blocked by a co-administered drug or is genetically deficient, the others still clear the drug, so its level changes less.</td><td>&mdash;</td><td>45</td></tr>
</tbody></table>

<h3>Lecture 14 (MCMet-9_16_2026.pdf) &mdash; functional groups, then factors</h3>
<table class="reftab"><thead><tr><th style="width:22%">Looks alike</th><th>What separates them</th><th style="width:26%">The trap</th><th style="width:9%">Slide</th></tr></thead><tbody>
<tr><td><b>Alkanes</b> vs <b>alkenes</b></td><td>Both are mostly stable in vivo and excreted unchanged. The exceptions differ: alkanes, CYP oxidation; alkenes, CYP oxidation to an epoxide followed by epoxide hydrolase (EH).</td><td>Giving the alkane the epoxide.</td><td>5, 6</td></tr>
<tr><td>An epoxide's <b>two fates</b></td><td>Hydrolysed by EHs, or conjugated by phase 2 GSTs. Both end the reactivity. Only when both are outrun does the epoxide carbon reach protein or DNA (L15 slides 33, 60).</td><td>Naming only one, or adding a route the slide does not list.</td><td>20</td></tr>
<tr><td><b>Primary</b> vs <b>secondary and tertiary</b> amines</td><td>1&deg; amines undergo oxidative deamination. 2&deg; and 3&deg; N-methyl or N-ethyl groups undergo N-dealkylation. Amines also undergo phase 2 (slide 11).</td><td>Deaminating a tertiary amine.</td><td>10, 11</td></tr>
<tr><td><b>Aldehydes</b> vs <b>ketones</b></td><td>Aldehydes undergo both oxidative and reductive metabolism. Ketones undergo reduction only, to secondary alcohols.</td><td>Oxidising a ketone.</td><td>12</td></tr>
<tr><td><b>Ester</b> vs <b>amide</b> vs <b>carbamate</b> vs <b>carbonate</b></td><td>All four are hydrolysed by carboxylesterase (CE; amides by its amidase activity, and amides are more stable in vivo than esters). The products follow what sits on the carbonyl carbon: ester gives acid + alcohol; amide gives acid + amine; carbamate gives amine + alcohol (+ CO<sub>2</sub>); carbonate gives two alcohols (+ CO<sub>2</sub>).</td><td>Writing an acid as the product of a carbamate or carbonate. The carbon leaves as CO<sub>2</sub>.</td><td>8, 9, 14, 15, 16</td></tr>
<tr><td><b>Ethers</b> vs <b>thioethers</b></td><td>Ethers: O-dealkylation, mostly methyl and ethyl groups. Thioethers: oxidative biotransformations and S-dealkylation.</td><td>&mdash;</td><td>17, 18, 19</td></tr>
<tr><td><b>Phosphate ester</b> vs <b>sulfate ester</b> vs <b>carboxylate ester</b></td><td>Each is cut by its own enzyme: phosphatase (fosphenytoin, ATP, DNA), sulfatase, carboxylesterase.</td><td>Sulfatase removes a sulfate; sulfotransferase (slide 29) adds one. Same root, opposite direction.</td><td>16, 27, 28, 29</td></tr>
<tr><td><b>Primary, secondary, tertiary alcohol</b></td><td>All three can undergo phase 1 and phase 2. Phase 1 oxidation stops at the tertiary alcohol (no hydrogen on the carbinol carbon), which the slide diagram marks unchanged; phase 2 conjugates it as usual. Phenolic OHs go to phase 2.</td><td>Oxidising a tertiary alcohol to a ketone.</td><td>22, 23</td></tr>
<tr><td><b>Halogenated hydrocarbons</b></td><td>Very lipophilic and not readily metabolised to hydrophilic metabolites, so a long half-life, which raises the potential for hepatotoxicity. CYP2E1 is the isoform (L13 slide 28).</td><td>&mdash;</td><td>21</td></tr>
<tr><td><b>Purines</b> vs <b>pyrimidines</b> vs <b>quinones</b></td><td>Purines: xanthine oxidase (XO) oxidises them to uric acid; allopurinol inhibits XO. Pyrimidines: dihydropyrimidine dehydrogenase (DPD) deactivates them, DPD is polymorphic, more than 80% of 5-FU is inactivated by it. Quinones: NQO1 (inducible, polymorphic, overexpressed in many cancers).</td><td>Giving 5-FU to xanthine oxidase.</td><td>24, 25, 26</td></tr>
<tr><td><b>Phase 2 enzyme &rarr; which group it takes</b></td><td>Count the handles: UGTs take four (-OH, -CO<sub>2</sub>H, -NH<sub>2</sub>, -SH); methyltransferases take three (-OH, -NH<sub>2</sub>, -SH); the three specialists take one each, and the one is in the name: sulfotransferase makes a sulfate ester, so -OH; N-acetyltransferase, -NH<sub>2</sub>; acylsynthetase with an amino acid, -CO<sub>2</sub>H. GSTs are the opposite kind: glutathione is the nucleophile, so the drug must carry an electrophile, R-X or an epoxide. Cofactors: UDPGA, SAM, PAPS, acetyl-CoA, acetyl-CoA + glycine or glutamine, GSH.</td><td>Handing an amine to sulfotransferase from this table (L11 slide 47 does list aromatic amines for it; the L14 table lists only -OH).</td><td>29, 30</td></tr>
<tr><td><b>Intrinsic</b> vs <b>extrinsic</b> factors</td><td>Intrinsic belong to the parent drug (dose, route, absorption, distribution, physicochemical properties) or to the patient (DME presence, DME co-factors, disease, age, gender, genetics). Extrinsic is exposure to xenobiotics, and its key consideration is induction and inhibition DDIs.</td><td>Filing "genetics" under extrinsic, or "ethanol" under intrinsic.</td><td>33, 51, 52</td></tr>
<tr><td><b>Dose</b> vs <b>route</b> as a factor</td><td>Dose: overdosing overwhelms DME capacity and toxicity follows (APAP). Route: oral dosing meets pre-systemic metabolism in the gut (stomach, intestinal mucosa, microbiome) and on the first pass through the liver, so bioavailability falls. First-pass examples: isoproterenol (COMT and sulfation), lidocaine (CYPs and CE, ineffective by mouth), nitroglycerin (GST, given buccally).</td><td>&mdash;</td><td>34, 35, 36</td></tr>
<tr><td><b>ABC</b> vs <b>SLC</b> transporters</td><td>ABC (ATP-binding cassette): mostly efflux, P-gp/MDR1 and MRP1&ndash;4. SLC (solute carrier): influx and efflux, OATs and OCTs. Induction or inhibition of either changes how much drug reaches the enzymes.</td><td>&mdash;</td><td>37</td></tr>
<tr><td><b>Albumin</b> vs <b>&alpha;<sub>1</sub>-acid glycoprotein</b></td><td>Weak acids bind albumin (warfarin, NSAIDs, sulfonamides); weak bases bind &alpha;<sub>1</sub>-acid glycoprotein. Binding lowers metabolism and lengthens t<sub>&frac12;</sub>; only free drug is metabolised. Tissue binding (slide 39) raises the total tissue concentration, and again only the free fraction is metabolised.</td><td>&mdash;</td><td>38, 39</td></tr>
<tr><td>Which <b>disease</b> raises DME activity</td><td>Liver disease, cardiac disease (less liver blood flow) and inflammation or infection all lower DME activity. Hyperthyroidism raises it (more protein synthesis). The slide adds that the effects are not always predictable.</td><td>Thyroid disease is the one arrow pointing up.</td><td>43</td></tr>
<tr><td><b>Fetus</b> vs <b>neonate</b> vs <b>elderly</b></td><td>Fetus: CYPs form very early, phase II later; CYP1A, CYP3A7 and SULTs; more phase I than phase II capacity; exposed through the mother. Neonate: low UGT1A1, so bilirubin builds up (jaundice) and chloramphenicol gives gray baby syndrome; low CYP2C19, avoid omeprazole. Elderly: less liver mass and ER, less liver blood flow and renal filtration, polypharmacy, "start low and go slow".</td><td>Gray baby syndrome as a CYP problem. It is glucuronidation.</td><td>45, 46, 47</td></tr>
<tr><td><b>Polymorphic CYPs</b> and <b>species</b></td><td>Key polymorphic CYPs: 2A6, 2C9, 2C19, 2D6. Species: cats have STs but lack UGTs, pigs the reverse; humans have one CYP2D isoform (2D6), rats have six.</td><td>3A4 in the polymorphic list (slide 30 of L13 gives it minor genetic factors).</td><td>49, 50</td></tr>
<tr><td><b>Induction</b> vs <b>inhibition</b></td><td>Induction raises enzyme levels (more mRNA translation, less protein degradation) and activity; CYPs, UGTs and GSTs have inducible isoforms. With a substrate of the same enzyme: less drug efficacy, more effect from a prodrug, more bioactivation toxicity; drug levels and duration of action fall. Inhibition: reversible (competitive or non-competitive) lasts 2&ndash;3 days; irreversible keeps the enzyme bound longer and needs new enzyme to be made. Drug activity, levels and duration rise; metabolites fall.</td><td>Time course: induction builds over days as enzyme is made; reversible inhibition is immediate and outlasts the inhibitor by 2&ndash;3 days.</td><td>53, 59</td></tr>
<tr><td>The <b>inducer case</b> vs the <b>inhibitor cases</b></td><td>Cyclosporin A (a 3A4 substrate) plus a 3A4 inducer: more enzyme, faster inactivation, less immunosuppression, transplant failure. Inhibitor cases (slide 65): metronidazole + Coumadin, hemorrhage; erythromycin + glyburide, hypoglycemia; ketoconazole + cyclosporin, immunosuppression; Prozac or Paxil + dextromethorphan, CNS depression. Tyramine + MAOI: hypertensive crisis, because MAO no longer inactivates tyramine.</td><td>Direction: the inducer lowers the substrate, the inhibitor raises it.</td><td>55, 61, 65</td></tr>
<tr><td><b>Dietary inducers</b> vs <b>dietary inhibitors</b></td><td>Inducers: indoles from cruciferous vegetables raise 1A1 and 1A2; organosulfur compounds (garlic) raise 1A and 3A plus some phase II; PAHs from smoked or barbecued food and cigarette smoke raise 1A1 and 1A2; dioxins and PCBs raise multiple CYPs and some UGTs. Inhibitor: grapefruit juice furocoumarins (bergamottin, 6',7'-dihydroxybergamottin), mechanism-based inhibitors of 3A4; felodipine levels rise on the slide-66 plot.</td><td>Grapefruit as an inducer.</td><td>56, 57, 58, 62, 63, 66</td></tr>
</tbody></table>

<h3>Lecture 15 (MCMet-9_17_2026.pdf) &mdash; elimination, then toxicity</h3>
<table class="reftab"><thead><tr><th style="width:22%">Looks alike</th><th>What separates them</th><th style="width:26%">The trap</th><th style="width:9%">Slide</th></tr></thead><tbody>
<tr><td><b>Elimination</b> vs <b>metabolism</b></td><td>Elimination is the irreversible physical removal of metabolised and un-metabolised xenobiotics from the body; essential whatever the route of administration; prevents accumulation. Metabolism changes the structure; elimination removes the molecule.</td><td>&mdash;</td><td>5</td></tr>
<tr><td><b>Renal</b> vs <b>hepatic/biliary</b></td><td>Renal: the primary route for polar, free (unbound) drugs and metabolites; glomerular filtration and active transport; non-polar drugs that reach the urine (phenytoin) are reabsorbed. Examples atenolol, ampicillin, vancomycin. Hepatic/bile/fecal: the primary route for lipid-soluble drugs and metabolites, by active transport; steroids (methylprednisone), digoxin, many anticancer agents.</td><td>Sending a lipophilic drug out through the kidney.</td><td>7, 8, 16</td></tr>
<tr><td><b>Filtration</b> vs <b>secretion</b> vs <b>reabsorption</b></td><td>Filtration: low molecular weight (&lt;60 kDa) and unbound drugs pass; inflamed glomerular capillaries may raise GFR. Secretion: active transporters, anions by OATP1 and 3, MRP2 and 4; cations by OCT2, MDR1, MATE1 and MATE2K; probenecid inhibits renal OATPs and slows penicillin excretion. Reabsorption: the un-ionised drug diffuses back into the circulation; the ionised drug stays in urine.</td><td>Probenecid as an inducer, or as acting on filtration.</td><td>11, 12, 13</td></tr>
<tr><td><b>pH trapping</b>, which way</td><td>Acidic urine lowers elimination of acidic drugs and raises it for bases; basic urine the reverse. A drug that ionises in the urine cannot be reabsorbed, so it is trapped. Aspirin overdose is treated by alkalinising the urine with NaHCO<sub>3</sub>.</td><td>Acidifying the urine for an aspirin overdose.</td><td>14, 15</td></tr>
<tr><td><b>Enterohepatic recycling</b> vs <b>pH trapping</b></td><td>Recycling: drug excreted in bile is reabsorbed from the intestine before fecal elimination, so duration of action lengthens (ezetimibe, t<sub>&frac12;</sub> 22&ndash;24 h; isotretinoin; morphine); slide 20 draws the glucuronides of diclofenac, indomethacin and ketoprofen cleaved by microbial &beta;-glucuronidase. It is disrupted with PO charcoal or anion exchange resins. Trapping is the renal tubule and ionisation.</td><td>Both prolong or shorten exposure, but one is bile and gut, the other urine.</td><td>18, 19, 20</td></tr>
<tr><td><b>Intestinal</b> vs <b>lung</b> vs the minor routes</td><td>Intestinal: unabsorbed oral parent drug, GI and bile metabolites; intestinal P-gp/MDR1 efflux and GI metabolism (diltiazem about 75%, midazolam more than 40%). Lungs: volatile and gaseous agents by passive diffusion (inhaled anesthetics). Milk: not major but reaches the nursing infant (topotecan; cimetidine, which the slide labels a PPI although it is an H<sub>2</sub> antagonist). Skin/sweat/oil, tears (rifampin colours tears orange-red), hair and saliva (5&ndash;48 h post exposure) are minor routes used for monitoring and testing.</td><td>Ranking a minor route above renal or biliary.</td><td>21&ndash;26</td></tr>
<tr><td>Both <b>high and low log P</b> drugs in sweat</td><td>True. The skin secretes watery sweat and oil, so both lipophilic and hydrophilic molecules can leave that way, in small amounts. The lecture asked this as a TRUE/FALSE (09/17 audio).</td><td>&mdash;</td><td>24</td></tr>
<tr><td>The six <b>causes</b> of toxicity</td><td>Toxicophores; dose (overdose, narrow-TI drugs); drug interactions (polypharmacy, distribution-related); low deactivating enzyme capacity (genetics, inhibitors); idiosyncratic reactions; hypersensitivity and immune response.</td><td>Mistaking a mechanism (an epoxide) for a cause (a toxicophore).</td><td>29</td></tr>
<tr><td><b>Toxicophore</b> vs <b>pharmacophore</b></td><td>A toxicophore is a toxic or potentially toxic functional group, existing in the parent or bioactivated in an intermediate or metabolite. Five categories: electrophilic carbons, electrophilic carbonyls, electrophilic double bonds, free radicals (ROS and RNS), and others (haptens, azo, N-OH).</td><td>&mdash;</td><td>29, 30</td></tr>
<tr><td><b>Existing</b> vs <b>bioactivated</b> electrophilic carbons</td><td>Existing: halogenated carbons and allylic carbons are electrophilic as found. Bioactivated: epoxide carbons (carbamazepine 10,11-epoxide by 3A4), aflatoxin B1 (hepatocarcinogen, binds DNA), benzo[a]pyrene to BPDE (binds DNA).</td><td>&mdash;</td><td>31&ndash;35</td></tr>
<tr><td><b>Carbonyl</b> vs <b>double bond</b> vs <b>radical</b> vs <b>other</b> examples</td><td>Carbonyls: aldehydes (abacavir's alcohol oxidised by ADH). Double bonds: bioactivated intermediates, tolcapone and diclofenac (slide 37) and the quinone, quinonemethide, 3-alkylindole and iminoquinone types (slide 38). Radicals: isoniazid (two radicals: the mycobacterial catalase-peroxidase makes the isonicotinoyl radical that treats TB; liver NAT makes acetylhydrazine, whose acetyl radical harms the host), phenytoin (teratogenic radical), ROS/RNS oxidative stress. Others: haptens (ethanol, urushiol in poison ivy, hepatic hypersensitivity), azo reduction (Solvent Red 1 to carcinogenic aromatic amines), N-hydroxylation (acetylaminofluorene, then sulfation, to the carcinogen).</td><td>Putting isoniazid's therapeutic radical and its toxic radical on the same enzyme.</td><td>36&ndash;44</td></tr>
<tr><td><b>Hepatotoxicity risk factors</b></td><td>Genetics (DME phenotypes, UM to PM); age (elderly); gender (F &gt;&gt; M for acetaminophen, halothane, diclofenac, sulindac); alcohol (cirrhosis, GSH depletion); liver disease (HIV with hepatitis B or C); pharmacokinetics (sustained-release and long-acting drugs).</td><td>&mdash;</td><td>47</td></tr>
<tr><td><b>APAP</b> at a normal dose vs in <b>overdose</b></td><td>Safe below 4 g/day: sulfates and glucuronides are the major metabolites. Overdose exhausts UGTs and STs and phase I bioactivation to NAPQI takes over. NAC is the antidote, deactivating the electrophile as glutathione would. Nitrofurantoin (nitroso and hydroxylamine intermediates) and NDMA in ranitidine are the other hepatotoxicity examples.</td><td>NAPQI at every dose. It is the overflow route.</td><td>48, 49, 50, 63</td></tr>
<tr><td>The <b>extra-hepatic</b> examples, organ by organ</td><td>Heart: doxorubicin (mitochondrial Fe and ROS, CHF) and terfenadine (parent accumulates and inhibits hERG, arrhythmias; fexofenadine keeps the effect without the inhibition). Blood: clozapine (imine binds neutrophils, agranulocytosis). Lungs: amiodarone (cLogP 9, drug and des-ethyl metabolite accumulate). Neurons: MPTP to MPP<sup>+</sup> by MAO-B, Parkinson's symptoms. Kidney: ethylene glycol by ADH and ALDH to toxic species. Skin: sulfamethoxazole, CYP metabolism to nitroso haptens.</td><td>Swapping the two cardiotoxicity mechanisms: doxorubicin is radicals, terfenadine is hERG.</td><td>51&ndash;58</td></tr>
<tr><td><b>Enzyme defense</b> vs <b>treatment</b></td><td>Defense: GSTs and EHs deactivate electrophiles; antioxidant enzymes handle oxidative stress. Treatment: antidotes, supportive care, PO activated charcoal within 1 h of ingestion, enhanced elimination (forced diuresis, ion trapping, dialysis, hemoperfusion, hemofiltration, exchange transfusion). NAC for APAP; 2-PAM (pralidoxime, an oxime) for organophosphates, regenerating AChE and BuChE, not BBB-penetrant, and only before "aging".</td><td>2-PAM given after aging, or expected to cross into the brain.</td><td>60&ndash;64</td></tr>
</tbody></table>
`;
